### ISSUE TITLE
Allow curators to specify translations for page titles

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/exhibits#1005]
As a curator or exhibit admin, I want to provide translations in one or more languages for titles of pages (including feature pages, about pages, and exhibit home pages).

**Acceptance criteria**

When I select the a locale from the locale selector:

* [ ] If a translation exists for a page's title in that locale, I should see the translation for that locale 
* [ ] If a translation does not exist for a page's title in that locale, I should see the default translation

**Comment by ggeisler** [comment]
Closing; replaced by https://github.com/projectblacklight/spotlight/issues/1919
