### ISSUE TITLE
Allow curators to provide translations for Sir Trevor widget content

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/exhibits#1006]
As a curator or exhibit admin, I want to provide translations for page content created in Sir Trevor widgets (including content on feature pages, about pages, and exhibit home pages).

**Acceptance criteria**

When editing a page:

* [ ] I want to be able to enter a translation for a given locale along side the default translation when creating new widget content or editing content for an existing widget.
* [ ] I want translations to be able to mirror the structure of a page as much as possible, so I don't need to rebuild the widget order from the default locale.

When I select the a locale from the locale selector:

* [ ] If a translation exists for a page's title in that locale, I should see the translation for that locale 
* [ ] If a translation does not exist for a page's title in that locale, I should see the default translation

**Comment by ggeisler** [comment]
Closing; replaced by https://github.com/projectblacklight/spotlight/issues/1919
