### ISSUE TITLE
Date slider displaying incorrect results

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1009]
Re: date slider facet behavior.

I typed into the facet 1976 to 1976. Slider bar shows 1976 to 1977. 

Results include several objects with dates not within that span. 

Example: https://exhibits.stanford.edu/shpc/catalog/fm969cx0806

**Comment by cbeer** [comment]
If you type 1976 - 1976, the slider bar seems to correctly display the covered range (January 1, 1976 - December 31, 1976). Do you have a screenshot of different or wrong behavior you can share?

**Comment by cbeer** [comment]
I'll follow up with Arcadia about the date parsing; I think the way we've encoded the dates is standards-compliant but potentially unparsable.

**Comment by cbeer** [comment]
I think that's how the date range slider works; it's showing the range selected covers the year 1976. If we want to do something else, this should be tagged design-needed and we'll have to figure out a new way to display this.
