### ISSUE TITLE
Date range facet not working on exhibits home page(s)

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1010]
For example, look at the Images of Rome exhibit:
https://exhibits.stanford.edu/lanciani

<img width="295" alt="screen shot 2017-12-12 at 11 02 10 am" src="https://user-images.githubusercontent.com/3210225/33903087-f68bd630-df2b-11e7-94e2-c8d1eb5b3301.png">

**Comment by cbeer** [comment]
I've started investigating this; the date range limit plugin is incompatible with current blacklight configuration practices, which is a pretty hard requirement for making it work on these pages. This will be a significant exercise (3-5 days?) to modernize the plugin so we can use it.
