### ISSUE TITLE
Inconsistent full-screen icon in Mirador

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#1017]
The full-screen icon/capability works for some objects but not for others - see examples below:

Works: https://exhibits.stanford.edu/parker-2/catalog/pm049bv8195
![screenshot 2017-12-13 12 17 38](https://user-images.githubusercontent.com/796990/33960480-b5bfddf2-dfff-11e7-9582-bef4d2f2cd70.png)

Doesn't work/appear: https://exhibits.stanford.edu/parker-2/catalog/kz540zc7240
![screenshot 2017-12-13 12 20 20](https://user-images.githubusercontent.com/796990/33960587-0e5ce874-e000-11e7-9aff-71631be42a32.png)

Could this have something to do with the width of the page-picker widget at time of instantiation? Weird if so, but that's the only difference I see between these two objects.

**Comment by camillevilla** [comment]
@blalbrit you've got it. The full screen icon gets pushed down onto the next row if the page-picker widget is too wide. 
<img width="419" alt="screen shot 2017-12-13 at 5 23 05 pm" src="https://user-images.githubusercontent.com/5402927/33970889-6506ea56-e02a-11e7-9e6c-90d398eb957a.png">

**Comment by blalbrit** [comment]
Interesting! I know it's not a lovely user experience, but is there any way to lock the width of that widget so it doesn't push important stuff off the screen? Thanks for doing the analysis on that @camillevilla !
