### ISSUE TITLE
When a search is executed in the Rare Music exhibit, "we're sorry but something went wrong" is the result

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1018]
The exhibit is: https://exhibits.stanford.edu/rare-music.

NOTE: the search must be for a keyword that is indexed, such as "Haydn"

The exhibit creator hadn't worked on this exhibit in quite a while, and then just yesterday he did a reindex, to capture an item that was pushed to SW.

I just kicked off a reindex of this exhibit, and I am seeing the same error.

I am unable to repeat this behavior in any other exhibit thus far.

**Comment by cbeer** [comment]
https://app.honeybadger.io/projects/49092/faults/35819735#notice-comments

Looks related to the blacklight_range_limit plugin.

**Comment by cbeer** [comment]
Fixed by https://github.com/projectblacklight/blacklight_range_limit/pull/74
