### ISSUE TITLE
Date range slider ignores start date

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/exhibits#1024]
Limit date range to 1960-1978:
https://exhibits.stanford.edu/shpc/catalog?q=&range%5Bpub_year_tisim%5D%5Bbegin%5D=1960&range%5Bpub_year_tisim%5D%5Bend%5D=1978&search_field=search

Values in single date facet show all years up to 1978, and results include objects whose dates do not overlap with the span 1960-1978. See results of adding single date facet of 1890, yielding objects dated 1890-1899:
https://exhibits.stanford.edu/shpc/catalog?f%5Bpub_year_w_approx_isi%5D%5B%5D=1890&q=&range%5Bpub_year_tisim%5D%5Bbegin%5D=1960&range%5Bpub_year_tisim%5D%5Bend%5D=1978&search_field=search

**Comment by cbeer** [comment]
This sounds like a duplicate of #1009. I'm not sure whether that fix has been deployed or if the data has been reindexed?

**Comment by arcadiafalcone** [comment]
Oops, my bad -- from the comments on #1009 I thought only the labeling issue had been addressed. Closing.
