### ISSUE TITLE
Collection facet not showing collection name

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/exhibits#1029]
I imagine this has to do w/ #1004

We'll need to address this (possibly by doing #1020), or revert that PR before our next release.

On exhibits-stage:
<img width="301" alt="colection-facet-bug" src="https://user-images.githubusercontent.com/96776/34063515-6e3b4576-e1a7-11e7-871e-b94c7ddec17e.png">

**Comment by camillevilla** [comment]
Re-indexing exhibits seems to fix this. @jkeck Should we kick off some jobs before the weekend?

## Before
<img width="228" alt="before_druids" src="https://user-images.githubusercontent.com/5402927/34063967-7f8da654-e1aa-11e7-8852-f9459913d676.png">

## After
<img width="229" alt="after_collection_names" src="https://user-images.githubusercontent.com/5402927/34063966-7f62757e-e1aa-11e7-8445-ba7cc6b8f298.png">

**Comment by jkeck** [comment]
Now that I think about it #1004 made a change to indexing logic as well as display logic (which will require a re-index of everything).

We have a few options (I'm sure there are others, feel free to chime in):
1. Revert the PR (leaves our collection facet sorting incomprehensible)
1. Create a new PR to add a new field instead of changing this one (per @cbeer)
1. Keep the PR and ensure that we kick off a full re-index when we deploy.
1. Complete #1020 in a backwards compatible way with the current indexing format (which basically means keep the helper, but change the indexing to drop the druid).

**Comment by jkeck** [comment]
One concern I have about `#2` is what would the admin experience be for that?

Would both facets exist simultaneously? Would we remove the old facet configuration all together?

**Comment by mejackreed** [comment]
I had a similar concern about that (option 2), and things not getting cleaned up (lingering around for infinity).

**Comment by jkeck** [comment]
If we can pull option 4 off, we might have the best of both worlds.  We would prob. want to keep a TODO around about removing the helper if we ever end up doing a re-index and/or can validate that all documents that have a collection indexed have been updated.

**Comment by jkeck** [comment]
Closing this, as we've identified an alternate solutions and opened issues them.
