### ISSUE TITLE
Expose content_search implementation through to VT test exhibit

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/exhibits#1038]
Once we have a version of the app up, we need to surface the content_search implementation through to the VT test exhibit so we can begin to experiment with it.

Currently, this is deployed within UAT; not sure if we need a feature flag to allow us to pull from `embed-uat` instead of `embed-prod`.

**Comment by jkeck** [comment]
I'm exploring the possibility of using the exhibit specific manifest configuration for this.  I know this isn't a manifest, but it's trying to accomplish very much the same thing (e.g. for an exhibit, we want to define a separate end-point to load the embed).  I think it's possible, but just want to make sure we don't abuse the feature...

**Comment by jkeck** [comment]
Looking into an exhibit specific feature flag based approach.
