### ISSUE TITLE
Design for presenting AV content and transcripts together

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/exhibits#1047]
Per the [December 14](https://consul.stanford.edu/display/VT/2017-12-14+Requirements+analysis) meeting with the VT stakeholders, we should prepare a design for the presentation of audio or video side by side with their associated transcript. 

A key feature is the ability to synchronize the AV content and the transcript when a time-coded transcript is available. For example:

* Playback of the AV should highlight the current point in the transcript
* Changing of the AV playback point should move the transcript to the associated point
* Selecting a position in the transcript should move the AV playback to that point

An example provided by one of the stakeholders is this [Stanford edX course](https://lagunita.stanford.edu/courses/course-v1:FSI+NuclearTerrorism+Fall2017/courseware/5281d29bb54b429d8c6071bc9ca68596/8a56e50379444ddf9b2acc227ad0d6f2/). 

Screenshot

![screen shot 2018-01-15 at 11 58 29 pm](https://user-images.githubusercontent.com/73732/34977728-83c1214c-fa50-11e7-9f33-0fde0874d176.png)

**Comment by ggeisler** [comment]
@anarchivist This ticket provides some helpful context, but is it different from the goal of #1026?

**Comment by anarchivist** [comment]
I completely overlooked that I created a ticket before break! I'll copy the context from this ticket to #1026 and close this one.
