### ISSUE TITLE
Display each instance of abstract element on new line instead of concatenating

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/exhibits#1051]
Abstracts are often a prose paragraph of complete sentences ending with a period, so concatenation with "and" is not appropriate. Per LC MODS guidelines, this field is repeatable, and in particular MODS records converted from MARC may have multiple instances of the abstract field.

Example: https://exhibits.stanford.edu/time-travel-japan/catalog/fr878dp2426

Related issue in mods_display gem: https://github.com/sul-dlss/mods_display/issues/54

**Comment by ggeisler** [comment]
@arcadiafalcone Can a single abstract field be multiple paragraphs? Or would each entry, if the field is repeated, only consist of a single paragraph?

I agree with your suggestion, just trying to figure out if we can simply display each field instance in a separate paragraph, without having to use bullets for each instance as we did with the Notes field (given the abstract field is more narrative, it feels less desirable to present the paragraphs with bullets, though not terrible if it makes more sense).

### Ideal (ignore vertical gray bars)
> Map showing major bus routes throughout Okinawa; includes Okinawa basu, Gin basu, Sakura basu, Tōyō basu, Shōwa basu, Aima basu, Aragaki, Hirao basu, Okinawa Ao basu, Kyōwa basu, Sankyō basu, Daiichi Kōtsu, Naha basu, Shuri basu operated routes. Also includes directory of bus companies in Okinawa Hontō. 

> "A map of the Islands, surrounded by colorful advertisements. One is for Bireley's Orange drink, which was introduced in to Japan, in a bottle, in 1951, and put into cans in 1957. As the advertisement shows the drink in a bottle, therefore the circa date of 1955."--Bookseller's note.

### Less Ideal

- Map showing major bus routes throughout Okinawa; includes Okinawa basu, Gin basu, Sakura basu, Tōyō basu, Shōwa basu, Aima basu, Aragaki, Hirao basu, Okinawa Ao basu, Kyōwa basu, Sankyō basu, Daiichi Kōtsu, Naha basu, Shuri basu operated routes. Also includes directory of bus companies in Okinawa Hontō. 

- "A map of the Islands, surrounded by colorful advertisements. One is for Bireley's Orange drink, which was introduced in to Japan, in a bottle, in 1951, and put into cans in 1957. As the advertisement shows the drink in a bottle, therefore the circa date of 1955."--Bookseller's note.

**Comment by arcadiafalcone** [comment]
I think the vast majority of multiple abstract instances in our data are from MARC conversions, which would not contain paragraphs. I don't know of any actual examples in our data, but the two scenarios I can think of that could combine paragraphs and multiple abstracts would be 1) data mapped from other sources, such as a FileMaker Pro database, and 2) multilingual metadata with the same abstract given in two languages.
