### ISSUE TITLE
Remove specific resources from the Parker Index

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#1054]
We have a situation in which we have nearly 10K non-working annotation objects (page-level details) in the Parker index. These are duplicates of working annotation lists.

These need to be removed very soon.

It would be good to get feedback from the team about how best to effect this update in the index:
a) clear out all page-level details and reindex
b) clear out entire index for Parker and reindex
c) build admin/curator tools to allow admin/curators to self-serve this kind of request
d) other

Note, this is related to #1053 - and approach might be influenced by that ticket.

**Comment by jkeck** [comment]
It looks like there are just over 10k documents that have not been updated w/ the latest re-index of parker.  @blalbrit if you could spot-check/verify that this looks right to you (based on the link below), that would be awesome.

a) clear out all page-level details and reindex
* I think we can narrow the scope more so we don't have to remove the good documents in this process (given the last_updated date)

b) clear out entire index for Parker and reindex
* I think this would be the easiest to do in a very simplistic manner, but feel like the impact of removing all Parker content from the exhibit is really high and this should be an absolute last resort.

c) build admin/curator tools to allow admin/curators to self-serve this kind of request
* I would love to do this upstream in Spotlight, it's a highly desired feature, but not trivial to implement.

d) other
* Using the link below (filled in appropriately w/ our solr url) we can generate a list of the ~10k identifiers.  We have a script that was written for a previous document removal that could easily take those out of solr.  We would then want to use that same druid list to do some cleanup in the database, which I would need to do a bit more investigation about what that would involve (we don't have anything that can automate that currently)

https://solr-url.example.com/solr/exhibits_prod/select?indent=on&q=format_main_ssim:%22Page%20details%22&wt=json&fl=id,last_updated&fq=last_updated:[2017-01-01T00:00:00Z%20TO%202017-12-31T00:00:00Z]

Happy to entertain alternate solutions as well.

**Comment by blalbrit** [comment]
@jkeck - spot-checked and confirmed. those are the offending page details. thanks for the last_updated tip - that is extremely helpful in this situation, and agree completely with your approach in d) above.

So if I understand that approach, removing the list of bad ids from solr will remove the incorrect page details from the live Parker instance, but if we were to reindex before the database side of things is taken care of they would annoyingly reappear. Is that right?

If so, I wonder if we could prioritize cleaning up the solr index and I would then tell the Parker librarians (and myself) not to hit reindex until further notice. That would give the users a better experience, for sure.

**Comment by jkeck** [comment]
Yeah, that would be a possibility, looking over the spotlight code, I _think_ we'll be okay re-indexing w/o clearing out the database (that's more just for good database hygiene 😉).  Particularly given the fact that the solr documents themselves haven't been updating w/ subsequent re-indexes, I think we're good there.

**Comment by jkeck** [comment]
@blalbrit the database cleanup should be complete.  Feel free to close this ticket if things are looking good to you.

**Comment by blalbrit** [comment]
Looking awesome @jkeck - thanks for a very quick turn-around on this!
