### ISSUE TITLE
Make viewer full-width of item show page

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1062]
This has been discussed before and I can't remember if there is a reason we haven't done it, but unless there are objections I suggest we update the layout of the item show page to give the viewer full-width. This will match the layout of the item show page in an exhibit where the Mirador viewer is configured as the viewer, and it will provide more usable space in the viewer for zooming, show the info panel, etc.

Here's a rough idea of how it will look with the change:

----
<img width="525" alt="viewer-full-width" src="https://user-images.githubusercontent.com/101482/35460646-f7530aea-02a1-11e8-95b8-906d87c5a701.png">

----
Getting to that includes these updates:

* Make the viewer take 100% of the width, from 50%.
* Increase the height of the viewer (the current height is arguably too limited and that limitation will be more noticeable with the increased width). It's hard for me to suggest the optimal height without actually implementing it, so I suggest we experiment with the height setting, but as a start I'd suggest `600px` (or possibly using `65vh` for a more responsive height).
* Change the width of the metadata `dl` so it doesn't span the full-width of wide pages. I'd suggest using `width: 85ch;` (it looks like it is set to `50%` on the page when using the Mirador viewer, but I think `width: 85ch;` might work better at most viewport widths).
* Add spacing between the bottom of the viewer and the start of the `dl` (20px), but that might be better addressed in #1063, which suggests adding a Purl link below the viewer, if we implement that ticket.

**Comment by anarchivist** [comment]
This would certainly be a nice to have for VT.
