### ISSUE TITLE
For exhibits with the Mirador-enabled viewer, any "add slot..." option is unresponsive

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1065]
Reported by Curator Reagan Murphy-Kao for her Travel Through Time exhibit

**Comment by anarchivist** [comment]
Confirmed on 1/29 sprint planning; requires more testing and info. Confirmed that this is also happening on the Secret Service exhibit.

**Comment by jkeck** [comment]
I did a little digging and there are currently 7 published exhibits using the Mirador viewer:
- parker
- time-travel-japan
- burke_mss
- mss
- secret-service
- epl
- medieval

**Comment by jkeck** [comment]
This is our current configurations for all non-parker mirador viewers: https://github.com/sul-dlss/exhibits/blob/40ef5fed2bfa16ba6d6956036fbac4ee75e47bb3/config/settings.yml#L44-L51

Maybe there is a miss-understand of what `sidePanelVisible` means/does in this context?

**Comment by anarchivist** [comment]
Fixed by sul-dlss/purl#208; @caaster, please confirm and close.

![screenshot](http://g.recordit.co/AB2NUy2hqS.gif)

**Comment by caaster** [comment]
Confirmed. Fixed.
