### ISSUE TITLE
Exhibit specific: Unable to reindex Stanford Community Centers exhibit

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1068]
Daniel Hartwig filed a feedback ticket on 26 Jan 2018. The following exhibit does indeed seem "stuck" and unable to reindex:
https://exhibits.stanford.edu/community

I am able to successfully reindex other exhibits, but not this one.

Daniel needs to publish the exhibit, but before he can he needs to reindex it.

**Comment by jkeck** [comment]
It looks like this is stuck in a failure loop due to trying to index references to a missing image.  Will need a bit of time to do some sleuthing.

**Comment by jkeck** [comment]
I believe I found the offending uploaded document that was in a stale/uncompleted state and had no images/solr document associated with it.  I've removed that record and kicked off a re-index (which appears to be running).

Please feel free to close if you can confirm.

**Comment by caaster** [comment]
@jkeck do you have the druid for the offending document by any chance?

**Comment by jkeck** [comment]
It was an uploaded document (e.g. not from the SDR).  We shouldn't run into these problems w/ SDR documents, its when thing go wrong in the process of uploading a document directly to the exhibit that this seems to crop up.

**Comment by caaster** [comment]
Fixed
