### ISSUE TITLE
Browse categories showing inaccurate item totals

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1103]
Some, but not all, browse categories in more than one exhibit seem to show inaccurate counts of the items in that browse category. 

In the cases I've found, the browse category always shows more items than should be in the category. That is, the counts on the browse landing page of the exhibit show the number of items that **should** be in each category, but when you click on a browse category its show page shows a different (always higher) count of items (next to the category title), and the items included in the results of the  category are consistent with that higher number (i.e., as if the category is no longer based on the query that was used to show the number of items on the browse landing page).

Some examples:

The [browse landing page of Fitch](https://exhibits.stanford.edu/fitch/browse) shows 32 items for the "Thomas Gilmore, the black sheriff of Greene County" category. But when you click on it, the [show page for Thomas Gilmore, the black sheriff of Greene County](https://exhibits.stanford.edu/fitch/browse/thomas-gilmore-the-black-sheriff-of-greene-county) says there are 2902 items (almost all items in the entire exhibit) and all those items are included in the category results.

Almost all the categories for Fitch show the same issue, always including 2902 items instead of the ~30 to 100 items most categories should have.

There are some categories that are okay (mostly at the bottom of the browse page), such as "[Fitch Favorites](https://exhibits.stanford.edu/fitch/browse/fitch-favorites), which indicates 9 items on both the browse landing page and the category show page.

Spot-checking other exhibits, some don't seem to have any similar issue but at least one other one does: [Helen Mayer Harrison and Newton Harrison](https://exhibits.stanford.edu/harrison/browse). "Lagoon Cycle" is correct, for example, but "Trümmerflora, The Topography of Terrors" should have 2 items, while the [category page ](https://exhibits.stanford.edu/harrison/browse/trummerflora-the-topography-of-terrors)includes 346 (all items in the exhibit, I believe).

**Comment by jkeck** [comment]
I wonder if this is a string vs symbol issue introduced in https://github.com/projectblacklight/spotlight/blob/0a3e4302e1240efbd084e7cd2d833e2f826f310e/app/controllers/spotlight/browse_controller.rb#L42

**Comment by camillevilla** [comment]
So I agree with the change that Jessie is suggesting. I'm hoping it will be as simple as changing `@search.query_params[:q]` to `@search.query_params["q"]`. Currently, categories that are not working return `nil` for `query_params[:q]`. Working categories will return the query string (e.g. "mh046jn5172"). 

I'm pretty puzzled as to WHY these seemingly identical browse categories are responding to `query_params[:q]` in totally different ways...

## Examples


❌[Thomas Gilmore, the black sheriff of Greene County](https://exhibits.stanford.edu/fitch/browse/thomas-gilmore-the-black-sheriff-of-greene-county) 
```ruby
2.4.0 :006 > Spotlight::Search.find(262).query_params
 => {"f"=>{"format_main_ssim"=>["Image"]}, "q"=>"jz603wz5203", "search_field"=>"search"}
2.4.0 :007 > Spotlight::Search.find(262).query_params[:q]
 => nil
```

❌[SCLC Civil Rights Campaigns, 1965-1966](https://exhibits.stanford.edu/fitch/browse/sclc-civil-rights-campaigns-1965-1966)
```ruby
2.4.0 :010 > Spotlight::Search.find(266).query_params
 => {"f"=>{"format_main_ssim"=>["Image"]}, "q"=>"fs479kv1719", "search_field"=>"search"}
2.4.0 :011 > Spotlight::Search.find(266).query_params[:q]
 => nil
```

✅[Fitch Favorites](https://exhibits.stanford.edu/fitch/browse/fitch-favorites)
```ruby
2.4.0 :015 > Spotlight::Search.find(316).query_params
 => {"f"=>{"format_main_ssim"=>["Image"]}, "q"=>"mh046jn5172", "search_field"=>"search"}
2.4.0 :016 > Spotlight::Search.find(316).query_params[:q]
 => "mh046jn5172"
```

**Comment by jkeck** [comment]
```
