### ISSUE TITLE
Unable to add items or reindex items in an exhibit

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1107]
Reported by user Amy Hodge for https://exhibits.stanford.edu/data:

"I am trying to add a collection druid to this collection but it doesn't seem to be working. I add mp757fq0674 to the list of items and clicked "Add items" but even when I have tried to reindex all the items in my collection, this single item in this collection, jf481sc6894, never shows up in a search. Nor does the collection itself, though I can reload the page and see that the collection druid is in the item list."

I have validated this behavior in a test exhibit (unpublished) that I use in exhibits-prod

**Comment by anarchivist** [comment]
We think #1105 fixes this, but it has yet to be deployed.

**Comment by jkeck** [comment]
Deployed this morning in v1.16.1
