### ISSUE TITLE
University Counsel image pulldown request for copyright infringement

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1109]
Daniel Hartwig requested via email at 4:24 pm today. @jkeck is on it. Image was uploaded directly (perhaps via a widget?): https://exhibits.stanford.edu/uploads/spotlight/attachment/file/510/size_810_16_9_Sergey-Brin-e-Larry-Page.jpg

**Comment by jkeck** [comment]
I have confirmed this was a `Spotlight::Attachment` which is what is backs the storage of images uploaded via the sir-trever image upload widget.

I removed the reference to the attachment in the database as well as the original, small, medium, and large derivatives we created on disk.
