### ISSUE TITLE
Keyword searches in exhibits-stage lead to "Sorry, I don't understand your search" message

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/exhibits#1113]
![](http://g.recordit.co/DQ0RbODSGg.gif)

**Comment by jkeck** [comment]
This is because of the current work I'm doing w/ highlighting.  Solr is throwing errors.

**Comment by jkeck** [comment]
This has been resolved by re-indexing the content.  It was in a state where it had been re-indexed w/o termOffsets and then we were configuring to use a highlighter that requires offsets.  Re-indexing w/ the new configuration seems to have solved this.  Please feel free to re-open if you see this again.
