### ISSUE TITLE
Identify YAML keys for localization to establish level of effort needed by translators

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/exhibits#1137]
We need to identify the subset of YAML keys needed to translate user-facing parts of the UI, to accurately reflect the level of effort needed by translators (particularly at SUL). Based on analysis, these keys are sourced from locale files in Blacklight, blacklight-maps, blacklight-gallery, and spotlight.

Ref projectblacklight/spotlight#1972.

**Comment by mejackreed** [comment]
https://github.com/projectblacklight/spotlight/pull/1973 might help with this.

**Comment by mejackreed** [comment]
Potential unused keys:
`spotlight.searches.edit.query_params`

**Comment by mejackreed** [comment]
This has turned into a much larger task unfortunately and is quite involved. I think a hands on approach is needed once a target language and translator to undertake this. I estimate at least 4 hours of collaborative work directly with a Spotlight developer.

**Comment by anarchivist** [comment]
Closing since suggestion of creating of local demo/test exhibit for translation is a better target.

**Comment by anarchivist** [comment]
These are:

```
activemodel.attributes.spotlight/contact_form.email
activemodel.attributes.spotlight/contact_form.message
activemodel.attributes.spotlight/contact_form.name
cancel
helpers.action.cancel
submit.contact_form.create
submit.contact_form.created
spotlight.about_pages.contacts.header
spotlight.header_links.contact
spotlight.shared.report_a_problem.honeypot_field_explanation
spotlight.shared.report_a_problem.title
```
