### ISSUE TITLE
Implement routing scheme for locale switcher

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/exhibits#1138]
See #984, projectblacklight/spotlight#1920 for details about how to implement.

**Comment by mejackreed** [comment]
Checkout: https://github.com/sul-dlss/exhibits/compare/spotlight-2

**Comment by mejackreed** [comment]
Outstanding issues: 

via @jkeck 

 - [ ] I was seeing the home page fail out (which you would need > 1 exhibit locally to reproduce).
 - [ ] Also, when there were docs in an exhibit blacklight’s /track path wasn’t working (making clicking into any document from results error out).

**Comment by jkeck** [comment]
Closed by #1164
