### ISSUE TITLE
Prepare documentation about the localization process for Exhibits

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/exhibits#1148]
Per the 4/10/18 storytime, we need to prepare documentation about the process to localize an exhibit at Spotlight at Stanford. Items to cover include:

* Who needs to be involved (at least a developer and someone with language expertise) 
* A rough overview of the protocol - introduce YAML keys, the different sources for localized content, any workflow considerations, etc.
* Estimated time necessary (at least 4 hours, per @mejackreed's estimate)

**Comment by mejackreed** [comment]
@caaster where would you like these docs to live?

**Comment by anarchivist** [comment]
* Related audiences: curators/potential curators; service team

As of 4/24, @ggeisler has good first drafts for this content.

**Comment by laurensorensen** [comment]
Comments during VT meeting suggest that this ticket is sufficient and the 4 years old documentation seem to be working.
