### ISSUE TITLE
Restore druids added list to https://exhibits.stanford.edu/radarfilm

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1150]
Exhibit creator has been adding druids but deleting all previous druids added, each time she adds a new druid to the exhibit. She has been told not to do this, and to always add druids to the existing list.

**Comment by cbeer** [comment]
I'm only seeing one DOR-backed item in the exhibit; should there be more? It seems like the other 25 items are uploaded items.

**Comment by caaster** [comment]
Got further clarification from the exhibit creator. There should only be one druid so no action is required on this ticket. Creator added all other objects from her desktop. She kept trying to re-add some of the same objects during the time we were deploying the app to prod which resulted in some duplicate images being added, but she can live with the dupes being there.
