### ISSUE TITLE
Need better way to add druids to an exhibit

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1151]
Currently, exhibit creators must add new druids to their existing druid list as opposed to deleting druids added from the list before adding a new druid. This is confusing to users, despite this being in the training and documentation. It would be helpful if we could come up with a more intuitive way of adding druids to an exhibit.

**Comment by mejackreed** [comment]
It might be good here to understand the technical concerns w/ adding a druid, then replacing it with another druid. I'm not sure I understand the implications.

**Comment by caaster** [comment]
Closing. At least we display help text now, which somewhat mitigates the potential problems.
