### ISSUE TITLE
Create translations demo exhibit

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/exhibits#1158]
## Goal
- Help the service team and curators assess the effort required to translate an exhibit
- Illustrate the gap between UI-translatable elements and elements that require locale file translations

## Requirements
- TBD

## Questions
- [ ] Should this live in stage or prod?

**Comment by anarchivist** [comment]
From today's meeting with @jkeck, @ggeisler and @caaster:

* For the VT demo, this will be the `vt-test` exhibit in stage
* Needs a few about pages/feature pages/browse categories

Ref #1160

**Comment by ggeisler** [comment]
Done!
