### ISSUE TITLE
Consolidate image indexing logic to just use the manifest

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#1168]
With our current SDR indexing pattern, and with the additional complexity added of virtual objects in https://github.com/sul-dlss/exhibits/pull/1166 we would like to consolidate this image indexing logic to just go look at the manifest instead of the current approach of the sketchy contentMetadata logic

**Comment by corylown** [comment]
Completed by https://github.com/sul-dlss/exhibits/pull/2421
