### ISSUE TITLE
[exhibits/stage] ActionView::Template::Error: undefined method `catalog_facet_url' for #<ActionDispatch::Routing::RoutesProxy:0x00007f8ba0f03d30>

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/exhibits#1171]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49092/faults/37671820)

**Comment by corylown** [comment]
Looks like this might still be an issue. Here's an updated link to the honeybadger error: https://app.honeybadger.io/projects/49092/faults/108526139

**Comment by dnoneill** [comment]
closed by https://github.com/projectblacklight/spotlight/pull/3134
