### ISSUE TITLE
Reindexing is erroring out on https://exhibits.stanford.edu/sftjf

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1178]
On Sunday, 13 May around 8:30 pm, as I was attempting to reindex the following exhibit (https://exhibits.stanford.edu/sftjf) I received this error message.

<img width="1232" alt="screen shot 2018-05-13 at 8 32 44 pm" src="https://user-images.githubusercontent.com/3210225/40006434-40f885ce-574f-11e8-96a9-060ecfbff05d.png">

We are on a tight timeline to build this exhibit in collaboration with SFTJF outside partners, and reindexing is essential so we can have access to the most current descriptive metadata for the objects in the exhibit. We will need to reindex a couple of times at least over the next few weeks.

**Comment by caaster** [comment]
NOTE: there is no geoospatial metadata associated with druid:zm764wc3407, the object/step where the reindex job errored out.

**Comment by mejackreed** [comment]
Getting errors on `zm764wc3407`

```
Error: {"responseHeader":{"status":400,"QTime":2135},"error":{"metadata":["error-class","org.apache.solr.common.SolrException","root-error-class","java.text.ParseException","error-class","org.apache.solr.update.processor.DistributedUpdateProcessor$DistributedUpdatesAsyncException","root-error-class","org.apache.solr.update.processor.DistributedUpdateProcessor$DistributedUpdatesAsyncException"],"msg":"Async exception during distributed update: Error from server at http://sul-solr-b.stanford.edu:8080/solr/exhibits_prod_shard1_replica2: Bad Request\n\n\n\nrequest: http://sul-solr-b.stanford.edu:8080/solr/exhibits_prod_shard1_replica2/update?update.distrib=TOLEADER&distrib.from=http%3A%2F%2Fsul-solr-c.stanford.edu%3A8080%2Fsolr%2Fexhibits_prod_shard1_replica3%2F&wt=javabin&version=2\nRemote error message: Unable to parse shape given formats \"lat,lon\", \"x y\" or as WKT because java.text.ParseException: Expected a number input: ENVELOPE(KQED, corporate, host, (Berkeley,)","code":400}}
```

**Comment by cbeer** [comment]
The geospatial metadata is in zp741cd0081, which is a member of that collection.

**Comment by caaster** [comment]
@arcadiafalcone I just emailed Frank with a high priority request to look into this.

**Comment by caaster** [comment]
The metadata has been remediated & the exhibit has now successfully reindexed.
