### ISSUE TITLE
Feature request: bulk upload of exhibit tags for SDR and non-SDR exhibit objects

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1182]
As an exhibit creator, I need to create exhibit tags to enhance my ability to create specific browse categories for my exhibit. When I need to create exhibit tags for more than a few objects, this is a labor intensive activity. For more than 50-100 objects, I don't have the resources to create tags individually, which makes my ability to tell my exhibit story -- with custom browse categories -- not as effective. If there was a way to bulk-upload exhibit tags this would be very useful -- for objects from the SDR in my exhibit, as well as for objects I upload to my exhibit from my desktop.

**Comment by caaster** [comment]
@ggeisler will this need design?

**Comment by ggeisler** [comment]
I think so. I'll add the label.

**Comment by caaster** [comment]
On further thought, I think this may be a request for 3 different (yet related) features:
1) ability to bulk upload exhibit tags for items in the exhibit from the SDR
2) ability to bulk upload exhibit tags for items in the exhibit I've uploaded from my desktop
3) ability to bulk upload exhibit tags for items in the exhibit I've uploaded using the CSV feature (include extra field(s) on the CSV template for exhibit tags, by chance?)
