### ISSUE TITLE
Titles have disappeared from uploaded objects in https://exhibits.stanford.edu/medieval

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1184]
Exhibit creator Lora Webb reported on Monday, 14 May, that all titles disappeared from the following exhibit:
https://exhibits.stanford.edu/medieval

**Comment by mejackreed** [comment]
related to https://github.com/sul-dlss/exhibits/commit/9b2c20042dd493154cb393add973050cf0ef9902 ?

**Comment by jkeck** [comment]
Okay, we have gotten the configs updated in prod, ran an additional migration script (to update the related sidecars), and re-indexed.

This seems to have addressed many of the missing titles.  Doing a quick search through the database, there are still 31 total objects that don't have titles (many of which are in the medieval exhibit), and I'll work with @caaster to figure out what to do with those.

**Comment by caaster** [comment]
Titles missing from medieval exhibit were not expected to be there, according to exhibit creator, as they hadn't yet been added. I am good with closing this ticket as the other missing titles were all onesies, twosies, and many from test exhibits. I consider this issue to be resolved.
