### ISSUE TITLE
Exhibit creators report "save" not working

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1188]
Here are the user reports, verbatim:

1. From exhibit creators: https://exhibits.stanford.edu/sftjf
![screen shot 2018-05-29 at 2 34 01 pm](https://user-images.githubusercontent.com/3210225/40686841-822fb9fe-634d-11e8-8af2-9f802efed21c.png)

2. From Daniel Hartwig:
Re: https://exhibits.stanford.edu/oral-history/dashboard
![screen shot 2018-05-29 at 2 36 37 pm](https://user-images.githubusercontent.com/3210225/40686902-c0771766-634d-11e8-988f-1dcca1580478.png)

3. Also from Daniel Hartwig -- this may or may not be related:
![screen shot 2018-05-29 at 2 38 46 pm](https://user-images.githubusercontent.com/3210225/40687042-34d00a14-634e-11e8-9d6d-6047c329c90b.png)

**Comment by jkeck** [comment]
Oral History issues may be related to https://app.honeybadger.io/projects/49092/faults/37151357

**Comment by caaster** [comment]
Closing this ticket as we have stopped receiving complaints about this problem.
