### ISSUE TITLE
Deploy latest version of exhibits to eportfolios

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1194]
Version 1.18.2 of exhibits needs to be deployed to eportfolios. An eportfolios user has reported intermittent save failures, by filing a feedback ticket on 5 June at 4:09 pm.

**Comment by jkeck** [comment]
Deployed [v1.18.2](https://github.com/sul-dlss/exhibits/blob/master/CHANGELOG.md#1182---2018-05-31) this morning
