### ISSUE TITLE
Update sidebar links

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1199]
exhibits.stanford.edu sidebar links need updating:

1) link to microsite either disappeared recently, or was never added:
https://library.stanford.edu/research/spotlight

2) the current top 2 links are partially duplicative -- could we delete the first link, and keep the second link but rename it? or some other better solution?

**Comment by camillevilla** [comment]
Is this closed by #1259 and #1254?

**Comment by ggeisler** [comment]
Good question @camillevilla. #1259 did address the second item on @caaster's list. But I don't think we addressed the first one.

@caaster Do you still think we need a link pointing to the microsite from the Exhibits home sidebar links? The EoE obviates the need a bit, but the microsite does have some high-level info the EoE does not. I guess the question is how likely is it that a user already at exhibits.stanford.edu would benefit from the first few pages of the microsite? Is that (presumably) rare case worth adding another link to the sidebar on exhibits home?

**Comment by caaster** [comment]
Yes thank you @camillevilla & @ggeisler for this reminder. I believe we need a link to the microsite. Not just because it contains info that is not in the EoE, but also because it is very buried on library.stanford.edu. I'm open to whatever link text seems best. Maybe `Spotlight at Stanford microsite` ?

**Comment by ggeisler** [comment]
Okay, how about this @caaster 

<img width="304" alt="stanford_university_libraries" src="https://user-images.githubusercontent.com/101482/47683273-57d0b480-db8c-11e8-93c7-000a15a592cf.png">

**Comment by caaster** [comment]
@ggeisler perfect thanks
