### ISSUE TITLE
Problem with SAVE button

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1200]
Feedback ticket received at 11:30 am on 18 Jun 2018

From: "Penelope Van Tuyl" <pvantuyl@stanford.edu>

When I was adding a feature page to the Virtual Tribunals exhibit, I clicked "Save" and got sent to a System Status page for searchworks that had a twitter feed for SUL. Not sure what that bug was all about...

----
REMOTE_IP
10.34.229.198
USER AGENT
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
EXHIBIT
Virtual Tribunals
CURRENT_URL
https://exhibits.stanford.edu/virtual-tribunals/feature

**Comment by jkeck** [comment]
Relevant HB report: https://app.honeybadger.io/projects/49092/faults/38271095

**Comment by caaster** [comment]
Hi @jkeck can you explain the "record not unique" error to me? So, something Penelope was trying to create was duplicative, and...then I am lost. I'd like to be able to give her feedback on what kind of user error to avoid making - if this in fact is the problem?

**Comment by caaster** [comment]
This issue is related to #1206 (which I am keeping open), so I'm closing it.
