### ISSUE TITLE
Idea: Widget to link-back to spotlight exhibits from other websites (like searchworks and purl)

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/exhibits#1203]
Wouldn't it be cool if when you found an item in Searchworks that happened to be part of an exhibit, you could see this in the Searchworks results page with a link right back to the exhibit itself?  This would give you better context for the item you just found via search.  

So maybe we could have a embeddable JS widget that, given a druid, looks into the Spotlight solr index (via some API call?) to identify if the druid is part of an exhibits, and if so, which ones.  It then constructs a link back to the exhibit(s) in HTML that is part of the widget.  You then drop this widget into Searchworks or PURL.

**Comment by caaster** [comment]
We now do this. Yay! Closing this ticket.
