### ISSUE TITLE
Enable external IIIF resources to be viewable in the selected viewer

### ISSUE THREAD

**Issue by snydman** [sul-dlss/exhibits#1216]
External IIIF resources that are added to an exhibit should be viewable in the selected IIIF-compatible viewer for that exhibit (either UV or Mirador).

**Comment by mejackreed** [comment]
It is going to be challenging viewing external resources in UV since we don't use UV directly but call our embed service.

**Comment by snydman** [comment]
@mejackreed same with Mirador?

**Comment by mejackreed** [comment]
Much more feasible (quicker to do) in Mirador than in UV.
