### ISSUE TITLE
Reindex jobs are failing

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1220]
11:34 am, 30 July: I just tried to reindex this exhibit & the following error displayed. Wondering if I should try again, or? https://exhibits.stanford.edu/sftjf/catalog/admin — it is great to see the error displayed — first time I have ever seen this before for a failed job.

![screen shot 2018-07-30 at 11 33 02 am](https://user-images.githubusercontent.com/3210225/43420736-9303a4e8-93f9-11e8-95b6-aa78844d96ab.png)

1:05 pm, 30 July: Since I had a bonafide failed reindex, and since I noticed that one of the objects I was trying to reindex was stuck in an error state in Argo — and on the off-chance that was the problem — I just tried to reindex again. Failed again around 1:03 pm. This time with no error message — the progress bar which was at 50% just zeroed out & stopped.

![screen shot 2018-07-30 at 1 08 17 pm](https://user-images.githubusercontent.com/3210225/43420768-a9cc8b7c-93f9-11e8-8b83-d09b00f31b89.png)

In addition, I am noting that Ben is having the same reindex fail experience, documented in the slack channel #dlss-spotlight-dev, in the thread starting at 11:10 am on Friday, 27 July.

**Comment by blalbrit** [comment]
See: https://app.honeybadger.io/projects/49092/faults/38839550#notice-summary
