### ISSUE TITLE
Can't save long versioned feature page

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1225]
Discussed with @jkeck and he knows what the cause and solution are. Here's the related Honeybadger link: https://app.honeybadger.io/projects/49092/faults/38702349#notice-summary

For reference, here's the user feedback that raised the issue:

> I was having trouble editing the Kid Ory page: https://exhibits.stanford.edu/sftjf/feature/kid-ory My edits would not save. I kept getting the Stanford "Check System Status" error page. So I created a brand new page called Kid Ory 2: https://exhibits.stanford.edu/sftjf/feature/kid-ory-2 I reentered all the text and it saved the edits just fine. Then I added 2 images with druid numbers and thats when I ran into the same issue.. I cannot save any changes to this new page now. I keep getting the Stanford "Check System Status" error page. We are on deadline with these materials and would appreciate a quick response so we can proceed and meet our go-live date. Thank you!

https://jirasul.stanford.edu/jira/browse/EXHBTF-814

**Comment by jkeck** [comment]
This is how we addressed it upstream in spotlight: https://github.com/projectblacklight/spotlight/pull/2067

We'll need to do the same thing with (at least) the `object` column of the `versions` table.
