### ISSUE TITLE
Lingering reindex messages after a reindex completes

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#1226]
Reported originally by @caaster 

After a reindex completes (with progress bar successfully filling), a lingering message is displayed.

![image](https://user-images.githubusercontent.com/1656824/43852478-903c982a-9afa-11e8-8d94-f96f42f50aa3.png)

**Comment by caaster** [comment]
I am closing this ancient ticket. If this concern resurfaces (although fyi the reindexing status display has always been somewhat inconsistent/wonky), then we can create a new ticket.
