### ISSUE TITLE
Remove locale files that should be provided through upstream repos

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1228]
As a temporary measure, we've added a small handful of locale files for Chinese and Portuguese to Exhibits. When these translations are provided through Spotlight, Blacklight-gallery, and Blacklight-heatmaps, we should remove them from the exhibits application.

**Comment by camillevilla** [comment]
### Spotlight
- [ ] Chinese
- [ ] Portuguese

### blacklight-gallery
- [ ] Chinese
- [ ] Portuguese

### blacklight-heatmaps
- [ ] Chinese
- [ ] Portuguese

**Comment by mejackreed** [comment]
I couldn't find the blacklight_heatmaps translations. Are those hidden away somewhere?

**Comment by mejackreed** [comment]
They are in blacklight-maps, but should be in blacklight_heatmaps.

**Comment by mejackreed** [comment]
This is now resolved.
