### ISSUE TITLE
Stanford Atlas exhibit reindex job fails

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1236]
This afternoon Josh Schneider attempted to reindex this exhibit just after 3:30 pm. The reindex job started to run -- I saw it at 6% on the progress bar -- and within the next 2-5 minutes the progress bar reverted back to 0% and closed. It now appears that the reindex job has failed:
https://exhibits.stanford.edu/ua-maps-drawings

There are multiple collections in this exhibit, and many single druids. There are also virtual objects in some of the collections, and I wonder if this is causing a problem?

This exhibit should contain all of the images from a long-running digital collections project (3 1/2 + years). I am trying to close out the project and write a final report that will be sent to our campus stakeholders, so it is important that at some point sooner rather than later, we get this exhibit to reindex.

**Comment by cbeer** [comment]
I haven't seen the entire job fail yet, but there were some individual item errors because the collection(?) `fp486hj1517` was purged, but is still listed as the collection for a whole bunch of items.

**Comment by caaster** [comment]
@cbeer - I have reached out to Josh Schneider regarding this ticket, asking for more info. Please stay tuned.

**Comment by cbeer** [comment]
With #1297 and #1298, we no longer abort the entire indexing process when geo metadata syntax errors occur, so the exhibit was able to fully reindex. There remain various data issues with the exhibit that may cause individual items or collections to fail to reindex, and these should be visible from the item status page. These include ~81 objects that have invalid geo metadata:

```
hp656rh4584, kn887cy9953, qb323kd8785, xy777pc0218, dm950dt9108, wd831jj2040, pd479wt3843, gg040ts8434, td700qd1364, vj144gc9585, vg769kx4611, qg786bw1417, km150rk0553, fn048yb0399, pv074tf4597, fs728zb9197, ff007rt8972, mc032vw0464, mv867bn2908, wb508qb7313, wv359fn8587, wp783sr8146, qw245wy0241, wq959qy8947, yr361dm9055, pj797sc2066, sh653rk3294, mj464jk9254, qd031hr6475, kj554py1598, xm777vm8125, vv107wx7460, rt391yd3157, hr047nj9101, xt684br0125, br056qk1625, yx067zd0194, hz949st7862, wk298pc4214, ft267zj9265, kk099wp8283, zv566zc4357, yf943db8018, qz581mp2411, dj533dw4541, pd508tt5106, cm074bc6402, hy557wf3427, wm223xh4680, qz085yd6273, gf942jy5097, xj124jv0048, kn321pf3150, xb884ws2776, vm333qq1440, hc908bf5547, qj142hx9344, yn408nh2692, rr125dg5891, qb323kd8785, kn887cy9953, tb827pm6728, yn240gk0740, yn781rq4446, tk919sq4018, db215wh4865, hp656rh4584, md202qw1712, rq678rq0596, sf631qf4895, ws709rs7902, xt604fq6362, jj274xf5646, rr125dg5891, sf631qf4895, tk919sq4018, wd831jj2040, ws709rs7902, xy777pc0218, yn240gk0740, yn781rq4446
```

as well as items that belong to collections that have been unpublished (e.g. those belonging to fp486hj1517).
