### ISSUE TITLE
Adding custom tag to exhibit item causes item title to be replaced with item druid

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1237]
I have experienced the following behavior in two unpublished exhibits:
https://exhibits.stanford.edu/warhol
https://exhibits.stanford.edu/reid-dennis

I navigate to a browse category, and select an exhibit item. I click on the "edit" button for that item. I add a custom tag (single word). I click save. The save action causes the item title to be replaced with the item druid. The custom tag is also saved. I try and edit the item again, to delete the custom tag and see if that action, once saved, will result in the title re-appearing. It does not. I spoke with Gary, and he tried to reproduce this bug in the Vatican instance, and he is unable to do so.

**Comment by blalbrit** [comment]
Just tested the above with an object from the Parker collection. In this case, it was not even necessary to add a tag, the simple action of clicking `edit` and then `save` forced the item title change.

**Comment by cbeer** [comment]
Probably related to https://github.com/sul-dlss/exhibits/pull/1177?

**Comment by caaster** [comment]
Yesterday, an exhibit creator tried to add custom tags to some items in the following exhibit: https://exhibits.stanford.edu/beautifulbooks. Predictably, the titles changed to the druids when she attempted to save the tags. Next, she reindexed the exhibit, only to find that for selected items, the druid still remained as the title, like this item for example: https://exhibits.stanford.edu/beautifulbooks/catalog/xf235zd7750. She then reported the problem to me. I reindexed the exhibit again -- just to be certain, and in fact, there are still druids that remain as titles -- the titles are not being picked up in the reindex.
