### ISSUE TITLE
Edit item UI displays multiple blank metadata fields (like title); expectation is that only tag & custom fields to be displayed

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1238]
I have experienced the following behavior in two unpublished exhibits:
https://exhibits.stanford.edu/warhol
https://exhibits.stanford.edu/reid-dennis

I navigate to a browse category, and select an exhibit item. I click on the "edit" button for that item, so that I can add a tag. I see multiple metadata fields displayed -- like title, description, etc. (with no data) in the UI. I expect to only see the tag field and any custom fields that have been added, and not the standard fields like title, description, etc. I spoke with Gary, and he tried to reproduce this in the Vatican instance, and he was unable to do so. He does not see the blank field like title, description, etc.

**Comment by cbeer** [comment]
Are you still able to reproduce this? I'm not seeing the described behavior in warhol, and reid-dennis is no longer available.

**Comment by caaster** [comment]
I am no longer able to reproduce this behavior, so I am closing this ticket.
