### ISSUE TITLE
Item Embed widget: title & heading not saving / saving dependent upon having text in text field

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1245]
When I use the Item Embed widget, I expect the ability to add and save a title, a heading, or text -- or any combination of these to be able to be added and saved. 

It appears that a title can never be saved.

It appears that a heading can only be saved if you have also added text.

Screencast below illustrates the problem, a couple of times.
https://stanford.box.com/s/tjopntmdjbnqehae32bw5euzns95oqto

**Comment by ggeisler** [comment]
Duplicate of https://github.com/sul-dlss/exhibits/issues/1208?

**Comment by caaster** [comment]
Thanks @ggeisler -- closing this.
