### ISSUE TITLE
Item Grid widget will not allow selection of uploaded items (only allows SDR items)

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1246]
When I upload items to my exhibit that are not in the SDR, I expect them to be available for selection in the Item Grid widget. 

Unfortunately, uploaded items are not available in the Item Grid widget.

We tried reindexing after uploading images, just to see if that mattered. The bug is still there.

Will try one more thing to help troubleshoot, and comment back on this ticket if more information is uncovered.

**Comment by camillevilla** [comment]
Team will investigate uploaded images vs. SDR image behavior for this ticket

**Comment by cbeer** [comment]
I'm no longer able to replicate this. It's possible the uploaded item indexing fixes in #1296 fixed a much bigger issue with uploaded items.
