### ISSUE TITLE
"Sign in" from parker.stanford.edu does not work

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#1247]
From https://parker.stanford.edu/parker, clicking on 
<img width="116" alt="screenshot 2018-09-18 22 35 39" src="https://user-images.githubusercontent.com/796990/45732925-5eced500-bb93-11e8-9e46-95621adb40f8.png"> sends the user to the following page: 
<img width="1172" alt="screenshot 2018-09-18 22 35 27" src="https://user-images.githubusercontent.com/796990/45732939-6d1cf100-bb93-11e8-94a5-9de44358b6db.png">

**Comment by blalbrit** [comment]
@caaster - it's likely an ops issue.

**Comment by tallenaz** [comment]
If I sign in from [https://exhibits.stanford.edu/parker](https://exhibits.stanford.edu/parker), shibboleth will authorize me, so there is a way for exhibits admins to log in, just not presently through `parker.stanford.edu/parker`. How important is it to stakeholders to hold on to `parker.stanford.edu`? 

There may be operations options, though I'm unfamiliar with how `parker` is set up. I see that it is assigned to an IP address whose record suggests proxying/load balancing. @rsmith11 do you have some insight here as the admin of that record?

**Comment by blalbrit** [comment]
Hi @tallenaz - thanks for weighing in and @'ing Rob as well, you're right, he'll know the ins-and-outs of this set-up better than anyone.

parker.stanford.edu is the only access point we really offer to the public for Parker on the Web. The site exists within the exhibits.stanford.edu cluster, but only because it was built within that platform. It is an independent product and is marketed as such - particularly because it is co-owned by a college in the UK and the separate branding/URL path is particularly important politically.

I can make the librarians at Corpus Christi College, Cambridge, log in through exhibits.stanford.edu - of course - but for many reasons it would be better to have them go in directly from the `parker.stanford.edu/parker` landing page.

Understanding the level of effort would be helpful.

**Comment by tallenaz** [comment]
From a chat with Rob, it's possible that we can update the shibboleth config for exhibits to include a parker alias, and this would fix the issue. If it's just this, the effort would be under a day. It's also possible that we might need to put in a workgroup request for the shibboleth principal of parker. Those requests take days to weeks to complete.

We want to check in with @jonrober who's available on our end tomorrow, to see if the above plan will work. If so we can test this out in the exhibits/parker stage environment.

**Comment by jonrober** [comment]
Yes, it should just be a matter of re-creating the metadata (and certs to be on the safe side) for exhibits to include parker.stanford.edu and any other aliases exhibits has.  You wouldn't need to do a separate workgroup request unless exhibits is missing workgroups currently.

**Comment by tallenaz** [comment]
I've done the following in stage:

- re-certed shibboleth on exhibits-stage-a/b
- created a new shib service provider for exhibits-stage
- removed the service provider for stage-a/b, since they're included in the new service provider

I can now sign in successfully through parker-stage. @blalbrit can you verify parker-stage is doing what we want?

**Comment by tallenaz** [comment]
-stage looks good. will roll the fix out to prod this week.

**Comment by tallenaz** [comment]
From https://parker.stanford.edu/parker/ I click on "Sign in", am successfully logged in via shib.
