### ISSUE TITLE
Reindexing Beautiful Books exhibit does not fix bug that replaced titles with druids

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1286]
Reindexing [Beautiful Books](https://exhibits.stanford.edu/beautifulbooks) exhibit does not fix bug that replaced titles with druids. This bug is the blocker preventing the publication of this exhibit.

**Comment by cbeer** [comment]
I took a look at some of the records with druids in their title (wn630dm7862, bf423tz3138, ff110sw1559). I'm not seeing them in the list of druids on the "add items" page, explaining why they aren't being reindexed. In fact, only 87 of the the 104 objects in the index are on the list.

Just to test, I added `wn630dm7862` to the list and it was reindexed and now has a title. Before adding the rest, I want to confirm that all the records currently in the exhibit are supposed to be there?

**Comment by caaster** [comment]
@cbeer Yes, all of the records currently in the exhibit are supposed to be there. Thank you.

**Comment by cbeer** [comment]
Ok; I've switched the list of items to all 104 items in the exhibit. You might want to remind the curators to make sure to only _add_  items to the list.

**Comment by caaster** [comment]
@cbeer It is top on my list to remind the curators of this. A key item we cover in hands on training, and it is also in our creator-facing documentation.
