### ISSUE TITLE
Add Honeybadger javascript console error logging

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/exhibits#1288]
https://docs.honeybadger.io/lib/javascript/integration/browser.html

We're interested in gathering more data on #1206

**Comment by aeschylus** [comment]
Another hiccup: https://github.com/honeybadger-io/honeybadger-js/issues/99

I'm now going to try installing from npm in case the packaging is different.

**Comment by camillevilla** [comment]
Closed by #1303
