### ISSUE TITLE
Newly added slideshow widget does not display images

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1289]
Reported by exhibit creator for: https://exhibits.stanford.edu/nash. You can see broken image icon/no image display on the home page.

I verified this behavior in a test exhibit here: https://exhibits.stanford.edu/service-sandbox/feature/cathy

**Comment by mejackreed** [comment]
@caaster it seems that our slideshow widget does not support images that have viewing restrictions on them. In this case `<world rule="no-download"/><world rule="no-download"/>` prevents the size needed to view the slideshow.

I see a few ways forward here:
 - See if it is possible to remove the `no-download` rights from the content in question. This would automatically fix the issue at hand without code changes
 - Support smaller images to be displayed. (400, max-width). However this option is likely non-trivial to implement and really is not going to be a great experience for users as the max size thumb will be in the slideshow.

I'd say education that no-download images do not work in the slideshow is the best path forward. The changes needed to implement support for no-download in the slideshow would be significant and in the end will not provide that great of an experience for the end user.

I've created a slideshow for an item that has no restrictions: https://exhibits.stanford.edu/jack-test/home.exhibit-home

**Comment by caaster** [comment]
@mejackreed thank you for this key analysis and explanation.

Number one, I will add this to our documentation. It would be good to know (if you can easily determine) -- if there are other widgets that do not support display of images that have viewing restrictions. I'd like to be as comprehensive as possible in our documentation, and relieve you all from being bothered about this going forward.

Secondly, I understand about the non-trivial option, and feel that it should not be on the table. Certainly not right now, and maybe never.

Third, thanks for your very speedy response. This will enable me to get back to the exhibit creators asap, as I know they are anxious to get their exhibit published. They'll have to decide to either lift viewing restrictions, or use different widgets that are not impacted by this issue on their home page

**Comment by mejackreed** [comment]
I think a full analysis of what is/is not supported should be reticketed and prioritized separately. A basic rule of thumb to go by for now is:
 - Widgets that use sul-embed should be supported for all content scenarios
 - Widgets that no not use sul-embed need further investigation for auth scenarios besides fully public

**Comment by caaster** [comment]
@mejackreed - Do you know now which widgets use sul-embed and which do not? Or is this part of the analysis that is required?

**Comment by mejackreed** [comment]
Part of the analysis. The general rule is if you see that brown border around something its using sul-embed, see first widget in page https://exhibits.stanford.edu/jack-test/home.exhibit-home

**Comment by caaster** [comment]
@mejackreed -- thanks -- that I am aware of. Not intuitive with the slideshow widget, though. Thanks! I am closing this ticket & I'll reticket per your recommendation.
