### ISSUE TITLE
Broken display of SFTJF homepage

### ISSUE THREAD

**Issue by snydman** [sul-dlss/exhibits#1317]
From Cathy : "After changing the name of a feature page the first instance of the feature page widget on the home page (there are 2) was not displaying the feature page that I renamed (check the exhibit creator view to see what is really supposed to be happening!) When I went in to delete the old name and add the new name, the page went bonkers and came up with this display. "

![image](https://user-images.githubusercontent.com/3279382/50197802-a46b7d00-02fd-11e9-8f28-a02f2eaee82c.png)

**Comment by mejackreed** [comment]
i removed the feature page widget and then readded it. The problem is now resolved.
