### ISSUE TITLE
External IIIF resources not using title on show page

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/exhibits#1323]
External IIIF resources are not displaying a title on the show page. The show page title should use the manifest label, which is currently displayed in the results view.

## Show page (bug) 
<img width="599" alt="show page with incorrect title" src="https://user-images.githubusercontent.com/5402927/50715595-e3563e00-1032-11e9-9c16-5f85e4e4e084.png">

## Curation > Items
<img width="233" alt="item indexed with correct title" src="https://user-images.githubusercontent.com/5402927/50715614-f6690e00-1032-11e9-865a-b087bf730419.png">

## Search Results view
<img width="537" alt="search results with correct title" src="https://user-images.githubusercontent.com/5402927/50715721-64add080-1033-11e9-8323-f9ef3a99f237.png">

## Manifest
https://iiif.bodleian.ox.ac.uk/iiif/manifest/390fd0e8-9eae-475d-9564-ed916ab9035c.json
`"label": "Bodleian Library Arch. G c.7",`

**Comment by cbeer** [comment]
Fixed by #1416
