### ISSUE TITLE
SAVE button not working - a repeatable instance

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1326]
I have been able to repeat the following save error.

I navigate to an exhibit page with text, and click on the Edit button.

I make no attempt to edit the page, but I do not cancel. Instead, I simply navigate away from the page, to a different page in the exhibit.

Then, I navigate back to the page I wish to edit (the original page that I navigated away from without canceling). This time, I make an edit. I click the Save button. The popup message tells me that the page was successfully updated.

When I check to make sure the edit was successful, I discover it was not.

**Comment by jkeck** [comment]
I was just able to reproduce the behavior in a test exhibit as well.  Thank you for giving these helpful steps.

I took the same steps, but instead I refreshed the page once on the edit screen and the behavior did not exist (indicating that this may be an issue w/ turbolinks).

**Comment by jkeck** [comment]
Things to try potentially:
- Disable turbolinks on edit forms
- Disable turbolinks everywhere
- Others?

**Comment by jkeck** [comment]
Fixed in Spotlight update during #1329
