### ISSUE TITLE
"Upload multiple items" feature not working properly

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1328]
I am working with the SLAC Archivist re an exhibit that they have requested and wish to publish ASAP. Purpose of the exhibit is to commemorate the 100-year anniversary of the birth of Wolfgang K. H. Panofsky, the founder and first director of SLAC. Content featured in the exhibit will be ~100 *non-SDR* images and metadata.

Although we have a recent successfully-published exhibit featuring non-SDR content (which I did not facilitate - https://exhibits.stanford.edu/medieval), I wanted to test the "upload multiple items" feature myself first, before scheduling a Spotlight training session with the SLAC archivist. I followed the steps as outlined, below:

- I created this exhibit in stage: https://exhibits-stage.stanford.edu/cathy-s-test-exhibit
- I added the extra MD fields needed: https://exhibits-stage.stanford.edu/cathy-s-test-exhibit/metadata_configuration/edit
- I created a csv (attached) and uploaded the file to the Upload multiple items tab
(note I had to do this twice, as the first time the csv contained non-public box URLs, which Dorothy (Archivist) informed me of literally seconds after I pushed the upload button! I uploaded a new csv with corrected URLs - using different objects this time)
- it is good to note I only received the upload/indexing confirmation email one time, which afaik was for the second, correct csv file)
- No images or metadata have appeared in this exhibit.

- I decided to create a test exhibit in prod and try again, because I am aware that stage doesn't necessarily maintain parity with prod (I don't know if that is only a lack of individual exhibit parity, or if that could also be code parity?): https://exhibits.stanford.edu/cathy-s-slac-test
- I followed all the steps I listed above for the stage instance -- but of course just did one upload (the same attached csv)
- I did receive the upload/indexing confirmation email
- No images or metadata have appeared in the exhibit.

**Comment by caaster** [comment]
OK, csv file upload not supported. Ping me for the file & I am happy to email it.

**Comment by caaster** [comment]
Chris Beer [8:05 PM] 11 Jan 2019
@caster: i’ve been unsuccessfully trying to look into that; those 3 rows indexed just fine for me, which makes me wonder if it’s something about the original file itself. on Monday, can you shoot me an email with the original file (in case slack is somehow normalizing it or something?)?

Cathy Aster [6:21 PM] 13 Jan 2019
Hi @cbeer just emailed csv to you. Thanks.

Chris Beer [7:16 AM] 14 Jan 2019
thanks @caster; i see the problem; there’s a non-printing character at the start of the file.. it’d be good to know what tools were used to produce the CSV, and after this week full of mirador meetings we can try to find a fix.. in the meantime, a workaround could be adding an empty column at the beginning of the spreadsheet (before `url`) and that ought to work.

Cathy Aster [7:49 AM] 14 Jan 2019
@cbeer I am very relieved. Thank you for taking the time to figure this out. We can loop back next week and I will try your fix in the meantime.

**Comment by caaster** [comment]
@cbeer I opened the csv in Atom & re-saved it. That did the trick.

**Comment by caaster** [comment]
Since this was a user-created problem, I am closing this ticket. I will make sure a note about csv tool creation is included in our documentation to help ensure that this doesn't happen in the future.

**Comment by Caster** [comment]
Just for reference: I was notified of this issue, but I am not familiar with this repository or issue. I think the pasted chat transcript caused this, but if you intended to notify someone else, @caaster, then please be aware that something may have gone wrong.

**Comment by caaster** [comment]
Thank you @caster -- the issue is an internal one/confusion with my git name, which is @caaster. Duly noted. fyi @cbeer
