### ISSUE TITLE
Correct image orientation not retained when non-SDR items are added to exhibit

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1334]
I am working with the SLAC archivist who wants to create an exhibit and populate it with images uploaded from stanford box. Please ping me for access to the box directory if needed.

All of the images must be uploaded and in the correct orientation **no later than 1 Mar 2019**, so that SLAC staff can complete the exhibit and publish it in time for the 100th anniversary of Panofsky and various celebrations at SLAC.

When I upload items directly from box (using the box URLs), some images that are displayed in the correct orientation in box have their orientation switched when they are uploaded. See: 
https://exhibits.stanford.edu/panofsky/catalog/163-25512

I have tried downloading the image from box, where it appears in the correct orientation when opened on my laptop. Further, I have tried to upload the image downloaded to my laptop directly to the exhibit (bypassing the box URL), and the image still does not display in the exhibit in the correct orientation.

I have created 2 unpublished exhibits that I have been using to test various issues including the image orientation issue (PLEASE NOTE - at this point, both of these exhibits should be considered test exhibits - a different exhibit stub will be created once these issues are resolved, for publication):
https://exhibits.stanford.edu/panofsky
https://exhibits.stanford.edu/cathy-s-slac-test

**Comment by jkeck** [comment]
Can you please provide some original images (or the URLs to the Box version).

**Comment by caaster** [comment]
![32_test](https://user-images.githubusercontent.com/3210225/52652477-03371800-2ea3-11e9-87de-e1d81b286f32.jpg)
![dictaphone](https://user-images.githubusercontent.com/3210225/52652492-08946280-2ea3-11e9-87b8-a1865d678b5c.jpg)

**Comment by caaster** [comment]
@jkeck -- Ha!! the images are in the correct orientation on my laptop, but I see they upload incorrectly here in git!

**Comment by caaster** [comment]
https://stanford.box.com/s/s8v5ndkd17se7uuse3n545cw7ydp5iam

https://stanford.box.com/s/39nnyjbd26b8bwiglrxsqswi93s6lbb0

**Comment by cbeer** [comment]
Yeah, I think what's going on is the images are /not/ natively in the correct orientation, but there's metadata in the image that instructs some viewers to rotate it. The easiest solution from spotlight's perspective is to make sure the images are exported in the right orientation.

**Comment by caaster** [comment]
Cool but I am not sure what I need to do to make that happen.

**Comment by caaster** [comment]
Maybe I will reach out to Wayne to see if he can assist.

**Comment by caaster** [comment]
Wayne (who recalls this problem from an earlier time) is going to ask @calavano if he can assist. Stay tuned here.

**Comment by caaster** [comment]
From the SLAC Archivist:

"The majority of the images were scanned using an Epson Perfection 4990 Photo (and edited/cropped using Photoshop CC 2019).

Photos of the 3-D artifacts were taken from an iPhone 6s."

Per @matienzo, I wonder if the iPhone is the culprit. I think most of the wrong-orientation images are the 3-D artifacts.

**Comment by blalbrit** [comment]
@caaster - @calavano has extensive experience with this bug. There is a rotation specified in metadata that needs to be corrected. Please touch bases with him on this.

**Comment by calavano** [comment]
When this was a problem in the DPG labs, it was typically due to different pats of the pipeline improperly handling the image orientation flag in the image header or EXIF data.

In the labs, we try to ensure that all our images are oriented proper with the orientation flag set to default the top-left because it makes it difficult to spot during QC.

**Comment by caaster** [comment]
I appreciate the technical information, @calavano. How can we translate this information into actionable options for me and/or for the SLAC Archivist?

**Comment by caaster** [comment]
For example, @calavano - one clunky option I just tried that works is to take a screen shot of the image, and upload that saved png to the exhibit. Voila! Correct orientation.

**Comment by calavano** [comment]
We solve this by just opening and saving using Photoshop, other applications might require a save as. I can confirm that just opening and saving resets the orientation flag back to 1 using Photoshop CS5 on Windows.

The two images you posted above are marked as being last edited with 'Windows Photo Editor'.  Adobe Bridge is another tool that only sets the orientation flag instead of actually rotating the pixels.

**Comment by caaster** [comment]
Thank you, @calavano -- exactly the info I needed. Closing this ticket now.
