### ISSUE TITLE
Parker Feedback is no longer working as expected

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#1337]
For the first year of Parker 2.0, the feedback button successfully opened a ticket in JIRA in the parker user feedback project, using the email configured in Parker (parker-support@jirasul.stanford.edu).

Unfortunately, this stopped working sometime after Dec. 18 2018, and user feedback tickets are now only generated in the exhibits feedback JIRA queue.

I have conferred and tested with @rsmith11 on this over the last few days and it appears that nothing has changed in JIRA that would have caused this.

The team at Corpus Christi needs to be able to respond to user feedback in a timely manner, and we do not want them to have to monitor the entire exhibits feedback queue to see if any questions pertain to Parker materials.

Associated tickets are:
* https://github.com/sul-dlss/exhibits/issues/528
* https://github.com/sul-dlss/exhibits/issues/1212

@snydman @caaster - can you weigh in on when we can get this fixed?

**Comment by camillevilla** [comment]
@blalbrit @jkeck and I did some quick investigation into this. We've dug into the Exhibits logs and the emails are successfully sent to parker-support et. al. I've emailed you, Rob, Cathy, and Stu info from the production server.

**Comment by blalbrit** [comment]
Abandoning this issue in favor of Trello integration for incoming Parker feedback tickets. I don't know if other projects on the exhibits platform will have a similar requirement - but if we ever fix this issue I'll migrate back into Stanford-ticketing-land.
