### ISSUE TITLE
Slideshow option for Browse category display throwing error

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1338]
Exhibit creator is working on this exhibit: https://exhibits.stanford.edu/tress

Slideshow option for Browse category display is throwing an error, so I have unchecked slideshow display for now.

Screen shot appears to be the related error??

![screen shot 2019-02-21 at 4 53 02 pm](https://user-images.githubusercontent.com/3210225/53212366-8837d500-35f9-11e9-9409-ced4d2a148cb.png)

**Comment by caaster** [comment]
It is a mystery to me that slideshow works on published exhibits, such as Fitch: https://exhibits.stanford.edu/fitch/browse/sclc-civil-rights-campaigns-1965-1966?view=slideshow

**Comment by cbeer** [comment]
Where was the error occurring? I re-enabled the slideshow view momentarily, and clicking around the site everything seemed to work fine.

Also, was it just the honeybadger alert, or did a user report a problem?

**Comment by caaster** [comment]
I'm reporting it, as I'm the one who found the problem when doing a pre-publication review. I have re-enabled slideshow view, and here is what I see using: Chrome Version 72.0.3626.109 (Official Build) (64-bit) - https://exhibits.stanford.edu/tress/browse/dream-collector?view=slideshow

<img width="1385" alt="screen shot 2019-02-22 at 4 40 56 pm" src="https://user-images.githubusercontent.com/3210225/53278878-f398aa00-36c0-11e9-91a9-92ea0afdedf6.png">

**Comment by caaster** [comment]
@cbeer  Also seeing the same problem in Safari Version 12.0 (14606.1.36.1.9)

<img width="1425" alt="screen shot 2019-02-22 at 4 48 03 pm" src="https://user-images.githubusercontent.com/3210225/53278984-cef10200-36c1-11e9-923a-ffad0535ccf5.png">

**Comment by cbeer** [comment]
Thanks; it looks like the images in that collection are marked as no-download, so we can't provide a slideshow-sized image.

**Comment by caaster** [comment]
Thank you @cbeer - sorry for the trouble. Closing ticket.
