### ISSUE TITLE
Limit the size of uploaded images

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/exhibits#1342]
There are three parts to this ticket:
- [x] 1. Cut a new release of Spotlight with #2146 (fixes our ability to validate featured image uploads)
- [x] 2. Implement a file size validator (@cbeer has the start of this)
- [x] 3. Include file size in the help text for the upload form 
![Current upload item form](https://user-images.githubusercontent.com/5402927/54227813-f9aec900-44bd-11e9-9819-603b472ef260.png)

**Comment by mejackreed** [comment]
Do we want to add additional help text for image uploads elsewhere (e.g Exhibit masthead image upload )?

cc @ggeisler 

Also, @ggeisler how does this work for you?

![Screen Shot 2019-05-14 at 1 59 01 PM](https://user-images.githubusercontent.com/1656824/57728176-7aba4600-7650-11e9-9731-3463bbf570b7.png)

**Comment by ggeisler** [comment]
@mejackreed Sure, but how about a slight rewording of the hint text:

> File should be less than 10MB in size.

You're right that while we're at it, we should probably add something similar to the Appearance > Exhibit Masthead and Exhibit Thumbnail upload inputs:

<img width="378" alt="Screen Shot 2019-05-14 at 1 24 30 PM" src="https://user-images.githubusercontent.com/101482/57729775-d8985f00-764b-11e9-80cd-d793358fd9eb.png">

**Comment by mejackreed** [comment]
@ggeisler it seems like we don't have helper text available there yet in Spotlight. Should we add it upstream?

Or we can do this?
![Screen Shot 2019-05-14 at 3 13 27 PM](https://user-images.githubusercontent.com/1656824/57732701-e4d7e880-765a-11e9-9c66-9bcd000c5dc4.png)

**Comment by ggeisler** [comment]
@mejackreed I think the upstream approach makes more sense, from a UX perspective.

**Comment by mejackreed** [comment]
Fixed in #2168
