### ISSUE TITLE
Support full text search/indexing of hOCR 

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/exhibits#1357]
This builds on #1039, and adds support for hOCR, the format used by Google Books. 

Assumptions:

* hOCR files will have `role="transcription"` associated with them in their contentMetadata

As an exhibit creator:

* When I add an SDR object with hOCR files associated with it, I want the text within those files to be searchable within the exhibit.

As a user:

* I want to be able to search the full text of a item, and find items that whose full text matches my search terms.

**Comment by caaster** [comment]
Information regarding fixtures from @andrewjbtw:
Five books in this collection were Google Books accessioned during the analysis work cycle last spring: https://argo.stanford.edu/catalog?f%5Bis_member_of_collection_ssim%5D%5B%5D=info%3Afedora%2Fdruid%3Avk199pb0657
Some of them are embargoed but I think they all have HOCR shelved as the html file next to the jp2s.

It doesn’t seem likely based on what I know from the planning that more google books will be accessioned during the time frame that the access team has to look at supporting HOCR early in the year.
