### ISSUE TITLE
Dashboard not available for https://exhibits.stanford.edu/data

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1363]
It has just been reported by an exhibit admin that the dashboard is not available (System Status page displays) for https://exhibits.stanford.edu/data. 

I checked 3 or 4 other exhibits and their dashboards all display fine.

**Comment by mejackreed** [comment]
Error is here: https://github.com/sul-dlss/exhibits/issues/1362

**Comment by caaster** [comment]
Thank you @mejackreed is anyone actively working this issue that you are aware of?

**Comment by caaster** [comment]
Another user has reported this error, for this exhibit: https://exhibits.stanford.edu/medieval

"I'm trying to upload a new entry to the Medieval Collections at Stanford Spotlight. I cannot get to the Dashboard from the upper right dropdown menu. It takes me to a Searchworks status page. But I can get to the Dashboard by going to Browse and then Edit. However, when I go to add an entry, it takes me back to the Searchworks status page."
