### ISSUE TITLE
Indexing status displays non-accessioned items in a collection

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1397]
Current behavior:
An exhibit creator adds items to an exhibit using the collection druid, for expediency. In this use case, some items in the collection are Accessioned in the SDR, while other items in the collection are Registered in the SDR. When the indexing job begins and the progress bar is displaying, the total number of items being indexed displays as the total number of items in the collection, regardless of SDR status. This is confusing to the exhibit creator.

Desired behavior:
It would be better for the total number of Accessioned items to display when a collection druid is being indexed or reindexed, instead of also including non-Accessioned content. If that is not possible, an explanation that displays to the creator "only Accessioned items will be indexed; please check Argo to validate the total number of items Accessioned in this collection" would be helpful to have.

**Comment by ggeisler** [comment]
When a developer looks at this, if it is **not** possible to exclude non-accessioned objects from the count of total number of items, please add a design needed label to this issue and I'll provide a more concrete design for @caaster's explanation message suggestion.

**Comment by cbeer** [comment]
Is there an example exhibit or collection we can use to test this? I'm a little surprised at the behavior described, because it looks like we use purl-fetcher to retrieve collection members (and that data source should only contain items that have been published)

**Comment by caaster** [comment]
@cbeer I am working on getting an example.

**Comment by caaster** [comment]
After further investigation, I am unable to repeat this behavior. Closing this ticket.
