### ISSUE TITLE
Item images broken on feature page but not on other pages

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1406]
In the Rare Music exhibit, there are four items included in this feature page:

https://exhibits.stanford.edu/rare-music/feature/early-american-tune-books

whose images are not loading (in any browser) on that feature page, although if I do a wildcard search they do show up on the search results page, and they load fine in the viewer on the item details page (and load fine on their Purl pages). I see a couple of 404 errors on the feature page that look like this:

https://exhibits.stanford.edu/images/undefined/full/!400,400/0/default.jpg

This problem was reported by the exhibit curator.

@caaster I notified Ray via the [JIRA ticket](https://jirasul.stanford.edu/jira/browse/EXHBTF-1046) that I filed this Github issue and let the dev team know about it.

**Comment by cbeer** [comment]
I've restored the data for that particular page. It seems like this may be a relatively old exhibit, and the embedded images haven't been updated to use the new way of picking images?

**Comment by ggeisler** [comment]
Okay, that would make sense. You're correct that this was one of the very earliest exhibits.

@caaster I think we can close this issue as fixed; I'll assume you will notify Ray and deal with the JIRA issue.
