### ISSUE TITLE
Choose an approach to handling HTML in IIIF Import metadata

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/exhibits#1424]
Metadata fields created from IIIF manifests will occasionally contain HTML tags.

## Assumptions
- Curators do have the option to hide individual fields
- We can't reliably predict which fields will have HTML
  - example: this [Bodleian manifest](https://iiif.bodleian.ox.ac.uk/iiif/manifest/390fd0e8-9eae-475d-9564-ed916ab9035c.json) has "Homepage" field with a `<span>` and an `<a>`
- Guidance on HTML markup in IIIF Presentation [2.1](https://iiif.io/api/presentation/2.1/#html-markup-in-property-values) and [3.0](https://iiif.io/api/presentation/3.0/#45-html-markup-in-property-values)

## Questions
- Should we whitelist a subset of HTML tags? (`<span>`, `<a>`)
- Or should we try to scrub HTML tags from the metadata?

**Comment by mejackreed** [comment]
I haven't checked this out, but I'm wondering if the sanitization in https://github.com/projectblacklight/spotlight/pull/2209 helps this out in some way.

**Comment by camillevilla** [comment]
Just tested this out and confirmed this is the case. Imported IIIF resources are stripped of HTML tags. Note that Mirador 3 will still render links appropriately.
