### ISSUE TITLE
Multiple user reports of problems with MJF exhibit feature page - item results pagination

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1426]
Today a non-SUL user reported that when they are in the MJF exhibit (https://exhibits.stanford.edu/mjf) and they navigate to the Festival Posters feature page (https://exhibits.stanford.edu/mjf/feature/festival-posters), that they are unable to navigate to page 2 and page 3 of the posters. Navigation is located at the bottom of the page.

Similar problems were noted by SUL users:
- Jerry McBride, using Dell/Chrome, only page 2 of teh posters displays
- Mark Matienzo, "I’m seeing the same thing as Jerry while in incognito mode in Chrome on Mac OS. I do not see the issue if I’m logged in to Spotlight."
- Hannah Frost, stating she could not get past the first page of posters

I am logged in to Spotlight, on Mac OS version 10.14.5, Chrome Version 76.0.3809.132 (Official Build) (64-bit), and I am not able to reproduce the problem.

**Comment by anarchivist** [comment]
Here's a screenshot of it getting stuck on page 2 no matter how you navigate.

![bug](https://user-images.githubusercontent.com/73732/64467841-e4fc6800-d0d1-11e9-90d4-b61e1da10eea.gif)
