### ISSUE TITLE
Create set of SUL-themed color tiles to use a browse category thumbnails

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1434]
The goal is to provide an exhibit curator with a selection of colored tiles that can be used as uploaded images for a browse category thumbnail.

The use case is an exhibit with all or many non-image items where the curator wants to create a more attractive browse landing page than they can get with the default placeholder image or thumbnail images of a PDF documents.

This might be something we want to integrate into the browse category editing process at some point, but as a first step I'm proposing to create a set of colored tile images in the appropriate size for browse category thumbnails and store them in Box for curator access. We can assess how to provide a more streamlined way of using the tiles as a future next step.

**Comment by ggeisler** [comment]
@caaster Below is a proposed solution to this issue. Let me know if you think it will meet the needs of Kris or other curators who might be looking for an alternative to our current browse category thumbnail options.

### Thumbnail tiles
I've created 12 different tiles, all using SU colors from the Stanford Identity color palette. They are stored on Box, in a folder that should be available to any exhibit curator: https://stanford.box.com/s/ruul5i6nkc7ouxhfngb422wdc0d5vn0s

### Documentation
In addition to directly explaining to curators this option when applicable, we probably want to add some documentation to the documentation exhibit so curators might discover this option on their own. I can fine-tune the documentation when adding to the exhibit, but in general:

- Add the text below immediately after the "How to Add an Exhibit Thumbnail" video in the "Updating a browse category" section on this page: https://exhibits.stanford.edu/exhibits-documentation/feature/creating-managing-browse-categories

> Some exhibits contain only non-image items, or contain browse categories that aren't suited to being represented by an image. If that's the case for your exhibit you have two options:

> - You can ignore the browse category thumbnail option. A default thumbnail image showing an image icon will be used for that browse category.
> - You can [download from Box](https://stanford.box.com/s/ruul5i6nkc7ouxhfngb422wdc0d5vn0s) a colored background image tile created specifically for use in Spotlight at Stanford exhibits. There are a range of tiles to choose from, each one in a color from the Stanford Identity Toolkit. To use this option, first download a tile to your computer and then follow the instructions above to upload the image to use as the browse category thumbnail. You can use multiple colored tiles to give your exhibits browse landing page visual variety.

### Example of tiles in use
Here's a screenshot with all 12 tiles in use on the browse category landing page of a test exhibit:

<img width="962" alt="Screen Shot 2019-10-15 at 2 50 55 PM" src="https://user-images.githubusercontent.com/101482/66874920-6fea4100-ef61-11e9-9837-276d4b842dcd.png">

**Comment by caaster** [comment]
@ggeisler this all looks good with one caveat. To be perfectly honest, I worry about offering the following as an option: "You can ignore the browse category thumbnail option. A default thumbnail image showing an image icon will be used for that browse category." I worry because:
- some curators feel selecting a thumbnail is tedious and may use this option as an out even when they have images they could select
- my opinion is that if they create browse categories, they have 3 options:
-- select an image from the exhibit
-- upload an image
-- use the handy colored blocks they can download from box
- personally I feel this option looks highly unpolished 

I'd rather that we say rephrase to say, here is this great option we have for you when...or something similar...

What do you think?

**Comment by ggeisler** [comment]
@caaster Sure, I understand your concern. How about we make a minor modification that omits the mention of the default thumbnail option and displays this text immediately below the "How to Add an Exhibit Thumbnail" video:

> Some exhibits contain only non-image items, or contain browse categories that aren't suited to being represented by an image. If that's the case for your exhibit you can [download from Box](https://stanford.box.com/s/ruul5i6nkc7ouxhfngb422wdc0d5vn0s) a colored background image tile created specifically for use in Spotlight at Stanford exhibits. There are a range of tiles to choose from, each one in a color from the Stanford Identity Toolkit. To use this option, first download a tile to your computer and then follow the instructions above to upload the image to use as the browse category thumbnail. You can use multiple colored tiles to give your exhibits browse landing page visual variety.

**Comment by caaster** [comment]
@ggeisler - Perfect!

**Comment by ggeisler** [comment]
@caaster Okay, I've updated the documentation and I believe the image tiles are publicly available from the Box link so I think this issue is completed.
