### ISSUE TITLE
Add reference links to exhibit invitation email

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#145]
When we have a more formal policy around creating SUL exhibits and some SUL-specific exhibit documentation online, we should enhance the invitation email users get when they are invited to work on an exhibit (#144) with a few links at the end of the email so users unfamiliar with exhibits have something to reference before making the decision to accept the invitation. These might be:

- Name and email of contact person if they have questions (e.g., Tony N or equivalent)
- Link to SUL exhibits landing page 
- Link to SUL exhibits policy

**Comment by cbeer** [comment]
Given #201, do we still want to include additional links?

**Comment by ggeisler** [comment]
It's not critical, but it's easy enough so I think I'd like to add a couple of links. 

How about we merge #201 and then I'll submit a PR to address this ticket later.

**Comment by cbeer** [comment]
👌 . Since #201 was about removing all the other links from the email, I just wanted to make sure we wanted to add any links back in.

**Comment by ggeisler** [comment]
Ah, I see your point. Adding more links might bring back the distraction we are trying to avoid.

Let me think about it and see how it feels if I add the additional links after the invite link. I'll either submit a PR or close this ticket.
