### ISSUE TITLE
If possible, need bulk upload of 35 Opera DB records into Opera DB exhibit

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1452]
The following records didn't make it into initial Spotlight upload because their multiple composers (and a few other data fields) had thrown SOLR indexing errors, thus hadn't been indexed in legacy operadata-prod, and thus did not produce the JSON data needed for Spotlight import. Is it possible for a DLSS developer to upload these records in bulk, to: https://exhibits.stanford.edu/operadata?

If these records can't be uploaded by DLSS developers in bulk, they will be hand-entered into Spotlight by Music staff, where the information can be copied from the source XML and pasted into the Spotlight records editing interface:

(Count = 35)

10122099.xml : multiple values encountered for composer: [Giuseppe Nicolini, Luigi Grassi]

10128024.xml : multiple values encountered for composerSort: [Scarlatti, Alessandro, Scarlatti, Alessandro]

19961612.xml : multiple values encountered for composer: [Mikis Theodorakis, Aristophanes]

20100182.xml : multiple values encountered for composer: [Philip Glass, Robert Moran]

20100188.xml : multiple values encountered for composer: [Arthur Honegger, Jacques Ibert]

20100232.xml : multiple values encountered for composer: [Mark Moebius, Karola Obermüller]

20100261.xml : multiple values encountered for composer: [Thomas Kürstner, Sebastian Vogel]

20100392.xml : multiple values encountered for composer: [Joan Magrané, Raquel García-Tomás]

20100436.xml : multiple values encountered for composer: [Helmut Oehring, Iris ter Schiphorst]

20100485.xml : multiple values encountered for composer: [Hilda Paredes, Arlene Sierra, Lei Liang, Hebert Vázquez]

20100773.xml : multiple values encountered for composer: [Michele della Valentina, Aurelio Scotto]

20100780.xml : multiple values encountered for composer: [Robert Ashley, David Rosenboom]

20100978.xml : multiple values encountered for genre: [Opera, Operetta]

20101039.xml : multiple values encountered for composer: [Jury Everhartz, Daniel Pabst]

20101070.xml : multiple values encountered for composer: [Ralph Benatzky, Johann Strauss Jr.]

20101086.xml : multiple values encountered for composer: [Dieter Schönbach, Alessandro Scarlatti]

20101104.xml : multiple values encountered for composer: [Hans Erismann, Wolfgang Amadeus Mozart]

20101114.xml : multiple values encountered for composer: [Johann Adam Hiller, Christian Gottlieb Neefe]

20101123.xml : multiple values encountered for composer: [Heinrich Berté, Franz Schubert]

20101124.xml : multiple values encountered for composer: [Benedikt Schack, Franz Xaver Gerl]

20101129.xml : multiple values encountered for composer: [Johann Nepomuk Hummel, Ludwig van Beethoven, et al]

20101212.xml : multiple values encountered for composer: [Benedikt Schack, Franz Xaver Gerl, Johann Baptist Henneberg]

20101253.xml : multiple values encountered for composer: [Jacques Offenbach, Julius Stern, Alfred Zamara]

20101256.xml : multiple values encountered for composer: [Franz Schubert, Johann Herbeck]

20101257.xml : multiple values encountered for composer: [Ernst Reiterer, Johann Strauss Jr.]

20101262.xml : multiple values encountered for composer: [Johann Nepomuk Hummel, Adalbert Gyrowetz, Ludwig van Beethoven]

20101282.xml : multiple values encountered for composer: [Ludwig Thuille, Walter Courvoisier]

20101291.xml : multiple values encountered for composer: [Giovanni Porta, Johann Paul Kunzen]

20101295.xml : multiple values encountered for composer: [Joesph Aloys Schmittbauer, Johann Friedrich Gräfe, Anton Schweitzer]

20101305.xml : multiple values encountered for composer: [Philipp Röth, Philipp Jakob Riotte]

20101331.xml : multiple values encountered for composer: [Anton Laube, Joseph Schubert]

20101371.xml : multiple values encountered for composer: [Sebastian Bark, Sven Holm]

20101372.xml : multiple values encountered for composer: [Sebastian Bark, Sven Holm]

20101373.xml : multiple values encountered for composer: [Sebastian Bark, Sven Holm]

20200029.xml : multiple values encountered for composer: [Paul McCartney, Carl Davis]

**Comment by cbeer** [comment]
The script Glen and I developed requires the data already be in solr. For only 35 records, I'd suggest entering the data manually and using it as a test for the ongoing data creation.
