### ISSUE TITLE
Need bulk upload of 55 items into Opera DB exhibit

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1453]
The following records didn't make it into the initial Spotlight upload because they hadn't yet been indexed in operadata-prod at the time of the initial migration -- though they are included in the legacy http://operadata-dev.stanford.edu instance and in its accompanying SOLR index at https://sul-solr.stanford.edu/solr/dig_opera_test/.  

First preference for upload to https://exhibits.stanford.edu/operadata:
Extract the JSON from the dig_opera_test SOLR index, isolate these particular records by their record numbers, and bulk-import them into Spotlight.

If the above task is not possible, then Music staff can hand-enter the records into Spotlight.

Count = 55

20101331.xml
20101333.xml
20101334.xml
20101335.xml
20101337.xml
20101338.xml
20101339.xml
20101340.xml
20101341.xml
20101342.xml
20101343.xml
20101344.xml
20101345.xml
20101346.xml
20101347.xml
20101348.xml
20101349.xml
20101350.xml
20101351.xml
20101352.xml
20101353.xml
20101354.xml
20101355.xml
20101356.xml
20101357.xml
20101358.xml
20101359.xml
20101360.xml
20101361.xml
20101362.xml
20101363.xml
20101364.xml
20101365.xml
20101366.xml
20101367.xml
20101368.xml
20101369.xml
20101370.xml
20101371.xml
20101372.xml
20101373.xml
20101374.xml
20101375.xml
20101376.xml
20101377.xml
20101378.xml
20101379.xml
20101380.xml
20101381.xml
20101382.xml
20101383.xml
20101384.xml
20101385.xml
20101386.xml
20101387.xml

**Comment by cbeer** [comment]
These records are not in the dig_opera_test index:

20101331
20101334
20101371
20101372
20101373

**Comment by cbeer** [comment]
I've loaded the remaining 50 into the exhibit using the script Glen and I developed last year.
