### ISSUE TITLE
Prevent exhibit admins from using the Parker theme

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1462]
Sometimes an exhibit admin will select the Parker theme. However, the Parker theme omits the Stanford + SUL footer, so we don't want the Parker theme to be used except in very specific cases (so far, just for Parker).

I wonder if we can just omit the display of the Parker option on the Configuration > Appearance > Visual theme page unless the current user is a super-admin? If possible that would be the most straightforward option; we wouldn't need to add any text we hope an exhibit admin pays attention to, but at the same time if we do want to apply the Parker theme to a future exhibit it wouldn't be a big deal for one of the super-admins to select it.

**Comment by mejackreed** [comment]
Per @caaster this causes questions and confusion around the Exhibits appearance theme selection page

**Comment by jkeck** [comment]
Re-opening.  I didn't intend for my issue to close this one (just to indicate that it could, whoops).  Once we're on a version of Spotlight that includes projectblacklight/spotlight#2372 we can configure this appropriately on our side.

**Comment by jkeck** [comment]
(Blocked by a release of Spotlight)

**Comment by jkeck** [comment]
Closed by #1607, will roll out with Blacklight/Bootstrap updates
