### ISSUE TITLE
Page navigation doesn't work on MJF exhibit feature page

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1463]
On Dec 20, 2019, at 10:54 AM, nathan coy <ncoy@stanford.edu> wrote:

When using the page navigation for the posters sections of the Monterey jazz Festival spotlight the 1,2,3 prev next does not work, this must be done via an incognito or private browsing session as having SU privileges seems to to not produce this problem, ergo outside public users experience the problem but we don't internally. Thanks, Nathan

Feature page Nathan is referring to is: https://exhibits.stanford.edu/mjf/feature/festival-posters

I have validated this behavior as Nathan has reported.

**Comment by ggeisler** [comment]
FWIW, I suspect this might be the Search results widget, since this occurs on a feature page and I couldn't reproduce with any regular search or browse results.
