### ISSUE TITLE
BL7 upgrade: OSD control buttons not rendering

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/exhibits#1474]
Part of #1473 

To recreate:
Curation > Items > Add item > Upload item > Item page

### Before upgrade
<img width="632" alt="Screen Shot 2020-01-14 at 3 36 32 PM" src="https://user-images.githubusercontent.com/5402927/72391967-b3308900-36e3-11ea-8066-fbe1d2c92580.png">

### After upgrade
<img width="983" alt="Rendering XML instead of buttons" src="https://user-images.githubusercontent.com/5402927/72391810-1e2d9000-36e3-11ea-90cd-ede33b26ead5.png">

**Comment by mejackreed** [comment]
Are we moving to sul-embed for this type of display at some point? (I can't remember)

**Comment by camillevilla** [comment]
@mejackreed that's the hope in #1439 but we're blocked until we can find a clever workaround for the CORBs stuff.
