### ISSUE TITLE
BL7 upgrade: Fix landing page styling

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/exhibits#1488]
![Screen Shot 2020-01-14 at 6 05 11 PM](https://user-images.githubusercontent.com/1656824/72395995-833fb080-36f8-11ea-8d17-b09a6c88c673.png)

- [ ] `Unpublished` label should be white

**Comment by mejackreed** [comment]
Now that I'm looking at this. Should we just keep the black text to keep the contrast?

**Comment by mejackreed** [comment]
Not really a fan of this:

![Screen Shot 2020-01-15 at 1 31 18 PM](https://user-images.githubusercontent.com/1656824/72468840-54c6e180-379b-11ea-998a-18c6b21c2dd3.png)

**Comment by ggeisler** [comment]
Black text is fine with me. It seems like the orange is brighter than before, which makes the white not work as well.

It feels like the exhibit title text is too close to the badge now, and the title font feels heavier than before (doesn't look like Source Sans 500 to me, offhand), but maybe those are separate issues to deal with.

**Comment by mejackreed** [comment]
Got it.. adding back the margins in Spotlight.
