### ISSUE TITLE
BL7 upgrade: Search type icon titles have "icon" in them

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/exhibits#1515]
Not sure if this is an upstream spotlight issue, or local, but creating the ticket here for now.

<img width="216" alt="Screen Shot 2020-01-16 at 10 04 30 AM" src="https://user-images.githubusercontent.com/96776/72550547-d116fe80-3847-11ea-9ead-08ed3a3da3b0.png">

**Comment by mejackreed** [comment]
This is a Blacklight thing. Might be good to determine what behavior we want here in all the apps.

**Comment by mejackreed** [comment]
Some discussion in here: https://github.com/projectblacklight/blacklight/issues/2150
