### ISSUE TITLE
Add facets to site sidebar

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1524]
Part of #1466 and related to #1520.

- [x] Add new section to the site sidebar, below the new search form, with the (`h2`) heading `Limit your search`

<img width="1079" alt="Screen Shot 2020-01-16 at 5 52 03 PM" src="https://user-images.githubusercontent.com/101482/72575244-faa44a00-3888-11ea-932f-7c60006e9550.png">

### Facets to include
We can iterate on this (and I defer to developers who have other thoughts on what facets might be useful in this context), but my current thoughts are to include these "new" facets:

- [x] Exhibit subject area - using the exhibit tag controlled vocabulary as values
- [x] Exhibit title

<img width="797" alt="Screen Shot 2020-01-16 at 5 59 55 PM" src="https://user-images.githubusercontent.com/101482/72575550-06dcd700-388a-11ea-8500-598ed3d6318e.png">

And then facets we currently use for individual exhibits:

- [x] Date range - the date range slider
- [x] Item visibility - only displayed if the user is a superadmin

### Responsive considerations
The facet section should follow the search form placement as discussed in #1520.

- [x] At mobile viewport widths (`md` and narrower), display the facets initially as collapsed: 

<img width="1004" alt="Screen Shot 2020-01-16 at 5 48 19 PM" src="https://user-images.githubusercontent.com/101482/72575067-7c47a800-3888-11ea-8545-9a22b8df2d00.png">

- [ ] Selecting the button expands the facets:

<img width="1004" alt="Screen Shot 2020-01-16 at 5 48 49 PM" src="https://user-images.githubusercontent.com/101482/72575073-8073c580-3888-11ea-997e-b2b147cb8b30.png">

- [x] If we only end up with three or four facets, we might consider omitting the expand/collapse button and just show the facets as always open.

**Comment by jkeck** [comment]
Met w/ @ggeisler and validated that it appears all the tasks are complete.  We're holding off on changing the facet responsive behavior for now (as we're re-using the results facets markup and getting the responsive behavior from there).  We can open a new issue if we decide we need to go down that route later.
