### ISSUE TITLE
BL7 upgrade: view icons are slightly bigger than sort + per page 

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/exhibits#1525]
<img width="430" alt="Screen Shot 2020-01-17 at 08 08 52" src="https://user-images.githubusercontent.com/111218/72627038-a177fd00-3900-11ea-8174-5cb4fd65b1be.png">

**Comment by mejackreed** [comment]
Resolved in https://github.com/sul-dlss/exhibits/pull/1587
