### ISSUE TITLE
Missing  bottom margin/padding before footer on all pages

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/exhibits#1529]
Before:
<img width="940" alt="Screen Shot 2020-01-17 at 08 53 09" src="https://user-images.githubusercontent.com/111218/72630242-cbccb900-3906-11ea-8a3f-4b1247cf880c.png">

After:
<img width="949" alt="Screen Shot 2020-01-17 at 08 52 40" src="https://user-images.githubusercontent.com/111218/72630207-bb1c4300-3906-11ea-95f7-f78f0bfd6c00.png">

**Comment by mejackreed** [comment]
I think this might be resolved already. I'm seeing that margin present in the latest `bl7` b7ef1e6aad92ba7f421e66f7bccd3a10a193f7d3


http://127.0.0.1:3000/test/about 

![Screen Shot 2020-01-17 at 12 08 15 PM](https://user-images.githubusercontent.com/1656824/72639088-160f6380-3922-11ea-832a-96a2372d97eb.png)
