### ISSUE TITLE
Add Grouped by exhibit option to gallery view of site search results

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1534]
Part of #1466.

For the Grouped by exhibit display option, we won't show any individual result items. Instead we'll feature the exhibits that contain one or more result items, and indicate how many result items are a part of each exhibit. Although the display features the exhibits rather than the individual result items, the search terms and facet values are obviously applied to individual items.

The goal for the Gallery view version of the Grouped by exhibit display option is something like the mockup below. However, we might want to worry about some details like font sizes and spacing after we get all the elements in place, just because I can't reproduce everything in static mockups as accurately as I'd want to make final styling decisions.

<img width="996" alt="Grouped-gallery" src="https://user-images.githubusercontent.com/101482/72649030-be7cf200-3939-11ea-8c1d-92f299b16f8a.png">

- [x] **A:** I'm not sure if we need to adjust what sort options we present when we switch to Grouped mode? We don't seem to in ArcLight so I guess not? It does seem a bit odd, however, to offer sorting by something like "Year" when we're only showing exhibit metadata, not the item metadata where the year value actually exists. The ideal sort options in the Grouped by display might be more like `[Exhibit title | Result count]`. We might need to discuss this.

- [x] **B:** Display the exhibit group info in a card-like way, very similarly to how we currently display the exhibit cards on the site landing page. It might be useful to start with the structure and styling we use on the landing page, because we will want the responsive behavior we have there (the mockup above is roughly the `LG` viewport width; when the viewport is in the wider `XL` viewport width, we will want the cards to widen to fill the main content area width, in the same way the landing page cards do).

- [x] **C:** Unlike the landing page cards, the cards here should not flip (no back), so we need to make the exhibit title a link, which goes to the exhibit home page. The exhibit title is an `<h2>`, probably `20px` (the landing page titles are `18px` but we need to differentiate enough between the title and subtitle in this case; we can experiment with font-size after getting things in place).

- [x] **D:** Exhibit subtitle.  We can probably go with `<p class="subtitle">` like the landing page cards.

- [x] **E:** The number of result items that area associated with this exhibit, linked to the search results page in that exhibit for the current search parameters. For this to work I think we need to make sure to drop the Exhibit subject area and Exhibit title constraints from the passed parameters, if they are used, but you all know better than me how to make that work.

### Responsive considerations
As I mentioned above, I think the responsive aspect of this display could be a little tricky, so hopefully using the landing page card display will help as a model. In general what should happen is we always show rows of 3 cards at `MD` and above; the cards get wider at the `XL` viewport width than the `LG` and `MD` viewports, and below `MD` we show rows of 2 or 1 card based on what fits the available width.

**Comment by jkeck** [comment]
Met w/ @ggeisler and validated that it appears all the tasks are complete.
