### ISSUE TITLE
Add Grouped by exhibit option to list view of site search results

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1539]
Part of #1466 and related to #1534.

For the Grouped by exhibit display option, we won't show any individual result items. Instead we'll feature the exhibits that contain one or more result items, and indicate how many result items are a part of each exhibit. As I noted in with the Gallery view of Grouped by results in #1534, we might want to worry about some details like font sizes and spacing after we get all the elements in place, so the mockup and recommendations below are more like a starting place from which we can tweak things.

I'm using an `XL` viewport width layout for the primary requirements and will note differences for other viewport widths below, after the primary requirements.

<img width="1189" alt="Group-by-List-view-XL" src="https://user-images.githubusercontent.com/101482/72828283-9216ed80-3c39-11ea-99fb-7e8aa8c2dff9.png">

- [x] **A:** Result item panel. The goal for this view is to keep the exhibit thumbnail and all result item metadata inside a visible container (`#FBFBF9` background color), which doesn't get taller than the fixed height thumbnail image.

- [x] **B:** Result item thumbnail. The exhibit thumbnail is `200px x 200px`. 

- [x] **C:** Exhibit title as an `<h2>` and font-size `24px` (note that this is intentionally larger than the Grouped by, Gallery view title font-size specified in #1534; we'll see how it works here). The title is linked to the homepage of the exhibit.

- [x] **D:** Exhibit subtitle. We can probably go with `<p class="subtitle">`, so font-size `16px`, line-height `22px` .

- [x] **E:** Exhibit description. Font-size: `14px`, line-height: `20px`, max-width: `75ch`. To keep all result item elements within the fixed-height background container, we'll need to truncate the description, using the responsive truncator to deal with the different viewport widths. For the `XL` viewport I'm hoping we can show 3 lines of the Exhibit description before truncating. We can fine-tune this after we see how things look with a wider variety of exhibit result examples.

- [x] **F:** Result item count. Font-size: `16px`. The link is to the search results page of the exhibit, with the current search parameters.

### Responsive considerations
Designing List view to use these consistently-sized panels creates some challenges at viewports smaller than `XL` because there's less horizontal space to fit all the result item text. Below are adjustments that I hope will be good starting points and we can fine-tune as necessary.

#### MD and LG viewports
Both of these viewports can be handled in the same way, I think, because while `MD` is a narrower viewport width, we collapse the sidebar at `MD` so the main content area ends up similar in width to `LG`.

<img width="732" alt="Group-by-List-view-MD-LG" src="https://user-images.githubusercontent.com/101482/72830591-4450b400-3c3e-11ea-9525-fd0a632ed118.png">

- [x] Adjust exhibit description truncation. I'd prefer to show three lines of the exhibit description before truncating, as in the `XL` viewport width, but because we're more likely to have exhibit title and/or exhibit subtitle wrapping with the reduction in horizontal space in the result item panel, we might need to adjust the responsive truncator to truncate at 2 lines instead of the 3 in the `XL` viewport width.

#### SM and XS viewports
There are more adjustments needed at the smaller mobile viewport widths, but I think we can apply the same adjustments for everything below `MD`. The mockups below show how the results are styled the same way, the `XS` just has more text wrapping because of the narrower horizontal width.

<img width="1200" alt="Screen Shot 2020-01-21 at 11 32 43 AM" src="https://user-images.githubusercontent.com/101482/72832363-f938a000-3c41-11ea-86d3-6f72ef92defe.png">

- [x] Omit display of the result item panel background (this is checkbox A above). Without the panel acting as a visual container we can let the result item metadata extend below the thumbnail without it looking weird (e.g., the French Revolution item in the XS example above).

- [x] Reduce the exhibit thumbnail to `100px x 100px`. 

- [x] Reduce the exhibit title font-size to `20px`.

- [x] Omit display of the exhibit description.

**Comment by jkeck** [comment]
Met w/ @ggeisler and validated that it appears all the tasks are complete.  We're holding off on any more/less truncation toggle as it will potentially introduce other issues and complications that would need to be accounted for.  A new Design Needed issue can be created if we decide we need to reconsider.
