### ISSUE TITLE
Multi-row grid widget on home page displaying broken image icons

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1540]
The multi-row grid widget on home page is displaying broken image icons.

Appears to be isolated to this exhibit only: https://exhibits-stage.stanford.edu/ua-maps-drawings -- as I checked another exhibit that also uses the multi-item grid: https://exhibits.stanford.edu/herbert-matter.

In the Stanford Atlas exhibit, I see the broken image links in Safari, Firefox and Chrome.

**Comment by mejackreed** [comment]
@caaster this is likely due to the stage exhibit being imported from prod and that our uploaded items do not transfer over. This is a common thing where we cannot transfer uploaded items between environments.

**Comment by caaster** [comment]
Thanks, Jack. This leaves me with questions about testing which I'll ask at another time. Closing this ticket now.
