### ISSUE TITLE
UI changes to improve exhibit creator experience for adding druids to an exhibit

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1557]
Looking for UI improvements to better guide/inform exhibit creators and prevent ongoing confusion. Clarifying how to correctly add druids - maybe as simple as adding better help text (but could be more than this).

**Comment by ggeisler** [comment]
How is this different from #1151?

**Comment by caaster** [comment]
Good point -- my error. Closing this ticket. @ggeisler
