### ISSUE TITLE
BL7 Update: Prod vs Stage differences

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/exhibits#1566]
## Exhibits Landing Page Buttons
- [ ] Buttons are now center aligned
- [ ] Active button highlight is less prominent

### Prod
<img width="716" alt="before" src="https://user-images.githubusercontent.com/96776/73372194-a8413100-426b-11ea-97d3-49384bd8deb3.png">

### Stage
<img width="710" alt="after" src="https://user-images.githubusercontent.com/96776/73372192-a7a89a80-426b-11ea-8dc2-637839315964.png">

## Facet Heading
- [ ] Bottom border does not extend full facet element width

### Prod
<img width="242" alt="facet-before" src="https://user-images.githubusercontent.com/96776/73373362-5ef1e100-426d-11ea-846d-e60a4b8ad972.png">

### Stage
<img width="239" alt="facet-after" src="https://user-images.githubusercontent.com/96776/73373388-674a1c00-426d-11ea-9de8-015e5032cf61.png">

## Facet Highlighting
- [ ] Selected facet value and facet border is now green. See #1568.

### Prod
<img width="230" alt="facet-hl-before" src="https://user-images.githubusercontent.com/96776/73373779-03742300-426e-11ea-92a0-2d85b4e48d01.png">

### Stage
<img width="225" alt="facet-hl-after" src="https://user-images.githubusercontent.com/96776/73373777-03742300-426e-11ea-8d04-0ee82d082897.png">

## Sir Trevor Widget Thumbnails
- [ ] Addition of `.img-thumbnail` adds a 1px rounded border.

### Prod
<img width="248" alt="before-img" src="https://user-images.githubusercontent.com/96776/73373594-babc6a00-426d-11ea-82de-b14b45f9e471.png">

### Stage
<img width="253" alt="after-img" src="https://user-images.githubusercontent.com/96776/73373593-babc6a00-426d-11ea-8542-3ffa17384c65.png">

## Search Button
- [ ] It's red now. See #1569.

### Prod
<img width="212" alt="search-before" src="https://user-images.githubusercontent.com/96776/73373943-40d8b080-426e-11ea-9c4f-42228b353c02.png">

### Stage
<img width="251" alt="search-after" src="https://user-images.githubusercontent.com/96776/73373944-41714700-426e-11ea-80f5-8867de5ffb50.png">

## Search Breadcrumb
- [ ] Start over is button
- [ ] Takes space above facets (as opposed to next to facets)
- [ ] "You searched for" text is no longer present
- [ ] Background color / Hover highlight color of breadcrumb is off

### Prod
<img width="996" alt="breadcrumb-before" src="https://user-images.githubusercontent.com/96776/73374447-0cb1bf80-426f-11ea-9a30-81a2456f196e.png">

### Stage
<img width="996" alt="search-breadcrumb-after" src="https://user-images.githubusercontent.com/96776/73374507-2b17bb00-426f-11ea-9565-969319796a8c.png">

<img width="396" alt="breadcrumb-hl-after" src="https://user-images.githubusercontent.com/96776/73374305-d5431300-426e-11ea-9263-884a328c1158.png">

### Metadata Display 
- [ ] Labels are wonky (off to the right)

### Prod
<img width="748" alt="lanciani-qb107zw4834-before" src="https://user-images.githubusercontent.com/96776/73374739-8ea1e880-426f-11ea-90da-3a5c21aaa0ab.png">

### Stage
<img width="807" alt="lanciani-qb107zw4834-after" src="https://user-images.githubusercontent.com/96776/73374737-8ea1e880-426f-11ea-9171-eac425042110.png">

**Comment by jkeck** [comment]
Some of these things @ggeisler may have already noticed and dismissed as not relevant / an improvement / something that we'll live with.  Just wanted to list down some things that I had noticed when poking around the site.  Feel free to nix any of these or spin off into tickets.

**Comment by ggeisler** [comment]
Thanks @jkeck. Yes, pretty much all of these are on my list to deal with. I wanted to get the font-sizes corrected first and now I'm looking at button sizes and colors (definitely want to change the green used for the facets, for example). There are also a couple of issues I want to get JV's thoughts on before writing up a ticket (e.g. thumbnails now having a border and rounded corners, which I am inclined to want to revert, but again want to get a second opinion to make sure I'm not just defaulting to what I'm used to).

Note that the issue you mention with the facet bottom border was included in https://github.com/sul-dlss/exhibits/issues/1547, so hopefully that's been taken care of.

The one thing you list that I hadn't noticed is the last one, where the metadata labels show to the right.

**Comment by jkeck** [comment]
It looks like that metadata thing is specific to when a map is being shown and is not the last metadata item.  Not sure if this is an issue that would also happen before the Bootstrap/Blacklight updates.

**Comment by jkeck** [comment]
Closing this in favor of the tickets that @ggeisler will create.  Sorry for the confusion.
