### ISSUE TITLE
BL7 upgrade: update styling of the .img-thumbnail class

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1570]
The BL7 upgrade added a border around the Sir Trevor-derived thumbnail images. JV seconded my feeling that we don't want that styling in Exhibits. I don't think we want to make that decision in Spotlight because other implementors might have site designs where the image thumbnail border looks appropriate, so this is probably an Exhibits-specific decision.

- [ ] Remove the styling related to adding a border to image thumbnails, added by the `.img-thumbnail` class (first four of the unchecked styles below; `max-width` was unchecked by a higher-priority style unrelated to the thumbnail border):

<img width="387" alt="Screen Shot 2020-01-29 at 2 40 25 PM" src="https://user-images.githubusercontent.com/101482/73399940-5a491f00-42a5-11ea-8f55-04b9e6f36a25.png">

**Comment by mejackreed** [comment]
Is it reasonable to think that we want to override those `img-thumbnail` behaviors globally in Exhibits?

**Comment by ggeisler** [comment]
@mejackreed Not sure if you're asking me or just generally, but I don't think we want that border styling for any thumbnails in exhibits.
