### ISSUE TITLE
BL7 upgrade: reduce size of buttons/inputs on results page

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1576]
BS4 increased the size of form elements so that the default is 38px. We can stick with that default in most places. However, on the search/browse results pages we can display quite a few form elements at the same time, and the pages would look better if those elements were smaller.

<img width="1021" alt="Screen Shot 2020-01-30 at 10 36 46 AM" src="https://user-images.githubusercontent.com/101482/73475187-17db1d00-434d-11ea-8844-b5b08f482a2d.png">

---

<img width="1021" alt="Screen Shot 2020-01-30 at 10 38 10 AM" src="https://user-images.githubusercontent.com/101482/73475197-1d386780-434d-11ea-9c0d-b59060de92b2.png">

---

- [x] Reduce the size of all elements highlighted in the screenshots above, including the optional browse page searchbox, to BS4's `sm` size, which I believe is `31px` high. Hopefully this can be done via `@extend .input-group-sm` or equivalents. If not, and we have to more manually change the height of these elements, I'd suggest with we go with the `34px` height we currently use for those elements on -prod.

- [x] The above includes the "Save this search" button that is only visible to exhibit curators

**Comment by mejackreed** [comment]
Resolved in https://github.com/sul-dlss/exhibits/pull/1587
