### ISSUE TITLE
BL7 upgrade: investigate what we can do to reduce page margins

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1579]
I assume this has something to do with using flexbox as part of the upgrade, but we've lost quite a bit of horizontal space for page content versus our current production version of exhibits.

For example, these two examples are the same viewport width (about 700px, or `sm` viewport size):

#### BS4 version on -stage

<img width="691" alt="Screen Shot 2020-01-30 at 12 22 36 PM" src="https://user-images.githubusercontent.com/101482/73483733-2fba9d00-435d-11ea-9997-4e99e5ece402.png">

#### BS3 version on -prod

<img width="691" alt="Screen Shot 2020-01-30 at 12 23 09 PM" src="https://user-images.githubusercontent.com/101482/73482838-b40c2080-435b-11ea-98be-c226d653a3d6.png">

---

This is particularly a problem (I assume it is at least related) for results pages. It's very noticeable in gallery view, as in the examples above, since we lose columns at wider viewport widths with the new layout.

There might be some other issue going on with gallery view as well, since the thumbnails are smaller than they need to be, given the available content area width:

<img width="691" alt="Screen Shot 2020-01-30 at 11 28 51 AM" src="https://user-images.githubusercontent.com/101482/73483277-617f3400-435c-11ea-91dc-05318bbcab0e.png">

---

<img width="1153" alt="Screen Shot 2020-01-30 at 11 26 39 AM" src="https://user-images.githubusercontent.com/101482/73483639-039f1c00-435d-11ea-8587-ed22762b1cbf.png">

---

The current -prod layout makes much better use of available content area width, always showing thumbnails as large as possible to fill out the available horizontal area:

<img width="995" alt="Screen Shot 2020-01-30 at 12 38 22 PM" src="https://user-images.githubusercontent.com/101482/73483905-9344ca80-435d-11ea-9ce0-a91959dbb085.png">

---

I can write up a more specific ticket for gallery view if necessary, but maybe it makes sense to wait until someone can look into whether we can reduce the page margins first, since that will affect how much content area is available at a given viewport width.

**Comment by jkeck** [comment]
This has mostly been completed.  New tickets will be opened for refinements to what is here (particularly around gallery where not all breakpoints have an ideal display).
