### ISSUE TITLE
BL7 upgrade: increase width of searchbox's select menu

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1583]
Given the decision in #1576 to keep most of our form elements the new, larger BS4 default size, the searchbox in the main menu will continue to be the size it is in -stage. But the select menu part is now too narrow to comfortably contain the default label and other longer labels:

<img width="480" alt="Screen Shot 2020-01-30 at 4 19 32 PM" src="https://user-images.githubusercontent.com/101482/73499366-25100000-437d-11ea-962e-5cd7db69457e.png">

---
<img width="480" alt="Screen Shot 2020-01-30 at 4 29 23 PM" src="https://user-images.githubusercontent.com/101482/73499598-c0a17080-437d-11ea-93d3-90856ebf2947.png">

---

### Option 1
This is probably a lot easier than option 2, though I'd sort of prefer option 2 because it would reduce the height of the searchbox a few pixels.

- [ ] Widen the search field select menu so it comfortably contains the entire text label

### Option 2
- [ ] Change the font-size of the search field labels and the input box text to `0.9375rem` (15px). That will reduce the height of their containers a few pixels. But you'd also need to adjust the size of the search button/icon accordingly, and when I tried this it seemed finicky to get all three elements to look like they are the exact same height. So this option would be great, but perhaps challenging, not sure.

**Comment by mejackreed** [comment]
I tried option 2 here, but there are some browser specific inconsistencies. I'm going to try for option 1 now instead.
