### ISSUE TITLE
BL7 upgrade: increase font-weight of current tab label 

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1588]
In -prod we use a heavier font-weight (600) for the label of the current tab. I suggest we continue to do that because it makes it easier to recognize which tab you are currently working with.

<img width="1113" alt="Screen Shot 2020-01-31 at 9 22 29 AM" src="https://user-images.githubusercontent.com/101482/73555638-3c95ca00-440b-11ea-9bc5-98191f72ac42.png">

- [ ] Add `font-weight: 600;` to the label of the currently selected tab

The relevant tabs occur on these pages:

#### Exhibit admin pages
- Config > General
- Config > Appearance
- Config > Search
- Config > Viewers
- Curation > Add items
- Curation > Edit browse category
- Curation > Translations

#### Feature/About pages
- Top of page when editing a page

#### Site admin pages
- Landing page
- Manage exhibits > Customize appearance

If it's relevant, this seems reasonable to do in Spotlight (it seems like a reasonable default and would be easy enough for an adopter who didn't want it to override the font-weight locally).

**Comment by mejackreed** [comment]
Resolved in https://github.com/projectblacklight/spotlight/pull/2399
