### ISSUE TITLE
BL7 upgrade: update font size of "help text" text

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1591]
It appears that BS4 did away with the `help-block` class, which we used on some admin pages to provide help text under some form fields (e.g., `<span class="help-block"`). The equivalent text is now structured as `<small class="form-text text-muted">`, and sized using `font-size: 80%` on the `<small>` element.

This creates a problem because making the `<small>` element 80% might work in other contexts but in this form context it makes the help text font too small (11px or 12px):

<img width="746" alt="Screen Shot 2020-01-31 at 10 17 09 AM" src="https://user-images.githubusercontent.com/101482/73559750-e62c8980-4412-11ea-814a-304b13e2f358.png">

I think we need to target the help text more directly so we have more control over its sizing. Maybe something like:

```CSS
small.form-text.text-muted {
    font-size: 90%;
}
```

The form fields are currently at `14px`, which makes the help text `13px` with that specification, but I'm going to make a future PR/ticket to increase the body font size back to `15px`, which will result in that specification making the help text `14px`, which I think is good for this context (but would be too large for the `<small>` element in other contexts like headings).

**Comment by mejackreed** [comment]
Resolved in https://github.com/projectblacklight/spotlight/pull/2389
