### ISSUE TITLE
BL7 upgrade: make Configuration > Viewers label inline

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1594]
I think the Viewers form label would look better (and be consistent with our other Admin page forms) if it were inline with the other form elements:

<img width="699" alt="Screen Shot 2020-01-31 at 12 23 10 PM" src="https://user-images.githubusercontent.com/101482/73568059-df0e7700-4424-11ea-8d3e-ae5ade5f075b.png">

(I also want to add some vertical space between options, but that's a global issue I'll deal with in a separate vertical spacing PR or ticket.)

**Comment by mejackreed** [comment]
Resolved in https://github.com/sul-dlss/exhibits/pull/1599
