### ISSUE TITLE
BL7 upgrade: fix metadata alignment in Gallery view of results

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1605]
Currently in -prod, we always show metadata for results items in gallery view using stacked label/values:

<img width="891" alt="Screen Shot 2020-02-03 at 10 59 05 AM" src="https://user-images.githubusercontent.com/101482/73677784-38b8b080-4674-11ea-86f1-5ea06bedf397.png">

whereas on -stage we're showing metadata in gallery view with inline label/values:

<img width="1140" alt="Screen Shot 2020-02-03 at 10 53 56 AM" src="https://user-images.githubusercontent.com/101482/73677436-7f59db00-4673-11ea-91d6-d0af0228a1dc.png">

Note that the metadata also extends into the padding area of the item, both on the left and right:

<img width="299" alt="Screen Shot 2020-02-03 at 10 55 15 AM" src="https://user-images.githubusercontent.com/101482/73677545-baf4a500-4673-11ea-85bc-46ca24b86eb0.png">

In gallery view, for all viewport widths:

- [x] Use the stacked label/value layout we currently use in -prod
- [x] Ensure that metadata is contained within the item's content area, and doesn't extend into the left and right padding areas

**Comment by jkeck** [comment]
This will be resolved once we get a release/update
