### ISSUE TITLE
BL7 upgrade: reduce title overlay width in Mosaic view of results

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1606]
On -stage the overlay used to display title of the item on hover in Mosaic view of results extends beyond the edges of the image. On -prod the overlay fits the image width exactly:

<img width="986" alt="Screen Shot 2020-02-03 at 11 08 27 AM" src="https://user-images.githubusercontent.com/101482/73678395-85e95200-4675-11ea-93f5-32976a45d0be.png">

**Comment by jkeck** [comment]
This will be resolved once we get a release/update
