### ISSUE TITLE
BL7 upgrade: add icon to Start over button on results page

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1610]
As part of the BL7 upgrade the search results header controls changed a bit, moving the Start Over and search constraints to left-align with the sidebar rather than the main content area as currently seen in -prod.

Overall this change is fine for the search results page. (We would like to make a change to the item detail page, which I'll [ticket separately](https://github.com/sul-dlss/exhibits/issues/1611).) But to follow the SearchWorks pattern a bit more closely, and maybe make it slightly more clear to the user that "Start Over" returns them to the homepage, it would be great if we could:

- [x] add an icon to the "Start Over" button, similar to SW

<img width="781" alt="Screen Shot 2020-02-03 at 4 22 27 PM" src="https://user-images.githubusercontent.com/101482/73699977-76343280-46a2-11ea-905b-ab6498c59d6e.png">

In the mockup above I've used the "FirstPageSharp" icon from the Material UI icon set (https://material-ui.com/components/material-icons/) (apparently you can no longer provide a direct link to a MUI icon...).

- [x] To be more consistent with SUL's sentence-case writing style, it would be great to update the label to read "Start over" rather than "Start Over", unless that is technically difficult.

**Comment by jkeck** [comment]
Closing this out, the button text has been updates and the icon will display once we're released a new version of blacklight and update to it.
