### ISSUE TITLE
Iframes need title attribute  (severity 7)

### ISSUE THREAD

**Issue by jvine** [sul-dlss/exhibits#1613]
Any frame or iframe element requires a title attribute. The title doesn't need to be unique on the page, but it's intended to let a screen reader user know if they can skip this block, so it can't be completely meaningless. We can provide a title for the embedded Mirador viewer, but it's not clear how we can address this for content embedded via the Embed or Iframe widgets; will we need to provide an additional field for the curator?

Minimum task here:
- [ ] Add `title="Mirador viewer"` to Mirador iframes.

**Comment by jvine** [comment]
oembed types:

- Image viewer 
- Map viewer
- PDF viewer
- 3-D object viewer
- UV - PDF or 3-D
- Web archive seed viewer

**Comment by jkeck** [comment]
This is ultimately a SUL Embed issue.  Might be nice to have Viewer's indicate their iframe title and that be sent to clients (or something along those lines)
