### ISSUE TITLE
BL7 upgrade: viewer on item detail page not using full width of page

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1620]
It looks like there are certain cases where the viewer on the item page is not taking full-width of the content area, possibly related to the max-size of the item's image. Here's the same item page on -stage versus -prod (we should follow the prod example):

### Prod
https://exhibits.stanford.edu/david-rumsey-map-collection/catalog/tc186wy5027

<img width="994" alt="Screen Shot 2020-02-05 at 11 13 24 AM" src="https://user-images.githubusercontent.com/101482/73870312-1ad08480-4809-11ea-9b3a-422fed4cb9c8.png">

### Stage
https://exhibits-stage.stanford.edu/david-rumsey-map-collection/catalog/tc186wy5027

<img width="994" alt="Screen Shot 2020-02-05 at 11 13 12 AM" src="https://user-images.githubusercontent.com/101482/73870358-3471cc00-4809-11ea-8861-60d2b0139b3a.png">

**Comment by jkeck** [comment]
It might be worth waiting to see if projectblacklight/spotlight#2400 ends up addressing this.

**Comment by cbeer** [comment]
Seems like that did it?
