### ISSUE TITLE
Reduce the width of item show page content area

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1621]
This is a problem I have occasionally noticed on -prod but never wrote up a ticket for. 

On the item show page, it appears that we need some left and right padding or margin on the main content area -- from the item title on down (H1, viewer, etc.). The left and right edges of the content area should be aligned (not extend past) either edge of the horizontal rule below the breadcrumb. See the red vertical lines in the screenshot below:

<img width="1017" alt="Screen Shot 2020-02-05 at 2 13 34 PM" src="https://user-images.githubusercontent.com/101482/73884379-fb465580-4822-11ea-9a3d-0146807af77c.png">

**Comment by jkeck** [comment]
Was this possibly addressed upstream? (It at least seems to be somewhat better on stage now)

## Prod
<img width="1263" alt="prod" src="https://user-images.githubusercontent.com/96776/74577265-2b88a500-4f43-11ea-88ea-822e94c9114b.png">


## Stage
<img width="1157" alt="stage" src="https://user-images.githubusercontent.com/96776/74577268-2d526880-4f43-11ea-98f7-2314837437a1.png">

**Comment by ggeisler** [comment]
Yep, it looks like this is fixed. Closing.
