### ISSUE TITLE
Problematic icon on facet config page

### ISSUE THREAD

**Issue by jvine** [sul-dlss/exhibits#1630]
AMP really doesn't like the info icon on **Configuration : Search - Facets tab**. 

<img width="722" alt="Screen Shot 2020-02-06 at 5 45 17 PM" src="https://user-images.githubusercontent.com/6945691/73993945-9cf3a280-4908-11ea-9c0b-31e0cf4a2cba.png">

It's a repeated icon that has non-unique title values and non-unique IDs. The title is non-informative ("info icon"). The hover text is "Image" and "info icon" at the same time. (?!)

Is the icon adding value to the page? I would recommend removing it to avoid the issues.

**Comment by ggeisler** [comment]
It doesn't add value when the facet only has a single value, as in your example, but when there are many values it can provide the curator a quick way to see what unique values this facet has, as an aid to deciding whether this facet is worth making visible or not:

<img width="728" alt="Screen Shot 2020-02-07 at 9 05 18 AM" src="https://user-images.githubusercontent.com/101482/74045042-55612b00-4989-11ea-9345-0d16e3a6e601.png">

How many curators actually use this feature, which is not super evident on the surface, I have no idea.

I wouldn't be opposed to removing it, on the assumption that it probably isn't heavily used, and the curator can always see what values a facet has by going to a search results page and looking at the facets. That's not as convenient if the curator is in the middle of making decisions about the facet in the admin interface, but again, I don't know how many users actually use it (especially given many curators seem to leave all facets turned on).

**Comment by jvine** [comment]
Ah. It's also not keyboard-focusable, so that's another consideration if we were to keep it.
