### ISSUE TITLE
Search results controls should float right at md viewport

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1649]
There's a `.float-md-right` class on these but it doesn't seem to work (I can get it to work by manually adding `float: right` in the web inspector):

![Screen Shot 2020-02-12 at 1 43 00 PM](https://user-images.githubusercontent.com/101482/74380260-1a526380-4d9e-11ea-8bc6-bf99816baf42.png)

It would be good to get this working so users always see the controls in the same alignment.

**Comment by cbeer** [comment]
I see it floating right at `md` viewports; do you mean `sm` (and, if I remember, maybe `sm` is the  new `md`? or was it the other way around)?

**Comment by ggeisler** [comment]
Ah, yeah, you're correct, I meant `sm` instead of `md`.
