### ISSUE TITLE
Metadata alignment off in search results >  gallery view

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1650]
I thought I saw this fixed in a PR but I still see the issue where in Gallery view, the metadata isn't left-aligned with the image and title:

![Screen Shot 2020-02-12 at 1 49 04 PM](https://user-images.githubusercontent.com/101482/74380569-b2e8e380-4d9e-11ea-80ac-00605911cbe8.png)

Or maybe it is fixed, but we need a release of blacklight-gallery?

**Comment by mejackreed** [comment]
Resolved in #1675
