### ISSUE TITLE
Extraneous border on item show page

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1651]
![Screen Shot 2020-02-12 at 1 53 39 PM](https://user-images.githubusercontent.com/101482/74380868-3c001a80-4d9f-11ea-8f46-db624f5bc317.png)

**Comment by mejackreed** [comment]
@ggeisler just confirming to remove that border. It looks like that border exists already in production and comes from the Blacklight pagination tools. (when not navigating from a search result the controls will not show up)

https://exhibits.stanford.edu/leonardo/catalog/180-25705

![Screen Shot 2020-02-14 at 6 36 21 AM](https://user-images.githubusercontent.com/1656824/74535998-60b9d680-4ef4-11ea-9988-8a75b978210b.png)

**Comment by ggeisler** [comment]
@mejackreed Yeah, I noticed that it existed in production but it still seems like something we should address if we can.

I don't know how challenging this is to do, but it's definitely not desirable to show two borders in a row like this. As you said, the second border is intended to delineate the pagination tools from the main content area -- if there are no pagination tools present, we don't need the delineating border. In other words, the border goes with the pagination tools, visually.

This obviously isn't the most critical ticket, but the extra border is visual clutter that adds unnecessary vertical space before the main content of the page, so it would be good to eliminate if and when possible.
