### ISSUE TITLE
Add vertical spacing between item viewer and metadata sections

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1652]
![Screen Shot 2020-02-12 at 1 56 56 PM](https://user-images.githubusercontent.com/101482/74381102-b5980880-4d9f-11ea-920c-fca496b11b42.png)

Add `1rem` vertical margin should be okay:

![Screen Shot 2020-02-12 at 1 58 46 PM](https://user-images.githubusercontent.com/101482/74381166-cf395000-4d9f-11ea-98ed-b91ed931d2a0.png)

**Comment by cbeer** [comment]
#1664 re-adds the top margin the metadata used to  have 🤷‍♂
