### ISSUE TITLE
Adjust spacing in About page sidebar

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1653]
The current spacing in the About page sidebar is very loose:

![Screen Shot 2020-02-12 at 2 05 08 PM](https://user-images.githubusercontent.com/101482/74381873-28ee4a00-4da1-11ea-94ed-7c119184b8f7.png)

- [x] AA: `.blacklight-about_pages-show #sidebar` change `margin-top: 2rem` to `margin-top: 1rem`

- [x] A: `#sidebar .contacts-header` change `margin-top: 4rem` to `margin-top: 2.5rem`

- [x] B: `#sidebar ol.sidenav li` change `margin-top: 1rem` to `margin-top: 0.25rem`

- [x] C: `#sidebar ol.contacts li` change `margin-bottom: 2rem` to `margin-bottom: 0.5rem`

The end result should make things look more like this:

![Screen Shot 2020-02-12 at 2 21 55 PM](https://user-images.githubusercontent.com/101482/74382897-09f0b780-4da3-11ea-819c-96f91cdbfd24.png)

**Comment by jkeck** [comment]
This stying would affect almost all links in sidebars (feature pages, admin dashboard, etc).  This ticket seems to intend to be specific to About pages though.  Is the intention to update all sidebar navs or **just** the about page?
