### ISSUE TITLE
Inconsistency in display of Uploaded Item Row widget with single item

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1654]
See the weird placement of the image in second row of the -stage example below. These are Uploaded Item Row widgets, each with a single item. See the bottom of this page for the actual -stage example: https://exhibits-stage.stanford.edu/lanciani/about/project-team

![Screen Shot 2020-02-12 at 2 26 41 PM](https://user-images.githubusercontent.com/101482/74383436-090c5580-4da4-11ea-9c0b-3aac7caa8139.png)

**Comment by mejackreed** [comment]
Might be related to #1655 initial investigation indicates our mixing of flex/block display.

**Comment by jkeck** [comment]
This might benefit from adding a `cleafix` class to the wrapping div in the block (and maybe all the blocks where we do this floating now).  When testing I was using lots of text to ensure it would wrap around the content, but w/ small amounts of text we'll need to ensure the blocks are cleared of each other.  I can push up a quick PR to add that.
