### ISSUE TITLE
Can't load image in ZPR viewer

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1656]
When selecting the ZPR viewer button for an item, the modal with the viewer shows 404 loading the image:

![Screen Shot 2020-02-12 at 2 48 13 PM](https://user-images.githubusercontent.com/101482/74384879-16770f00-4da7-11ea-982c-35cf80b5232e.png)

I tried this in a couple of different exhibits with the same result. One example is near the top of this feature page: https://exhibits-stage.stanford.edu/lanciani/feature/lost-rome

**Comment by mejackreed** [comment]
@ggeisler were those examples working previously in stage? I've just tried this in a new exhibit widget and things were working for me ok: https://exhibits-stage.stanford.edu/test-coll-indexing/home.exhibit-home

**Comment by cbeer** [comment]
I'd also assume it's bad data in -stage.

**Comment by ggeisler** [comment]
Ah, okay, it didn't occur to me it was bad data. These were existing exhibits so I just assumed they should work, but happy to close this given @mejackreed's working example.

**Comment by camillevilla** [comment]
👍 I kicked off a reindexing after reading this ticket and it seemed to fix things
