### ISSUE TITLE
Contacts sidebar entries overflow column

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1657]
This happens on -prod so isn't a new BL upgrade issue, but it would be good if we could ensure that the list items in the Contacts sidebar don't extend past the sidebar column width:

![Screen Shot 2020-02-12 at 2 56 43 PM](https://user-images.githubusercontent.com/101482/74385336-2cd19a80-4da8-11ea-8a05-387b2378d441.png)

**Comment by cbeer** [comment]
I'm not seeing this. Can you have a link to -stage where this is happening?

**Comment by ggeisler** [comment]
https://exhibits-stage.stanford.edu/ua-maps-drawings/about/about-this-exhibit

You don't see it at `xl` but below 1200px wide you should.

**Comment by cbeer** [comment]
Interesting; it's wrapping just fine in other exhibits: https://exhibits-stage.stanford.edu/lanciani/about/acknowledgements
