### ISSUE TITLE
Need toggle affordance on Curation > Add items page

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1661]
The Item status and Item submission panels on the Curation > Add items page used to have visible toggle icons:

![Screen Shot 2020-02-12 at 5 03 46 PM](https://user-images.githubusercontent.com/101482/74391696-d4a39400-4db9-11ea-874c-c9ba468988bd.png)

But these have disappeared in the BL7 upgrade:

![Screen Shot 2020-02-12 at 5 03 26 PM](https://user-images.githubusercontent.com/101482/74391720-e2f1b000-4db9-11ea-991f-cab985871853.png)

I think we need visible toggle icons because I don't think the panel title being a link is a strong enough affordance for all users to understand these panels can be opened and closed.

**Comment by mejackreed** [comment]
Resolved in https://github.com/sul-dlss/exhibits/pull/1673

**Comment by mejackreed** [comment]
Reopening
