### ISSUE TITLE
Weird label alignment on Add items, Object druids form

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1663]
Label should be inline with the input:

![Screen Shot 2020-02-12 at 5 13 57 PM](https://user-images.githubusercontent.com/101482/74392511-42e95600-4dbc-11ea-88cb-e69518528f82.png)

**Comment by mejackreed** [comment]
@ggeisler I'm seeing this now resolved in stage in Chrome and Firefox at multiple screen resolutions. https://exhibits-stage.stanford.edu/test-coll-indexing/resources/new

![Screen Shot 2020-02-13 at 4 02 26 PM](https://user-images.githubusercontent.com/1656824/74486512-522ed900-4e7a-11ea-9bc0-7a11a4e65f25.png)

Feel free to reopen if this persists.
