### ISSUE TITLE
Widget layout problem: widget not flowing to new row

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1666]
The Browse categories widget is displayed next to the previous widget rather than below it.

Compare: https://exhibits-stage.stanford.edu/american-enlightenment/feature/two-founders-one-book

![Screen Shot 2020-02-13 at 9 48 25 AM](https://user-images.githubusercontent.com/101482/74463131-327dbd80-4e46-11ea-8f80-1abdb1cf6908.png)

to: https://exhibits.stanford.edu/american-enlightenment/feature/two-founders-one-book

![Screen Shot 2020-02-13 at 9 51 10 AM](https://user-images.githubusercontent.com/101482/74463233-61942f00-4e46-11ea-9ed0-b1f135f248bc.png)

**Comment by mejackreed** [comment]
We think this is resolved by https://github.com/projectblacklight/spotlight/pull/2456 .

**Comment by mejackreed** [comment]
Resolved in https://github.com/projectblacklight/spotlight/pull/2456
