### ISSUE TITLE
Heading text wraps for unclear reason

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1667]
I haven't seen this anywhere else yet, but this heading is wrapping, even though there seems to be no reason it should (and it would look better if it didn't wrap). This is at `xl` viewport width at https://exhibits-stage.stanford.edu/herbert-matter/home.exhibit-home

![Screen Shot 2020-02-13 at 9 59 28 AM](https://user-images.githubusercontent.com/101482/74464068-bc7a5600-4e47-11ea-8a8b-be29c3466b62.png)

**Comment by jkeck** [comment]
This will also be resolved by projectblacklight/spotlight#2456

**Comment by mejackreed** [comment]
Confirmed this is now fixed.
