### ISSUE TITLE
Update breadcrumb styling

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1671]
It looks like the recent updates to the SCSS stuff might have overriden our previous styling of the breadcrumbs:

![Screen Shot 2020-02-13 at 1 38 47 PM](https://user-images.githubusercontent.com/101482/74481128-fd359780-4e66-11ea-80d3-1553b6a7da52.png)

**Comment by mejackreed** [comment]
Resolved in https://github.com/sul-dlss/exhibits/pull/1672
