### ISSUE TITLE
Item show page metadata layout is now wonky

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1676]
@caaster just noticed this. I think this must've been a fairly recently introduced issue, since I've looked at the item show page a lot in recent days and didn't see the problem then:

<img width="965" alt="Screen Shot 2020-02-14 at 10 44 17 AM" src="https://user-images.githubusercontent.com/101482/74558418-244ba200-4f17-11ea-8ffa-5d2792c50ab7.png">

**Comment by jkeck** [comment]
Closed by #1679
