### ISSUE TITLE
Parker theme not applied (at least on -stage)

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1690]
Not sure if this is a peculiarity related to -stage, but the [version of Parker on -stage](https://exhibits-stage.stanford.edu/parker-00357808-6987-4f9e-9678-fbaad451fb91?q=) doesn't use the Parker theme, which should:

- Change the background color of site pages
- Remove the SUL/Stanford footers

See -prod for examples of what we do want for those.

This might be easy to fix if, when we go to -prod, the theme selection is available to us as superadmins (I don't see it on -stage).

**Comment by jkeck** [comment]
This is because it's based on the slug of the exhibit, and the slug on stage isn't "parker".  This should work out when we're in production. We can either add the odd stage parker slug to our config or have an actual parker exhibit on stage.

**Comment by ggeisler** [comment]
Sure, I'm happy to let this ticket sit until we deploy to -prod. I'll just double-check it then and then close this ticket, if that sounds okay.

**Comment by ggeisler** [comment]
Closing since the latest deploy to -prod shows the correct background color and removes the footers.
