### ISSUE TITLE
BL7: Metadata display for search results is not working properly

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1708]
Ben states: It also would appear that my choices for metadata display for search results, etc. have been lost from https://exhibits.stanford.edu/burke_mss/catalog?f%5Bgenre_ssim%5D%5B%5D=illuminations+%28painting%29&search_field=search (note… everything is there now rather than selected fields)

![Screen Shot 2020-02-18 at 4 25 14 PM](https://user-images.githubusercontent.com/3210225/74790118-88e66400-526b-11ea-9b65-a2697d1c0b09.png)

**Comment by jkeck** [comment]
I believe this was just a blip in our configurations as we we were pushing some updates up (and was resolved a bit earlier).

**Comment by blalbrit** [comment]
Yep - agreed. Search result md fields are back to normal. Thanks all!
