### ISSUE TITLE
capistrano prod deploy:  deploy to all prod boxes with single command

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/exhibits#171]
Ideally, we could type

```
cap production deploy
```

and, with user prompts, be deploying to all prod boxes at once, rather than to each one individually.

**Comment by ndushay** [comment]
Perhaps http://capistranorb.com/documentation/advanced-features/host-filtering/   provides a solution?

**Comment by cbeer** [comment]
Fixed by 88237e890b372753e8a172bf423c3f2d7e0ce71d
