### ISSUE TITLE
Home page redesign part 1: Make cards accessible

### ISSUE THREAD

**Issue by jvine** [sul-dlss/exhibits#1712]
Goal of this card redesign is to:
- make subtitle/description information perceivable to assistive technology on hover/focus
- eliminate perceivable duplication
- use meaningful link text in place of "Visit exhibit" buttons
- remove animation that affects mouse behaviour

<img width="709" alt="Screen Shot 2020-02-18 at 5 10 52 PM" src="https://user-images.githubusercontent.com/6945691/74792229-aa4a4e80-5271-11ea-9583-72f1c5df2fb8.png">

1. When the card is not in hover/focus state, the title displays below the image, as it does currently.
2. When the user tabs to or hovers over a card, the text section of the card expands upwards over the image to show the subtitle and description.
     - Same truncation rules apply.
     - Transitional animation is meant to make this visual change less jarring, but it has to be done in a way that doesn't break goal 4 above. See Note below.
3. The entire card is clickable.
4. The exhibit title is the link text.
5. The remaining content (subtitle and description) are connected to the link text via `aria-describedby` (so unique IDs are required).'
   ```
   <h2><a href="" aria-describedby="id1">Exhibit title</a></h2>
   <div id="id1">subtitle and description</div>
   ```

**Note**
The challenge is to make the card the (apparent) focusable element, while not including all its content in the link text. I think this combination might work:

- add `.stretched-link` on the title `<a>`
- turn `outline` off on these specific links
- add `outline: -webkit-focus-ring-color auto 5px;` to the `card:focus-within` state instead

**Styling**
- `.card-body` has `padding:10px` instead of 15px;
- title `<h2>` has `font-size: 1.125rem;`
- subtitle has `font-size: 1rem;`
- description has `font-size: .8rem;` with `line-height: 1.6em;`
(Gary may want to refine this later.)

**Comment by ggeisler** [comment]
@jvine Just to avoid potential confusion, in your mockup it appears that the title in the left- and right-most cards is left-aligned. The intention is to maintain the title and subtitle as centered, and the description left-aligned, correct?

**Comment by jvine** [comment]
Thanks @ggeisler, good catch! I don't even know how that happened. Yes, they are meant to be centered in the same way they are now.

**Comment by cbeer** [comment]
What should we do with  the unpublished tag?

<img width="368" alt="Screen Shot 2020-02-20 at 11 39 32" src="https://user-images.githubusercontent.com/111218/74971921-b2230380-53d5-11ea-981f-6e32c45d02e7.png">

**Comment by jvine** [comment]
When card is not in focus:  keep it in the same location. When card is in focus/hover: can the tag slide up with everything else? Margins need adjusting, but like so:

<img width="462" alt="unpublished" src="https://user-images.githubusercontent.com/6945691/74972442-8b190180-53d6-11ea-9e8e-b73179ab75e0.png">

**Comment by cbeer** [comment]
Thanks..and I want to confirm we're ok with the `:focus-within` selector only supporting newer browsers (most have it since 2017, IE Edge  just  added it  in Jan 2020)

**Comment by jvine** [comment]
I'm going to say yes because of usage stats for non-compliant browsers, overlaid with keyboard-only users. 

The alternative is to leave the outline on the title link itself, and do something else visually to "raise" the highlighted card. I may be over-concerned about the movement of the title, but I want it to be very clear that the entire card is active. I'd like to start with this method.
