### ISSUE TITLE
BL7: Analytics results for an exhibit includes pages from other exhibits

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1724]
I definitely saw this while I was training Spencer today, but I neglected to take a screen shot of the Dashboard/Analytics for that exhibit (https://exhibits.stanford.edu/medicineinnovation), and now the history has been overwritten. So I am leaving this ticket open, because I hope I can add "proof" via a screen shot.

**Comment by caaster** [comment]
Yay! I found an example. Please see the second entry under Most popular pages.

![Screen Shot 2020-02-21 at 10 09 58 AM](https://user-images.githubusercontent.com/3210225/75059819-9467a400-5492-11ea-8f26-380bf013b92d.png)

**Comment by cbeer** [comment]
It looks like we're faithfully representing the data from Google. They seem to have some bad data from late January. In spotchecking this week's data, I'm not seeing any evidence it's an ongoing thing, and I don't think there's a way to remediate Google's data.

**Comment by mejackreed** [comment]
@caaster since we have indicated we think this is a data issue with Google, would we be ok to close for now? Perhaps reopen if we see something else fishy with the data?
