### ISSUE TITLE
Home page cards:  Description truncation is awkward at some screen widths

### ISSUE THREAD

**Issue by jvine** [sul-dlss/exhibits#1726]
### min-width: 1200px
Expanded text area extends above top of card, no margin at bottom. 

<img width="570" alt="Screen Shot 2020-02-20 at 4 43 45 PM" src="https://user-images.githubusercontent.com/6945691/74993562-2f636e00-5400-11ea-9854-ba8bb02177a5.png">

Text has no bottom margin, is hidden or cut off

<img width="271" alt="Screen Shot 2020-02-20 at 4 48 48 PM" src="https://user-images.githubusercontent.com/6945691/74993785-00013100-5401-11ea-9741-40eaef627c16.png">   <img width="278" alt="Screen Shot 2020-02-20 at 4 47 15 PM" src="https://user-images.githubusercontent.com/6945691/74993793-042d4e80-5401-11ea-835f-da2e513f8b16.png">

### max-width: 720px
Text is truncated but the overlay is extending up over the card above it.

<img width="510" alt="Screen Shot 2020-02-20 at 4 53 11 PM" src="https://user-images.githubusercontent.com/6945691/74993975-9897b100-5401-11ea-937b-7fa2e9f49ac7.png">

Card is intended to have a bottom margin, and should not extend beyond the outer size of the card. The description needs to be truncated if it can't fit. (Was it not previously?)

**Comment by jvine** [comment]
(I wonder if this is related to font sizes?)

**Comment by cbeer** [comment]
Can you clarify what  truncation behavior you'd like to see? Previously, we truncated the text to 168 characters up to medium viewports and provided the  full description otherwise (presumably trusting the curator or service team review to address any problems?). Previously, it looked like:

<img width="310" alt="Screen Shot 2020-02-21 at 07 25 46" src="https://user-images.githubusercontent.com/111218/75047353-76db1000-547b-11ea-9f76-042ecbfb53a1.png">

**Comment by jvine** [comment]
It's challenging when all three elements can be multi-line and unpredictable. At a minimum, the overlay should never be allowed to extend beyond the card. A bottom margin should apply no matter how much text is present. Character count is likely not the best way to achieve this, though. Maybe just a maximum height (for the overlay as a whole) with hidden overflow, even if we lose the ellipsis. 

I'd really like @ggeisler 's input on this as well, but he's still out.

**Comment by jkeck** [comment]
One possible approach would be to use [`line-clamp`](https://caniuse.com/#search=line-clamp) (and have IE fallback to the hidden overflow).  I poked around a tiny bit w/ it, and would be happy to pair up to see if it might be viable.

**Comment by jkeck** [comment]
Using line-clamp to truncate the exhibit title, subtitle, and description (differently at various breakpoints) as well as updating the `max-height` of the element that we use to "slide" the subtitle/description section up/down I was able to get here:

## Before
![responsive-truncation-before](https://user-images.githubusercontent.com/96776/75203642-89777280-5723-11ea-89d7-1ad4af7e67e7.gif)

## After
![responsive-truncation-after](https://user-images.githubusercontent.com/96776/75203654-91371700-5723-11ea-834b-f8a2d2b6b7b9.gif)

If this seems reasonable I'll get this ready for a PR.

**Comment by ggeisler** [comment]
Looks good to me.

**Comment by jvine** [comment]
I think it looks good too, but I'm wondering if the title truncation might be an issue. At medium width, the titles below are three lines, so would be truncated - ellipsis indicates what would be hidden. In some cases, it's meaningful text, and I think the curators might be concerned about it. (Even at large width a few titles are three lines, but lose a word rather than 2 or 3.)

I wonder if we can cap the title at 3 lines on medium? or large and medium? 

OR - are you truncating only when the overlay is open? (would that be a weird effect?)

**Truncated titles**
1. Wang Jingwei and Lin Baisheng Photograph ... collection
2. The San Francisco Traditional Jazz ... Foundation Collection
3. Secret Service: Old and Young King Brady, ... Detectives
4. Herbert Matter: Modernist Photography and ... Graphic Design
5. Ancient, Medieval, and Early Modern ... Manuscripts at Stanford
6. Universe of Maps - Opening the David ... Rumsey Map Center
7. Barry L. Ruderman Conference on ... Cartography Exhibits
8. Coordinates: Maps and Art Exploring Shared ... Terrain
9. Stanford University Board of Trustees ... Records

**Comment by jkeck** [comment]
We have flexibility to choose how many lines to truncate each piece of content at the various breakpoints, so that shouldn't be a problem.  It will require removing lines from other sections to make it fit, but I think that's the tradeoff we have to make.

**Comment by jkeck** [comment]
This should hopefully be closed by projectblacklight/spotlight#2489.  🤞
