### ISSUE TITLE
Page navigation is still wonky

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1730]
When I scroll to the bottom of exhibits.stanford.edu to navigate to the next page of exhibits, the navigation is still wonky. There are now two little boxes next to each other, one outlining "next" and another box just to the left of the "next" box, that highlights when I hover over it with my mouse. This is confusing because it is not clickable and goes nowhere. A similar problem is present at the bottom of the other pages.

![Screen Shot 2020-02-21 at 8 07 33 AM](https://user-images.githubusercontent.com/3210225/75051009-f370ed00-5481-11ea-8d5a-671ec3086b33.png)

**Comment by jkeck** [comment]
Closed by projectblacklight/spotlight#2487
