### ISSUE TITLE
Bibliography reference structure is not correct

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1736]
This is a Parker-specific issue related to the Bibliography section on the manuscript item show pages.

Several aspects of the reference seem to be built incorrectly. I don't know if this is a new problem or if it existed before the BL7/BS4 upgrade (doesn't seem like it should've been affected by the upgrade, but it also doesn't seem like Ben or I would not have noticed these issues when we first developed the Bibliography feature for Parker).

<img width="733" alt="Screen Shot 2020-02-24 at 1 08 34 PM" src="https://user-images.githubusercontent.com/101482/75187641-b0c04680-5707-11ea-948f-eb9851d52592.png">

Here's the item used in the screenshot above: https://exhibits.stanford.edu/parker/catalog/wz026zp2442

- A: There should not be a comma between the year and the title of the book. Just year, followed by a period, followed by a space, then the title.

- B: There shouldn't be a comma followed by a period at the end of the book titles. Just a period, space.

~- C: It looks like something is off when a reference includes a volume number. For example, the reference indicated for C here has the volume as both part of the title and a separate volume specification.~

~- Volume in Reference item show page: If you follow the reference above to the [full reference page](https://exhibits.stanford.edu/parker/catalog/D5IVTFTE), or look at any other reference item page, we are not displaying the volume as a metadata field. Again, not sure if we did this prior to the upgrade, but it seems like we should display every part of the reference on the reference item page (for the user, but would also make it easier to troubleshoot the reference display problems).~

**Comment by mejackreed** [comment]
In regards to "C", that particular example has the volume number within the title, so it is displaying twice. We can't do anything about that except ask someone to remediate the data if it should even be.

**Comment by mejackreed** [comment]
@ggeisler With regards to Volume, it seems like this is turned off in the item details configuration.

![Screen Shot 2020-02-24 at 2 26 35 PM](https://user-images.githubusercontent.com/1656824/75192598-bfabf680-5711-11ea-8831-c336ad724895.png)

I'm not sure we have the ability to differentiate in this config between the types of docs, but do we need to confirm what this should be before proceeding?

**Comment by ggeisler** [comment]
Ah, I forgot that the Metadata configuration would apply to this type of show page as well.

I will look at those fields in the config; I think any missing ones we want to show in the Reference item page will be okay to turn on, since they are unlikely to be present in the Manuscript item show page (at least, volume seems fine to turn on in that sense).
