### ISSUE TITLE
Reference item show page fails to load when many documents

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1737]
It's possible this is a problem with my browser setup, but I see the same issue on both Chrome and Firefox so it's at least worth someone else verifying.

It appears that for Parker reference items that are included in many different Parker documents, the list of documents is too large to load, so we just get the "This reference is found in these document bibliographies" heading but the list of documents that should appear below does not ever show up.

For example, I go to: https://exhibits.stanford.edu/parker/catalog/KAGI2SI5

No list of documents is displayed, but looking at the inspector there seems like a long list that should be displayed, and looking at the console (in Chrome, don't see the equivalent in Firefox) it seems like Chrome just gave up because the request was too large:

<img width="1044" alt="Screen Shot 2020-02-24 at 1 34 57 PM" src="https://user-images.githubusercontent.com/101482/75189342-35f92a80-570b-11ea-8158-334973c178d6.png">

**Comment by mejackreed** [comment]
I would gather that this bug existed previously.
