### ISSUE TITLE
OSD version of the Item Embed widget needs sizing and styling fixes

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1744]
The Item Embed widget, when using an uploaded (as opposed to an SDR) item, needs updating. In the screenshot below, there are three consecutive item embeds used. The top two are SDR items and the bottom one uses an item uploaded to the exhibit, and thus is shown in the OSD viewer.

<img width="1176" alt="Screen Shot 2020-02-25 at 1 11 39 PM" src="https://user-images.githubusercontent.com/101482/75284827-bf276480-57d2-11ea-93a5-957144b14788.png">

- [ ] OSD viewer needs to use full width available.

In the screenshot, the image is zoomed in but the viewer (and associated controls) are only using 50% of the width available to the viewer half of the rendered widget. I think this has to do with the `.col-md-6` class on the `<div class="opensedragon-container">` element; if I change that to `.col-md-12` the viewer takes the full-width as desired. And this is not an issue at `sm` viewport and below.

(Same issue is present when there is no heading/text used in the widget; it only uses half the width of the page.)

- [x] OSD viewer controls need to use full width available. 

Same issue as above; we want the `<div class="controls"` element to use the full width available so that the OSD controls are centered above the viewer image area.

- [x] OSD viewer needs a border. `border: 1px solid $color-gray-80:` (or the `thumbnail-image-border()` mixin, which defines the same thing).

With the fixes above there is still a styling issue, in that if the image is not zoomed in enough to take up the full space of the viewer, it can feel disconnected from the OSD controls. I suggest we add a border around the viewer so the image and the controls are more clearly associated. 

The end result of the fixes above should look roughly like:

<img width="956" alt="Screen Shot 2020-02-25 at 1 41 05 PM" src="https://user-images.githubusercontent.com/101482/75285860-a4ee8600-57d4-11ea-99d4-75ff5d7c2d27.png">

---

<img width="956" alt="Screen Shot 2020-02-25 at 1 42 38 PM" src="https://user-images.githubusercontent.com/101482/75285899-b46dcf00-57d4-11ea-96b9-ff6a5ed4fd51.png">

**Comment by mejackreed** [comment]
@ggeisler I'm looking at resolving this issue. It seems like several of these will be resolved with an upstream change in blacklight-gallery. 

With regard to:

> OSD viewer needs a border

I don't think this was previously in Exhibits. It does show up on the show page, but looking at all the styles I can't see it being used previously. 

Also, instead of centering, I'm proposing pull to the right (previous behavior) to account for pagination tools.

**Comment by ggeisler** [comment]
@mejackreed Yeah, I don't know that the OSD border was used previously, it just seems like it would be very useful to have now. Images don't necessarily fill the OSD viewer area, and if there is a lot of whitespace between the image and the controls a user without prior understanding of what's going on might not understand that they are associated (plus it looks sort of unpolished when there is a big whitespace gap around the image with no clear reason for it).

Pulling the controls to the right is fine; I just said center because that was the result we'd get for free if the tools column specification was fixed to match the viewer column specification.

**Comment by mejackreed** [comment]
Just awaiting new releases and deployment now.

**Comment by mejackreed** [comment]
Now released
