### ISSUE TITLE
Caching (?) issue related to search result context being displayed

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1747]
JV and I noticed a couple of what seem to be related issues:

- In an exhibit in which you haven't conducted a search, when you go to an item show page via means other than from a search result page (e.g., from a widget on a home/feature/about page), the item show page displays the breadcrumb and then the item title, as expected (other than showing a redundant border, which is probably related to all of this).

- Same exhibit, after you have done a search a some point, when you go to the same item show page via means other than the search results page, the item show page displays - in addition to the breadcrumb and title - the "previous | next" pagination, which should not be displayed because we haven't come from a search result and thus the "previous" and "next" items don't really make sense.

Here are how the item page looks in the two scenarios above:

<img width="1072" alt="Screen Shot 2020-02-25 at 4 56 58 PM" src="https://user-images.githubusercontent.com/101482/75298484-daed3380-57ef-11ea-8961-d33b2a44deb9.png">

The second scenario should look like the first, unless we've arrived at the item show page directly from a search result page (or another item show page in the current result set).

### Possibly related
If I go to a new exhibit where I haven't yet conducted a search, and I navigate to an item show page as in the first scenario above (from a widget item on a page), the "Search Results" breadcrumb item is linked to the search result of the last exhibit I did do a search in.

For example, after getting a search result in the Hopkins Transportation exhibit (gardiner-sfba), I go to the Automobility exhibit, select an item from the homepage grid, and on that item show page, the "Search Results" breadcrumb link points to the search result in the Hopkins Transportation:

<img width="644" alt="Screen Shot 2020-02-25 at 4 46 34 PM" src="https://user-images.githubusercontent.com/101482/75298887-e5f49380-57f0-11ea-936b-ecaead751662.png">

**Comment by mejackreed** [comment]
With regard to the redundant border, that was resolved in https://github.com/projectblacklight/blacklight/commit/ab536bf7c608e82db3d324da5350f1ade2be8c1c but has yet to be released yet.

**Comment by cbeer** [comment]
I think @mejackreed 's work on search sessions in https://github.com/projectblacklight/spotlight/pull/2500 will fix this?
