### ISSUE TITLE
Landing page redesign part 2: Remove the sidebar.

### ISSUE THREAD

**Issue by jvine** [sul-dlss/exhibits#1750]
Remove right sidebar from the landing page to allow the exhibit cards to use the full width of the page. [Interactive mockup](https://xd.adobe.com/view/2754001b-3f94-433f-7f07-e1e57aa2efc2-5165/).

<img width="1179" alt="Screen Shot 2020-02-25 at 4 16 17 PM" src="https://user-images.githubusercontent.com/6945691/75299540-2dc3ec80-57ea-11ea-9ae1-16980dfab78d.png">

- [x] Add a menu bar to the landing page
- [x] Add two right-aligned menus for the sidebar links visible to all users:
   - About 
        <img width="314" alt="Screen Shot 2020-02-25 at 4 18 38 PM" src="https://user-images.githubusercontent.com/6945691/75299692-927f4700-57ea-11ea-9c30-3cc47f2ce93d.png">
   - More at Stanford 
        <img width="352" alt="Screen Shot 2020-02-25 at 4 18 50 PM" src="https://user-images.githubusercontent.com/6945691/75299710-9dd27280-57ea-11ea-93a1-a1697cf68a8e.png">
- [x] When the user is logged in, add a third menu to the far right:
   - Admin
        <img width="224" alt="Screen Shot 2020-02-24 at 3 12 12 PM" src="https://user-images.githubusercontent.com/6945691/75299560-403e2600-57ea-11ea-9919-02b6335f96eb.png">
- [x] Add a right-aligned search box
      <img width="416" alt="Screen Shot 2020-02-25 at 4 21 31 PM" src="https://user-images.githubusercontent.com/6945691/75299821-f0139380-57ea-11ea-9f33-760ca15cdcea.png">
   - Suppress the fielded search
   - Placeholder text is "Find items in all exhibits"
- Search results are as specified in #1531 
- [x] Add a breadcrumb to the search results page:
  - Exhibits / Search results
      <img width="380" alt="Screen Shot 2020-02-25 at 4 24 04 PM" src="https://user-images.githubusercontent.com/6945691/75299941-42ed4b00-57eb-11ea-8780-1ecc5d179378.png">

### Notes
- Goals are to offer the search feature efficiently, but without making the Exhibits landing page look like a search-focused application; and to allow for future expansion of features without dramatically changing the layout again.
- Fielded search in this context seems like it would invite errors that outweigh the potential benefit to a small category of users.

**Comment by ggeisler** [comment]
> Add a right-aligned search box

Ha, didn't we just discuss the difference between right and left?

**Comment by cbeer** [comment]
I assume that should  read `left-aligned search box`?

**Comment by ggeisler** [comment]
Yes.

**Comment by ggeisler** [comment]
It's not mentioned directly in the original description, I believe we also intend for the breadcrumb to display on the admin pages. So if you select Admin.. Order exhibits:

> Exhibits / Order exhibits 

(It would be more complete context to be "Exhibits / Admin / Order exhibits" but we don't have a parent "Admin" page to link to.)

**Comment by cbeer** [comment]
I think we should push those additional breadcrumbs to a separate ticket. That'll probably be done up in spotlight.

**Comment by ggeisler** [comment]
Okay, will post a ticket there.
