### ISSUE TITLE
Search across: Grouped, list view result set count doesn't match exhibit count

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1759]
In the grouped mode, list view, we show the number of matching results for each exhibit. That number is linked to that exhibit's search results page, passing the current query. However, the result set count in the individual exhibit most often does not match the count provided in the link we selected to get there.

Here's [an example](https://exhibits-stage.stanford.edu/search?group=true&q=manuscript&search_field=search&sort=pub_year_isi+asc%2C+title_sort+asc&utf8=%E2%9C%93&view=list). I searched "manuscript" with no other query parameters. For the first five exhibits returned, only one had a matching number of result items when I navigated to its results page:

<img width="860" alt="Screen Shot 2020-02-26 at 11 44 03 AM" src="https://user-images.githubusercontent.com/101482/75377250-a1b7d080-588e-11ea-8367-ed277dec6242.png">

**Comment by cbeer** [comment]
The discrepancy is due to a  change in how we index exhibit membership (from 2017), and some of these exhibits haven't been reindexed in awhile.. After reindexing the first exhibit, we have the same number appearing. There's a few documents (ok, 334629) like that in -prod too

**Comment by cbeer** [comment]
This is done in -prod, except for copyrightrenewals and mjf, both of which need a slightly more extensive remediation.

**Comment by cbeer** [comment]
MJF is remediated; copyright renewals is in progress.

**Comment by caaster** [comment]
Work appears to be complete; closing this issue.
