### ISSUE TITLE
Search across: exclude unpublished exhibits?

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1762]
I assume that only superadmins would see unpublished exhibits in the results, but even so, I wonder if there is enough value for superadmins to see unpublished exhibits in results to justify cluttering the results with exhibits that are old, unused, or otherwise probably not relevant to the search a superadmin might be doing?

@caaster @jvine: Do you see any argument against including only published exhibits in the results, for all users?

<img width="860" alt="Screen Shot 2020-02-26 at 12 08 56 PM" src="https://user-images.githubusercontent.com/101482/75378435-e7759880-5890-11ea-8575-49a309c75cde.png">

**Comment by caaster** [comment]
@ggeisler - I don't see any argument against including only published exhibits in the results, for all users.

**Comment by jvine** [comment]
Nor do I.

**Comment by mejackreed** [comment]
The only argument I would see is that there would be no other way for a super admin to determine if a given document is indexed in multiple unpublished exhibits without checking them all individually.

**Comment by jvine** [comment]
Erm. That's actually a pretty good argument.

**Comment by caaster** [comment]
I agree @mejackreed @jvine

**Comment by ggeisler** [comment]
True, and I'm fine with keeping the current behavior, as long we think this is something that a superadmin would really have a reason to do (_as a superadmin, I want to find which **unpublished** exhibits that contain a specific item_).

**Comment by jvine** [comment]
Fine distinction, but maybe _as a superadmin, I want to find all exhibits that contain a specific item, including unpublished exhibits_, in the sense that as superadmin I want the complete picture - that feels like a legit perspective for that role.

**Comment by ggeisler** [comment]
Well, that's what I'm getting at, does a superadmin ever really have a reason to want to know which unpublished exhibits contain a specific item? I'm just not aware of a use case where unpublished exhibits would be relevant to a goal. But I'm fine with assuming there could be, and will close this issue.

Longer term, I think having a superadmin-only facet for published/unpublished exhibits might be useful; otherwise the superadmin is going to have to logout or use a non-logged in browser if they want to get results that aren't polluted with unpublished exhibits (including lots of extra titles in the Exhibit title facet).

**Comment by jkeck** [comment]
Would a possible enhancement be to indicate that the exhibit being displayed in the metadata is not published? (using a label or something similar like we do elsewhere)?

**Comment by caaster** [comment]
@jkeck from my point of view this would be great, of course if it were for super admins only (just making sure that's what you're referring to here)

**Comment by ggeisler** [comment]
That might be a nice compromise. Let me think about how that would look across all of our views and mockup something up in a new ticket. Thanks @jkeck.
