### ISSUE TITLE
Search across: Link document titles when an item is in multiple exhibits, but only one is visible to the user

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/exhibits#1767]
E.g. for https://exhibits-stage.stanford.edu/search?q=manuscript&search_field=search&sort=pub_year_isi+asc%2C+title_sort+asc&view=list

<img width="877" alt="Screen Shot 2020-02-26 at 13 07 13" src="https://user-images.githubusercontent.com/111218/75387930-ee080e00-5898-11ea-9053-51d4e07428df.png">

**Comment by ggeisler** [comment]
This is likely affected by #1771.

**Comment by cbeer** [comment]
Yay!
