### ISSUE TITLE
Search across: item visibility facet?

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1769]
There might be a good reason for this, but in the search across facet design ticket #1524, the Item visibility facet todo is checked off, but I don't see it in the UI on -stage?

Whether we include or don't include private items in the results seen by superadmins seems like a tradeoff similar to that discussed in #1762 about including unpublished exhibits in the results. It could be useful for some use cases to see private items (I suppose? thoughts @caaster?) but including them by default has the potential to confuse the result set for superadmins. 

If we can't provide a superadmin-only facet to control private item visibility, I can look at doing a design where we clearly label private items, similar to what @jkeck suggested for unpublished exhibits.

I still think a facet is better overall, though, since labeling private items doesn't affect search result counts and things like that that a use case might care about determining.

And I personally am not opposed to not including private items at all, but there might be use cases that warrant their inclusion, again based on the unpublished exhibit discussion in #1762.

**Comment by cbeer** [comment]
Hm. I thought it was working, but  maybe that  was in an earlier iteration.

I'll work on readding it, but it seems like the facet might  be confusing because an item is private/public in the context of an exhibit, so an item could be public in some exhibit but private in another.

**Comment by ggeisler** [comment]
> an item could be public in some exhibit but private in another.

Good point. So will the facet work by only excluding items that are private in _all_ included exhibits? 

This will be harder to apply a labelling strategy to than unpublished exhibits.

I guess we can see how things look in your PR. I'm a little worried this might create more confusion than it is worth, versus just ignoring private items (or, more specifically, the instances of items that are private).

**Comment by cbeer** [comment]
The other way around -- visibility > private will limit  your search to items that are marked as private in any exhibit.

**Comment by camillevilla** [comment]
^-- sorry, @ggeisler just saw your comment now. I assume we'll be doing more testing for this in stage.

**Comment by ggeisler** [comment]
> The other way around -- visibility > private will limit your search to items that are marked as private in any exhibit.

I see, okay, we can test it out and see how it feels.
