### ISSUE TITLE
Search across: add vertical margins to facet section

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1773]
I'm hoping we get to #1750 and the sidebar won't be relevant, but in case we don't we need some spacing around the new search across sidebar elements.

- [ ] Add `2rem` vertical margin above and below the `<div id="facets"` element 

Result should look something like:

<img width="414" alt="Screen Shot 2020-02-26 at 4 04 59 PM" src="https://user-images.githubusercontent.com/101482/75396503-dd17c680-58b1-11ea-8855-5896591d9162.png">

Compared to current:

<img width="414" alt="Screen Shot 2020-02-26 at 4 06 17 PM" src="https://user-images.githubusercontent.com/101482/75396522-f02a9680-58b1-11ea-8ae7-76d890b0b5c6.png">

**Comment by cbeer** [comment]
There's a PR up for #1750, and  I thought we agreed we weren't  shipping search across  without the sidebar / nav change, so I suspect no action is needed?

**Comment by ggeisler** [comment]
Ah, okay, lost track of the plan. Closing.
