### ISSUE TITLE
Site landing page searchbox sizing and menu alignment

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1783]
This is based on latest `master` running locally, so we can close if these are known issues that just haven't been completely addressed yet.

- [x] Searchbox in site menu isn't wide enough at `md` and larger viewports to contain the placeholder text (and there is space for it to be wider in those viewport widths)

- [x] The right-side menus are aligned more like left-side menus, in that when open they extend to the right instead of the left, thus cutting off the menu options at some viewport widths.

<img width="1184" alt="Screen Shot 2020-02-27 at 10 13 24 AM" src="https://user-images.githubusercontent.com/101482/75468624-bce81600-594a-11ea-934d-b4ba31052567.png">

**Comment by cbeer** [comment]
What browser + viewport size are  you seeing that search box issue?

**Comment by ggeisler** [comment]
Chrome and the screenshot is `xl`. But I believe it was also on `lg` (i.e., all viewports above where it collapses and takes full-width).

If you aren't seeing it I'll take another look after I switch back to running exhibits locally.

**Comment by ggeisler** [comment]
@cbeer Yeah, it is only in Chrome (Version 80.0.3987.122 (Official Build) (64-bit)), at `md` and above. Below is what I currently see in Safari, Firefox, and Chrome (left to right):

<img width="1188" alt="Screen Shot 2020-02-27 at 4 22 49 PM" src="https://user-images.githubusercontent.com/101482/75496153-998a8e80-597d-11ea-821c-3a26be058344.png">

**Comment by cbeer** [comment]
Firefox and Safari were fine with it. Ugh. We're not  currently setting  a width and expected the browser to flexbox appropriately. Can we just add, say, `min-width: 17em` and call it  a day?

**Comment by ggeisler** [comment]
Sure, I was going to say, we only need a little bit more to work for Chrome so we just add a bit it should still look fine on the other browsers. `17em` looks good.
