### ISSUE TITLE
Rare Music Materials: note text not displaying in note field

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/exhibits#1786]
Reported via exhibits-feedback: The note is not displaying in the note: field in 
"Rare Music Materials at Stanford" -- https://exhibits.stanford.edu/rare-music/catalog/xk766xt3708

<img width="1002" alt="Screen Shot 2020-02-27 at 10 26 22 AM" src="https://user-images.githubusercontent.com/73732/75474352-b312e280-594b-11ea-83cf-5533d7c437fb.png">

**Comment by jkeck** [comment]
The note field in question is an exhibit specific field. 

<img width="890" alt="Screen Shot 2020-02-27 at 10 40 48 AM" src="https://user-images.githubusercontent.com/96776/75475469-b27b4b80-594d-11ea-99fb-a44c09fea23f.png">

Do we know if the user expected data in the note field for this record that no longer exists, or just that the record w/o Note data is unnecessarily showing the Note label? (I know the Feedback wasn't descriptive about this, but it might be useful to gather if the expectation is that curator provided content should be there or not).  From looking in the DB it looks like this field is associated w/ a blank string (which can/should be addressed, but just want to validate that we're not expected to have any note data for this item)

**Comment by jkeck** [comment]
I feel like this issue was attempted to be addressed in projectblacklight/spotlight#2356

**Comment by jkeck** [comment]
And FWIW, the label no longer displays. I added the document to my local unpublished exhibit, which I'm not sure if that would/could have caused the blank data to be excluded (as would be expected if the note was empty)

**Comment by caaster** [comment]
Closing this very old ticket; if the issue resurfaces a new ticket can be created.
