### ISSUE TITLE
Possible problem with the Search Results widget

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1796]
I noticed that the [search result widget used on a page](https://exhibits.stanford.edu/gardiner-sfba/feature/streetcar-staff-portraits) (existing prior to the BL7 upgrade) no longer renders any content:

<img width="1158" alt="Screen Shot 2020-02-27 at 5 46 28 PM" src="https://user-images.githubusercontent.com/101482/75500043-20913400-5989-11ea-9432-32cb2f514e60.png">

The saved search that it appears to be using does exist: https://exhibits.stanford.edu/gardiner-sfba/browse/transit-employees

So I tried to recreate it, but I can't select the Search Results widget:

<img width="1134" alt="Screen Shot 2020-02-27 at 5 43 13 PM" src="https://user-images.githubusercontent.com/101482/75500106-4a4a5b00-5989-11ea-8a95-ea0b4bdff35d.png">

**Comment by cbeer** [comment]
It seems like it's working to me (some weird caching issue?). I think the  widget thing might  be because we limit you to only one search result widget per page?

**Comment by ggeisler** [comment]
Yep, weird, I see it now. And, yeah, I didn't think about the limit to one for this widget, but I believe you're correct about that and it certainly explains the behavior I saw.
