### ISSUE TITLE
Home page exhibit card truncation updates

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/exhibits#1803]
With the removal of the sidebar on the homepage we will need to update the # of lines we truncate particular data at various breakpoints.  (This may be changing based on current convo, so the exact lines may change)

This will be more ergonomic with something like variables added upstream in Spotlight to set the line clamp numbers (that we can override locally)

**Comment by jkeck** [comment]
Looking at this w/ the typo fix in #1809 the truncation isn't ending up looking as bad as it originally was.  I'll let @jvine / @ggeisler comment if they think we need to do anything special locally for our updated home page wrt truncation (and if not we can close this)

**Comment by jvine** [comment]
@jkeck did you mean specifically with 4 columns at md width? because currently I am not seeing anything really problematic with the truncation. Are there specific things you're looking at?

**Comment by jkeck** [comment]
Yeah, I think that was were I noticed the most egregious of the truncation issues (which is we were truncating way to early at that breakpoint).  With the updated columns, it doesn't appear to be problematic to me either.

**Comment by jkeck** [comment]
Closing this as things are looking 👌.  If we need to update the truncation spec, we can open a new issue to do that.
