### ISSUE TITLE
Font size for card heading <h2> has reverted to 1rem

### ISSUE THREAD

**Issue by jvine** [sul-dlss/exhibits#1805]
Size for the `<h2>` heading was spec'd as 1.125rem, and that is what is currently on prod. On stage, it's now 1rem. Also would like to improve the line spacing.

- [x] make the font size 1.125rem
- [x] increase the line height to 1.3

**Prod**
<img width="273" alt="Screen Shot 2020-02-28 at 11 14 50 AM" src="https://user-images.githubusercontent.com/6945691/75581060-a8c11900-5a1d-11ea-9d63-761249a36806.png">

**Stage**
<img width="273" alt="Screen Shot 2020-02-28 at 11 14 58 AM" src="https://user-images.githubusercontent.com/6945691/75581063-a959af80-5a1d-11ea-9470-e6ac2358d8fb.png">

**Desired**
<img width="267" alt="Screen Shot 2020-02-28 at 11 31 27 AM" src="https://user-images.githubusercontent.com/6945691/75581178-e160f280-5a1d-11ea-881e-edaa1b655da7.png">

**Comment by cbeer** [comment]
https://github.com/projectblacklight/spotlight/pull/2498 will restore the font size.
