### ISSUE TITLE
Search across: grouped by results don't include pagination

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1826]
When a search across result set include more than 10 exhibits and you are looking at one of the Grouped by views, the `page-entries` text indicates a paged result ("1 - 10 of 14 exhibits") but all result items are shown on a single page (all 14 exhibit result items are displayed on the page in this example):

![Screen Shot 2020-03-03 at 1 08 56 PM](https://user-images.githubusercontent.com/101482/75820042-80ecf080-5d50-11ea-970b-2b514a8835a2.png)

**Comment by jkeck** [comment]
@ggeisler is the desire to paginate the exhibits, ensure that the `N - N of N` number is accurate, or remove the `N - N of N` text all-together?

**Comment by ggeisler** [comment]
As we discussed, let's omit pagination from the Grouped by result views, at least for now, under the assumption that a user interested in viewing results by exhibit probably will want to easily scroll through all the matching exhibits.

So this means removing the `page-entries` display and maintaining the current non-paginated behavior.
