### ISSUE TITLE
Pagination border missing / needs margin

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1833]
Two issues related to the border that goes above the search results pagination. These apply to both an exhibit's results and search across results.

### Need vertical space between pagination and border
I think this might be a Blacklight issue that Exhibits is inheriting. There should be whatever vertical space we used to have, or about `0.5rem`.

![Screen Shot 2020-03-05 at 10 07 26 AM](https://user-images.githubusercontent.com/101482/76011294-2fb43c80-5ec9-11ea-9f74-fa27a6070409.png)

---

![Screen Shot 2020-03-05 at 9 53 52 AM](https://user-images.githubusercontent.com/101482/76011306-35118700-5ec9-11ea-9d84-c0a97e119862.png)

### Gallery view results need a pagination border
![Screen Shot 2020-03-05 at 9 54 33 AM](https://user-images.githubusercontent.com/101482/76011340-435fa300-5ec9-11ea-9ec2-7783bec93a0d.png)

**Comment by ggeisler** [comment]
@mejackreed and @jkeck Since the BL PR closed this ticket just checking that the second part of this ticket was accounted for. That was for Gallery view results.

**Comment by mejackreed** [comment]
@ggeisler the pagination wasn't using a border it was coming from the individual results items. Yep seems like we need another PR to add for gallery view ill reopen.

**Comment by mejackreed** [comment]
@ggeisler one question here I raised in https://github.com/projectblacklight/blacklight-gallery/pull/87 . Would it just be better to remove the border? (The border is coming from the Blacklight list item)

**Comment by ggeisler** [comment]
@mejackreed I personally don't think it's better to remove the border, because I feel that the pagination border echoes the border that precedes the view content; the two borders separate the view content (the result items) from the view controls. It doesn't feel right to me to separate the top controls from the result items but not separate the pagination controls. Here's a comparison:

<img width="1309" alt="Screen Shot 2020-03-10 at 9 15 50 AM" src="https://user-images.githubusercontent.com/101482/76334289-0ec85e80-62b0-11ea-9596-da2b138f2ae0.png">

This is just my opinion, however, and it is a pretty subtle thing. If it makes more sense when taking into account that this is a library that implementors might style differently or have different viewpoints about, I don't have any problem with leaving out the border in blacklight-gallery. I'd likely add it back in Exhibits as a Stanford customization, though.
