### ISSUE TITLE
Find exhibits by title, version 1

### ISSUE THREAD

**Issue by jvine** [sul-dlss/exhibits#1842]
Related to #1838 and #1843

This is a slightly novel UX that uses a dropdown to present both search and typeahead features.

### Current search box is replaced by a new input. 

- The search icon at the front is a prepend that's been custom styled. Intent is to provide an affordance that is clearly "Search" without implying a button.

   <img width="400" alt="search 1 start" src="https://user-images.githubusercontent.com/6945691/76570084-cd7fac80-6471-11ea-8aa1-6a70bde93f20.png">

### On focus, a popup appears below the search box.

- Popup has two sections with headers. Structure:
   - hidden `<h2>Search</h2>` within the popup
   - `<h3>` for the visible headings
- User can click Search button for an empty item search

   <img width="400" alt="search 1 focus" src="https://user-images.githubusercontent.com/6945691/76570083-cce71600-6471-11ea-8553-424efd48d16b.png">

### User begins typing, content appears in popup

- typed term is duplicated in the Find items section
   - click Send or press Enter to submit the keyword search
- up to 5 exhibit titles that match the string are included in the Exhibit titles section
   - tiny thumbnails are included to offset a usability issue discovered in a very limited test
   - matched text in the titles is non-bold; remainder (differentiating text) is bold
   - keyboard tab order is Search button then exhibit titles

   <img width="400" alt="search 1 typeahead" src="https://user-images.githubusercontent.com/6945691/76570082-cc4e7f80-6471-11ea-9635-a5dd0cd8b8a3.png">

### If there's no matching exhibit title

- Explicit "no matches" text

   <img width="400" alt="search 1 no title match" src="https://user-images.githubusercontent.com/6945691/76570080-cbb5e900-6471-11ea-8748-3811619640d1.png">

### Feature is also present on to search results page

- Search term is retained in the input

   <img width="400" alt="search 1 results" src="https://user-images.githubusercontent.com/6945691/76570077-cb1d5280-6471-11ea-9a81-84d42a348e6f.png">

### On focus from search results

- Exhibit titles list is already populated from the search term (example has one fewer result now that the full term is present)

   <img width="400" alt="search 1 results focus" src="https://user-images.githubusercontent.com/6945691/76570073-c789cb80-6471-11ea-8eb2-63da0ef02ec7.png">

### Here's an animation

![search 1](https://user-images.githubusercontent.com/6945691/76571430-b2fb0280-6474-11ea-86ae-6f715495d742.gif)

**Comment by jkeck** [comment]
Is it "okay" that we've gone w/ Version 2 (#1843) as it's a bit easier to integrate w/ our current patterns.  If so, should this be closed or do we want to keep this in our backlog as a reference for potential redesign/future work?

**Comment by jkeck** [comment]
Closing this as we went with Version 2 described in #1843
