### ISSUE TITLE
Find exhibits by title, version 2

### ISSUE THREAD

**Issue by jvine** [sul-dlss/exhibits#1843]
Related to #1838 and #1842

This version uses existing patterns (mostly) to present separate search options.

### Add a button dropdown in front of the search box

- Same style as the Sort by button on search results
- NOT a select (as in Arclight) as it will actually change the search field and behaviour

   <img width="495" alt="search 2 start" src="https://user-images.githubusercontent.com/6945691/76571792-9d3a0d00-6475-11ea-943d-69a31f67b50c.png">

### Button dropdown has two options

- Default is exhibit title
- Alt is Find items in all exhibits

   <img width="400" alt="search 2 button open" src="https://user-images.githubusercontent.com/6945691/76571670-3f0d2a00-6475-11ea-8b76-217b8deb6f9c.png">

### Typeahead in exhibit title search

- as the user types in the exhibit input, up to 5 matching titles are listed
- matched text in the titles is non-bold; remainder (differentiating text) is bold
- down arrow highlights a title, enter selects it

   <img width="400" alt="search 2 typeahead" src="https://user-images.githubusercontent.com/6945691/76571667-3e749380-6475-11ea-915a-efb9d4ff6b4c.png">

### User selects Find items

- existing item search field appears with a standard search button
- user types, submits, gets results

   <img width="494" alt="search 2 item search" src="https://user-images.githubusercontent.com/6945691/76571666-3ddbfd00-6475-11ea-9108-609fdb6e53a3.png">

### Same feature on search results

- default on result page is "Find items", with search term in in the input

   <img width="400" alt="search 2 search results" src="https://user-images.githubusercontent.com/6945691/76571662-3d436680-6475-11ea-8309-3b259cf759f2.png">

### Title search from search results

- If user selects Find exhibits from the button dropdown, the search box switches modes

   <img width="400" alt="search 2 search results title search" src="https://user-images.githubusercontent.com/6945691/76571657-39afdf80-6475-11ea-9ed6-b8f48a575dac.png">

### Here's an animation

![search 2](https://user-images.githubusercontent.com/6945691/76571697-53512700-6475-11ea-879f-451e839a0886.gif)

**Comment by jkeck** [comment]
I believe this is completed now, we can open new issues w/ any follow on tasks if need be.
