### ISSUE TITLE
Opera DB: Searches for Composer & Librettist not working

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1853]
Exhibit: https://exhibits.stanford.edu/operadata

Try fielded search for Composer > Draghi. This is the result:

![Screen Shot 2020-03-25 at 2 11 37 PM](https://user-images.githubusercontent.com/3210225/77586026-b2199600-6ea2-11ea-9e0a-77423fcb5ab9.png)

Try fielded search for Librettist > Zeno. This is the result:

![Screen Shot 2020-03-25 at 2 13 47 PM](https://user-images.githubusercontent.com/3210225/77586154-ec833300-6ea2-11ea-9ea6-f4a280f6bdc4.png)

**Comment by caaster** [comment]
Hi @cbeer I see you closed this ticket. Can you comment on the disposition, please? Many thanks.

**Comment by cbeer** [comment]
Sorry, I replied to you in Slack. There was just a configuration mismatch in field names.

**Comment by caaster** [comment]
Aha, ok, thanks. Communicate deluge over here. Much appreciated.
