### ISSUE TITLE
Masthead image not displaying for https://exhibits.stanford.edu/bacon

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1860]
The masthead image is not displaying in this exhibit. This seems to be a repeat of a recent bug/problem.

https://exhibits.stanford.edu/bacon

**Comment by cbeer** [comment]
The selected image has no-download rights, so stacks can't deliver a banner-sized image.

**Comment by caaster** [comment]
Thank you, @cbeer
