### ISSUE TITLE
Opera DB - titleSort data not imported from github, rendering Title Sort unusable in exhibit

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1867]
Music Library staff overlooked mentioning `titleSort` data/requirements for the Opera DB exhibit during all previous requirements discussions with DLSS. That said, the issue is now surfacing. Spot checking of titles in the exhibit with definite articles reveals no data in the titleSort field, while the data appears to be present in github, for example:

<img width="674" alt="Screen Shot 2020-04-07 at 11 48 41 AM" src="https://user-images.githubusercontent.com/3210225/78937059-a31b1200-7a64-11ea-94f5-5e2e003d5ca7.png">

Is it possible to re-harvest the data from github to populate the `titleSort`field in the published Opera DB exhibit?

**Comment by cbeer** [comment]
We copied the data from the original solr documents into the exhibit. A reindex is in progress to make it functional.
