### ISSUE TITLE
Browse category tile shows 63 items, but 65 items are actually present

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1875]
Please see: https://exhibits.stanford.edu/bacon/browse/philippines-banana-workers.

I checked and none of the 65 items in the browse category are marked private. So I am confused about what is happening here.

**Comment by ggeisler** [comment]
Caching issue? I see 65 items on the tile:

<img width="385" alt="Screen Shot 2020-05-07 at 12 27 57 PM" src="https://user-images.githubusercontent.com/101482/81336468-3e040d80-905e-11ea-8ec2-737f4fa4a48f.png">

**Comment by caaster** [comment]
Yay! Thanks, @ggeisler
