### ISSUE TITLE
Map view doesn't display geolocated items for Browse categories

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1876]
I thought this was fixed in the Spotlight workcycle earlier this year, but it appears to be broken again.

See for example: https://exhibits.stanford.edu/lanciani/browse/roma-xi-1-colosseo-f7f5a2f1-9b7e-459e-b08a-431ad37cff96?view=heatmaps

**Comment by cbeer** [comment]
Fixed in spotlight 3.0.0.rc6.
