### ISSUE TITLE
Drop-down in main exhibits masthead has disappeared!

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1882]
I wonder if this happened with the prod deploy today? Now users no longer have a link to request an exhibit or learn more, and I no longer have access to admin function like creating exhibit stubs and ordering exhibits.

**Comment by ggeisler** [comment]
Links are actually there, but something is off with the styling, so the link color is not really visible. 

<img width="1042" alt="Screen Shot 2020-06-15 at 3 11 16 PM" src="https://user-images.githubusercontent.com/101482/84711143-7c70d000-af1a-11ea-9be1-b791a42dd85d.png">
