### ISSUE TITLE
Image manipulation tools in M2 exhibits are broken

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/exhibits#1886]
Reported by Ben in Slack and on [EXHBTF-1205](https://jirasul.stanford.edu/jira/browse/EXHBTF-1205). Looks like it's impacting `parker`, `mss`, and `burke_mss`. 

Example: https://parker.stanford.edu/parker/catalog/nm203xw8381UUID5b18443e-5a96-42e4-8750-84c707872f39

![Screenshot 2020-06-18 10 13 30](https://user-images.githubusercontent.com/73732/85052321-8d555780-b14d-11ea-9c18-d9e9095456d9.png)

**Comment by cbeer** [comment]
M2 depends on the insecure behavior of unpatched versions of jQuery and downgrading jQuery is not a good option. Instead,  we've added Mirador 3 with image tools and recommend these exhibits migrate viewer:

<img width="434" alt="Screen Shot 2020-07-24 at 07 59 42" src="https://user-images.githubusercontent.com/111218/88405097-a328ee80-cd83-11ea-8a09-8eac15edda03.png">
