### ISSUE TITLE
Ability to toggle to Spanish version of exhibit requires login: https://exhibits.stanford.edu/garcia-sampedro_rolls

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1896]
This is a blocker for this published exhibit

**Comment by camillevilla** [comment]
Hi @caaster! I looked into this and this is configuration issue. 
The curator needs to go into Configuration > General > Languages and publish the language. I've gone ahead and done this for this exhibit.


![Screen Shot 2020-07-27 at 3 00 27 PM](https://user-images.githubusercontent.com/5402927/88596621-56127a00-d01a-11ea-9c10-6313ff6bd7f0.png)

**Comment by camillevilla** [comment]
Also, can you confirm: Is the curator able to toggle that setting on their own or do they need admin help to do that? I see that the [Exhibits Documentation for multilingual exhibits](https://exhibits.stanford.edu/exhibits-documentation/about/multilingual-exhibits) doesn't feature that panel, so I wasn't sure if this was a permission issue or a service design choice.

**Comment by caaster** [comment]
My mistake for overlooking + user mistake. Thank you for checking!
