### ISSUE TITLE
[exhibits/stage] NoMethodError: undefined method `parameterize' for nil:NilClass

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#1901]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49092/faults/66185190)

**Comment by mejackreed** [comment]
If an exhibit custom field does not exist, we should create it on import

**Comment by corylown** [comment]
This hasn't happened in 4 years and only on stage. We can create a new issue if we see this problem again.
