### ISSUE TITLE
Error introduced by exhibit creator: both Paci and Garcia-Sampedro exhibits

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1906]
https://exhibits.stanford.edu/paci
https://exhibits.stanford.edu/garcia-sampedro_rolls

![Screen Shot 2020-08-04 at 7 50 41 AM](https://user-images.githubusercontent.com/3210225/89308847-98921300-d627-11ea-9776-60ea98d1efa1.png)

**Comment by cbeer** [comment]
Druids re-added.
