### ISSUE TITLE
Uploaded items aren't displayed in results > slideshow view

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1920]
In the Say Their Names exhibit all items are uploaded items. We noticed that in the [search results slideshow view](https://exhibits.stanford.edu/saytheirnames/catalog?utf8=✓&exhibit_id=saytheirnames&search_field=search&q=), none of the items images display, although they do in the list and gallery views:

<img width="960" alt="Screen Shot 2020-08-21 at 3 15 32 PM" src="https://user-images.githubusercontent.com/101482/90939683-3b38e880-e3c1-11ea-8c95-b268b1ae231e.png">

I checked Spotlight running locally, and uploaded items **do** display in the slideshow view. So it seems this might be an Exhibits-specific issue.

To double-check, I added three uploaded items to the existing SDR items in [my test exhibit](https://exhibits.stanford.edu/gary-testing/catalog?q=brady%27s&search_field=search&utf8=✓&view=list) (first three are uploaded, second three are SDR): 

<img width="960" alt="Screen Shot 2020-08-21 at 3 12 37 PM" src="https://user-images.githubusercontent.com/101482/90939876-be5a3e80-e3c1-11ea-9a5a-2d22cf8014d7.png">

---

While the three uploaded items do display in other result and show page views, their images do not display in the results slideshow view:

<img width="960" alt="Screen Shot 2020-08-21 at 3 12 52 PM" src="https://user-images.githubusercontent.com/101482/90939894-cd40f100-e3c1-11ea-9473-cb8e085bc1fa.png">

---

When I navigate to the fourth item, which is an SDR item, it does display, as do the other SDR items:

<img width="960" alt="Screen Shot 2020-08-21 at 3 23 23 PM" src="https://user-images.githubusercontent.com/101482/90940035-480a0c00-e3c2-11ea-9182-23928cd51f0b.png">

**Comment by caaster** [comment]
@geisler, I have noted this issue as described above also occurs with IIIF items uploaded to an exhibit. The details of why it isn't working (in exhibits) may or may not be the same as what you have described.
