### ISSUE TITLE
Issue with search result for https://exhibits.stanford.edu/rarebooks

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1933]
Nicole reported the following experience with https://exhibits.stanford.edu/rarebooks, which I have validated in the screenshot below.

Searching for this string as Title "Manuel de l'amateur de livres" in the exhibit produces a strange result with strikethrough on much of the text on the page: https://rarebooks.stanford.edu/rarebooks/catalog?utf8=%E2%9C%93&exhibit_id=rarebooks&search_field=search_title&q=Manuel+de+l%27amateur+de+livres

![Screen Shot 2020-09-24 at 12 22 47 PM](https://user-images.githubusercontent.com/3210225/94192768-3f46a300-fe64-11ea-86c4-2ff236afabdf.png)

**Comment by jkeck** [comment]
FWIW, this appears to be caused by some `<`, `>` characters in the full-text hit highlighting for record nr944mm8979.

`Livres du xix e siècle i <S < > i -1 8 9 3 Éditions originales.`

**Comment by caaster** [comment]
@jkeck I want to make sure I understand. You are saying that the OCR -provided coordinates for the full text contain some <, > characters, which is causing the error, correct? So the only way to stop this issue from occurring would be to remediate the full text and re-accession it in the SDR, I imagine.

**Comment by anarchivist** [comment]
We can probably provide better handling to escape the incoming data.

**Comment by caaster** [comment]
@anarchivist I want to get back to Nicole. Should I let her know we'll put this in the queue for the next Spotlight workcycle, or?

**Comment by jkeck** [comment]
I agree w/ @anarchivist that we should be handling this on the indexing or application side, and not remediate the data.

**Comment by anarchivist** [comment]
I'll put it in our maintenance backlog; we may be able to pick it up sooner.
