### ISSUE TITLE
Bug on Dashboard - Configuration - General for https://exhibits.stanford.edu/site

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1934]
This morning I created the stub for https://exhibits.stanford.edu/site.

I went to Configuration > General and added the tag "Government & Society."

Then, I conducted a training session for the exhibit creator, and this is what I saw (and still see) on the General tab.

This needs to be fixed so the creator can work on this part of their exhibit. If it can be fixed within the next week that would be most helpful. Thanks.

![Screen Shot 2020-09-25 at 12 02 28 PM](https://user-images.githubusercontent.com/3210225/94306749-5e0e6d80-ff28-11ea-967e-2917ca93d54f.png)

**Comment by jkeck** [comment]
Hi Cathy,
I believe this is because of the slug of this exhibit (`site`) conflicting with our site-wide administration paths (which are all under the `SiteController` and have a path of `site`).  

I think our best bet might be to recreate the exhibit under a different slug and delete this one.  I would be happy to handle the delete (as I believe that page will be inaccessible due to this issue).

**Comment by jkeck** [comment]
We can also look at ensuring that exhibits are not created w/ that slug, but that might need to be something that should happen upstream so could take a bit longer.

**Comment by caaster** [comment]
@jkeck I have asked the exhibit creator to select a new slug. I'll let you know here as soon as I have it. Thanks.

**Comment by caaster** [comment]
@jkeck -- the new slug decision is: 

site-archive

Please let me know when this is changed so that I can inform the exhibit creator.

**Comment by jkeck** [comment]
@caaster would it be too onerous to create a new site with that new slug?  I ask because I don't know if there might be potential elbow effects of changing the site's existing slug.  (e.g. documents that have been added to the exhibit likely won't transfer over automatically)

**Comment by caaster** [comment]
@jkeck Hmmmm. I did change a number of configs. I can ask the creator not to work on the site until we have a chance to fix this. She and I are having another training session on Monday, so I can create a new site with the new slug and copy over various configs before I delete it.

**Comment by caaster** [comment]
@jkeck, I am not able to delete this exhibit: https://exhibits.stanford.edu/site -- but it is ok to delete now, if you could please.

**Comment by jkeck** [comment]
I have deleted the old exhibit manually.

**Comment by caaster** [comment]
Thanks again @jkeck

**Comment by jkeck** [comment]
No problem at all!

Hopefully after the next release of spotlight this won't be possible anymore.
