### ISSUE TITLE
Change the search results per_page option values?

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1942]
Because virtually all of our Spotlight at Stanford exhibits include gallery view in the search result options, is there any reason why we shouldn't change the search results per_page options to numbers that are evenly divisible by 3 and 4, which are the number of items we display in a row when in gallery view (3 for normal search results and 4 for browse category results where we don't display the facet sidebar)?

Doing so would eliminate the empty spaces we (almost) always get in gallery view at the end of a results page:

<img width="896" alt="Screen Shot 2020-10-15 at 3 37 29 PM" src="https://user-images.githubusercontent.com/101482/96193213-90463600-0efc-11eb-9a5e-baac9c800fbc.png">

For example, if we configured things like this:

```
# Maximum number of results to show per page
max_per_page: 96,
# Options for the user for number of results to show per page
per_page: [12, 24, 48, 96],
```

In gallery view the rows would always fill out (except possibly on the last result page, depending on the total number of result items), which would look much better.

For the the list and mosaic views I don't think the per_page number affects how the displayed result items look. For slideshow view we currently show rows of 6 items, which also doesn't work to fill out rows completely with our currently per_page options but would with the options proposed above, since they are all multiples of 6.

The only downside I see is that the per_page menu options are a bit harder to scan when they don't end in zero:

<img width="395" alt="Screen Shot 2020-10-15 at 3 47 38 PM" src="https://user-images.githubusercontent.com/101482/96193984-3a728d80-0efe-11eb-89d9-b91229206673.png">

But I suspect users don't access this menu all that often, and the arguably minor additional effort in scanning the options might be a worthwhile tradeoff for the improved page layout, especially since our exhibits often use gallery view as the default layout?

**Comment by ggeisler** [comment]
Just a reminder that if we do decide this makes sense to do, we should also do it in DLME, which is where the question of _why are there empty blocks at the bottom of the search results_ came up.

**Comment by mwerla** [comment]
@jacobthill Not sure what you expect from QNL here. We asked to have the DLME results pages reconfigured to have the number of results divisible by 12, so that it can be presented with 6, 4, 3, 2, and 1 item in the row, depending on the user's device screen size (assuming responsive design).

**Comment by jacobthill** [comment]
@mwerla I think this design meets those requirements. I just wanted the QNL team to see the plans before development started. I don't think anything else is needed. I'm removing the `qnl design` tag.

**Comment by mejackreed** [comment]
@ggeisler Should we go ahead and automatically update all of the existing exhibits with a new default ?

```
10 -> 12
20 -> 24
50 -> 48
100 -> 96
```

**Comment by ggeisler** [comment]
@mejackreed Yes, if that's possible I think that's what we want to do.

**Comment by mejackreed** [comment]
Just a heads up. Cathy confirmed on Slack this was 👍 to 🚢

**Comment by mwerla** [comment]
I went to dev environment, searched for Qatar, and got search results. The number of items looks good, but there are no thumbnails visible.

https://dev.dlmenetwork.org/library/catalog?f%5Bagg_provider_en%5D%5B%5D=Harvard+University+Library&per_page=24&q=qatar&search_field=all_fields&view=gallery

![image](https://user-images.githubusercontent.com/562200/104995248-0a73e280-5a37-11eb-8b1e-4789f445c9cd.png)

**Comment by mwerla** [comment]
I am not sure, if you change anything, but now the thumbnails load.

**Comment by mejackreed** [comment]
Yes, thanks. An upstream dependency update was made while adding a seam for other DLME issues without a needed config change was made. We saw your comment this morning and made the update accordingly.
