### ISSUE TITLE
Items have disappeared from browse categories in the Fitch exhibit

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1946]
The issue of disappearing items from browse categories has happened before. I am trying to find the closed ticket. @cbeer I recall you worked on this at that time. Here is a Fitch browse category with -0- items:
https://exhibits.stanford.edu/fitch/browse/farmworker-union-field-organizing-special-actions-1969-1975

Here is the feedback report from Curator Ben Stone:

From: exhibits-feedback <exhibits-feedback-bounces@lists.stanford.edu> on behalf of Benjamin Lee Stone <bstone@stanford.edu>
Sent: Wednesday, October 21, 2020 10:22 PM
To: exhibits-feedback@lists.stanford.edu <exhibits-feedback@lists.stanford.edu>
Subject: [exhibits-feedback] Content missing from browse galleries in Fitch Spotlight exhibit
 
Dear Colleagues,

A quick note-I discovered this evening that several galleries in the Fitch Spotlight exhibit are showing either no content or
greatly diminished content, e.g.
https://exhibits.stanford.edu/fitch/browse/meredith-march-against-fear-june-1966
https://exhibits.stanford.edu/fitch/browse/farmworker-union-field-organizing-special-actions-1969-1975
https://exhibits.stanford.edu/fitch/browse/ron-dellums-for-congress-1970
https://exhibits.stanford.edu/fitch/browse/the-berrigans-the-catonsville-nine-1968-1972

I believe I last reindexed the site at the end of last week; not sure if I somehow deleted content in the process?

Thanks for any help you can provide.

All best,

Ben

**Comment by cbeer** [comment]
We shipped https://github.com/sul-dlss/exhibits/pull/1898 without shipping the corresponding solr changes (https://github.com/sul-dlss/sul-solr-configs/pull/228 or https://github.com/sul-dlss/sul-solr-configs/pull/229), so some searches for metadata in fields we didn't explicitly index returned no results.

A temporary fix is in place (making the new MODS catch-all field searchable), and a reindex will fix it the right way.
