### ISSUE TITLE
[exhibits/prod] ActionView::Template::Error: No route matches {:action=>"facet", :controller=>"spotlight/catalog", :exhibit_id=>"renaissance-exploration", :"facet.page"=>nil, :"facet.sort"=>"index", :id=>"geographic_facet", :locale=>nil}

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/exhibits#1952]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49092/faults/69401151)

**Comment by corylown** [comment]
This appears to have been fixed by https://github.com/projectblacklight/blacklight/pull/2381
Has not occurred in three years.
