### ISSUE TITLE
Problem importing items for Rumsey exhibit

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#197]
Salim asked me to import a long list of items for the Rumsey Center exhibit he is currently working on, because he wasn't able to import them. I first tried a chunk of 50 druids but they didn't import. I next tried just the first druid in his list, which I verified is a legitimate item via its PURL page, but that also doesn't seem to work. Not sure how to troubleshoot further.

Attached is the list of druids.

[rumsey-druids.txt](https://github.com/sul-dlss/exhibits/files/200964/rumsey-druids.txt)

**Comment by cbeer** [comment]
It looks like there's a lot of unpublished druids in that list, including:

vx569ks1410
cp230cz2480
fd963cz7503
sk452mp8895

I removed them and seems seem to be working fine now.

**Comment by ggeisler** [comment]
Great, thanks for the quick attention! Good to know the cause of the problem. I'll create another ticket to keep track of the need for better error reporting.
