### ISSUE TITLE
4 IIIF manifests not uploading to an exhibit

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1987]
I just spoke with Andrea Renner today. They are creating an exhibit that needs to be published by 22 March: https://exhibits.stanford.edu/islamicworld

There are 4 IIIF manifests they have tried to upload unsuccessfully to the exhibit, from 2 different institutions. I have validated this problem. I go to Add items > IIIF URL > enter manifest URL > click add IIIF items -- and the item doesn't upload. No message displays indicating what might be amiss.

Here is a link to a spreadsheet listing the 4 items: https://docs.google.com/spreadsheets/d/1dO6PzZDmJBIqdfxba1ipNGuWvD8iIvTWXZ7Poz_DHIk/edit?usp=sharing

Andrea stated they wish to display a single image/page. However, if that's not possible (as in the case of QDL possibly, for whole atlases), they would use the full volume for the "Browse categories" and upload the single page as a jpg for the "Curated pages."

Finally, I understand this may well be a host institution problem, of course -- and that it is not our mandate to resolve these problems, if so. But it would be most helpful if we can validate that it is not our issue, along with any other information available that might help pinpoint the issue, that I can convey back to Andrea. Thanks.

**Comment by blalbrit** [comment]
@camillevilla - this seems to be CORS-related
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.qdl.qa/en/iiif/81055/vdc_100000004987.0x000001/manifest. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

**Comment by mejackreed** [comment]
FWIW QDL blocks CORS for all requests except from a permit list.

**Comment by caaster** [comment]
When someone has time, can you all explain how CORS may/may not impact the problem Andrea has reported. Thank you.

**Comment by camillevilla** [comment]
@caaster QDL's default CORS settings restrict the ability of non-QDL websites to request IIIF resources. To use QDL resources in Andrea's exhibit will require getting in touch with QDL and asking them to add exhibits.stanford.edu to their permit list. We did something similar for DLME so that it could use IIIF resources provided by QDL.

I'm looking into the issues with the LOC manifests and will have more info on that soon.

**Comment by caaster** [comment]
@camillevilla passing along Andrea's thanks. Andrea is asking, do you, or @anarchivist or @mejackreed possibly have a name of someone at QDL that she can reach out to?

**Comment by caaster** [comment]
@jacobthill -- at Jack's suggestion, looping you in on this ticket. Do you have recommendations for who Andrea Renner (SUL staff) from the DRMC can contact at QDL? The ticket thread above explains. Please let me know if you have questions or if I can clarify anything. Thank you in advance.

**Comment by jacobthill** [comment]
@caaster Marcin will be the best contact at QNL.

**Comment by caaster** [comment]
I introduced Andrea to Marcin via email. Keeping this ticket open for the LC items.

**Comment by caaster** [comment]
Hi @camillevilla - checking in with you on this ticket. I wanted to let you know Marcin at QNL has gone silent, despite my attempts to follow up with him. He said QDL changed the CORS settings to enable Spotlight at Stanford's use of their resources, but their IIIF manifests still fail to upload (he is aware but hasn't responded further). I know Andrea is working with a faculty member here at Stanford on the exhibit for the virtual event, so if you have an update to provide that would be helpful. I also want to be really clear I don't expect for us to pour lots of resources into solving the issue for these 4 IIIF manifests. When you think it is time to give up if the issues can't be easily resolved (and happy to discuss if you feel uncertain), I'd like to give a heads up to Andrea. Thank you.

**Comment by camillevilla** [comment]
@caaster An update from this morning! I was able to pair program with @cbeer on a fix for this today. We should have this deployed tomorrow.

**Comment by camillevilla** [comment]
I reopened this issue because I haven't been able to investigate whether anything has changed re: QDL manifests.
