### ISSUE TITLE
Add fields to item view page in Parker on the Web

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#1988]
In the Parker on the Web configuration, the item view page (eg. https://parker.stanford.edu/parker/catalog/kz540zc7240) has a subset of MODS fields available, and a click-through for "More Details" for the full MODS record.
![Screen Shot 2021-02-10 at 4 28 16 PM](https://user-images.githubusercontent.com/796990/107590469-0877ec00-6bbd-11eb-8737-b50042051d98.png)

In the upcoming release for Parker (Parker 2.1), we have overhauled the MODS extensively and added more item-level information to the records. The team in Cambridge would like to add the following fields to item view page:
* "Provenance" - available in MODS as `<note` displayLabel="Provenance" type="provenance">Lorum ipsum</note>`)
* "Height and Width" - available in MODS as:
```
  <physicalDescription>
    <note displayLabel="Height (mm)" type="dimensions">146</note>
    <note displayLabel="Width (mm)" type="dimensions">102</note>
  </physicalDescription>
``` 
* If it is possible to concat Height and Width into a single string as "Measurements (mm)" in the format H x W, that would be very helpful.

The Corpus team has already been told that this update will probably not be completed before we go live with 2.1 and will, instead, be an incremental update whenever the access team has a chance to review, scope, and implement this change.

If you have any questions about this, please don't hesitate to let me know. cc. @mejackreed @caaster

**Comment by blalbrit** [comment]
<img width="887" alt="Screen Shot 2021-02-15 at 3 34 47 PM" src="https://user-images.githubusercontent.com/796990/108002330-24580500-6fa4-11eb-9e2c-cbd4c8168a7a.png">

"Measurements" should follow "Extent", "Provenance" should follow "Approximate Date"

**Comment by mejackreed** [comment]
@blalbrit with regard to dimensions here. We might need to do something like this so this functionality is extensible to other types of dimensions that may exist in mods.

Would something like this be acceptable?

![Screen Shot 2021-03-11 at 10 43 33 AM](https://user-images.githubusercontent.com/1656824/110830769-cc38b980-8256-11eb-9c00-dac0391ef85b.png)

A concatenation of the displayLabel and value with the ability for a curator to rename "Dimensions". This would also be able to be reordered per exhibit. We could change the order and/or downcase as needed.

**Comment by mejackreed** [comment]
Another example where this can get weird and we want to handle multiple values:

cf386wt1778

![Screen Shot 2021-03-11 at 11 33 18 AM](https://user-images.githubusercontent.com/1656824/110836757-a6fb7980-825d-11eb-993f-f9412196fefd.png)
