### ISSUE TITLE
Problem selecting display page (beyond page 12) in multi-image objects

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#199]
Salim reports that when working on a feature page in the Renaissance Exploration exhibit, it is not possible to select a page (beyond about page 12) when using a multi-image item in a widget, such as the item row widget. I see the same problem. It appears that the src of the page image is not added to the DOM for items past about 12 for any multi-image item.

Examples can be seen by editing this page:
https://exhibits.stanford.edu/renaissance-exploration/feature/highlights-from-the-collection

**Comment by jcoyne** [comment]
I do not have authorization to edit that page, so I can't see what you mean. Can someone grant them to me?

**Comment by ggeisler** [comment]
@jcoyne Done

**Comment by jcoyne** [comment]
I'm not sure I'm able to duplicate. Here I was able to select any item. ("9 of 71" was the default)
<img width="750" alt="screen shot 2016-07-08 at 12 53 24 pm" src="https://cloud.githubusercontent.com/assets/92044/16696554/1ba78ef8-450b-11e6-8ce3-2fffaf2e197f.png">

**Comment by ggeisler** [comment]
Yep, although I remember testing this pretty thoroughly at the time and recreating the problem, it does not seem to be a problem any longer. I verified with an exhibit on -stage, changing the selected page for two different items to many different pages. I'll close the issue.
