### ISSUE TITLE
Deprecate Mirador 2 viewer

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#1990]
Due to security issues with the current version of Mirador 2 running in Exhibits we will need to deprecate the ability for users to use this viewer in their exhibit.

Current exhibits (as of 2021-02-12) that use the viewer: ["parker", "time-travel-japan", "burke_mss", "secret-service", "ars-test", "epl", "medieval", "service-sandbox", "tress", "paleography", "test-lgbtqdhh"]

Likely steps that need to be taken:
 - Contacting exhibit curators
 - Disabling the ability to select Mirador 2 in curator viewer config. https://github.com/sul-dlss/exhibits/blob/master/app/views/viewers/edit.html.erb#L27
 - Migrate exhibits to using Mirador 3.

Mirador 3 is already an option that can be chosen, and curators have the ability to make this change on their own.

**Comment by caaster** [comment]
OK. This will not be trivial for Parker. I will start by checking with Ben next week. If I understand correctly, this would mean a loss of functionality for Parker.  I will change now without issues: "secret-service", "ars-test", "service-sandbox", "test-lgbtqdhh"

**Comment by mejackreed** [comment]
I _think_ that in the Mirador 3 viewer embedded for use in Parker we have taken into account already all of the needed features and functionality. 🤞

**Comment by caaster** [comment]
OK, this now leaves the following on Mirador 2:

Ben Albritton, exhibit owner: "parker", "burke_mss", "epl", "paleography"
Rowan Dorin, exhibit owner (Stanford faculty): "medieval"
Peter Blank, exhibit owner: "tress"
Regan Murphy-Kao, exhibit owner:  "time-travel-japan"

I'll start by contacting Ben on Tuesday.

Is there a timeframe for this, @mejackreed?

**Comment by mejackreed** [comment]
If possible in the next month

**Comment by blalbrit** [comment]
@caaster and @mejackreed - the switch to M3 in Parker prod is already on our 2.1 release roadmap. We're aiming for March 1 going live with the updates.

I have changed to M3 for the other indicated exhibits.

Thanks both for your work on this.

**Comment by caaster** [comment]
@mejackreed  "medieval" "tress" "time-travel-japan" have all been changed to M3
