### ISSUE TITLE
Add progress indicators to the Bulk updates > Upload CSV page

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#2001]
Part of #1995. Assumes #2000  is done.

As the uploaded CSV is processed, we'd ideally want to convey to the user that things are happening. As some of us discussed offline, the most obvious model for this might be a variation of the progress box we use for reindexing:

<img width="745" alt="upload-tab-progress" src="https://user-images.githubusercontent.com/101482/108786323-94c8ce00-7530-11eb-9df2-c50d88bdf2c7.png">

---

- [x] Box heading: `CSV processing status`
- [x] Start notification: date, time, `Begin CSV processing`
- [x] Progress bar

When the CSV is fulling processed, presumably we need to reindex to capture the updates so perhaps we update the progress box to something like this after processing is completed:

<img width="745" alt="upload-tab-completed" src="https://user-images.githubusercontent.com/101482/108786365-b033d900-7530-11eb-9db3-286a083b55a5.png">

---

Where we remove the progress bar and add:

- [x] Completed notification: date, time, `Completed CSV processing`
- [ ] Flash message: `Exhibit items will be reindexed. See the exhibit dashboard for reindexing status.` where "exhibit dashboard" is linked to `/dashboard` where we have the "Recent item indexing activity" table.

### Error reporting
I assume there are a bunch of things that could go wrong when processing the CSV file and we should convey to the user as much as we can about what went wrong. I don't know enough about the potential errors and the info we would have to convey, though, so I won't try to design anything around that here. But I'm happy to work with whoever is working on this ticket to add text, etc. as needed to deal with the non-ideal scenarios.

**Comment by cbeer** [comment]
Fixed by https://github.com/projectblacklight/spotlight/pull/2725. There is not a separate indexing step, so I did not implement the additional flash-message-inside-the-progress-box feature.

https://github.com/projectblacklight/spotlight/pull/2681 will give us some information about errors and other state and we can add more information to the box in a separate ticket.
