### ISSUE TITLE
Revamp how we populate Author/Creator and Contributor fields/facets

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#2003]
Related previous discussion in #936, #545, #546, and #547.

Potentially relevant example objects:
- https://exhibits.stanford.edu/cathy-test-exhibit/catalog/yr455dn2133 
- https://exhibits.stanford.edu/sftjf/catalog/dq777fd7798 
- https://purl.stanford.edu/rs380fd6758

As discussed in a storytime, I think the main work here is revamping the technical strategy of how names get assigned to one field/facet or another. Below is what I think we're aiming for, at least speaking from the UI perspective:

## Assigning names to fields

- Names gets assigned to one of two fields/facets:

- **Creator** (as a default label, modifiable by the exhibit curator; is currently "Author") - this includes the MARC 100 field, MODS fields with `<name usage="primary">`, and the current fallback pattern for making sure there is a name in the Creator field. This might not be stated correctly but I think the developers know what we agreed on.

- **Contributor** (as a default label, modifiable by the exhibit curator; is currently "Author (no collectors)" - includes all other names that weren't assigned to Creator above.

- Roles we currently break out into separate fields should go into Contributor rather being represented as distinct fields, I suggest. We didn't discuss this too much so let me know if there is a reason this might not make sense, but for example, we currently have a distinct field for both Collector and Editor. If those are derived from Name `<role>`s, maybe they should be part of Contributor, in the interests of keeping names limited to two fields. But I don't remember why we initially broke Collector out into its own field, so not sure if there might be a good reason for maintaining that. @caaster maybe you have thoughts?

- Note: @mejackreed suggested we keep the current Author field in place in case of concerns from existing exhibit curators and this being a breaking type of change. It seems reasonable to me to maintain the Author field at least until we  do the work to create the new Creator and Contributor fields, and then we could compare the changes and see how big the delta is between the old Author and the new Creator field. And based on that decide if we should keep all three or just the new ones. And if we do end up keeping all three, ideally we'd make the display of the older Author field off by default. That way it is there if a curator feels it really makes sense for their exhibit, but it wouldn't display if an exhibit curator was just lazy about evaluating their fields/facets and it really isn't useful or is redundant with the new Creator field.

## Displaying name fields
At least as a first pass, I think we can display the Creator and Contributor field values in the same way for both search results and item details pages.

- **Creator**: list of names same as we currently do, except if it's possible I'd suggest using a semicolon to separate names in the list. We currently use a comma to separate names but we also use a comma to separate the first and last portions of a single name, and visually that's a bit ambiguous, or at least hard to quickly scan.
- If possible omit the semicolon or comma separating the last (or when there are only) two names and rely on the word "and" to separate them (we might already do this).

- **Contributor**: list of names with the person's role in parenthesis after the name
- Same formatting as above except because we show the role after each name, the comma to separate names is okay

### Example: Fixture Object #1
https://purl.stanford.edu/rs380fd6758

<img width="597" alt="Screen Shot 2021-02-24 at 3 58 00 PM" src="https://user-images.githubusercontent.com/101482/109079408-257fe500-76bc-11eb-976a-19955e8f46d9.png">

---

The example above assumes Leticia Martin is not assigned as an Creator using any of the rules we discussed, even though she does have a role of author.

### Example: Sonate IV
https://purl.stanford.edu/yr455dn2133

<img width="597" alt="Screen Shot 2021-02-24 at 3 56 49 PM" src="https://user-images.githubusercontent.com/101482/109079504-40eaf000-76bc-11eb-8548-5906b9f1af31.png">

## Future work
I might want to look at splitting up names into new lines on the item details page, similar to Searchworks but maybe that should wait until we revamp things and see how pages look with the new approach. It seems likely that a formatting update would be pretty simple to do later.

**Comment by caaster** [comment]
See also: https://github.com/sul-dlss/exhibits/issues/936

**Comment by corylown** [comment]
Closed by:
- https://github.com/sul-dlss/exhibits/issues/2506
- https://github.com/sul-dlss/exhibits/issues/2526
- https://github.com/sul-dlss/exhibits/issues/2527
