### ISSUE TITLE
Update invitation email

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#201]
Update the text of the invitation email people receive when they are added as a user to an exhibit so that: 

- User's email address is not linked (or just say "Hi" without including their email address)
- Exhibit URL is not linked, or not included
- The "Accept invitation" link is more likely to be clicked on

A more involved option would be to accomplish the above with HTML-formatted email.

**Comment by cbeer** [comment]
I think we still need to address this in our own overrides:

https://github.com/sul-dlss/exhibits/blob/master/config/locales/spotlight.en.yml#L5
