### ISSUE TITLE
Exhibit masthead title text changes size when in Browse context

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#2039]
This is a subtle problem but when you are in a browse context (`.blacklight-browse` I believe) the exhibit site title font size changes slightly but noticeably:

https://user-images.githubusercontent.com/101482/110870798-682fe880-828a-11eb-9701-3ab99d9957f3.mov

I think we have an unnecessary CSS selector (`.blacklight-browse h1`) in `app/assets/stylesheets/modules/spotlight_overrides.scss` that is causing this. I think we (probably me, not sure) added that selector to fine-tune the font size of the H1 heading of the browse category show page. But it also affects the H1 in the exhibit masthead (because that falls within the `.blacklight-browse h1` context), which is causing the problem.

I suspect all that needs to be done is to remove the CSS selector `.blacklight-browse h1` in `app/assets/stylesheets/modules/spotlight_overrides.scss`, which won't affect the font size of the H1 heading of the browse category show page enough to worry about. But for reasons not worth explaining I can't currently test this locally so want someone else to verify this is all that needs to be done to fix it.

This is an Exhibits-specific CSS selector so the problem doesn't appear in Spotlight.

**Comment by camillevilla** [comment]
@ggeisler Does this look like the intended font size? Removing that `.blacklight-browse h1` selector bumps the browse category show page title to `40px`.

![Screen Shot 2021-03-22 at 4 26 23 PM](https://user-images.githubusercontent.com/5402927/112070815-b6b37180-8b2b-11eb-8f98-92fa4bb2316f.png)

I think the `.blacklight-browse h1` selector keeps the title at 32px, which seems to be consistent with the About page and feature page titles.

If the desired behavior is that the masthead title is 34px(?) on all pages, I can add some additional selectors so that overrides the `.blacklight-browse h1`.

**Comment by ggeisler** [comment]
@camillevilla Hmm, I think Option A makes the page title too big. It feels weird to me for the page title to be so noticeably larger than the exhibit title itself, except when you are on more mobile viewports (I'm not sure that is a very logical position to take, but if we start to try to responsively size the page title like we do the masthead title it'll probably be more involved because we should do it for all pages to be consistent, like feature pages, about pages, and the item show page).

Maybe the fix requires Option B, but keeping it fairly simple (I'll specify in `px` below but I think we use `rem`s in the SCSS?):

- [ ] Make sure we keep the current responsive sizing for the masthead H1 on all pages. I think this is:

Viewport `lg` and wider: `34px` 
Viewport `md`: `28px` 
Viewport `xs` and `sm` : `26px` 

- [ ] For the Browse show page H1, use `32px` at all viewports

So maybe this just means targeting the browse show page H1 to make it 32px, and doing that in a way that doesn't affect the masthead H1 on the browse (or any other) pages.
