### ISSUE TITLE
Always show Feedback link

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#204]
SUL exhibits should always show the Feedback link. Details need to be more fully fleshed out but generally the goals are:

- Update the feedback submission form so that `exhibits-feedback@lists.stanford.edu` is always a recipent
- If an exhibit curator adds one or more contact email addresses in Configuration > General > Basic settings, add those as recipients
- Update the Contact emails help text to make clear that feedback goes to the exhibits-feedback mailing list in addition to any contacts added there

**Comment by cbeer** [comment]
Set the `Spotlight::Engine.config.default_contact_email` setting appropriately:

https://github.com/projectblacklight/spotlight/blob/master/lib/spotlight/engine.rb#L157-L158
