### ISSUE TITLE
Feature Request: Enable Layers View in M3 in Exhibits

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#2044]
This is a request to enable the layers tab in Mirador 3 within Exhibits. I have several projects coming up that would benefit greatly from this feature (including a large Diego Rivera scientific imaging project which currently has two layers and potentially up to four).

I understand that there are UX / design issues that will crop up around this, but wanted to flag it as a desirable feature. I have some manuscript imaging projects that could benefit from this, and I think we may also have some map projects that could also benefit from this feature.

**Comment by ggeisler** [comment]
@blalbrit I'm not sure if there is something I'm not thinking of, but off-hand I don't think there are any special UX or design concerns related to displaying layers in the Mirador 3 viewer. An object with layers will just have an additional sidebar menu option, and working with the layers takes place within the viewer, just as with other sidebar options, so I can't think of any special UX concerns displaying layers would introduce. (And I'd love to see more objects that take advantage of the layers feature!)

I'm speaking strictly about UX here, of course. I'll leave it to the developers to speak to whether there are any technical concerns related to displaying layers for Exhibit objects.

**Comment by mejackreed** [comment]
Ah you are right @ggeisler . I was thinking there might be an issue where this would always be present, but i guess we fixed that in Mirador.

**Comment by ggeisler** [comment]
Well, I assumed that was the case, but you would know better than me, so correct me if I'm misremembering!

**Comment by mejackreed** [comment]
Nope... I just double checked it, you were right!
