### ISSUE TITLE
Bug: image won't save for feature page tiles

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2045]
Staff are working on the following exhibit: https://exhibits.stanford.edu/conservation

The problem they are having, described below, is happening for multiple feature pages. Here are two similar examples:

1. They are trying to upload, crop and save a feature page tile with no success:
https://exhibits.stanford.edu/conservation/feature/stanford-tree-collection

And they want the feature page tile to display on this page when they use the pages widget:
https://exhibits.stanford.edu/conservation/feature/collection-storage-and-enclosures

And here is the image:
![After - off the floor and wrapped up](https://user-images.githubusercontent.com/3210225/111519165-0c46e300-8714-11eb-9560-86ac7fcb9ca8.jpg)

2. They are trying to upload, crop, and save a **new image** for this feature page tile with no success:
https://exhibits.stanford.edu/conservation/feature/conservation-treatment-97f22302-0693-4014-b71f-c4927cd2f27d

And they want the feature page tile to display on the home page when they use the pages widget:
https://exhibits.stanford.edu/conservation

And here is the new image they are trying to upload:
![sewingCapture](https://user-images.githubusercontent.com/3210225/111519818-b6266f80-8714-11eb-9776-7472dcd80404.JPG)

**Comment by mejackreed** [comment]
Related to https://app.honeybadger.io/projects/49092/faults/78432965 ??

**Comment by caaster** [comment]
Just checking - if it is correct that #2046 is in prod, fyi the problem is still present.

**Comment by cbeer** [comment]
🤞 fixed by https://github.com/projectblacklight/spotlight/pull/2731

**Comment by camillevilla** [comment]
@caaster We confirmed this issue is fixed in other exhibits, but we needed to do some manual remediation on this specific feature page. It should be ready for a new feature page thumbnail now.
