### ISSUE TITLE
New problems with rendered quality of uploaded images in exhibits

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2047]
From: Rueiyun Wang <rueiw@stanford.edu>
Sent: Thursday, March 18, 2021 12:57 PM
To: Catherine A. Aster <caster@stanford.edu>
Cc: Andrea Renner <arenner@stanford.edu>
Subject: Image quality in Spotlight question
 
Hi Cathy, 

We've noticed that some images appear to upload slightly blurrier than in previous exhibits.

For example, the quality of the last image in this page from our DataViz spotlight (Carte agronomique des environs de Paris) is good.

However, to test, when uploading the same image to a page in the spotlight we're currently working on, it appears slightly blurrier (images at bottom of page): 
https://exhibits.stanford.edu/islamicworld/feature/mapping-culture

I uploaded both the image used when making the DataViz spotlight, and a file of the same image I downloaded today from davidrumsey.com to test.

It seems to only affect whole, unedited uploaded images (we're also including detail crops of some images in the exhibit and these show up clear). 

In case it helps, all images mentioned in my example (multiple versions of Carte agronomique de Paris) are 72ppi when checked in Photoshop.

Please let me know if I can provide more information, and thank you for your help.

All best,
Rueiyun

Rueiyun Wang
Center Services Support Specialist 
David Rumsey Map Center, Stanford University
rueiw@stanford.edu

**Comment by mejackreed** [comment]
We now post-process all images that are uploaded by users in Exhibits to a maximum width and height of 1080px while maintaining the aspect ratio. This is done to reduce the page load time as several exhibits had very large images uploaded to them. Causing multi-second to > 10sec page loads. While I recognize this might not be desirable by all it is definitely a tradeoff.

The original image could be optimized in advance to be displayed best at 1080px max dimension. This would eliminate some of the potential post-processing effects for users who this type of processing may affect.

**Comment by caaster** [comment]
@mejackreed -- can you tell me more about: "The original image could be optimized in advance to be displayed best at 1080px max dimension." What would this mean exactly? Looking to provide specific guidance to Rueiyun and other colleagues. Thank you.

**Comment by mejackreed** [comment]
Let me and @ggeisler chat about it and see if we can provide a better solution.

**Comment by anarchivist** [comment]
I will also note the following: 

* The version of the image on the Islamic World exhibit is the 1080 pixel-wide version and 216179 bytes
* The version on the DataViz exhibit predates this, and is 4104 pixels wide, and is 3,770,568 bytes (17 times the file size of the version on the Islamic World exhibit)

**Comment by caaster** [comment]
Closing this ticket as no further complaints have been received.
