### ISSUE TITLE
Support SDR item inclusion in multiple exhibits

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#205]
Currently, depending on whether an SDR item is added via a collection druid or a single object druid, it can only appear in one exhibit at a time. We know we have use cases for a given druid being included in multiple active exhibits.

**Comment by jcoyne** [comment]
When we pull collections from dor, we don't know which exhibits the item (in spotlight) is associated with.

**Comment by jcoyne** [comment]
@cbeer Can you provide more detail about this. How is this bug presenting itself?

**Comment by jcoyne** [comment]
I see, I get the dreaded "Something went wrong" when I attempt to add the second DRUID

**Comment by cbeer** [comment]
I'm trying (unsuccessfully) to dredge up the old email from late last year.. essentially, if you index a collection in two different exhibits, our indexing logic will correctly handle the collection records (recording exhibit and custom field information for both exhibits), but the contained items will only receive a single exhibit reference.

**Comment by jcoyne** [comment]
Here's a relevant stack trace:
https://gist.github.com/jcoyne/010835b18e9bbc36c5a34bf5582b5862

**Comment by cbeer** [comment]
Unrelated; that looks like Blacklight 6 upgrade fallout.

**Comment by jcoyne** [comment]
But the deployed code is on Blacklight 5.18.0

**Comment by cbeer** [comment]
Where are you looking (I'm seeing 6.3 on exhibits-stage:exhibits/current)

**Comment by jcoyne** [comment]
Yeah, looks like it got deployed earlier in the day. I didn't notice.

**Comment by jcoyne** [comment]
Okay, moved this other issue to https://github.com/sul-dlss/spotlight-dor-resources/issues/70

**Comment by jcoyne** [comment]
It seems like the last exhibit to index the item takes it. It is no longer visible in the search results for the other exhibit.

**Comment by jcoyne** [comment]
It appears that it is indexing this field to discriminate which exhibit to show it in.
```
        "spotlight_exhibit_slug_foo_bsi":[true],
```

**Comment by ggeisler** [comment]
Yes, that's the behavior we see in production, last exhibit to index is the one that gets to display it.

**Comment by jcoyne** [comment]
We think that when an item is indexed, it should union the sidecars of all exhibits it is a member of.

For example, if item 123 belongs to exhibit foo and exhibit bar, then when a field is added on the item 123 in exhibit foo, and then a field is added on the item 123 in exhibit bar, it should have both the fields from foo and bar in the document:

```
        "exhibit_bar_public_bsi":[true],
        "exhibit_foo_public_bsi":[true],
        "exhibit_bar_favorite-color_tesim":["Sky blue"],
        "exhibit_foo_favorite-ice-cream_tesim":["chocolate"],
```

**Comment by jcoyne** [comment]
In spotlight, the Resource class has the `reindex` method, but a resource is linked to a single exhibit.  We need to make a `DocumentIndexer` class that  creates a solr document for all the resources that share a single id across all exhibits it may be a member of.

**Comment by jcoyne** [comment]
We're going to need to rethink this.  We have no way of knowing if object 123 is in any other collections, because it doesn't necessarily have a resource in spotlight (it may be that it's collection is the resource).

**Comment by jcoyne** [comment]
It seems like the `spotlight_exhibit_slug_foo_bsi` field is the one that comes up missing.

**Comment by jcoyne** [comment]
The problem is that `CatalogController#update` triggers `SolrDocument#reindex` (via `SolrDocument#save`).  This calls SolrDocument#to_solr instead of Resource#to_solr, so none of the `#exhibit_specific_solr_data` is indexed.

**Comment by mjgiarlo** [comment]
See https://github.com/projectblacklight/spotlight/pull/1509 for a demonstration of the bug in Spotlight.

**Comment by mjgiarlo** [comment]
:speech_balloon: @jcoyne (on https://github.com/projectblacklight/spotlight/pull/1509)
> This behavior is triggered by CatalogController#update here:
> 
> https://github.com/projectblacklight/spotlight/blob/c0b782dda044faa6a724db18934f1063b3209cb7/app/controllers/spotlight/catalog_controller.rb#L78

**Comment by mjgiarlo** [comment]
From Slack:

There seem to be a few different pieces of work rolled up in this issue. Let me know if I'm close.
1. If a collection druid is imported, Spotlight should create one resource per druid from that collection.
2. Spotlight should have a DocumentIndexer class `that creates a solr document for all the resources that share a single id across all exhibits it may be a member of`.
3. Spotlight should use the DocumentIndexer class in the places where it currently calls `@document.save` (Not sure I got this one quite right.)

We should pair on this this week.

**Comment by mjgiarlo** [comment]
:clap:
