### ISSUE TITLE
Masonry view has lost its mosaic-arrangement visual qualities

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2052]
Please see some examples:

- https://exhibits.stanford.edu/maps/browse/united-states?view=masonry
- https://exhibits.stanford.edu/herbert-matter/browse/all-exhibit-items?page=8&view=masonry
- https://exhibits.stanford.edu/fitch/browse/martin-luther-king-jr-1965-1966?view=masonry

**Comment by camillevilla** [comment]
FYI there has been progress on this but it required some upstream work in projectblacklight/blacklight-gallery#99

**Comment by mejackreed** [comment]
@cbeer @camillevilla are we good to close this now?

**Comment by cbeer** [comment]
Looks mosaic-y to me 🤷‍♂️
