### ISSUE TITLE
Parker on the Web: Everything search not picking up some bibliography data

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#2054]
Per user:

The search box allows me to search keywords in bibliographic item titles but I can't search by the item's author - should that be possible and if not can we make it possible?

This refers to data pulled into Parker from Zotero - sample record here: https://parker.stanford.edu/parker/catalog/94257JYP

Search on keywords "scribal edition" returns a hit: https://parker.stanford.edu/parker/catalog?exhibit_id=parker&search_field=search&q=%22scribal+edition%22

Search on anything in the remaining fields is nil, for example: "Wood, Sarah" returns nothing - https://parker.stanford.edu/parker/catalog?exhibit_id=parker&search_field=search&q=%22Wood%2C+Sarah%22

Is it possible to index all content from the bibliography?

**Comment by corylown** [comment]
@dnoneill the PR you link to https://github.com/sul-dlss/exhibits/pull/2551 addresses author search and https://github.com/sul-dlss/exhibits/pull/2552 will address searching of `*_ssim` fields. Do we need to also consider `pub_display` and `*_ssi` fields?

**Comment by dnoneill** [comment]
That is a good point. Probably?

**Comment by corylown** [comment]
pub_display still not searched. _ssi fields should be assessed for suitability for search.

**Comment by hudajkhan** [comment]
A few comments:
- pub_display and pub_search are related, but may not be identical. pub_search is automatically added to all_search (which means a keyword search should return results), and pub_search is added to pub_display. (But pub_display is NOT added to pub_search).
- pub_display is populated based on bibtex_config.rb (extract_bibtex_field(:journal) and extract_bibtex_field(:publisher))
- pub_search is populated based on dor_config.rb (stanford_mods(:place))
- pub_search is also the field used for advanced search publisher text box (based on where it is mentioned in solrconfig.xml)

**Comment by hudajkhan** [comment]
- ref_type_ssm (reference type) is populated based on bibtex_config (seems to be extracting zotero mapping)
- _ssm fields are stored multi-valued string fields but not indexed, which explains why they are not showing up in search.

**Comment by hudajkhan** [comment]
The quickest mechanism to add both of these to search is to copy both ref_type_ssm and pub_display to all_search.  For pub_display, we can discuss if duplicates might show up in all_search (if pub_display ALSO has things that are already in pub_search) and if that is an issue. 

Tasks to complete:

- Code schema update
- Solr config schema update for staging
- Testing by stakeholder/devs to ensure it does what we want it to do
- Solr config schema update for production

**Comment by hudajkhan** [comment]
Current fields in use that end in _ssm:

- content_metadata_first_image_file_name_ssm
- content_metadata_first_image_height_ssm
- content_metadata_first_image_width_ssm
- content_metadata_iiif_manifest_ssm
- content_metadata_image_iiif_info_ssm
- content_metadata_type_ssm
- edition_ssm
- full_image_url_ssm
- large_image_url_ssm
- pages_ssm
- ref_type_ssm
- spotlight_full_image_height_ssm
- spotlight_full_image_width_ssm
- thesis_type_ssm
- thumbnail_square_url_ssm
- thumbnail_url_ssm
- volume_ssm

**Comment by hudajkhan** [comment]
Based on comments by @dnoneill , updating the approach.  This would still benefit from a schema change, but we will be:
a) having the same values indexed in both pub_display and pub_search. In other words, these fields will be equivalent.  Any value in pub_display will be searchable, and also now available through advanced publication search.
b) have the ref_type_ssm added to all_search directly

**Comment by hudajkhan** [comment]
Closed by #2597
