### ISSUE TITLE
Large items (from SDR?) overflow /tmp, causes app server to become unresponsive

### ISSUE THREAD

**Issue by julianmorley** [sul-dlss/exhibits#206]
A user-initiated request, presumably for large items from SDR (based on convo with @cbeer), causes mini_magick / mogrify to write large files to /tmp. When these files exceed the space available in /tmp, the web server becomes unresponsive which impacts service availability.

Over the weekend I saw multiple attempts by mini_magick to process 13GB files, taking down exhibits app servers. At one point both app servers were down, taking exhibits.stanford.edu offline.

Short term fix is to provision excessively large /tmp space, but there's a wider performance/scalability/accessibility issue of end users manipulating files of this size. 

Obviously, a legitimate end-user action should not crash the app server, and should scale beyond one or two concurrent users performing the same action.

**Comment by julianmorley** [comment]
Could be fixed with:
https://github.com/projectblacklight/spotlight/issues/1184

**Comment by cbeer** [comment]
Moved background tasks to a dedicated worker box, so at least the web app servers don't fall over.

**Comment by julianmorley** [comment]
Seems to have been fixed with an upgrade to Passenger from 5.0.29 to 5.0.30.
