### ISSUE TITLE
Reindexing in Exhibits is failing

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2069]
This afternoon I tried to kick off a reindexing job at 4:01 pm for: https://exhibits.stanford.edu/site-archive. At 4:17 pm, this is the status displaying:

![Screen Shot 2021-04-08 at 4 17 57 PM](https://user-images.githubusercontent.com/3210225/114107544-12009600-9886-11eb-9f97-f48e87666cca.png)

And this is the recent item indexing activity displaying:

![Screen Shot 2021-04-08 at 4 19 08 PM](https://user-images.githubusercontent.com/3210225/114107620-33fa1880-9886-11eb-84cc-e6750523fc3d.png)

While I was waiting, I went to a test exhibit to initiate a reindex: https://exhibits.stanford.edu/cathy-test-exhibit

This is the result:

![Screen Shot 2021-04-08 at 4 20 51 PM](https://user-images.githubusercontent.com/3210225/114107729-686dd480-9886-11eb-9850-bcd84826139c.png)

**Comment by cbeer** [comment]
It looks like the indexing is running, it's just the status is not being reported out the worker box. https://github.com/sul-dlss/shared_configs/pull/1646 should fix it.
 
In cathy-test-exhibit, it looks like there's a a IIIF item that may be invalid (https://api.cultural.jp/iiif/metmuseum-54052/manifest). Camille is looking into this, but it might be related to #1987 .

**Comment by caaster** [comment]
https://exhibits.stanford.edu/site-archive completed reindexing successfully - thank you
