### ISSUE TITLE
Need list of exhibit slugs or way for service manager to generate a current list

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2076]
I need a list of all exhibit slugs, so I can check it each time someone requests a new exhibit. If they are requesting a slug which will cause an analytics problem/conflict, I will recommend a different slug(s) for them to choose from instead. Is there a way I can generate the slug list myself, as this will of course change each time a new exhibit is created?

This is not urgent, but would be good to have in the next month or so if possible.

Related to #2065

**Comment by cbeer** [comment]
As a temporary stop-gap, I wonder if the [exhibits autocomplete API](https://exhibits.stanford.edu/exhibit_finder?q=*) provides enough information to make that determination.

It's not a list of slugs, but you should be able search the page (using cmd-F or whatever) for e.g. `"slug":"maps` and see which exhibit slugs start with `maps`.

**Comment by caaster** [comment]
This is great, but to be perfectly honest, if I could also have a one-time dump of all slugs at this moment in time that would be wonderful. I will then keep my own running list of all slugs by adding to the list every time I create a new stub. This will be simplest for me and how my brain works, so I appreciate it! Thank you.

**Comment by anarchivist** [comment]
Hi @caaster - can you try copying everything except the header row in [this spreadsheet](https://docs.google.com/spreadsheets/d/1yeMSYBVUBT4_5XxKOHN8sWHbmUJK0YnnJPrR2XIhQV4/edit#gid=0)?

**Comment by caaster** [comment]
This is almost perfect. Is there any way I can get a list of all slugs, whether the exhibits are published or not?

**Comment by cbeer** [comment]
```
1947-partition
Kahn
SAGR
Welte-Mignon
aaas
activism
africanamericansv
aguilar
ai
american-enlightenment
ams-city-plans
animals-of-sdr
arcadia
athletics
atomic-energy
automobility
awards
bacon
baltic-video
baltic-way
beautifulbooks
becoming-stanford
black-at-stanford
blrcc
blrcc2
blrcc3
bologna
bucky
bulk-actions-test-1
bulk-actions-test-2
bulk-actions-test-3
bulk-actions-test-4
bulk-update-test
burke_mss
california-as-an-island
calja
camille-s-test-exhibit
cartosym
cathy-s-bulk-updates-test
cathy-test-exhibit
chinese-ngos
cities-on-the-edge-north-africa
cms
community
conflict-sasia
conservation
coordinates-test
copyrightrenewals
creees
crrw
cs
dark-materials
data
dataviz
david-rumsey-map-collection
decamp
digital-bookplates
dms-discovery
drmc-sandbox
epl
exhibits-documentation
feigenbaum
fitch
foreign-bondholders
frenchrevolution
fur
garcia-sampedro_rolls
gardiner-sfba
gary-testing
gatt
gitai
global-imaginary
gordon-maps
hanna-house-collection
harrison
heckrotte
henro
herbert-matter
hume
hydrosurvey
iiif-demo-1
iiif-spotlight
islamicworld
jack-test
james-e-allen
jarndyce-test
john_w_gardner
josh-test
kepes
kzsu
lanciani
latinoax-at-stanford
lelandjr-legacy
leonardo
lianhuanhua
map-sandbox
maps
maps-of-africa
maps101
md
md-only
medhistory
medicineinnovation
medieval
menuez
mining
mjf
mmtest
mss
muybridge
my-favorite-cats
nash
news-service
nhdmaps
numismatics
operadata
operatest
oral-history
oss-maps
paci
panofsky-papers
papyrus
parker
parker-test
preventing-genocide
project-south
queer
radarfilm
rare-music
rarebooks
rbks-text
renaissance-exploration
riseup
rivera
rothman
rr
rstein
ruderman
saintjohn
sanborn-maps
saytheirnames
seaside
secret-service
service-sandbox
servicelearning
sftjf
sgctraining
sgs-collection
shahrokhmeskoob
shpc
silicongenesis
site-archive
spe
stanford-atlas
stanford-band
stanford-moments-of-crisis
stanford-pubs
stanford-quad
stanford-senate
stanford-stories
stanford-trustees
stanfordhumanrights
stanfords
station
su-photos
sunset
super-e
supra
syllabi
tel-aviv
test-lgbtqdhh
time-travel-japan
tohp
tokyomaps
tress
ua-maps-drawings
views-portraying-place-space
virtual-tribunals
vt-test
wangjingwei
warhol
watkins
women
women-art-revolution
wong-test
younge
```
