### ISSUE TITLE
Browse thumbnail (uploaded) image returns 404

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#2081]
https://exhibits.stanford.edu/site-archive/browse/group/2000s

The "Site 2007" tile image doesn't load. This is an uploaded image. Both the exhibit curator and I have tried with the same result. The [Edit browse category page](https://exhibits.stanford.edu/site-archive/searches/site-2007-f8aa1eda-802e-477b-a7fc-94d0da279e87/edit) shows the uploaded image in the cropping box after it was saved, but the image doesn't load:

<img width="1294" alt="Screen Shot 2021-04-30 at 9 33 12 AM" src="https://user-images.githubusercontent.com/101482/116726188-cd08e480-a997-11eb-91d0-19bea174f48e.png">

---

This is the source image:

![Lagunita](https://user-images.githubusercontent.com/101482/116726246-deea8780-a997-11eb-94fe-10ac8ee38f71.png)

**Comment by cbeer** [comment]
Maybe I'm lucky. I got it to upload just fine 🤷
