### ISSUE TITLE
Browse category thumbnail updates are not reflected on rendered browse landing page

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#2083]
This might be related to #2081 but I'll create this separate ticket in case they have separate causes.

The curator of [this exhibit](https://exhibits.stanford.edu/site-archive/browse/group/2000s) is updating browse categories thumbnails to use the same one for each year in given decade. In the screenshot of the Curation > Browse page below note that all of the 2000's browse category images have been changed to the same image (teal/Lagunita) and the 1990's images are also now all the same (Redwood):

<img width="863" alt="Screen Shot 2021-05-03 at 8 45 14 AM" src="https://user-images.githubusercontent.com/101482/116899621-a2fc3000-abec-11eb-82e4-0a5f1bc200fd.png">

---

But displaying the browse landing page for either the 1990's or the 2000's group renders the tiles with their previous thumbnail (tiles are different colors rather than all the same in a given group). This feels like a caching issue, but it is the case in any browser/incognito window I try:

<img width="1154" alt="Screen Shot 2021-05-03 at 8 44 46 AM" src="https://user-images.githubusercontent.com/101482/116900013-2158d200-abed-11eb-8160-5f7088812011.png">

---

<img width="1154" alt="Screen Shot 2021-05-03 at 8 44 54 AM" src="https://user-images.githubusercontent.com/101482/116900037-29187680-abed-11eb-9437-b5cc4761dc9c.png">

**Comment by ggeisler** [comment]
@cbeer Did you do anything to fix this? I just noticed that the browse group pages are rendering as expected now. So am curious if you fixed something versus maybe we just have to wait a few hours for caching to expire, or something like that?

**Comment by cbeer** [comment]
Maybe it was caching expiring 🤷‍♂️ . I think we can leave this open for more investigation because something was definitely funky.
