### ISSUE TITLE
Adjust spacing for rendered search results widget

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#2087]
This fix might need to be done in another repo, but since it sounded like the change might have resulted from a Blacklight update, I'm not certain which repo it should be fixed in, so it probably makes sense for a more knowledgeable developer to figure it out.

The rendered search result widget includes two places where the spacing needs adjusting:

- The item title needs to be left-aligned with the left edge of the thumbnail image and metadata
- There needs to be vertical space between the view options buttons and the top of the search results container

<img width="879" alt="Screen Shot 2021-05-04 at 10 38 47 AM" src="https://user-images.githubusercontent.com/101482/117046883-13c34b00-acc6-11eb-9ce4-e0a368994ca6.png">

---

- For the first issue, I believe giving the item title `padding-left: 0;` will fix it
- For the second issue, adding 1rem margin between the view options buttons and the top of the search results container seems about right

Those changes would result in something like this:

<img width="879" alt="Screen Shot 2021-05-04 at 10 42 14 AM" src="https://user-images.githubusercontent.com/101482/117047080-4c632480-acc6-11eb-89cc-6088ecf4514d.png">

---

I suspect the trickiest thing about this is to make those updates in a way that doesn't affect other search result views.

**Comment by caaster** [comment]
I think the fix for this was merged? Does this mean the fix is now in Exhibits? I don't know how to find this out.

**Comment by corylown** [comment]
@caaster this appears to be partially fixed. However, the document title/link under the image in the gallery view still has padding on the left that should be removed to make the design match what's described in this issue.
<img width="575" alt="Screenshot 2024-07-08 at 9 06 57 AM" src="https://github.com/sul-dlss/exhibits/assets/458247/d0686b6c-4547-4fdc-9759-079e69b38a78">

**Comment by corylown** [comment]
It appears that the fix applied in https://github.com/projectblacklight/blacklight-gallery/pull/105 is not working because `document-title-heading` class is not wrapped by `document-metadata`.
