### ISSUE TITLE
Selected feature pages error out when attempting to edit - https://exhibits.stanford.edu/awards

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2099]
Mike Keller contacted Josh Schneider today and wants him to update the following exhibit ASAP: https://exhibits.stanford.edu/awards, with new Stanford University award winners.

Josh successfully updated the exhibit home page, along with this feature page: https://exhibits.stanford.edu/awards/feature/kenneth-m-cuthbertson-award

When Josh tried to edit the following 2 feature pages, after editing, he saw the library status page displayed:
https://exhibits.stanford.edu/awards/feature/lloyd-w-dinkelspiel-award
https://exhibits.stanford.edu/awards/feature/walter-j-gores-award

I tried to edit the same feature pages, and experienced the same behavior.
![Screen Shot 2021-06-03 at 7 39 09 PM](https://user-images.githubusercontent.com/3210225/120737709-6f3e4f80-c4a3-11eb-9a91-d3a172c72dd3.png)

**Comment by anarchivist** [comment]
I'm waiting to hear about the kinds of edits that Josh made to these pages specifically, but it looks like there's considerable repeated use of the uploaded item row widget, with each instance only having one item:

<img width="376" alt="Screen Shot 2021-06-03 at 10 10 39 PM" src="https://user-images.githubusercontent.com/73732/120749023-ac610c80-c4b8-11eb-9998-4a4c04ed5181.png">

I think [this Honeybadger alert](https://app.honeybadger.io/projects/49092/faults/79773271) is the error that Josh is running into.

**Comment by anarchivist** [comment]
From Cathy:

> when I successfully validated the problem that Josh reported, I tried to edit a single word in the top-most text widget used on each of the feature pages in question (for each of these feature pages, the first widget used is the heading widget and the next widget used is the text widget) -- and when I tried to save each edit, the library status/outage page displayed.

From Josh: 

> Just as Cathy indicated, I am trying to edit and add new widgets to the top of these pages in the same format as the ones below.
