### ISSUE TITLE
Prevent requests for HUGE images via CSV

### ISSUE THREAD

**Issue by snydman** [sul-dlss/exhibits#210]

**Comment by jcoyne** [comment]
An expedient fix might be:
```ruby
Spotlight::Resources::Upload.validates :url, 
   file_size : { 
      maximum: 2.gigabytes.to_i 
    } 
```
This would allow the files to be uploaded, but I think it prevents them from being processed by imagemagick, which is where our current problem with `/tmp` filling up is occurring.

**Comment by jcoyne** [comment]
Another expedient fix is to limit the disk/memory useage in the `policy.xml` configuration file for ImageMagick.

**Comment by jcoyne** [comment]
not a high priority for Stanford as we aren't using CSV imports at this time.

**Comment by mjgiarlo** [comment]
Should this issue move to spotlight proper?

**Comment by jkeck** [comment]
Closing this in favor of projectblacklight/spotlight#2056
