### ISSUE TITLE
Adding new items to Opening Night! are not saving and reindexing results in an error

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2106]
Submitted by exhibit curator Ray Heigemeir on 8 July 2021:

After a period of hibernation, we want to begin adding new entries to the Opening Night! database. We added two yesterday, but they don't appear to have "saved."  The titles were "Guru" and "Happiness is the problem."  I reindexed and the blue "reindexing" indicator seems to still be incomplete (after three hours).  Not sure where the problem lies.

Could someone investigate when time allows?

**Comment by caaster** [comment]
@camillevilla does this fix mean that the new entries Ray tried to add will need to be re-added, or should he check first to see if they are there by doing a search in the exhibit?

**Comment by cbeer** [comment]
Once we deploy the changes (as time allows this week...), I think we index it without Ray's involvement.

**Comment by camillevilla** [comment]
@caaster I think Ray will need to re-add the items after reindexing - this bug was preventing saving uploaded items without thumbnails.

**Comment by caaster** [comment]
@cbeer @camillevilla could one of you kindly notify me when this change is deployed to prod? This is a part of dev work that is never entirely clear to me. Thank you.

**Comment by camillevilla** [comment]
@caaster this has been deployed and the exhibit items were reindexed, so Ray should be able to resume adding new items. I believe these are the items he tried to add?
https://exhibits.stanford.edu/operadata/catalog?exhibit_id=operadata&search_field=search&q=happiness+is+the+problem
https://exhibits.stanford.edu/operadata/catalog/183-70019
