### ISSUE TITLE
JSON exports for "large" exhibits are timing out

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2110]
Tue 7/13/2021 3:11 PM
From: "Mark Matienzo" <matienzo@stanford.edu>

Exports of "large"-ish exhibits (eg. Computer Science @ Stanford and Feigenbaum) are timing out. Instead of seeing the expected download of the JSON export, I am redirected to the Library Status page.

**Comment by anarchivist** [comment]
Related Honeybadger error: https://app.honeybadger.io/projects/49092/faults/80299421

**Comment by caaster** [comment]
Fixed. Successfully downloaded JSON file for Feigenbaum & CS @ Stanford.
