### ISSUE TITLE
Info requested: Facet display for non-SDR IIIF items added to exhibits

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2113]
Looking for information to understand why metadata for IIIF items added to an exhibit don't display MD facets (although from executing several searches it is clear that the metadata is being indexed). Here is an exhibit example that contains 2 IIIF items from the Bodleian Library:

https://exhibits.stanford.edu/cathy-s-test-iiif-exhibit

Is the facet display for IIIF items intended to work? Is there any host institution dependency (re how they provide metadata in the manifest?) Or is this functionality that would require additional work to Spotlight core code?

**Please note, this information is needed to inform the Jio collaboration effort prioritized by Mike & Tom.**

**Comment by cbeer** [comment]
I went into the metadata field settings for "Materials" field and changed it from "free text" to "controlled vocabulary" (as you would with any custom metadata field), and the Materials field is available as a facet as expected.

**Comment by caaster** [comment]
So this makes me wonder, if Andrew exports the MD for Jio, for all IIIF exhibit items -- would Jio be able to also import that MD into a Spotlight exhibit in bulk (somehow?) to get it to display as MD facets?

**Comment by caaster** [comment]
I am closing this ticket because we haven't heard a peep about the Jio collaboration from Tom since 2021.
