### ISSUE TITLE
Masthead image won't display for SAGR exhibit

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2119]
I'm working with the exhibit curator for the South Africa, Greece and Rome exhibit. https://exhibits.stanford.edu/SAGR 

They have selected an image from the exhibit (ym523jr7009), and they have defined the image region and saved it for the masthead. Unfortunately the image is not displaying as the masthead. I even tried using a Chrome incognito window in case there were caching issues -- the masthead image still does not display.

Any help would be much appreciated. Thank you.

**Comment by cbeer** [comment]
I'm seeing that `ym523jr7009` is marked as no-download?

**Comment by caaster** [comment]
Thank you. My bad for not checking that.
