### ISSUE TITLE
Restrict visibility of Request new exhibit button to super-admins

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#212]
We currently show the `Request new exhibit` button to any user viewing the Exhibits homepage. For the near-term timeframe, however, we want curators to follow a formal request process rather than create new exhibits themselves. So we should restrict visibility of the `Request new exhibit` button to only super-admin users (if we create an additional class of users to include non-super-admin members of the Exhibits service team, we might want to also enable that group to see the button and create new exhibits).

![online_exhibits](https://cloud.githubusercontent.com/assets/101482/16240634/f8b91aac-379e-11e6-986f-a4056e4c80d8.png)

If the `Create new exhibit` link in the user pulldown menu appears for non-super-admin users (I'm not sure how things look for WebAuthed non-super-admin users), we should restrict visibility of it in the same way.

![test_exhibit_one_-_online_exhibits](https://cloud.githubusercontent.com/assets/101482/16240827/cecc98a8-379f-11e6-9777-6f71cda21cd7.png)

**Comment by cbeer** [comment]
Configure the `Ability` class with this restriction.
