### ISSUE TITLE
Parker item page error

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#2122]
Feedback submitted by an end-user says they haven't been able to load the item on this page:

https://parker.stanford.edu/parker/catalog/cm287zk2842

The item doesn't load in the viewer.

For comparison, a related volume does load:

https://parker.stanford.edu/parker/catalog/cr633rp5601

I do see in the web inspector console this error for the problem page:

> InternalError: too much recursion

Which then references `Manifest.js`.

**Comment by cbeer** [comment]
The item seems to load for me; I see the object was recently republished, so maybe something was remediated in the data?

**Comment by ggeisler** [comment]
Interesting. Did you load for you in Firefox? It does load for me on Chrome and Safari, but still not Firefox, so I assume that might be what the feedback submitter is using.

<img width="1249" alt="Screen Shot 2021-08-20 at 9 32 21 AM" src="https://user-images.githubusercontent.com/101482/130265252-a9b2915e-2e3c-4978-a566-696dd6b47495.png">

**Comment by cbeer** [comment]
yep, firefox chrome and safari.

**Comment by cbeer** [comment]
I forgot these were also using Ben's special hand-rolled IIIF manifests; I see it was changed about 30 minutes ago too. I assume that was to correct a mistake, but have no way to verify that either.

**Comment by ggeisler** [comment]
Okay, thanks. Ben does see Parker feedback as it comes in, so it makes sense that he might working to fix this at his end. I'll check in with him (because I still can't get the page to load in Firefox no matter what I do).

**Comment by ggeisler** [comment]
Okay, my issue with Firefox was apparently just a caching issue after Ben fixed the problem with the manifest. All looks good now thanks to Ben's fix.
