### ISSUE TITLE
Please confirm: is this confirmation email legit?

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2128]
Hi, I don't receive automated exhibits emails when a new user is added to an exhibit, so I could use some help with confirming that this email is legitimate. Deardra has asked me to confirm that this is not spam. Thank you.

![Screen Shot 2021-09-13 at 3 16 57 PM](https://user-images.githubusercontent.com/3210225/133163831-0a192204-f716-440e-b2e3-7ff653109c09.png)

**Comment by ggeisler** [comment]
@caaster I think so. The text matches Spotlight's mailer text: https://github.com/projectblacklight/spotlight/blob/66776d7caa5f984246064e2dc33422af7fa734c3/config/locales/spotlight.en.yml#L409

I created #2129 to suggest that we should customize this text in Exhibits to make it feel more like a real email. I can do this sometime soon.

To be certain, Deardra could maybe mouse over the Confirm link and see if it looks like a legit link (I'm not sure off-hand what that link should look like, but am presuming it references an exhibit URL?).

**Comment by ggeisler** [comment]
As discussed offline, the email in question is legitimate, just not very helpfully worded/formatted. https://github.com/projectblacklight/spotlight/issues/2779 addresses those issues.
