### ISSUE TITLE
Parker on the Web: Inconsistent behavior viewing parker.stanford.edu

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#2142]
Hi all,

Not sure if this is the right place to drop this - please let me know if not and I'll move it.

Summary: the public-facing Parker on the Web URL, https://parker.stanford.edu, is displaying different behavior than the internal https://exhibits.stanford.edu/parker . 

Some symptoms as follows:
* sign in not allowed 
<img width="606" alt="Screen Shot 2021-11-04 at 9 06 19 AM" src="https://user-images.githubusercontent.com/796990/140376311-6f37d894-6132-468b-8da1-7ab1d0264479.png">
* (via https://parker.stanford.edu/users/auth/webauth?referrer=https%3A%2F%2Fparker.stanford.edu%2Fparker)

* Home image and branding not visible:
<img width="1369" alt="Screen Shot 2021-11-04 at 9 06 08 AM" src="https://user-images.githubusercontent.com/796990/140376453-a20dc007-47fe-488a-9be0-4c08cc542d77.png">
<img width="1366" alt="Screen Shot 2021-11-04 at 9 05 52 AM" src="https://user-images.githubusercontent.com/796990/140376476-be8680d1-8419-46d2-a6bd-9508045d7b58.png">
* Screenshot without library image from https://parker.stanford.edu/parker, with image from https://exhibits.stanford.edu/parker

Please advise.

Thank you,

Ben

**Comment by cbeer** [comment]
Is this fall-out from https://github.com/sul-dlss/operations-tasks/issues/2729?

**Comment by anarchivist** [comment]
* On exhibits.stanford.edu, the browser is loading https://exhibits.stanford.edu/uploads/spotlight/attachment/file/3491/parker-library-dean-krafft-with-logo-min.jpg
* On parker.stanford.edu, the browser is attempting to load https://parker.stanford.edu/uploads/spotlight/attachment/file/3491/parker-library-dean-krafft-with-logo-min.jpg, but that gets redirected to https://parker.stanford.edu/parker/uploads/spotlight/attachment/file/3491/parker-library-dean-krafft-with-logo-min.jpg which is not found

**Comment by blalbrit** [comment]
Quite possibly @cbeer - though the image disappearing seems to have happened in the last few weeks. Will follow up with @rsmith11 - thanks for making the link.

**Comment by blalbrit** [comment]
Thanks @anarchivist - that's an excellent data point.
