### ISSUE TITLE
Pages widget on home page is not displaying properly

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/exhibits#2144]
I'm working on completing the Lighting the Way exhibit (https://exhibits.stanford.edu/lightingtheway), and I've added the pages widget to the home page. Each page displayed in the widget has a thumbnail, but the thumbnail is not showing.

<img width="1786" alt="Screen Shot 2021-11-19 at 10 57 56 AM" src="https://user-images.githubusercontent.com/73732/142677670-45896941-cd1a-4e1a-a805-a60381528846.png">

**Comment by anarchivist** [comment]
Per @cbeer: 

> i think you can’t use that many pages in a single widget. there’s a ticket somewhere about that

Reducing the number of pages in the widget has helped.

**Comment by cbeer** [comment]
https://github.com/projectblacklight/spotlight/issues/1761

**Comment by caaster** [comment]
I see that this is working correctly so I am closing this ticket.
