### ISSUE TITLE
Contact images on Parker About pages have disappeared

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2147]
From: "Benjamin Albritton" <blalbrit@stanford.edu>

All contact images appear to have disappeared (see https://parker.stanford.edu/parker/images/7409/23,8,221,221/70,70/0/default.jpg for instance), impacting all about pages. Other uploaded images appear fine. Have checked with @azanella in Ops and they don't see anything in the vanity URL or systems that they can determine. Is there an issue with just contact images or uploads from a certain period? Please advise how I should proceed to recover these images.

*****************
I have spot checked a few other exhibits that have About page contact images and they are all displaying.

**Comment by cbeer** [comment]
I think this is yet more fall-out from https://github.com/sul-dlss/operations-tasks/issues/2729 and https://github.com/sul-dlss/exhibits/issues/2142. I'm still not sure what steps @blalbrit and the operations team took with establishing those redirects, but the correct URL for those images should be `https://parker.stanford.edu/images/....`

**Comment by blalbrit** [comment]
Thanks @cbeer - @tallenaz is this something I should move over to an ops queue?

**Comment by tallenaz** [comment]
Thanks @cbeer @blalbrit I've reopened https://github.com/sul-dlss/operations-tasks/issues/2729 and we can investigate further on the load balancer.

**Comment by caaster** [comment]
However the contact photo for Rare Books is displaying just fine: https://exhibits.stanford.edu/rarebooks/about/how-to-search-the-collection

**Comment by anarchivist** [comment]
@caaster The screenshots on that page are not appearing though: https://rarebooks.stanford.edu/rarebooks/about/how-to-search-the-collection

**Comment by caaster** [comment]
Oof. Thanks @anarchivist

**Comment by cbeer** [comment]
That's the same deal, the images are getting redirected to `https://rarebooks.stanaford.edu/rarebooks/upload/...` when they shouldn't be.

**Comment by tallenaz** [comment]
There's a `parker-proxy-rewrite-irule` on the load balancer that handles these. I've added a stanza for /images/ and it looks like the contact images for https://exhibits.stanford.edu/parker/about/about are back.

**Comment by tallenaz** [comment]
There's also a `rarebooks-proxy` irule. I've added a stanza for /uploads, and I'm seeing the images now. Any more missing we can look into?

**Comment by tallenaz** [comment]
Confirmed with @blalbrit that this is fixed.
