### ISSUE TITLE
Ability to link a URL to a caption for an image using the uploaded item row widget is not functioning

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2160]
Caption is not displaying as a link: https://exhibits.stanford.edu/cathy-test-exhibit/home

![Screen Shot 2022-01-28 at 10 34 01 AM](https://user-images.githubusercontent.com/3210225/151602572-35d6d7db-d4c2-48f1-9bdb-b0919b484c2d.png)

**Comment by ggeisler** [comment]
@caaster The image is a link, not the caption itself.

**Comment by caaster** [comment]
Thank you @ggeisler - I misunderstood how it was supposed to work!
