### ISSUE TITLE
Item embed widget zoom controls for non-SDR exhibit items has a bug

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2162]
When the item embed widget is used on a page more than one time, for non-SDR items that have been uploaded to the exhibit -- when a user clicks on the "+" or "-" zoom controls for one of the images, all of the images on that page using the widget zoom in and out simultaneously. As a user, I expect that the zoom controls for each instance of the widget on the page should work independently.

See my bug test page: https://exhibits.stanford.edu/cathy-test-exhibit/feature/testing-a-bug

See the bug in a published exhibit: https://exhibits.stanford.edu/blrcc3/feature/commissioning-indigenous-maps-james-g-scott-in-burma

Bug submitted by DRMC staff.

**Comment by anarchivist** [comment]
This is probably the same issue as projectblacklight/spotlight#2790.
