### ISSUE TITLE
Rare Music exhibit feature page content strangely replaced with content from a different exhibit

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2168]
On 18 Feb 22, Ray Heigemeir of the Music Library reported the following:
"Hello! I happened to open this feature page and see that Edweard Muybridge booted the Beethoven content off the page (!) Help?  - https://exhibits.stanford.edu/rare-music/feature/beethoven-at-stanford"

Today Ray and I attempted to sleuth the issue. The following details relate:
- Ray does not recall when the last time is that he edited the Beethoven page, nor the last time he looked at the Beethoven page prior to reporting this issue.
- Ray looked at the Wayback machine for the Rare Music/Beethoven exhibit page: https://web.archive.org/web/20210430072918/https://exhibits.stanford.edu/rare-music/feature/beethoven-at-stanford
- You can see from the Wayback captures that on 25 Nov 2020 the correct content was on the Beethoven page, and on 30 April 2021 the incorrect content is displayed.
- The incorrect content on the Rare Music/Beethoven page is from the following exhibit page: https://exhibits.stanford.edu/muybridge/about/biography
- Ray doesn't have admin permissions for the Muybridge exhibit. No staff in Univ Archives have permissions to the Rare Music exhibit.
- Please note the following oddities which seem like related, unusual coincidences:
1. Under Recent Site-building Activity on the Rare Music exhibit:
![Screen Shot 2022-03-01 at 10 23 08 AM](https://user-images.githubusercontent.com/3210225/156226678-7040ca95-fc08-4a9b-b4d6-451a36d0d977.png)
2. Under Recent Site-Building Activity on the Muybridge exhibit:
![Screen Shot 2022-03-01 at 10 24 37 AM](https://user-images.githubusercontent.com/3210225/156226873-a088a0e7-edce-4e91-8658-076591c0ed61.png)

**Comment by cbeer** [comment]
I've pulled the content over from -stage. My recollection is... this was probably caused by a failed data migration of some very old pages that used a retired block type.
