### ISSUE TITLE
Collection druid is not indexed (Fitch)

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#217]
From JIRA ticket EXHBTF-57:

A curator wants to add collection druid mp414ks8055 to Fitch. I add mp414ks8055 to the list of items in the exhibit last night and checked this morning to see if any new items were added. No new items were added to the exhibit. But I also don't see any delayed job errors in the UI. 

So I think what we want to investigate is what happens when druids nw358hg5491 and mp414ks8055 are added (or reindexed) in Fitch? Are there errors not visible through the UI that are available in logs somewhere? 

If mp414ks8055 is successfully added, a search for "Bayard Rustin" should return results. 
https://searchworks.stanford.edu/view/mp414ks8055 

If nw358hg5491 is successfully added, a search for "Catholic Worker" should return more than the three associated with Dorothy Day that are returned. 
https://searchworks.stanford.edu/view/nw358hg5491

**Comment by atz** [comment]
Most of my work will be tracing the codepath and context that accomplishes the indexing.

Notes to self from meeting w/ Cathy and Ben:
- determine whether indexing pulls from purl or dor
- reportedly edits to published objects are not propagated(?), requires manual reindex
- possibly alignment with `dispatcher`
- items cannot be added to two spotlight collections, a major logical failure
- No currently PCDM-like nested collections
- Ben: "spotlight index is read-only out of dor."  I.E., the object is NOT updated to retain associations made in spotlight.

Goals:
- don't block indexing

**Comment by atz** [comment]
@cbeer reports that the lack of update propagation is intentional, specifically that the the Curator/User is getting a snapshot of the item at a specific time.  They can also reindex a collection, but only manually. 

While more lightweight and self-contained than our other indexing infrastructure, this essentially means that propagating updates (from, say, Hydrus or Argo) is excluded by design.  It also relates to the reason multiple collections can't both include the same object.  Because object:solr_document is a 1:1 relationship, both identified by druid, the first Curator including an object gets the snapshot from that time.  A second Curator has no namespace to index the same object.

Cathy intends to review whether the static snapshot model or more of a dataflow model is preferred politically.  Right now they are antagonistic to and exclusive of each other.  

Personally, I see far less value to the snapshot indexing model over time.  Given a robust collection (say thousands of items):
- It is a bit of an evasion to believe that the Curator/User has comprehensive knowledge of the state of all objects when they click the **reindex_all** button.  
- We are creating maintenance burden for users that expands w/ number of collections.
- We are creating unnecessarily spiky load, instead of organically keeping updated.
- We're blocked from nested collections and other features that regard the objects as dynamic.

**Comment by atz** [comment]
An informal trace:
```ruby
# `Reindex all` button
-> ResourcesController#reindex_all
-> @exhibit.reindex_later
-> Spotlight::ReindexJob.perform_later(self) # self is @exhibit
-> resource_list(exhibit_or_resources).each(&:reindex) # i.e.,
-> @exhibit.find_each.each(&:reindex)
-> write_to_index(exhibit.solr_data.merge(spotlight_resource_metadata_for_solr))
```
So Spotlight::Exhibit's `solr_data` composes each doc for the update:
```ruby
    def solr_data
      filters.each_with_object({}) do |filter, hash|
        hash.merge! filter.to_hash
      end
    end
```
Each `filter.to_hash` does basically `{ field => value }`, so now one needs to know the content of the database to reason about what might get produced. Spotlight::Exhibit `has_many :filters`.  I need to understand how the object was imported into the DB for this to make sense.

Not sure about anything targeting SolrController, where a comment claims `This is an example of how you could integrate external indexing workflows with exhibit-specific content`.

**Comment by atz** [comment]
See the bulky class `ExhibitExportSerializer`.

**Comment by jcoyne** [comment]
Yeah, I'm not seeing how you are getting to the `-> @exhibit.find_each.each(&:reindex)` step in your trace.

I see:
 `Resource#reindex` https://github.com/projectblacklight/spotlight/blob/master/app/models/spotlight/resource.rb#L110
`Resource#documents_to_index` https://github.com/projectblacklight/spotlight/blob/master/app/models/spotlight/resource.rb#L60
`DorHarvester#to_solr` https://github.com/sul-dlss/spotlight-dor-resources/blob/master/app/models/spotlight/resources/dor_harvester.rb#L18
`DorHarvester#indexable_resources` https://github.com/sul-dlss/spotlight-dor-resources/blob/master/app/models/spotlight/resources/dor_harvester.rb#L50
`DorHarvester#resources` https://github.com/sul-dlss/spotlight-dor-resources/blob/master/app/models/spotlight/resources/dor_harvester.rb#L33

which is calling code such as: `Spotlight::Dor::Resources.indexer.resource("mp414ks8055").items`, which returns the items that eventually get indexed.   Could it be that this code is not pulling all the expected items?

**Comment by jcoyne** [comment]
I created a new exhibit and pulled in `mp414ks8055`. When it was done indexing it had 102 items.  This is what I expected because it's the code I get from running the indexer directly:

```ruby
Spotlight::Dor::Resources.indexer.resource("mp414ks8055").items.map(&:druid).count
 => 102
```

Then when I run a search for "Bayard Rustin" I still get zero results.   Are we certain that the data is in DOR correctly?

**Comment by ggeisler** [comment]
What happens if you run the indexer directly on -prod?

In your Bar exhibit on -stage, you can search for druid `ns593rz8367` and find it. If you search for `ns593rz8367` on -prod: https://exhibits.stanford.edu/fitch/catalog?utf8=%E2%9C%93&exhibit_id=fitch&search_field=search&q=ns593rz8367 , there are no results.

**Comment by jcoyne** [comment]
On both dev and production I see this result:
```
Spotlight::Dor::Resources.indexer.resource("mp414ks8055").items.map(&:druid).include?('druid:ns593rz8367')
 => true
```

When was the last time that the fitch exhibit was reindexed? Can I reindex it now?

**Comment by ggeisler** [comment]
Sure, definitely reindex.

**Comment by jcoyne** [comment]
When I attempt to run in production I get:
https://gist.github.com/jcoyne/a19bedf11c4ae6fdb4ee53346561f6f8

I wonder if the more updated versions of the dor-fetcher gem would work better?

**Comment by jcoyne** [comment]
Here's where that error is occurring:
https://github.com/sul-dlss/dor-fetcher/blob/v1.0.5/lib/dor-fetcher.rb#L134-L135

**Comment by jcoyne** [comment]
@ggeisler after reindexing now I can search for `https://exhibits.stanford.edu/fitch/catalog?utf8=%E2%9C%93&exhibit_id=fitch&search_field=search&q=ns593rz8367` on production and I get a result.

**Comment by atz** [comment]
@jcoyne the informal trace is occasionally me collapsing stuff mnemonically, not a literal debugger trace

**Comment by ggeisler** [comment]
Yep, that looks correct. This round of reindexing definitely added more items. The searches mentioned in the original ticket description now produce the expected results, I think. We probably should have the exhibit curator double-check, but this does look promising.

**Comment by atz** [comment]
Right now at least one worker box is unable to access `dorfetcher-prod` via http (port 80).  Errors from logs like:
```
E, [2016-07-15T14:38:51.093980 #66516] ERROR -- : 2016-07-15T14:38:51-0700: [Worker(delayed_job.4 host:exhibits-worker-prod-a.stanford.edu pid:66516)] Job ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper (id=703) FAILED (0 prior attempts) with RuntimeError: Connection Error with url http://dorfetcher-prod.stanford.edu/collections/zp940yp4275
```

From the same worker:
```
wget http://dorfetcher-prod.stanford.edu/collections/zp940yp4275 # fail
wget https://dorfetcher-prod.stanford.edu/collections/zp940yp4275 # fine
```

So we determined there is a firewall blocking the port the worker is requesting on.  This appears to be configured in **gdor.yml**:
```yaml
dor_fetcher:
  service_url: http://dorfetcher-prod.stanford.edu
```

I propose to configure that to use https.  Note: the application has not been updated to use our shared_configs.

**Comment by atz** [comment]
Also, would be really nice for that exception handler to expose more about the underlying error instead of obscuring it.

**Comment by jcoyne** [comment]
@atz those are good ideas. Can you create new issues to track them?

**Comment by atz** [comment]
I made a PR for the gdor.yml.example file.  Not sure about config mgmt for the app.  Working on dor-fetcher now.

**Comment by atz** [comment]
Probably dor-fetcher shouldn’t swallow all possible different RuntimeError's while raising it's own generic one.  It probably shouldn't even swallow different RestClient exceptions while raising a generic one.  What value is it providing there?

**Comment by atz** [comment]
https://github.com/sul-dlss/dor-fetcher/issues/15

**Comment by ggeisler** [comment]
Indexing on Fitch now seems to work.
