### ISSUE TITLE
Add Google Site Verification code

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/exhibits#2172]
We got a request from colleague to see if we could have a specific set of pages from exhibits given an issue with a misspelled name on the page (see [EXHBTF-1482](https://jirasul.stanford.edu/jira/browse/EXHBTF-1482)). According to the SUL staff member that reported it, the person reporting the issue is being vocal about having this happen soon. The request is for the following:

* All occurrences of https://purl.stanford.edu/bm287pw9541 and
https://purl.stanford.edu/vf263xt4595 in Chinese Railroad Workers exhibit, Transcontinental Railroad exhibit, and Stanford Oral History Collections exhibit
* And PURL and SW if those are crawled

The task here is to use Google Site Verification to add a specific `<meta />` tag in the `<head />`:

```html
<meta name="google-site-verification" content="eD_pZjh-aWkTGA3_iYHmMdGV2cNugc7FTwtgNv2EnZE" />
```

We should probably(?) make the changes to `shared_configs`; this will only apply to prod.

* [ ] Add `Settings.GOOGLE_SITE_VERIFICATION` value to be `eD_pZjh-aWkTGA3_iYHmMdGV2cNugc7FTwtgNv2EnZE` in `shared_configs` 
* [ ] Redeploy

See also sul-dlss/SearchWorks#2818, sul-dlss/purl#563, and sul-dlss/earthworks#851. EarthWorks **does not** need to be recrawled for this ticket to be resolved.

<details><summary>Background info</summary>

It appears that we can [ask Google to recrawl URLs](https://developers.google.com/search/docs/advanced/crawling/ask-google-to-recrawl) either by  using the URL Introspection tool in the Google Search Console, or by supplying a sitemap. The number of pages is relatively small, so the first option makes the most sense. However, we'll need to verify ownership of the site with the Google Search Console first. 

Relatedly, though, PURL and SearchWorks both have a verification code already deployed, but I don't know who has access to the Google Search Console to request the recrawl of the specific URLs.
</details>

**Comment by marlo-longley** [comment]
@anarchivist Here's a list of changes related to this issue. I have not deployed anything yet.

shared_configs:
- https://github.com/sul-dlss/shared_configs/pull/1758 (SearchWorks-Prod)
- https://github.com/sul-dlss/shared_configs/commit/39c8e1aef137b6d1f97e2a85a73582e2087b4608 (Purl-Prod)
- https://github.com/sul-dlss/shared_configs/pull/1760 (Earthworks-Prod)

[SearchWorks repo update](https://github.com/sul-dlss/shared_configs/pull/1758)
[EarthWorks repo update](https://github.com/sul-dlss/earthworks/pull/852)
[Purl repo didn't have this key in the codebase, so I did not add it]

**Comment by anarchivist** [comment]
As discussed on standup on 2022-03-17, it's fine if the deploys go out on Monday with the dependency updates. From highest to lowest priority:

* Exhibits
* SearchWorks and PURL
* EarthWorks

**Comment by marlo-longley** [comment]
@camillevilla here are the last two PRs:

shared_configs:
https://github.com/sul-dlss/shared_configs/pull/1761

Exhibits repo itself:
https://github.com/sul-dlss/exhibits/pull/2174
