### ISSUE TITLE
After searching, clicking on any record in the Rare Books exhibit results in a 404 error

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2178]
I am also able to validate Ben's report, below -- in Chrome as well.
**********

From: exhibits-feedback <exhibits-feedback-bounces@lists.stanford.edu> on behalf of exhibits-team@lists.stanford.edu <exhibits-team@lists.stanford.edu>
Sent: Thursday, March 24, 2022 9:26 PM
To: exhibits-feedback@lists.stanford.edu <exhibits-feedback@lists.stanford.edu>
Cc: spec-rarebooks@lists.stanford.edu <spec-rarebooks@lists.stanford.edu>
Subject: [exhibits-feedback] Rare Books exhibit feedback
 
Benjamin Albritton

From: "Benjamin Albritton" <blalbrit@stanford.edu>

Clicking on any of the records on this search page (https://rarebooks.stanford.edu/rarebooks/catalog?exhibit_id=rarebooks&search_field=search&q=) leads to a 404 error. Open the link in a new tab works though. Have tested in Firefox and Safari.

----
REMOTE_IP
67.188.238.232
USER AGENT
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:98.0) Gecko/20100101 Firefox/98.0
EXHIBIT
Rare Books
CURRENT_URL
https://rarebooks.stanford.edu/rarebooks/catalog?exhibit_id=rarebooks&search_field=search&q=
UUID
0603f42b-afc7-4f47-9251-7dbb76ba03e6

**Comment by tallenaz** [comment]
An example problem URL here is `https://rarebooks.stanford.edu/rarebooks/catalog/yh781qt6352`

I added a stanza for `/catalog/*` to the rarebooks proxy iRule on the load balancer and the link now behaves as expected.

@caaster can you verify this on your end?

**Comment by caaster** [comment]
@tallenaz now fixed thank you!

**Comment by tallenaz** [comment]
Connecting https://github.com/sul-dlss/exhibits/issues/2147 for future reference.
