### ISSUE TITLE
Improve support for social media?

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#218]
An exhibits service team member made this request:

> Social media support seems to be lacking for Spotlight -- and this really matters for sharing exhibits.stanford.edu links on Twitter & Facebook. (Among others -- but Twitter & FB is all I am reporting on here -- someone will need to look into Instagram, etc.). These are two issues that have jumped out at me recently (see screen shots attached): 

> 1) Twitter does not automatically display a visual snippet of an exhibits.stanford.edu web page when the URL is tweeted. Other URL's do this & it would be good to enable. Is there something we need to do to enable/allow this? 

> 2) Facebook displays the "&amp;amp;" in the title of an exhibit (in this case) when mentioning the URL in a post. This seems sloppy -- can this be fixed? 

Image examples attached:

![_thumb_51970](https://cloud.githubusercontent.com/assets/101482/16535279/fec412ea-3f9a-11e6-988a-f1373249db63.png)

![_thumb_51969](https://cloud.githubusercontent.com/assets/101482/16535283/032edc2a-3f9b-11e6-8ad7-9cb862a4c7f6.png)

**Comment by atz** [comment]
Yeah, it is basically providing microdata embedded in the page (importantly, to a bot request from twitter, not in the user's security/app context).  For Twitter that would include OpenGraph metadata.  Other consumers might prefer RDFa, oEmbed or other Schema.org description.  OSS library apps have approached this topic already (likely including some of our own), but I know Dan Scott made the rounds with such features in Koha, Evergreen, VuFind, etc., if we want a basis for comparison. 

Here's a not too recent but helpful overview: http://www.templatemonster.com/blog/implement-social-snippets-for-social-media/

It includes links to various online validators, including one for [twitter](https://cards-dev.twitter.com/validator) that says of the example page only:
```
INFO:  Page fetched successfully
INFO:  6 metatags were found
WARN:  Not whitelisted
```
Not super informative.  Note: our example resource (behind the **.io** link resolver) is: https://exhibits.stanford.edu/fitch/browse/the-berrigans-the-catonsville-nine-1968-1972

The page itself is in error, delivering:
```html
<title>The Berrigans &amp;amp; the Catonsville Nine, 1968-1972 | The Bob Fitch Photography Archive - Online Exhibits</title>
```

Need to determine whether that is a presentation or data error.  Likely presentation.

**Comment by mjgiarlo** [comment]
We've got this in Sufia too, @atz, though I wonder how well it survived getting dragged along from Sufia 6 to 7...

**Comment by atz** [comment]
My findings are that Spotlight intends to provide this functionality via the `tophat` gem.  Spotlight has a helper method `add_exhibit_twitter_card_content` that seems designed solely for collection level cards.  It provides: url, title, description, image.  

Spotlight's `pages/show` template calls `render 'tophat'`, but it also has two related partials:
- ./app/views/spotlight/pages/_tophat.html.erb -- empty!
- ./app/views/spotlight/home_pages/_tophat.html.erb: 
```html
<% description current_exhibit.description %>
<% add_exhibit_twitter_card_content %>
```
So this seems like a never fully integrated feature at the Spotlight level, only hitting the home pages.  Also, the only place we use that helper method, we seem confused about what the description should be.  Template says `current_exhibit.description`, method says `current_exhibit.subtitle`.

**Comment by atz** [comment]
OpenGraph apparently hasn't been attempted yet.

**Comment by mjgiarlo** [comment]
I'll start by adding rich snippets (for Twitter and Facebook) to the exhibit show view, and we can follow that up with rolling snippets out to the browse views, about page, and other featured pages after I get the metadata mappings right on the show view.

**Comment by mjgiarlo** [comment]
I can now confirm all the analysis that @atz already did, and here are the separate pieces of work related to this ticket:

* BUG: Exhibit browse views should not have double-escaped titles
* BUG: Open Graph helper should return meta tags containing the opengraph metadata from the Spotlight resource
* FEATURE: Twitter cards should be enabled for browse views, featured pages, and about pages

**Comment by mjgiarlo** [comment]
Will make tickets for the above bullets.

**Comment by mjgiarlo** [comment]
@ggeisler @atz @jcoyne @cbeer @caaster Now that I've decomposed this ticket into other, smaller tickets, can this ticket be closed? (If so, then please feel free to close it!)

**Comment by mjgiarlo** [comment]
@caaster: The `&amp;` bug is now fixed in Spotlight. Once a new version of Spotlight is released and exhibits points to that new version, we should see this fix in Exhibits.

**Comment by jcoyne** [comment]
@mjgiarlo you can cut 0.19.1 when ever you want.
