### ISSUE TITLE
Limit editing of "Tag list" field to superadmins

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#2183]
Exhibit administrators have the ability to edit the Configuration > General > Basic settings, Tag list field in their exhibit:

<img width="1005" alt="Screen Shot 2022-04-20 at 11 40 06 AM" src="https://user-images.githubusercontent.com/101482/164301211-820c69a0-c687-44ce-a828-7a7ce5d50c38.png">

---

The values in this field populate the tags used for filtering on the Exhibits landing page. We have a small set of tags used on the landing page, which we don't want to add to randomly. Although it rarely happens, an exhibit administrator can inadvertently mess up our carefully considered set of exhibit tags by adding new tags to their exhibit. When this happens we have no way of knowing about it unless someone happens to see the extra tags on the Exhibits landing page and reports it.

If technically possible, the best way to handle this might be to simply omit display of the Tag list field unless the user is an Exhibits superadmin. That would prevent someone who doesn't understand how the tags are used from doing something we don't want, while still enabling the superadmin to add and edit tags for individual exhibits.

(I'm filing this as an Exhibits ticket rather than a Spotlight ticket because I don't think we want to dictate how other implementors control access to the exhibit tags.)

**Comment by corylown** [comment]
In discussion with @caaster we prefer a solution where a multi-select input is provided with the different tag options (and the new issue would be a P1 or P2).
