### ISSUE TITLE
Delete some reference resources in Parker exhibit

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#2186]
Hi Mark,

I have a database task that I used to do myself, but with the change in job no longer have the permissions needed. It's fairly straightforward, but let me know how you would like for me to request it:

* in the exhibits/Parker db
** find all items of @type=reference (I believe - would need to see the avail. types) created 5/2/2022 (should be ~6000)
** delete them

Context: found an undocumented portion of the Zotero to Parker pipeline having to do with the custom BibTex translator that was created in 2017 and doesn't appear to be maintained as part of a DLSS repository as far as I can tell - might be somewhere I no longer have access to. More details in the meeting on Wednesday, but without that translator in place and the local instance of Zotero properly updated, an export produces new short-title-based @ids instead of the URL-based @ids that will allow old things to be reindexed instead of added as new references - thus ~6000 new references created today 🙁 . See https://github.com/camillevilla/bibtex-translator
for the translator .js file.

Many thanks,

**Comment by corylown** [comment]
@blalbrit I'm happy to help with this, but I want to be sure I know what you're asking to be deleted. I was able to find in the database roughly 6000 items that were created on 2022-05-20 using this query:

```
2.7.0 :026 > refs = Spotlight::SolrDocumentSidecar.where(exhibit_id: 70, create_at: Date.parse('2022-05-02').beginning_of_day..Date.parse('2022-05-02').end_of_day)
2.7.0 :027 > refs.count
 => 5865 
```

However, I don't see a `type` attribute that I can use to filter to just `references`.  Is there a specific database query you used in the past to find these items that need to be deleted? Did you also delete them from Solr, or just the database?

**Comment by blalbrit** [comment]
Hi @corylown - thanks again for your help today. As you suspected, the removal of items from the db was just the first step. Reindexing the exhibit did not remove them from the solr index. Let me know if I can help with that portion in any way.

Really appreciate your time on this, and it was good meeting you today!
