### ISSUE TITLE
Index appropriate geo-related fields to work with blacklight-heatmaps

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#219]

**Comment by ggeisler** [comment]
When this works, it closes #209

**Comment by mejackreed** [comment]
See https://github.com/sul-dlss/exhibits/issues/209#issuecomment-233408692 and https://github.com/sul-dlss/exhibits/issues/209#issuecomment-233411953 for info on what fields to index and how.

**Comment by jcoyne** [comment]
https://github.com/sul-dlss/spotlight-dor-resources/blob/b83c65147b6d169393d78a423e7cd19c7e2c6595/lib/spotlight/dor/indexer.rb#L55-L57

**Comment by atz** [comment]
Now spans: 
- #274 
- #275

**Comment by atz** [comment]
Requires `gdor-indexer` PR merge and release.
