### ISSUE TITLE
When trying to do a JSON export of the Say Their Names exhibit, 404 error displays

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2190]
When trying to do a JSON export of the [Say Their Names](https://exhibits.stanford.edu/saytheirnames) exhibit, the following error is displayed:

![Screen Shot 2022-05-23 at 2 30 49 PM](https://user-images.githubusercontent.com/3210225/169910005-5d8cb28b-c45d-4584-b109-f03a30271f47.png)

I was able to do a JSON export of an English only exhibit, and an English-French exhibit. 

The Say Their Names exhibit just published a Spanish translation, in addition to the existing English and Chinese. 

I want to save a JSON export, because so much effort went into this exhibit and creating the translations, and there have been many hiccups caused by the multiple hands involved. I am concerned about something going amiss in the future if a stakeholder makes an exhibit change, and it feels really important to me to have a recent JSON export saved as "insurance".

**Comment by cbeer** [comment]
I think this might have been related to #2045. I fixed up some thumbnail references for translated pages and the exhibit export worked for me.
