### ISSUE TITLE
Support any filename for uploaded images?

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2208]
Just worked with an exhibit creator and discovered a jpeg that uses an underscore at the beginning of the filename can't be uploaded and used as a main exhibit tile image.

Is it possible to support any filename, so in the future we don’t have to explain this to curators -- or instead, need to clutter the UI with more requirements for an uploaded file?

**Comment by cbeer** [comment]
I'm not aware of any intentional restrictions on file names. Can you provide the jpeg file?

**Comment by caaster** [comment]
File uploaded here: https://drive.google.com/file/d/1tycB9W5UeXD1igQy6u3Vn3WamZMG4E6Q/view?usp=sharing

**Comment by dnoneill** [comment]
@caaster I have tried this on multiple upload image pages and I haven't been able to recreate. Do you have more specific steps I can follow?

**Comment by dnoneill** [comment]
Okay this might be an issue. I am not quite sure if this is the issue being defined. The uploaded image on pages, and used for the page widget doesn't work. (Also happens in Spotlight) How to do this:

1. Go to the exhibit
2. Go to homepage
3. Go to thumbnail tab and upload and image and save.
4. Go to the feature pages tab in the dashboard
5. Create a new page.
6. Click + icon
7. Choose the pages widget.
8. Choose the homepage
9. Save
10. Look at the page. The widget is not going to show the image.

**Comment by dnoneill** [comment]
Closing in favor of https://github.com/projectblacklight/spotlight/issues/3201
