### ISSUE TITLE
[exhibits/prod] NameError: undefined local variable or method `facet' for #<Spotlight::HomePagesController:0x...>

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/exhibits#2213]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49092/faults/86707832)

**Comment by corylown** [comment]
This is the same issue as https://github.com/sul-dlss/exhibits/issues/2431
Which may be addressed by https://github.com/sul-dlss/exhibits/pull/2437
