### ISSUE TITLE
Look through Squash logs and see if anything warrants a work ticket

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#222]
For example, is the error below a problem that needs attention?

> Bug #130 on exhibits is occurring 
> a lot. Perhaps someone should look into it. 
> 
> https://sul-squash-prod.stanford.edu/projects/exhibits/environments/production/bugs/130 
> 
> Project: exhibits 
> Environment: production 
> Revision: c6e6e5ad7d4ef0e156e712b2a8eb9721d31c05a2 
> 
> ActionController::RedirectBackError 
> in app/controllers/login_controller.rb:10 
> 
> No HTTP_REFERER was set in the request to this action, so redirect_to :back could not be called successfully. If this is a test, make sure to specify request.env["HTTP_REFERER"].

**Comment by atz** [comment]
Now in honeybadger, but the problem is the same.  I posted a proposed workaround in the honeybadger issue.
