### ISSUE TITLE
Exhibits is not reindexing

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2242]
Exhibits is not reindexing. This was first reported this afternoon for the following exhibit: https://exhibits.stanford.edu/martin-wong. I was able to repeat the behavior described by the reporter, summarized below.

- Click on the reindex button in the exhibit
- See the "Reindexing all resources" message display
- Expect to see a reindex progress bar (which has not always worked reliably, however) -- and I don't see it
- Wait
- Refresh the Admin dashboard
- Should see, under "Recent item reindexing activity" - a reindex job in progress displaying as a top entry in the activity log, but there is no such display
- Conclusion: reindex job doesn't seem to have run
- Tried to reindex a different exhibit to make sure the behavior is not isolated to a single exhibit: https://exhibits.stanford.edu/secret-service
- Verified that reindexing doesn't work for this exhibit either

**This is a high-priority, time sensitive issue due to the fact that the Wong team needs to publish their exhibit on Wednesday morning, 5 October.**

**Comment by cbeer** [comment]
I gave redis a kick. I didn't see anything wrong with it, but that must have unjammed something.

**Comment by caaster** [comment]
This is happening again where exhibits are not reindexing. This is not an emergency but it it is definitely high priority to resolve.

**Comment by corylown** [comment]
Restarting redis resolved the issue, although redis was up and appeared to be responding normally. Chris also increased the log level so we have a chance of identifying a cause if it happens again.

**Comment by caaster** [comment]
This is happening again where exhibits are not reindexing. This is not an emergency but it it is definitely high priority to resolve. This time the behavior I see is different. Even though I see the blue dialog bar that items are reindexing after I push the reindex button, the bar eventually disappears and I do not see a reindex job logged on the dashboard. Reported by an exhibit creator who is trying to reindex to see metadata corrections reflected in her exhibit, which has not happened so far.

**Comment by corylown** [comment]
@caaster is this resolved? I haven't seen any reports of issues with re-indexing in a while.

**Comment by caaster** [comment]
I haven't received any reports of this behavior since 24 October. Therefore, closing this ticket.

**Comment by laurensorensen** [comment]
This same issue has resurfaced, am not able to re-index the Virtual Tribunals exhibit - here is a screenshot of the error I get. I also couldn't add an asset / druid from SDR. 

<img width="872" alt="Screen Shot 2023-01-11 at 5 52 44 PM" src="https://user-images.githubusercontent.com/3269689/211957060-b6c410d5-e73f-48a0-8985-5bcc584f5688.png">


When I click on "failed" this report comes up: 

`Spotlight::ReindexExhibitJob a4b94bb6
×
Failed about 3 hours ago in less than a minute

Message	Details
1	job started	January 11, 2023 14:37
2	job created by lsorens@stanford.edu	
3	wrong number of arguments (given 1, expected 0)	
{
  "backtrace": "/opt/app/exhibits/exhibits/shared/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/core_ext/object/blank.rb:18:in `blank?'\n/opt/app/exhibits/exhibits/shared/bundle/ruby/3.1.0/gems/blacklight-spotlight-3.5.0.2/app/models/spotlight/solr_document_sidecar.rb:105:in `reject'\n/opt/app/exhibits/exhibits/shared/bundle/ruby/3.1.0/gems/blacklight-spotlight-3.5.0.2/app/models/spotlight/solr_document_sidecar.rb:105:in `convert_stored_value_to_solr'\n/opt/app/exhibits/exhibits/shared/bundle/ruby/3.1.0/gems/blacklight-spotlight-3.5.0.2/app/models/spotlight/solr_document_sidecar.rb:68:in `block in custom_fields_data_to_solr'\n/opt/app/exhibits/exhibits/shared/bundle/ruby/3.1.0/gems/blacklight-spotlight-3.5.0.2/app/models/spotlight/solr_document_sidecar.rb:64:in `each'",
  "resource_id": 25269
}
4	wrong number of arguments (given 1, expected 0)	
{
  "backtrace": "/opt/app/exhibits/exhibits/shared/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/core_ext/object/blank.rb:18:in `blank?'\n/opt/app/exhibits/exhibits/shared/bundle/ruby/3.1.0/gems/blacklight-spotlight-3.5.0.2/app/models/spotlight/solr_document_sidecar.rb:105:in `reject'\n/opt/app/exhibits/exhibits/shared/bundle/ruby/3.1.0/gems/blacklight-spotlight-3.5.0.2/app/models/spotlight/solr_document_sidecar.rb:105:in `convert_stored_value_to_solr'\n/opt/app/exhibits/exhibits/shared/bundle/ruby/3.1.0/gems/blacklight-spotlight-3.5.0.2/app/models/spotlight/solr_document_sidecar.rb:68:in `block in custom_fields_data_to_solr'\n/opt/app/exhibits/exhibits/shared/bundle/ruby/3.1.0/gems/blacklight-spotlight-3.5.0.2/app/models/spotlight/solr_document_sidecar.rb:64:in `each'",
  "resource_id": 25266
}
5	wrong number of arguments (given 1, expected 0)	
{
  "backtrace": "/opt/app/exhibits/exhibits/shared/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/core_ext/object/blank.rb:18:in `blank?'\n/opt/app/exhibits/exhibits/shared/bundle/ruby/3.1.0/gems/blacklight-spotlight-3.5.0.2/app/models/spotlight/solr_document_sidecar.rb:105:in `reject'\n/opt/app/exhibits/exhibits/shared/bundle/ruby/3.1.0/gems/blacklight-spotlight-3.5.0.2/app/models/spotlight/solr_document_sidecar.rb:105:in `convert_stored_value_to_solr'\n/opt/app/exhibits/exhibits/shared/bundle/ruby/3.1.0/gems/blacklight-spotlight-3.5.0.2/app/models/spotlight/solr_document_sidecar.rb:68:in `block in custom_fields_data_to_solr'\n/opt/app/exhibits/exhibits/shared/bundle/ruby/3.1.0/gems/blacklight-spotlight-3.5.0.2/app/models/spotlight/solr_document_sidecar.rb:64:in `each'",
  "resource_id": 25270
}
6	wrong number of arguments (given 1, expected 0)	
{
  "backtrace": "/opt/app/exhibits/exhibits/shared/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/core_ext/object/blank.rb:18:in `blank?'\n/opt/app/exhibits/exhibits/shared/bundle/ruby/3.1.0/gems/blacklight-spotlight-3.5.0.2/app/models/spotlight/solr_document_sidecar.rb:105:in `reject'\n/opt/app/exhibits/exhibits/shared/bundle/ruby/3.1.0/gems/blacklight-spotlight-3.5.0.2/app/models/spotlight/solr_document_sidecar.rb:105:in `convert_stored_value_to_solr'\n/opt/app/exhibits/exhibits/shared/bundle/ruby/3.1.0/gems/blacklight-spotlight-3.5.0.2/app/models/spotlight/solr_document_sidecar.rb:68:in `block in custom_fields_data_to_solr'\n/opt/app/exhibits/exhibits/shared/bundle/ruby/3.1.0/gems/blacklight-spotlight-3.5.0.2/app/models/spotlight/solr_document_sidecar.rb:64:in `each'",
  "resource_id": 25270
}
7	wrong number of arguments (given 1, expected 0)	
{
  "backtrace": "/opt/app/exhibits/exhibits/shared/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/core_ext/object/blank.rb:18:in `blank?'\n/opt/app/exhibits/exhibits/shared/bundle/ruby/3.1.0/gems/blacklight-spotlight-3.5.0.2/app/models/spotlight/solr_document_sidecar.rb:105:in `reject'\n/opt/app/exhibits/exhibits/shared/bundle/ruby/3.1.0/gems/blacklight-spotlight-3.5.0.2/app/models/spotlight/solr_document_sidecar.rb:105:in `convert_stored_value_to_solr'\n/opt/app/exhibits/exhibits/shared/bundle/ruby/3.1.0/gems/blacklight-spotlight-3.5.0.2/app/models/spotlight/solr_document_sidecar.rb:68:in `block in custom_fields_data_to_solr'\n/opt/app/exhibits/exhibits/shared/bundle/ruby/3.1.0/gems/blacklight-spotlight-3.5.0.2/app/models/spotlight/solr_document_sidecar.rb:64:in `each'",
  "resource_id": 25267
}
8	wrong number of arguments (given 1, expected 0)	
{
  "backtrace": "/opt/app/exhibits/exhibits/shared/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/core_ext/object/blank.rb:18:in `blank?'\n/opt/app/exhibits/exhibits/shared/bundle/ruby/3.1.0/gems/blacklight-spotlight-3.5.0.2/app/models/spotlight/solr_document_sidecar.rb:105:in `reject'\n/opt/app/exhibits/exhibits/shared/bundle/ruby/3.1.0/gems/blacklight-spotlight-3.5.0.2/app/models/spotlight/solr_document_sidecar.rb:105:in `convert_stored_value_to_solr'\n/opt/app/exhibits/exhibits/shared/bundle/ruby/3.1.0/gems/blacklight-spotlight-3.5.0.2/app/models/spotlight/solr_document_sidecar.rb:68:in `block in custom_fields_data_to_solr'\n/opt/app/exhibits/exhibits/shared/bundle/ruby/3.1.0/gems/blacklight-spotlight-3.5.0.2/app/models/spotlight/solr_document_sidecar.rb:64:in `each'",
  "resource_id": 25268
}
9	processed 0 / 6	
10	job failed	January 11, 2023 14:37`

**Comment by jcoyne** [comment]
@laurensorensen that looks like a different, and new problem. Would you mind creating a new issue for that?

**Comment by laurensorensen** [comment]
Thanks @jcoyne - here is the new ticket: https://github.com/sul-dlss/exhibits/issues/2265
