### ISSUE TITLE
Searchbox on Exhibits home is (unintentionally) transparent

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#2244]
Not sure if this is something unique to my system or not, but at some point recently I noticed that the searchbox on the Exhibits landing page is being displayed as transparent, making it hard to see what you are entering in the input field:

<img width="534" alt="Screen Shot 2022-10-14 at 11 57 27 AM" src="https://user-images.githubusercontent.com/101482/195956836-a34f6d0e-b58b-47f8-ac9b-6fa682de50a8.png">

I see the same thing in Firefox and Chrome so assume it isn't just me, but I guess we can figure it out if someone else sees what they get at https://exhibits.stanford.edu/

**Comment by marlo-longley** [comment]
@ggeisler I am seeing the same transparent box.

**Comment by corylown** [comment]
This appears to happen only when the `feature_flags.exhibits_index` is set to `true`. If `exhibits_index` is set to `false` the search box appears correctly: 

![Image](https://user-images.githubusercontent.com/458247/208774750-8a57ee7f-77aa-490d-9351-09f958dd4dc6.png)

I'm also wondering whether it's expected that the search/submit button disappears when this feature is set?
