### ISSUE TITLE
[exhibits/prod] Slack::Web::Api::Errors::InvalidAuth: invalid_auth

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/exhibits#2258]
## Backtrace

    line 13 of [PROJECT_ROOT]/app/models/exhibit_bot.rb: message
    line 9 of [PROJECT_ROOT]/app/models/exhibit_bot.rb: message
    line 7 of [PROJECT_ROOT]/app/jobs/send_publish_state_change_notification_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49092/faults/88709185)

**Comment by corylown** [comment]
If we don't care about these notifications we could remove this features.

**Comment by jcoyne** [comment]
@caaster does care about this.  See #2300

**Comment by corylown** [comment]
Closed via #2300
