### ISSUE TITLE
For exhibits with translations: title, subtitle & top nav toolbar labels are not displaying translated terms

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2269]
I am currently doing a pre-pub review of the German translation for the [Say Their Names](https://exhibits.stanford.edu/de/saytheirnames/home) exhibit. In doing this, I discovered that for all translated exhibits, the following translated items are not displaying:

- Exhibit title
- Exhibit subtitle
- Top nav toolbar labels (home, about, etc.)

I see this in Chrome, Safari and Firefox on my Mac.

**Comment by corylown** [comment]
The masthead translations seem to break with this dependency update commit: https://github.com/sul-dlss/exhibits/pull/2202/files
