### ISSUE TITLE
Evaluate the design and behavior of IIIF drag/drop icon link

### ISSUE THREAD

**Issue by corylown** [sul-dlss/exhibits#2293]
The IIIF icon that appears below the lower right corner of the sul-embed viewer in exhibits is intended to serve as a way to drag and drop the IIIF resource into a viewer.

Currently when you click on this link it takes you to [a SUL web page](https://library.stanford.edu/projects/international-image-interoperability-framework/viewers) with some information about IIIF. This page also include a video tutorial about how to use drag and drop links to IIIF resources in Mirador and provides a link to the Stanford Mirador app instance that has been replaced by Mise. We should evaluate this page as well as the IIIF icon implementation for currency and accuracy and make any changes needed.

<img width="672" alt="Screenshot 2023-02-22 at 4 53 59 PM" src="https://user-images.githubusercontent.com/458247/220769681-37a2d4d7-a5ea-42b0-92f6-9626d5b5b527.png">

Relates to https://github.com/sul-dlss/dlme/issues/1355

**Comment by cbeer** [comment]
ref: https://github.com/sul-dlss/exhibits/issues/679

**Comment by corylown** [comment]
@caaster I don't mind closing this. The page itself has been reviewed and the work to create a new video is captured elsewhere -- in Jira: https://jirasul.stanford.edu/jira/browse/WEB5-64
