### ISSUE TITLE
Can we remove the site_sidebar that is currently not used?

### ISSUE THREAD

**Issue by corylown** [sul-dlss/exhibits#2323]
It's behind a feature flag. If we're not going back we could remove it.

https://github.com/sul-dlss/exhibits/blob/6fbae9c200cc152b0f7bca72043fd2dc48c2713c/app/views/shared/_site_sidebar.html.erb#LL1C1-L1C1

**Comment by dnoneill** [comment]
Assuming I am reading this correctly this was closed by https://github.com/sul-dlss/exhibits/commit/a2debee6fd33c2727532f4f68b07be43a02e4d9a

**Comment by jcoyne** [comment]
That's right.
