### ISSUE TITLE
Update "More at Stanford" links on main exhibits page to coincide with new library website launch

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2325]
(Updated by Sarah: Can be completed with other url updates rolling out Monday, July 31st.)

Change the links under the _More at Stanford_ dropdown on https://exhibits.stanford.edu/ so that they go to the correct pages on the new library website or other location (SW) as indicated.

![Screen Shot 2023-06-06 at 9 50 29 AM](https://github.com/sul-dlss/exhibits/assets/3210225/aa376f72-5880-4c89-91a0-2d4363a72571)

- Other library collections at Stanford - change existing link text (https://library.stanford.edu/collections) to: Explore library collections at Stanford - new link: https://library.stanford.edu/explore-collections
- Special Collections & University Archives (current link: https://library.stanford.edu/spc) - new link: https://library-prod.stanford.edu/libraries/special-collections
- Giving to Stanford Libraries - change existing link text (https://library.stanford.edu/department/library-communications-and-development) to: Support the Stanford Libraries - new link: https://library.stanford.edu/support-stanford-libraries

**Comment by saseestone** [comment]
Related to: https://github.com/sul-dlss/SearchWorks/issues/3344, https://github.com/sul-dlss/mylibrary/issues/891, https://github.com/sul-dlss/SearchWorks/issues/3346
