### ISSUE TITLE
Grant Lauren admin perms for exhibits

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2341]
Please grant @laurensorensen administrative permissions for exhibits.stanford.edu (same as my perms). As a member of the Spotlight service team, when she serves as a backup for me she will need these perms to assist exhibit creators. Thank you.

**Comment by cbeer** [comment]
I believe this is managed by the Stanford workgroup `dlss:exhibits-admin`? I think you, as the workgroup administrator, need to add Lauren to that group (and perhaps add her as a workgroup admin too?)

**Comment by caaster** [comment]
New info to me (or I forgot) - thank you so much, Chris. I'll take care of it!
