### ISSUE TITLE
Blank genre value showing up in facets

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/exhibits#2352]
Hello! In this [sandbox exhibit](https://exhibits.stanford.edu/lauren-s-sandbox/), I added a few druids and some have multiple genre attributes (form1.value and form2.value) and some only list one. After adding these items, in the Genre facet within the exhibit, there is a blank value that shows up (see screenshot). @arcadiafalcone took a look at the data, confirmed the data looks ok, and suggested it may be a bug. 

<img width="348" alt="Screenshot 2023-09-18 at 5 17 43 PM" src="https://github.com/sul-dlss/exhibits/assets/3269689/43e71981-275e-4af2-bfb8-f6bee7dca543">

**Comment by jcoyne** [comment]
It looks like there's a value of one blank space in those records:
```
        "id":"np784my6780",
        "collection":["cc853cn9643"],
        "collection_with_title":["cc853cn9643-|-Reviews of the Yokohama Class B and Class C war crime trials by the U.S. Eighth Army Judge Advocate, 1946-1949"],
        "format_main_ssim":["Book"],
        "url_suppl":["https://purl.stanford.edu/cc853cn9643"],
        "genre_ssim":["Posttrial records", " "],
```

**Comment by jcoyne** [comment]
<img width="472" alt="Screenshot 2023-09-19 at 2 51 39 PM" src="https://github.com/sul-dlss/exhibits/assets/92044/20abfcbd-e2bc-4974-afab-1a3cb6003b14">

In the cocina this looks like an empty extra object in the `description.form`

**Comment by laurensorensen** [comment]
I actually don't have cc853cn9643 in the sandbox. That one is a collection druid. 

I'll check the others for a space character in the form1.value or form2.value

**Comment by jcoyne** [comment]
This one is in the sandbox: https://argo.stanford.edu/view/zg893jk3553. 
<img width="243" alt="Screenshot 2023-09-19 at 3 11 28 PM" src="https://github.com/sul-dlss/exhibits/assets/92044/b3b9f686-6439-4b97-bd0d-0966ebc36ee2">

**Comment by laurensorensen** [comment]
I think I see what happened. I put a value in form2.type (genre) and no value in form2.value. 

As a user of cocina, this would be a strong wish-list item to allow a user like me to be able to have a value in *.type ignored if there's not value in *.value. Especially when there are a ton of rows, it is a major headache to have to keep filtering to make sure there are no associated types... 

Thanks for the help!

**Comment by jcoyne** [comment]
@laurensorensen That's certainly understandable, but the exhibits software doesn't use cocina, so you'd want to direct that request towards sul-dlss/argo  (or somewhere else?)

**Comment by laurensorensen** [comment]
@arcadiafalcone @andrewjbtw I don't know if this above feedback is helpful or a known issue, but I would be happy to make a ticket if it is! I have a lot of cocina wish list items at this point :)

**Comment by andrewjbtw** [comment]
I think what you're requesting is what's supposed to happen and there's a bug in how the spreadsheet gets processed. I can investigate and ticket in Argo.

**Comment by laurensorensen** [comment]
Closing this as it's being moved to a ticket in Argo now.
