### ISSUE TITLE
Change the default label for spotlight_upload_date_tesim

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2355]
There are currently 2 metadata facets listed on the metadata config page for each exhibit with the default label of "Date". This is confusing for exhibit creators and the service team/service manager. @justin submitted a PR https://github.com/sul-dlss/exhibits/pull/2354 to make the change from the label of "Date" to "Uploaded date" for spotlight_upload_date_tesim, after discussion on slack: https://stanfordlib.slack.com/archives/C060ZTZRV/p1695657449118049.

My biggest concern is about any potential elbow effects when this change would be implemented to prod. Is there a way to find out which exhibit (or exhibits) are using spotlight_upload_date_tesim? We want to make sure that this change would not override any custom label choice made for that exhibit(s) -- for that specific facet.

Also, is it true that when deployed to prod, any exhibit that had changes saved to metadata configuration would NOT display the name change "Uploaded date" -- but any exhibits that never had changes saved to metadata configuration WOULD display the name change "Uploaded date"?

It is true (tested in stage) that any new exhibit stub created would display the name change "Uploaded date".

**Comment by caaster** [comment]
It also turns out there are 2 metadata facets listed on the metadata config page for each exhibit with the default label of "Description". We also need a new label to differentiate these, and the same issues as above also apply.

**Comment by corylown** [comment]
Work in progress here: https://github.com/sul-dlss/exhibits/pull/2354

**Comment by corylown** [comment]
- Changing the default label will not impact any custom labels.
- Exhibits that have saved any custom metadata configurations will continue to show the original or custom label. In both cases the field would display "Restore default," which if clicked will apply the new default label.
- Exhibits that have not saved any custom metadata configurations will show the new default label.

**Comment by corylown** [comment]
I'm not sure that Upload Date is an appropriate field name for `spotlight_upload_date_tesim`. This appears to be a free text field for storing a date for uploaded items. It is NOT the date the item was uploaded.

For the duplicate "Description" fields. One is for adding a description to uploaded items and the other is where MODS abstracts are stored.

**Comment by corylown** [comment]
After discussion with @caaster and the team on 10/21/2024 we think this issue may be resolved by whatever the solution for https://github.com/sul-dlss/exhibits/issues/2602 ends up being.
