### ISSUE TITLE
Thumbnail image "squished" horizontally when uploaded into Browse category 

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/exhibits#2361]
I am finding that when I try and upload a rectangular image, instead of the image being slightly cropped on upload, the image gets "squished" (to use a technical term) horizontally.  This is for browse category images in Spotlight. Below is a screenshot of the image in normal view in Gimp at the bottom, and then the resulting image in Spotlight thumbnail above that. Thanks for any help! 
<img width="762" alt="Screenshot 2023-10-09 at 5 05 33 PM" src="https://github.com/sul-dlss/exhibits/assets/3269689/62750e68-a995-47d1-a8c4-4d56f7a485e1">

**Comment by laurensorensen** [comment]
Also want to note that the original file uploaded is 1.2 megabytes in JPEG format, in case that helps.

**Comment by marlo-longley** [comment]
Hi @laurensorensen, can you please provide a link to the page where you see this?

**Comment by laurensorensen** [comment]
https://exhibits.stanford.edu/virtual-tribunals/browse

Only Vogel and Goebell have this issue.

**Comment by laurensorensen** [comment]
All right, @marlo-longley assisted me with this and the issue appears to be that the image needs to be exactly 4:3 aspect ratio, otherwise the image will be altered upon upload if the box extends beyond the boundaries of the in-app Spotlight crop tool. I'll add this to the Spotlight documentation after running it by @caaster. 

However, as a user, it would be great to get some sort of warning about this happening upon save, and also worth considering that if someone isn't very proficient in image editing or technical aspects like aspect ratio, this could still be an impediment for them uploading an image which fits.

**Comment by marlo-longley** [comment]
Great, I'm glad these particular images were able to look correct when published. I will close this ticket and look out for any future discussion on image editing in Spotlight.
