### ISSUE TITLE
Blank facet in Virtual Tribunals exhibit

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/exhibits#2362]
Hello again! There is a blank facet in the Virtual Tribunals exhibit sidebar. It appears to be the place where "Date range" once was, which applies to to all collections in VT (Nuremberg has dates included). I checked both instances where Date is included in the Metadata section of the exhibit dashboard, made sure they were checked, but Date Range still isn't showing up.
<img width="499" alt="Screenshot 2023-10-10 at 10 10 12 AM" src="https://github.com/sul-dlss/exhibits/assets/3269689/b31c00e5-bd1b-4ec8-a2e2-3eb43239ad22">

**Comment by jcoyne** [comment]
@laurensorensen Can you report the URL of the page you are looking at that shows the blank facet title? I don't see it here: https://virtualtribunals.stanford.edu/nuremberg?f%5Bresource_type%5D%5B%5D=Official+court+transcripts

**Comment by jcoyne** [comment]
The first step was to revert the prod deploy to `v2.1.29`. I suspect there is a problem in the blacklight release in #2358 that broke the range limit.

**Comment by laurensorensen** [comment]
I don't know if this impacts your work, but a heads up that I made some cocina updates, so going to run re-indexing on the exhibit right now.

**Comment by laurensorensen** [comment]
Also, Date Range is now back! Thanks!
