### ISSUE TITLE
Bug in using uploaded image for a browse category in https://exhibits.stanford.edu/stanford-aapi #1563

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2364]
The exhibit creator reported being unable to upload an image from her desktop to https://exhibits.stanford.edu/stanford-aapi for the browse category thumbnail for Audio visual materials.

I investigated and found:

- When I first looked at the browse categories for this exhibit, I simply saw the default grey image that appears when a thumbnail image has not been uploaded -- for the Audio visual materials category only.
- The exhibit creator shared the thumbnail image she had tried to upload previously - this a 106 KB jpeg:
![origins](https://github.com/sul-dlss/exhibits/assets/3210225/62379d04-b18d-4567-822d-30f261cb8cc0)
- I tried to upload the image to the Audio visual browse category, adjusted the crop, and clicked "Save"
- I saw no error message, but this is what I now see for that browse category:
![Screen Shot 2023-10-13 at 11 08 30 AM](https://github.com/sul-dlss/exhibits/assets/3210225/05ca730c-48d9-4448-8b2c-f9d3551c12ee)
- Next, I went to this test exhibit of mine: https://exhibits.stanford.edu/cathy-test-exhibit
- There was no image for the browse category "all items", so I tried to upload the same image jpeg shown above that the exhibit creator of the AAPI exhibit shared with me. Voila! Success!
![Screen Shot 2023-10-13 at 11 13 03 AM](https://github.com/sul-dlss/exhibits/assets/3210225/db10dafe-ffed-4f40-bd49-194571345fdc)
- Please note that the ability to change the image for the AAPI browse category Audio visual is now frozen. I am unable to either upload a different image, or even to select an image to use that is in the exhibit.

**Comment by cbeer** [comment]
I tried to recreate this and had no trouble changing the thumbnail image. I noticed the previous browse category image was pointing at an exhibit item, so maybe it's possible the exhibit builder didn't toggle the image source?:
 
![Screenshot 2023-10-16 at 08 33 19](https://github.com/sul-dlss/exhibits/assets/111218/07541f1a-4ccd-4b94-815c-d3873bdc1673)
