### ISSUE TITLE
Ability to reindex an exhibit keeps throwing an error

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2367]
Please see this slack thread for extensive discussion: https://stanfordlib.slack.com/archives/C060ZTZRV/p1697668783858809

I am meeting with an exhibit creator soon about their reindexing problem (another stakeholder who is not referenced in the thread above). Prior to the meeting I thought I'd better try to reindex another test exhibit to make sure it is working. I tried to reindex this: https://exhibits.stanford.edu/service-sandbox which resulted in this error:

![Screen Shot 2023-10-19 at 1 52 09 PM](https://github.com/sul-dlss/exhibits/assets/3210225/c73812a8-0acb-452e-a53c-93eac8072514)

This is critical Exhibits functionality that needs to work. Thank you.

**Comment by corylown** [comment]
I'm seeing in the logs:
```
Oct 19 13:51:42 exhibits-worker-prod-a sidekiq[2873046]: 2023-10-19T20:51:42.434Z pid=2873046 tid=1mory class=Spotlight::ReindexJob jid=c9842cd958d14d0d0d8aa169 ERROR: Caught exception Tried to load unspecified class: IIIF::OrderedHash
```

**Comment by caaster** [comment]
Once I realized that a IIIF resource was in this test exhibit, this morning I reindexed a couple of additional test exhibits and had 100% success. So this reindexing problem appears to be isolated to IIIF only. We have IIIF resources in only a few exhibits (~3-4?), so this makes this reindexing problem less impactful -- especially if we discover it is perhaps isolated to this single IIIF resource?

**Comment by caaster** [comment]
@jcoyne reports: I think this may just have been old data in the database.  I cleared out that sidecar and re-indexed it from the manifest and I think its’ working now.

**Comment by jcoyne** [comment]
I fixed this one sidecar by doing the following:
```
sidecar = Spotlight::SolrDocumentSidecar.find_by(exhibit_id: 128, resource_id: 25244)
sidecar.update_column(:data, {})

exhibit = Spotlight::Exhibit.find(128)
data = Spotlight::Resources::IiifService.parse('https://gallica.bnf.fr/iiif/ark:/12148/btv1b550020492/manifest.json').first
data.to_solr(exhibit: exhibit)
```
