### ISSUE TITLE
Need reindexing help for: https://exhibits.stanford.edu/publicsyncopations

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2370]
I'm working with Nathan Coy to support his creation of this exhibit: https://exhibits.stanford.edu/publicsyncopations, which has not yet been published. 

We discovered that sometime in the past when adding new druids to the add item list, Nathan overwrote the existing list with a short list of new items. 

The items that are now no longer displaying in the add items list need to be added back to the exhibit. 

So, Nathan found the full list of druids that should be in the exhibit. I wanted to see if it was possible to add the missing items back to the add item list, so I attempted this with a single druid: bb858fm5011. 

After I added the druid, I then hit the reindex button and here is what happened:

![Screen Shot 2023-11-02 at 2 16 25 PM](https://github.com/sul-dlss/exhibits/assets/3210225/9c31de0e-7aaa-404c-9357-691a6bc7c195)

Is there a way to add back all of the druids currently in the exhibit to the item list? The full list (which includes the few still in the item list) is below:

bb858fm5011
bc255qx0156
bc394wn3514
bc819tb5038
bd931nh8993
bj607sm9913
bj967gq2832
bk370sj9010
bk378bv5672
bp307bz5648
bq295wz4543
bs031px2198
bt751nt1375
bw557jt2919
by326qv2779
cb572gn3852
cb832rs0719
cc869jf9364
cf398gn7751
cj005fj1701
ck899pw4276
cp778dc2764
cr998mz4336
cw081fx3945
db819qn9659
dc418px1255
dj129xy2947
dk016fb5757
dk756bt0073
dq094bg8773
dr780xw1981
ds114fm4046
dv309wd3769
dv576dw7537
dw674fq4281
dy145jc5638
dz345cj0463
dz736pz5691
fb652gc0117
fc033gz9064
fg375wn0081
fm209df9824
fm994rf5517
fp664hy2368
fq703zh2969
fq941xn6281
ft669pp5260
fv672ds3920
gd140wm2407
gg872jm7499
gp237zr9118
gr477nf1185
gt209qm2738
gt980tm6117
gx109gk1524
gx207dr1046
gy090dc2970
hb500df7172
hf666tv3911
hg050wy8038
hh422pg2351
hj314ph9601
hm279ys2987
hm719ms8434
hn602jf4616
hp144ft9440
hp322qv2153
hq330tk8674
hr203sd7338
hr573dc0983
ht688pf0720
hw186dj5377
hw294fp1414
hz234hd6411
hz935zf0704
jg979yf5651
jh180wx7148
js900wd2516
jw105cy5676
jw839th3844
jy025qt0636
jz107km4572
kb059dd1986
kf190hc9172
kh047tz1263
kj600sr8100
kk698fx4922
km969mx7928
ks765nj2744
kt877vt7158
kz989ng1824
mb249nv9897
md886wy1499
mh210zz5730
mk227gb7123
mk523dz1808
mn681nj1836
mp114jv1760
mq238xr3459
mq804vc7921
ms955cz2563
mt478vx7305
nb079cq7405
nm222hn3828
np247yd9041
ns730by8940
ns799gb2710
nv132hw6093
nx693sv2920
pb680qc3758
pc999kw9012
pf236kp5349
pf525rb8128
pf820xj2743
pg674vj8783
pg895sv5031
pj970gf8197
pm625hm3734
pn089yv7031
pr100hm3695
pt242qb9470
pw121zm7756
pw755jb1712
py497tz3368
qf003fd7074
qk854gg1940
qq753px2166
qr221gf1430
qr772zq0289
qt765jq6140
qw969ws8315
qy163wv3520
rb414vn4061
rg122zd1900
rg793yq4926
rj484vp5606
rr470dc5175
rs416hz1325
rt142vs5043
rt362hw8705
rv794pz2968
sc530mt9122
sf203bt0910
sf950yh5298
sh471yn0336
sj081qf3865
sm265xm9833
sm494rk1104
sp569jf7353
sr505dy4599
sv877hn2553
sz311mz7625
tb256gp3547
tc936pb8207
td965wt0972
tg899rs2314
tj289gp9328
tj850kz1745
tm635qp5674
tn560xw7880
tp461sz3344
tq565qb1919
tq978mg3846
tt282jy5483
ty699zn6004
tz633dd9575
tz759km5536
vb021hq4254
vd062zv8170
vd330ty8776
vf237pt8163
vf555jr4127
vg384fg0467
vg518mh7872
vn510ht2227
vq296dj8531
vr814qy7007
vs074vf8239
vs106tz6373
vx191zf2361
vz091nn7645
vz118kd7029
wb388sd9042
wb708yt7567
wc811xq0870
wf199fw7915
wg666nk1599
wh520wq7193
wm475gc5289
wn613tv9458
wn918bz6973
wq297ts4009
wq426dw1687
wq603bd9852
wr330yq5195
ws550tb0448
wv636bb1625
wz277fp0484
xb495ph2372
xf150my4761
xf436sr7289
xj288bw9099
xm839rb5958
xn433wg3172
xr102ws1534
xs938hv0979
xt359rz2715
xw435zt8082
xy119bg8065
xy691ry8981
xz590rv2087
yc410qw4273
yg955pf1459
yg978zw7930
yk459hb2000
yp049kd3463
yq015cr1227
yq158nd0287
yq882py1918
yr532tz6572
yr917zm0191
yt258bc3453
yt456hk8509
yw357py4567
yx875mc6123
yx914rb0069
yx990cr2474
yy969kk8123
yz027dd8591
zd816xr8746
zn384rv9428
zq214gs8200
zr477kv2702
zt684gp0733
zt822mf6378
zw050ms3751
zx532rn4148
zy420rk7198

**Comment by cbeer** [comment]
There was some bad data in one of the uploaded exhibit items (and, weirdly, an exhibit specific item that was shared by 2 different exhibits?). I remediated that uploaded item and the exhibit indexed successfully.

**Comment by caaster** [comment]
Hi @cbeer - thank you for tracking down the reindexing error. A problem still remains. The list of druids I provided above were mistakenly removed from the exhibit item list when Nathan added new items at some point. How do we properly add all of the druids back to the list? Will a copy and paste do it, or is there anything else we need to watch out for?

**Comment by cbeer** [comment]
Copy + paste seems fine to me. Did that not work?

**Comment by caaster** [comment]
I thought that would work, but when I tried it for one druid as I explained above, that threw the error I described. That is why I am double checking with you.

**Comment by caaster** [comment]
@cbeer I am still confused. So, the reindex job message says that 240 items were reindexed. There are only 238 druids in the exhibit item list (Nathan tells me these are all individual druids), AND even more confusingly, when I do an exhibit search there are 247 results.

**Comment by cbeer** [comment]
There's 1 uploaded item, and 8 druids not explicitly on the list you provided:
< gw704vc2606
< hr136pv7795
< jy265qb4339
< kg592sw2233
< kw561sk9574
< nn610qf4480
< nw298wx6333
< qc723sg0724

It looks like these were briefly added to the exhibit yesterday, probably when data from `test-public-syncopations` was imported, which does contain those druids.

**Comment by caaster** [comment]
@cbeer I don't understand your reply. Please let me know when you might have time for a quick huddle. I hope with a quick conversation we can get to the bottom of the discrepancies. Many thanks.
