### ISSUE TITLE
[exhibits/prod] I18n::InvalidLocale: "es?q=ariz" is not a valid locale

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/exhibits#2373]
## Backtrace
[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49092/faults/100329278)

From e.g. https://exhibits.stanford.edu/es, the "find exhibit by title" dropdown doesn't work:
<img width="592" alt="Screenshot 2023-11-16 at 07 37 12" src="https://github.com/sul-dlss/exhibits/assets/111218/93a29379-9e84-43ea-b82b-c7d694b2b1d2">

**Comment by marlo-longley** [comment]
![Image](https://github.com/user-attachments/assets/6a63388f-4b37-46dc-aece-fc0625be0804)


If you typeURL generated for this query directly into the search bar (`https://exhibits.stanford.edu/exhibit_finder?locale=es?q=a`) the browser redirects you to `https://library-status.stanford.edu/` -- the route page does not exist. Find out why...
