### ISSUE TITLE
Searching within categories not working in Virtual Tribunals

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/exhibits#2377]
Within the [Asia-Pacific collection](https://exhibits.stanford.edu/virtual-tribunals/feature/world-war-ii-u-s-army-courts-asia-pacific) recently added to Virtual Tribunals exhibit, the "search within this browse category" isn't working correctly. 
The link below is an example where the search for Shigemaru Odeishi results in 7 results but none of those 7 results has Shigemaru Odeishi mentioned anywhere. And there exist in the collection documents in which Shigemaru Odeishi is in the title field. 
Additionally, there are instances wherein a search within a browse category shows results from outside the browse category (saved search). Oddly, the also recently added collection pertaining to Europe does not seem to have the same errors re: search within browse categories 
https://exhibits.stanford.edu/virtual-tribunals/browse/reviews-of-yokohama-class-b-and-class-c-war-crimes-trials?q=Shigemaru+OdeishiUUID9541c066-bddf-4171-9668-da3e969eafd8

Another example of search within Browse category failing in Asia-Pacific collection recently added to VT. All 7 item results from a "Volume 3" search are from outside the browse category that was created for Soemu Toyoda (which this search was conducted within). They're all items from the Asia-Pacific > Yokohama Courts and Cases browse category.
https://exhibits.stanford.edu/virtual-tribunals/browse/u-s-v-soemu-toyoda?q=Volume+3UUID901f2165-3409-4e85-8c0f-1acc36d1f296

**Comment by laurensorensen** [comment]
Tried removing quotes from the saved search for Soemu Toyoda and conducting the search again. I'm finding that any search, no matter what the term results in the same 7 results outside of the saved search. I tried "Volume 3" and "defense" and same 7 results come up no matter what, and they are not in the saved search at all.

**Comment by laurensorensen** [comment]
I tried also deleting the entired saved search, re-creating it, deleting the box from the page, re-creating that. And am getting the same issue, no matter what is searched on, the same results come up, from outside the saved search.

**Comment by marlo-longley** [comment]
The Category Search feature was turned off in the past few weeks by someone on the VT team because it was broken. 
For testing purposes I have turned it back on for this single browse category: https://exhibits.stanford.edu/virtual-tribunals/searches/u-s-v-soemu-toyoda

This can be turned on/off as a logged in admin, by browsing to the exhibit, clicking Edit, and selecting this checkbox:
<img width="633" alt="Screenshot 2024-01-08 at 6 19 27 PM" src="https://github.com/sul-dlss/exhibits/assets/1328900/d7ecf789-ed4a-413b-9982-7460a678785b">

**Comment by corylown** [comment]
Our current theory is that the JSON DSL style query we're sending to Solr only works with the lucene query parser and the default query handler is set to edismax.

So...this works, with defType explicitly set to lucene:

`curl -X POST 'http://localhost:8983/solr/blacklight-core/select?debug=true&defType=lucene' -d '{"query":{"bool":{"must":[{"edismax":{"query":"melon"}}]}}}'`

And this...does not, using the default defType set in the config for the select search handler:

`curl -X POST 'http://localhost:8983/solr/blacklight-core/select?debug=true' -d '{"query":{"bool":{"must":[{"edismax":{"query":"melon"}}]}}}'`
