### ISSUE TITLE
Links to items have disappeared in search results when a "find items in all exhibits" search is conducted

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2389]
Filing this ticket based upon Andrew's exhibits feedback just received:

Hi exhibits team,

When I use the “find items in all exhibits” search, I don’t see links to the specific items that are returned in the results. This is in contrast to the links I see when I search within a specific exhibit. I see the same behavior in Firefox, Chrome, and Safari.

Below are two screenshots of what I see:

[Search with no links to items](https://exhibits.stanford.edu/search?search_field=default&q=arizona+garden):

<img width="1385" alt="image001" src="https://github.com/sul-dlss/exhibits/assets/3210225/941167af-b2ed-4cfa-953f-271ed861c7f6">

[Search with links to items](https://exhibits.stanford.edu/arizonagarden/catalog?exhibit_id=arizonagarden&search_field=search&q=arizona+garden):

<img width="1385" alt="image002" src="https://github.com/sul-dlss/exhibits/assets/3210225/90d58279-97c1-4086-b102-f4fb8edb1c20">

Apologies if this has been reported before. I checked the exhibits github repo but didn’t find an issue for this.

Andrew

**Comment by jcoyne** [comment]
This is just speculation, but is it possible this is intentional?  If an item is in more than one exhibit, we wouldn't know which page the user is trying to get to?

**Comment by corylown** [comment]
I'm thinking the same thing as @jcoyne. It's an unusual design and does at first glance seem broken, but it is one possible solution to handling an item being in more than one exhibit.

**Comment by jcoyne** [comment]
It looks like https://github.com/sul-dlss/exhibits/pull/1785 was the change that removed the header links.

**Comment by caaster** [comment]
Thank you @jcoyne and @corylown - I didn't remeber this. I will create a ticket to consider adding a dialog box for this type of search result with explanatory text, for the next work cycle. Tagging @andrewjbtw as fyi.

**Comment by andrewjbtw** [comment]
Thanks for the explanation. I see now that the links that looked to me like links to exhibits are actually links to the item in the exhibit listed. I obviously found that quite confusing.
