### ISSUE TITLE
Home page for the SFTJF exhibit is not displaying as expected

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2393]
The [home page for the SFTJF exhibit](https://exhibits.stanford.edu/sftjf) is not displaying as expected. I just stumbled across this today. 

What questions do you all have and is there anything I can do to help? This was a pet project of Mike Keller so I would value it being fixed before it is discovered by Mike or one of his jazz colleagues. Thank you.

**Comment by corylown** [comment]
@caaster looks like some of the links in that list were entered with html tags in the middle of the link text, which was generating invalid markup. I fixed it by cleaning up the links.

**Comment by caaster** [comment]
Thank you @corylown!
