### ISSUE TITLE
Add captcha to Spotlight exhibits feedback forms

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/exhibits#2411]
Hello! In the past 6 months or so, the Spotlight service team has been receiving multiple hits from bots/spam actors on various Spotlight exhibit feedback forms. This morning I was met with over 100 emails from a bot via the Parker Library exhibit. 

It seems like Captcha isn't set up for Spotlight exhibits feedback forms. I tested Virtual Tribunals and there was no Captcha when the form was submitted (I can test more exhibits if it's helpful). 

The fact that multiple users (including curators who receive feedback forms, for Parker, Ben Albritton, for example) makes it so those of us receiving the feedback have to sort through a hundred or so spam feedback emails. It makes it so viewing the actual feedback we get a big deal and more possible that we will miss the legit feedback... I have it set up to go to a folder in my email now, but even then I, as a user, still have to sort through to find the legitimate feedback. 

Setting up Captcha would be a highly desirable feature! Thank you!

**Comment by corylown** [comment]
From Slack discussion with Lauren and Cathy, this could done during a maintenance/unscheduled week.

**Comment by laurensorensen** [comment]
Just a heads up that this happened again today. Only a few spam emails this time (5 or so), not hundreds like before.

**Comment by corylown** [comment]
Fixed by #2436
