### ISSUE TITLE
Request/question from Martin Wong exhibit team re moving page content

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2448]
It would be helpful if this question (or maybe it is a task that only devs can do?) from the [Martin Wong](https://exhibits.stanford.edu/martin-wong) exhibit team could be answered by the end of this month.

The team would like to move the following pages from About to Essays (see below). Along with the move, they want to rename the "Primary Resources" page to "Resources" and have it appear at the bottom of the feature page list, followed by its child pages. To be clear, they want the pages listed _below_ Primary Resources/Resource to be turned into child pages. That would also mean that the 4 tile links on the Primary Resources/Resources feature page would need to be changed to point to the appropriate new child feature page.

[Primary Sources](https://exhibits.stanford.edu/martin-wong/about/primary-sources)
[– 1989 Martin Wong: Interview with Margo Machida](https://exhibits.stanford.edu/martin-wong/about/1989-martin-wong-interview-with-margo-machida)
[– 1991 SFAI Lecture Series: Martin Wong](https://exhibits.stanford.edu/martin-wong/about/1991-sfai-lecture-series-martin-wong)
[– 1998 Martin Wong Portrait by Charlie Ahearn](https://exhibits.stanford.edu/martin-wong/about/1998-martin-wong-portrait-by-charlie-ahearn)
[– 2021 Gary Ware: Interview with Marci Kwon](https://exhibits.stanford.edu/martin-wong/about/2021-gary-ware-interview-with-marci-kwon)
[– 2021 Gary Ware: Interview with Marci Kwon, pt. 2](https://exhibits.stanford.edu/martin-wong/about/2021-gary-ware-interview-with-marci-kwon-pt-2)
[– 2021 Gary Ware: Interview with Marci Kwon, pt. 3](https://exhibits.stanford.edu/martin-wong/about/2021-gary-ware-interview-with-marci-kwon-pt-3)
[– 2021 Gary Ware: Interview with Marci Kwon, pt. 4](https://exhibits.stanford.edu/martin-wong/about/2021-gary-ware-interview-with-marci-kwon-pt-4)
[– 2021 Gary Ware: Interview with Marci Kwon, pt. 5](https://exhibits.stanford.edu/martin-wong/about/2021-gary-ware-interview-with-marci-kwon-pt-5)
[– 2021 Gary Ware: Interview with Marci Kwon, pt. 6](https://exhibits.stanford.edu/martin-wong/about/2021-gary-ware-interview-with-marci-kwon-pt-6)

The question is, is there a way to make these changes without the team having to recreate the content on each About page to be able to move the content over to Feature pages?

**Comment by taylor-steve** [comment]
@corylown and I looked at this. It is possible for a dev to convert the pages from 'about' to 'feature'. After that, the exhibit creator could organize them and rename them in the dashboard. We'd likely want to coordinate a time to do this.

**Comment by caaster** [comment]
@corylown I am meeting with the Martin Wong exhibit creator on Tuesday, 23 July starting at 8:00 am PT. If the list of pages provided in this ticket can be moved from About to Feature just before 8:00 am on the 23rd that would be most helpful. Thank you. I will make sure I am online on the 23rd starting at 7:30 am PT.

**Comment by corylown** [comment]
@caaster sounds good.

**Comment by corylown** [comment]
IDs of pages that need to be changed from About to Feature

```
[3700, "primary-sources"],
[3696, "1989-martin-wong-interview-with-margo-machida"],
[3692, "1991-sfai-lecture-series-martin-wong"],
[3697, "1998-martin-wong-portrait-by-charlie-ahearn"]
[3698, "2021-gary-ware-interview-with-marci-kwon"]
[3717, "2021-gary-ware-interview-with-marci-kwon-pt-2"]
[3718, "2021-gary-ware-interview-with-marci-kwon-pt-3"]
[3719, "2021-gary-ware-interview-with-marci-kwon-pt-4"]
[3720, "2021-gary-ware-interview-with-marci-kwon-pt-5"]
[3721, "2021-gary-ware-interview-with-marci-kwon-pt-6"]
```

Script to update them:
```
ids = [3700, 3696, 3692, 3697, 3698, 3717, 3718, 3719, 3720, 3721]

ids.each do |id|
  page = Spotlight::Page.find(id)
  page.becomes!(Spotlight::FeaturePage)
  page.save!
end
```
