### ISSUE TITLE
Thumbnails no longer displaying for (non-SDR) uploaded image content on Panofsky exhibit

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2449]
This morning when touring Alan around the intricacies of Exhibits, I stumbled across the fact that thumbnails are no longer displaying in list view or gallery view for all images in the [Panofsky exhibit](https://github.com/sul-dlss/exhibits/issues/2448). I expect thumbnails to display. These are all uploaded images (not in the SDR). All images do display on the item view pages.

**Comment by jcoyne** [comment]
@caaster I don't think the "Panofsky exhibit" link is going to the correct place.

**Comment by caaster** [comment]
@jcoyne please try: https://exhibits.stanford.edu/panofsky-papers/browse/all-exhibit-items

**Comment by corylown** [comment]
@caaster it looks like the Solr documents for these items are missing fields that are required for the thumbnails to work. I could try re-indexing the items in this collection to see if that fixes the issue. Do we need to check with the exhibit creator before I do that?

**Comment by corylown** [comment]
A freshly indexed uploaded looks like this in Solr:

```
 {
        "spotlight_resource_id_ssim":["gid://exhibits/Spotlight::Resources::Upload/6982"],
        "spotlight_resource_type_ssim":["spotlight/resources/uploads"],
        "id":"107-6982",
        "exhibit_external-iiif-and-upload-images-test-august-2019_public_bsi":[true],
        "spotlight_exhibit_slug_external-iiif-and-upload-images-test-august-2019_bsi":[true],
        "spotlight_exhibit_slugs_ssim":["external-iiif-and-upload-images-test-august-2019"],
        "spotlight_full_image_width_ssm":["849"],
        "spotlight_full_image_height_ssm":["595"],
        "thumbnail_url_ssm":["/images/4508-78b64b9e702f6d2e0c12708c96211cae/full/!400,400/0/default.jpg"],
        "iiif_manifest_url_ssi":"/external-iiif-and-upload-images-test-august-2019/catalog/107-6982/manifest",
        "thumbnail_square_url_ssm":["/images/4508/square/100,100/0/default.jpg"],
        "large_image_url_ssm":["/images/4508/full/!1000,1000/0/default.jpg"],
        "_version_":1804196786138513408,
        "last_updated":"2024-07-10T12:55:36Z",
        "created":"2024-07-10T12:55:36Z",
        "timestamp":"2024-07-10T12:55:36.681Z"}]
  }
```

Whereas an image from the Panofsky exhibit where the thumbnails are missing (such as the one found by querying `exhibits-prod/query?q=id:165-25625&q.op=OR&indent=true&fl=*`) the `thumbnail_url_ssm` and `thumbnail_square_url_ssm` fields (as well as the other image related fields.)

**Comment by caaster** [comment]
@corylown there is no need to contact the exhibit creator before reindexing. This is because there are no SDR items in the exhibit. If there would have been SDR items in the exhibit, then I would always need to ask the creator. This is because a reindex pulls in all new MD for any exhibit items, and all new items (that may have incomplete MD) if a collection druid has been added to the exhibit.

**Comment by corylown** [comment]
@caaster reindexing fixed the thumbnail display issue for _most_ of the items in this collection. However, there are four items where image processing is failing that will require more investigation.

**Comment by caaster** [comment]
Thank you for this update @corylown - mysterious.

**Comment by corylown** [comment]
The four images that failed to re-index were larger than could be processed by the image software on the server. I reduced the size of the images somewhat, re-uploaded them and now all the items in this exhibit have thumbnails.
