### ISSUE TITLE
Only first instance of Item Embed widget (using SDR items) displays on page

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#245]
Moved from https://github.com/projectblacklight/spotlight/issues/1150

If you include more than one Item Embed widget using SDR items on a single page, it appears that the first widget is shown correctly, but the images for the second one are not. It looks like the images are not included in the generated HTML. 

![tem-embed-problem](https://cloud.githubusercontent.com/assets/101482/7574699/2cd49434-f7e4-11e4-8017-83ae70c8172c.png)

**Comment by mjgiarlo** [comment]
Chatted with @jkeck and @aeschylus on Slack today. A related ticket linked to the Media work cycle may resolve this for us by changing the way the embed service works: https://github.com/sul-dlss/sul-embed/issues/600

See also the related discussion that happened on an earlier version of this ticket in the Spotlight repo: https://github.com/projectblacklight/spotlight/issues/1150#issuecomment-101059460

We may want to punt on this ticket and return to it when sul-dlss/sul-embed#600 is closed and available via embed.stanford.edu. Thoughts, @cbeer & @ggeisler?

**Comment by ggeisler** [comment]
Sounds good to me.

**Comment by jkeck** [comment]
FWIW, we have shipped the update to embed that returns an iframe as the HTML payload.

**Comment by jkeck** [comment]
Closing this issue as we've addressed it in Embed.  If this pops up again, we can re-open or create a new one.
