### ISSUE TITLE
Questions re: adding MD for uploaded items (World in the Making exhibit)

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2450]
**Exhibit creator question**:

For the [World in the Making](https://exhibits.stanford.edu/a-world-in-the-making) exhibit, we’re wondering if you can offer advice on how to provide adequate bibliographic metadata to images which are being uploaded from local image files. Specifically, we’d like to include information such as “Author”, “Publisher”, “Date”, etc., but the available fields for the uploaded images seem to reflect permissions-related metadata like “Attribution”.
 
Here is an example of an image in the exhibit we would like to include “Author” within a field, but are not sure where it would be appropriate to add: https://exhibits.stanford.edu/a-world-in-the-making/catalog/316-70648

**Cathy’s background/info/questions**:

1.	For uploaded images, my understanding is that the MD needs to be added at the time of image upload, on the Items > Upload items > Upload item tab or on the Items > Upload items > Upload multiple items tab.

2.	For the Upload item tab, it is very strange to me that I see 2 different displays. For the World in the Making exhibit, I see:

 
![Screen Shot 2024-07-11 at 10 18 13 AM](https://github.com/sul-dlss/exhibits/assets/3210225/905f9840-b38d-4c3d-b435-6babff0fddc1)

3.	Yet, in this example – the [Service Team Sandbox](https://exhibits.stanford.edu/service-sandbox/resources/new) – for the Upload item tab I see this (the list of greyed-out fields is truncated in the screenshot):

 
![Screen Shot 2024-07-11 at 10 22 39 AM](https://github.com/sul-dlss/exhibits/assets/3210225/672c41e8-6381-46e1-9c50-1187b17931fb)

I think this may have something to do with selected exhibit customizations we have allowed in the past?

4.	I then reminded myself of the MD that was uploaded in bulk (multiple items) by the Panofsky exhibit creator. Here is an [example](https://exhibits.stanford.edu/panofsky-papers/catalog/165-25625). Unfortunately, the exhibit was created over 5 years ago so I don’t recall the MD upload details. But – when I download the CSV template under the Upload multiple items tab for this exhibit, I see: 

url,spotlight_upload_title_tesim,spotlight_upload_description_tesim,spotlight_upload_attribution_tesim,spotlight_upload_date_tesim,type_tesim,creator_tesim,format_tesim,other-number_tesim,relation_tesim

This is clearly NOT the default CSV but a modified one. The default CSV is:

url,spotlight_upload_title_tesim,spotlight_upload_description_tesim,spotlight_upload_attribution_tesim,spotlight_upload_date_tesim

Therefore, this makes me wonder if it is ok to alter the CSV template, and if there are any guidelines for doing so?

5.	Another question. Is the Multiple item upload the only way a creator can add additional MD? How do they add MD after the fact, as in this use case for World in the Making?

6.	@corylown, to your point about the Metadata configuration menu, that is for configuring the display of MD that has already been added to an exhibit.

7.	I believe there are limitations to MD facet display for uploaded items. My understanding is that while all MD is indexed for search, the only facets that will display are facets for uploaded items that would be displayed for SDR items. See this Panofsky example.

![Screen Shot 2024-07-11 at 10 42 25 AM](https://github.com/sul-dlss/exhibits/assets/3210225/5943ff12-af79-4c46-862e-097afafb3aaa)

8.	Last but not least, I think Chris knows a whole lot about all of this.

**Comment by corylown** [comment]
@caaster I think my note during today's (7/11) stand-up is accurate, that to add custom metadata fields to uploaded items you have to first add those fields to the list of "Exhibit-specific fields" that are at the very bottom of the page below where you can set the display and order of standard metadata fields. Once the fields exist then they will be available on new uploads, when editing already uploaded items, or in the bulk upload csv.

Exhibit specific fields I added to a test exhibit on stage:
<img width="888" alt="Screenshot 2024-07-11 at 5 01 35 PM" src="https://github.com/sul-dlss/exhibits/assets/458247/70fe7d3e-a9a7-41ca-814c-af74eb95e571">

The Edit view for an already uploaded item:
<img width="1155" alt="Screenshot 2024-07-11 at 5 03 39 PM" src="https://github.com/sul-dlss/exhibits/assets/458247/85802a4a-54d1-4675-ace6-fdc5fd1cd974">

And the CSV template also now includes the additional fields:
```
url,spotlight_upload_title_tesim,spotlight_upload_description_tesim,spotlight_upload_attribution_tesim,spotlight_upload_date_tesim,my-new-field_tesim,my-other-new-field_tesim 
```

See note on exhibit-specific fields: https://exhibits.stanford.edu/exhibits-documentation/feature/metadata

> You can create additional, exhibit-specific metadata fields to be associated with the items in your exhibit. Exhibit-specific fields can be managed (e.g., displayed or hidden on pages, display label changed, reordered) in the same way as other metadata fields as described above. Exhibit creators can populate these exhibit-specific fields with metadata by editing the Item Details pages for the items (see below).
> 
> Please note however, you can't limit your search to just exhibit-specific fields (you can only search against them by searching "everything"), which means they have limited utility in creating saved searches and browse categories.

Happy to review this and discuss in more detail in post stand-up or a separate meeting/huddle.

**Comment by caaster** [comment]
Thank you so much @corylown - you are right about that! And I was wrong. I'll let you know if I have questions.
