### ISSUE TITLE
Add a "restore default" option for each metadata field in the Dashboard > Metadata section

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/exhibits#2486]
If a user/exhibit creator goes into a Spotlight exhibit dashboard and to the metadata section, there is listed a wide assortment of fields. The names of these fields can be altered one-by-one (see screenshot below) 
<img width="368" alt="Screenshot 2024-07-18 at 4 33 21 PM" src="https://github.com/user-attachments/assets/f25ae4d4-f9bc-40a6-9c65-9f34f7d82707">

However, once the user/exhibit admin changes it, there is no "undo" button, and they have no idea what the original field name was in the beginning. Having a "restore default" button (or similar) for each field would be enormously helpful to those of us working on exhibits with many different metadata fields.

**Comment by caaster** [comment]
Here is a screenshot of the "restore default" option that is available for main menu items. 
![Screen Shot 2024-07-18 at 5 01 42 PM](https://github.com/user-attachments/assets/3e988645-e12e-4e55-9de4-c89ac940bc41)

**Comment by taylor-steve** [comment]
Let's do this in Spotlight if it makes sense.

**Comment by marlo-longley** [comment]
I created https://github.com/projectblacklight/spotlight/issues/3126 to track the upstream work.

**Comment by marlo-longley** [comment]
Closed by https://github.com/projectblacklight/spotlight/issues/3126
