### ISSUE TITLE
Help text needed to explain to users what advanced search features are available

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2487]
Expected behavior

Provide help text to let users know what advanced search features are available to them, with an explanation of Boolean searching which is enabled. For implementation, use whatever help text feature is a11y compliant.

**Comment by alundgard** [comment]
Here's the design specification and mockups.

- Add a `(i) Search tips` button to the left of the searchbox.
- Clicking this button opens a modal containing the following text.
```
Search tips
Refine your search
- Use quotation marks to search as a phrase. (Word-stemming will still be applied to words within the phrase.)
- Use "+" (no space) before a word to make it required.
- Use "-" (no space) before a word or phrase to exclude.
- Use "OR", "AND", and "NOT" (uppercase) to create Boolean logic within a field. You can use parentheses in your complex expressions.
- Use "*" to search a truncated term. (Word-stemming is done automatically.)
- Use "?" as a wildcard to replace a character in a word.
- Word-stemming automatically includes plural and singular forms, and common suffix and tense variations.
```

Note: this is the same text that appears under the [SearchWorks Advanced Search tips](https://searchworks.stanford.edu/advanced) (excluding the first 3 tips).

For design and styling, see the Figma File: https://www.figma.com/design/zaK3bvWYhO5Mg55utHQl8g/Exhibits?node-id=242-1422.

![Image](https://github.com/user-attachments/assets/dbce802b-fa71-4590-a481-2927f1c19b00)

**Comment by dnoneill** [comment]
Is this something that is only ever going to be in exhibits or is it something we would want in other apps?

**Comment by caaster** [comment]
We do have a version of this in SearchWorks, under [Advanced search](https://searchworks.stanford.edu/advanced) -- which we discussed as background/context during planning over the summer in order to spec this ticket.

**Comment by alundgard** [comment]
I think it's possible this could appear in other apps, but which apps is TBD. For example, [EarthWorks](https://earthworks.stanford.edu) appears to afford these search capabilities. Other apps may have the more comprehensive [Advanced Search](https://searchworks.stanford.edu/advanced) page and options, like in SearchWorks.
