### ISSUE TITLE
Create multiple selection drop down for Configuration > General > Tag list

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2492]
The values in the Configuration > General > Tag list field populate the tags used for filtering on the Exhibits landing page. We have a small set of tags used on the landing page, which we don't want to add to randomly. Although it infrequently happens, an exhibit administrator can inadvertently mess up our carefully considered set of exhibit tags by adding new tags to their exhibit. When this happens we have no way of knowing about it unless someone happens to see the extra tags on the Exhibits landing page and reports it.

To remedy this situation we need the tags available on the Exhibits landing page to be available as a multiple selection drop down.

**Comment by corylown** [comment]
![Image](https://github.com/user-attachments/assets/4e095a63-7d3c-4514-a3a2-2e4f98b0b04b)

**Comment by corylown** [comment]
Prior work: https://github.com/projectblacklight/spotlight/pull/1422

**Comment by dnoneill** [comment]
PR to get this into exhibits, github isn't working again: https://github.com/sul-dlss/exhibits/compare/tag-list?expand=1
