### ISSUE TITLE
Create field for display of all creators/contributors with their roles

### ISSUE THREAD

**Issue by corylown** [sul-dlss/exhibits#2506]
- Keep existing `author_corp_display`, `author_meeting_display`, `author_person_display`, `author_person_full_display` fields for compatibility with existing exhibits.
- New field could be named `contributor_display` or `creator_contributor_display`
- It may be desirable to store the name/role information as JSON so the display can be modified by the app if needed (without reindexing).
- Role strings should be normalized (downcase, strip leading and trailing punctuation and spaces) and then sentence-cased for display.
- Should include personal and non-personal names (don't exclude corporate and meeting names, etc.).
- Names should display in order of first appearance. If a name occurs more than once in the source metadata it should display only once with each role listed in parentheses. Some names will not have any role specified and may be displayed without a role. Example from https://purl.stanford.edu/yr455dn2133.xml:
`Creators/Contributors: Schumann, Robert, 1810-1856; Hewlett, Walter B. (Donor); Rice, Condoleezza, 1954- (Dedicatee)`

**Comment by alundgard** [comment]
Here are design mockups for the new `Creators/Contributors` field with their roles.
Figma File: https://www.figma.com/design/zaK3bvWYhO5Mg55utHQl8g/Exhibits?node-id=357-2156

<img width="3136" alt="Creators Contributors Field - Example 1" src="https://github.com/user-attachments/assets/2d6ce608-c00b-40bb-8bd8-82c28abe54b2">

<img width="3136" alt="Creators Contributors Field - Example 2" src="https://github.com/user-attachments/assets/bae75ad9-675b-4554-852d-e2515cd29dbe">
