### ISSUE TITLE
Convert to setting SECRET_KEY_BASE in the env via puppet

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/exhibits#2512]
Rails 7.2 no longer supports secrets.yml (stored in shared configs)

**Comment by corylown** [comment]
Completed via:

- https://github.com/sul-dlss/exhibits/pull/2515
- https://github.com/sul-dlss/exhibits/pull/2514
- https://github.com/sul-dlss/shared_configs/pull/2239
- https://github.com/sul-dlss/puppet/pull/11184
