### ISSUE TITLE
Problem with available search facets: https://exhibits.stanford.edu/mednarratives

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2518]
I just did a pre-pub review today with the exhibit creator for: https://exhibits.stanford.edu/mednarratives

I discovered he had made a mistake in the way that he added items to the exhibit. He failed to follow the instructions to add items, which states "When adding new items to an exhibit with existing items, do not remove the existing druids from the list." Instead, he added 17 separate batches of druids, and each time he added a new batch he deleted the existing druids from the list. 

This happened once long ago by a different exhibit creator for a different exhibit. At that time, when I checked in with Chris, he told me to make sure the creator added all of the druids back to the add items list asap. 

So, this time I asked the creator for Medical Narratives to add all of the druids back to the item list. He has done so.

However, both before and after he added the items back, I noticed the following exhibit anomaly that needs to be corrected:

The available search facet list is incomplete:
![Screen Shot 2024-08-22 at 4 41 00 PM](https://github.com/user-attachments/assets/dce21a70-5629-48c5-a198-a862e6c9aefe)

I don't know if this issue is related or unrelated to the way that the creator was incorrectly adding items to the exhibit.

**Comment by corylown** [comment]
@caaster can you give an example or two of facet fields that you expect to see but are missing for this exhibit?

**Comment by caaster** [comment]
I created this issue due to my misunderstanding of how facets are populated, so this is no longer a problem. Closing.
