### ISSUE TITLE
Date range facet is displaying for Medical Narratives exhibit and it should not be

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2519]
The date range facet is displaying for the following exhibit: https://exhibits.stanford.edu/mednarratives and it should not be. The content in the exhibit has no date metadata.

Cory has investigated and he states:

I know why the date range facet is showing up for the Medical Narratives exhibit. It's an icky bug that has probably always been present, but will only show up in cases where an exhibit has 0 items with values in the pub_year_tisim field. We could (1) try to fix it for real, or I think I could (2) "fix" it for this exhibit by turning the date range facet off for this exhibit via the console. It sounded like we were probably going to remove the date range limit controls because of accessibility concerns so I'm not sure spending time fixing this for real is time well spent. What do you think?

I replied that I vote for option 2.

Cory says: the good news is is that with option 2 if they add date metadata the facet control for the date range field will appear in the admin interface and they'd be able to turn the facet back on if they wanted without developer intervention.

**Comment by corylown** [comment]
The basics of the bug are:

Spotlight exhibit configurations for facets rely on the assumption the facets don't display if there are no values present. The administrator controls to turn a facet off don't display unless there are values for the particular facet field. This assumption is not true for the blacklight range limit date facet that always renders no matter if values are present or not.

**Comment by corylown** [comment]
@caaster the date range facet is now turned off via configuration for the Medical Narratives exhibit:

https://exhibits.stanford.edu/mednarratives/catalog?exhibit_id=mednarratives&search_field=search&q=
<img width="713" alt="Screenshot 2024-08-23 at 5 34 10 PM" src="https://github.com/user-attachments/assets/1e33e444-5c2a-4d86-9220-c2594f40f36d">
