### ISSUE TITLE
Create hierarchical facet category for roles

### ISSUE THREAD

**Issue by alundgard** [sul-dlss/exhibits#2527]
Related to #2506 and #2526.

Add a new facet category called `Role` which is hierarchical, similar to the `Workflows (WPS)` hierarchical facet found in [Argo](https://argo.stanford.edu/).

The Role facet should contain toggleable subgroups for each role, indicated by a `+` icon to expand (or a `-` icon to collapse). Toggling a subgroup (e.g., “Curator”) opens a sublist of Creator/Contributor names (e.g., “Baker, Clint” and “Smith, Hal (Drummer)”). Unlike the [new Creators/Contributors display field](https://github.com/sul-dlss/exhibits/issues/2506), do not include the names' corresponding roles in parentheses.

Figma File: https://www.figma.com/design/zaK3bvWYhO5Mg55utHQl8g/Exhibits?node-id=509-20951

![Role Hierarchical Facet](https://github.com/user-attachments/assets/cad44862-1cc5-490f-8d83-4f055846c457)

**Comment by taylor-steve** [comment]
This may have already been done in a similar fashion in vt-arclight and earthworks. Worth checking if it can be re-used?
