### ISSUE TITLE
Remove or disable analytics provider link

### ISSUE THREAD

**Issue by taylor-steve** [sul-dlss/exhibits#2546]
Reported by @caaster:

> Hi All, An exhibit creator has stepped on a confusing issue. With the new version of exhibits, the admin dashboard > analytics now contains a new message with a clickable link. I just spoke with a creator who clicked on that link and proceeded down a Github rabbit hole that was totally confusing and unnecessary. Can we either remove the message that displays, or disable the link? (Until we re-enable Google Analytics, of course.)

![Screen Shot 2024-09-13 at 11 31 13 AM](https://github.com/user-attachments/assets/e4df6f52-96bd-456b-81e1-17e3f6118e3b)

**Comment by corylown** [comment]
Link to analytics is gone:
![Image](https://github.com/user-attachments/assets/76a35d07-5855-4034-bce7-9bec5c1ded95)
