### ISSUE TITLE
Remove "shpc" documents from Solr index

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#255]
We've deleted the exhibit with the slug `shpc` from -prod but when we create a new exhibit with the same slug, that exhibit includes the items from the previous version of the exhibit. This is a problem because the reason for recreating the exhibit is to start from scratch with no items.

I think what we need is for the Solr index to be updated so that:

1. Items associated **only** with the `shpc` exhibit are removed
2. Items associated with `shpc` and one or more other exhibits are not removed but are disassociated with `shpc` 

I don't know for certain that there are items that fall into the second case, but if there are, we don't want to remove them completely because the other exhibit(s) still needs to include them.

**Comment by atz** [comment]
In production exhibits index, I find:
```xml
<lst name="spotlight_exhibit_slug_shpc_bsi">
  <str name="type">boolean</str>
  <str name="schema">I-S-M----OF-----l</str>
  <str name="dynamicBase">*_bsi</str>
  <int name="docs">993</int>
</lst>
```

Meaning SHPC has 993 docs (or former docs) indexed.  The same number is returned from query `spotlight_exhibit_slug_shpc_bsi:*`.   That is the only `slug_shpc` field.  

The total 34 "slug" fields (w/ document counts) are:
```
potlight_exhibit_slug_another-exhibit_bsi 1
spotlight_exhibit_slug_beasts_bsi 51
spotlight_exhibit_slug_becoming-stanford_bsi 20
spotlight_exhibit_slug_branner_bsi 2
spotlight_exhibit_slug_california-as-an-island_bsi 725
spotlight_exhibit_slug_classics-papyri_bsi 45
spotlight_exhibit_slug_data_bsi 45
spotlight_exhibit_slug_david-rumsey-map-collection_bsi 160
spotlight_exhibit_slug_digital-bookplates_bsi 773
spotlight_exhibit_slug_doris-test_bsi 0
spotlight_exhibit_slug_feigenbaum_bsi 27896
spotlight_exhibit_slug_fitch_bsi 4387
spotlight_exhibit_slug_hanna-house-collection_bsi 1655
spotlight_exhibit_slug_hanna-house_bsi 22
spotlight_exhibit_slug_harrison_bsi 344
spotlight_exhibit_slug_heckrotte_bsi 204
spotlight_exhibit_slug_herbert-matter_bsi 296
spotlight_exhibit_slug_humanities-design_bsi 1
spotlight_exhibit_slug_maps-of-africa_bsi 496
spotlight_exhibit_slug_menuez_bsi 8344
spotlight_exhibit_slug_mlm-test_bsi 0
spotlight_exhibit_slug_mss_bsi 346
spotlight_exhibit_slug_muybridge_bsi 4
spotlight_exhibit_slug_rare-music_bsi 124
spotlight_exhibit_slug_reid-dennis_bsi 61
spotlight_exhibit_slug_renaissance-exploration_bsi 643
spotlight_exhibit_slug_shpc_bsi 993
spotlight_exhibit_slug_stanford-band_bsi 51
spotlight_exhibit_slug_stanford-stories_bsi 1169
spotlight_exhibit_slug_stop-aids_bsi 1
spotlight_exhibit_slug_the-bob-fitch-photography-archive_bsi 0
spotlight_exhibit_slug_training-instance_bsi 26
spotlight_exhibit_slug_ua-maps-drawings_bsi 5624
spotlight_exhibit_slug_undergraduate-theses_bsi 42
```

So I can construct a fairly ornate query that finds the intersection of `spotlight_exhibit_slug_shpc_bsi:* AND (slug_2:* OR slug_3:* OR ...)` or I can process 993 docs looking for other slug fields.  

Since the use case (delete/purge a collection) is common, it should now be apparent that this indexing strategy was a limiting choice.  I don't see what the impediment would be to converting to a multi-valued field and using the slug string instead of an undetermined number of boolean fields.  Essentially, `spotlight_exhibit_slugs_ssim:['undergraduate-theses', 'humanities-design']`.  This should be pursued for long term viability.  Importantly, we can begin indexing such a field immediately and cut away from the boolean fields at a later time.

**Comment by atz** [comment]
Note the fields seem to be defined incorrectly.   In the schema line: 
```xml
<str name="schema">I-S-M----OF-----l</str>
```
The `M` means multi-valued.  But in Hydra's dynamic schema namespace `_bsi` should be Boolean, stored, indexed, i.e. single-valued.  So something is off.  Certainly we don't get any benefit from repeating `[true, true, true, true]`, and even less from allowing `[true, true, true, false]`!

**Comment by atz** [comment]
There doesn't appear to be any overlap based on the query:
```
/solr/exhibits_prod/select?defType=edismax&q.alt=spotlight_exhibit_slug_shpc_bsi:true AND (spotlight_exhibit_slug_another-exhibit_bsi:true OR spotlight_exhibit_slug_beasts_bsi:true OR spotlight_exhibit_slug_becoming-stanford_bsi:true OR spotlight_exhibit_slug_branner_bsi:true OR spotlight_exhibit_slug_california-as-an-island_bsi:true OR spotlight_exhibit_slug_classics-papyri_bsi:true OR spotlight_exhibit_slug_data_bsi:true OR spotlight_exhibit_slug_david-rumsey-map-collection_bsi:true OR spotlight_exhibit_slug_digital-bookplates_bsi:true OR spotlight_exhibit_slug_feigenbaum_bsi:true OR spotlight_exhibit_slug_fitch_bsi:true OR spotlight_exhibit_slug_hanna-house-collection_bsi:true OR spotlight_exhibit_slug_hanna-house_bsi:true OR spotlight_exhibit_slug_harrison_bsi:true OR spotlight_exhibit_slug_heckrotte_bsi:true OR spotlight_exhibit_slug_herbert-matter_bsi:true OR spotlight_exhibit_slug_humanities-design_bsi:true OR spotlight_exhibit_slug_maps-of-africa_bsi:true OR spotlight_exhibit_slug_menuez_bsi:true OR spotlight_exhibit_slug_mss_bsi:true OR spotlight_exhibit_slug_muybridge_bsi:true OR spotlight_exhibit_slug_rare-music_bsi:true OR spotlight_exhibit_slug_reid-dennis_bsi:true OR spotlight_exhibit_slug_renaissance-exploration_bsi:true OR spotlight_exhibit_slug_stanford-band_bsi:true OR spotlight_exhibit_slug_stanford-stories_bsi:true OR spotlight_exhibit_slug_stop-aids_bsi:true OR spotlight_exhibit_slug_training-instance_bsi:true OR spotlight_exhibit_slug_ua-maps-drawings_bsi:true OR spotlight_exhibit_slug_undergraduate-theses_bsi:true)&wt=json
```

I had to use eDisMax, because the standard query processor was not handling boolean clauses.  That being said, if I add the `spotlight_exhibit_slug_shpc_bsi:true` to the `OR` chain, I get the 993 docs, so I trust this execution is working.  Please confirm: that means we can delete the 993 documents in question?

**Comment by atz** [comment]
Definitely defined as multi-valued:
![screen shot 2016-07-21 at 3 38 35 pm](https://cloud.githubusercontent.com/assets/109954/17041190/404811da-4f59-11e6-88de-61cf477ba427.png)

From **schema.xml**:
```xml
<dynamicField name="*_bsi" type="boolean" stored="true" indexed="true" multiValued="true" omitNorms="true" />
```

It looks like the schema has many bespoke fields defined beyond just the old style `_search` and `_display`.  I don't recognize them, but the schema appears to be based on SearchWorks.

**Comment by atz** [comment]
It looks like Spotlight has this correct, so I'm wondering how far our schema may have fallen out of date:
https://github.com/projectblacklight/spotlight/blob/v0.19.1/solr_conf/conf/schema.xml#L176

```xml
<dynamicField name="*_bsi" type="boolean" stored="true" indexed="true" multiValued="false"/>
```

Exhibits doesn't have its own schema in the repo and doesn't use **shared_configs**, so there is no accounting for drift from upstream.  In fact, seems like a new install would either just rely on Solr already being setup (i.e. implicit knowledge or FAIL) or use the Spotlight schema unchanged (with unknown deviation from what is actually in production, likely FAIL).  This emphasizes a gap in our configuration management.

**Comment by atz** [comment]
Documents deleted.

**Comment by atz** [comment]
Looks like there is a dedicated gem just for solr config called [exhibits_solr_conf](https://github.com/sul-dlss/exhibits_solr_conf).  It has a schema, apparently for testing only?  That's a new one for me.  Probably not necessary to have it separate now that solr_wrapper is established.  There is also a schema in [sul-solr-configs](https://github.com/sul-dlss/sul-solr-configs/blob/master/exhibits/schema.xml) that is presumably authoritative over what is in production.  

If you think the aggregate is a maintenance headache, I'd agree with you.  In general, I don't see any value to testing one schema and running on another.  Versions of the *same* schema make sense, entirely separate (originally similar, now different in non-obvious ways) schemas do not.

**Comment by ggeisler** [comment]
The SHPC exhibit is now empty of items, which is what we want, so I'm closing this. Thanks @atz.
