### ISSUE TITLE
Duplicate bibliographies listed after using back button

### ISSUE THREAD

**Issue by corylown** [sul-dlss/exhibits#2561]
1. Go to https://parker.stanford.edu/parker/catalog/94257JYP
2. Under "This reference is found in these document bibliographies" click on "Cambridge, Corpus Christi College, MS 293: William Langland, Piers Plowman"
3. Go back to the original page using the back button
4. Notice duplicate link added for "Cambridge, Corpus Christi College, MS 293: William Langland, Piers Plowman"
5. Repeating steps 2 & 3 results in another entry each time

![Image](https://github.com/user-attachments/assets/60e04561-fc9d-4814-9df5-f9689ed697a1)

**Comment by jcoyne** [comment]
This is almost certainly due to turbo restoring a cache & then a script runs and appends a new element to the page on the load event.
