### ISSUE TITLE
Use shared_configs

### ISSUE THREAD

**Issue by atz** [sul-dlss/exhibits#257]
Configuration management affects implementation and deployment of many issues.  See #255 for **schema.xml** discussion, #219 for geonames account, #107 for merging in additional config, #253 for necessary HTTPS setting, etc.

**Comment by atz** [comment]
Created:
https://github.com/sul-dlss/shared_configs/tree/exhibits-stage
https://github.com/sul-dlss/shared_configs/tree/exhibits

**Comment by atz** [comment]
@eefahy Can you confirm this is sufficient from the config management side to convert the app to `shared_configs` model?  Any complication from configuring associated worker boxes?

**Comment by eefahy** [comment]
`exhibits-stage-*` and `exhibits-prod-*` are now using respective `shared_configs` branches
