### ISSUE TITLE
Add alt text instructions to widget introductory text

### ISSUE THREAD

**Issue by alundgard** [sul-dlss/exhibits#2581]
For [widgets with an alternative text field and decorative checkbox](https://github.com/sul-dlss/exhibits/issues/2568), append the following instructions the widget introductory text:

> For each item, please enter alternative text or appropriately check the decorative box. Guidelines for writing alt text.

Where “Guidelines for writing alt text” is a link that opens the guidelines in a new browser tab.

![Image](https://github.com/user-attachments/assets/8a473515-ff25-4914-b203-b959ef919fdd)
![Image](https://github.com/user-attachments/assets/59bbf34f-fa9a-45bc-88e0-6523f3105a93)

As the Spotlight default, link to general-purpose W3C alt text guidelines. Also, allow a custom link URL to be specified per Spotlight instance.

- [x] #2582 
- [ ] #2583

**Comment by dnoneill** [comment]
Kicking this back into ready. Needs to wait until a new release of spotlight.
