### ISSUE TITLE
Add widget instruction link to custom alt text guidelines in Exhibits

### ISSUE THREAD

**Issue by alundgard** [sul-dlss/exhibits#2583]
The “Guidelines for writing alt text” link opens the guidelines in a new browser tab.
Add customizability for institution-specific instructions, specified per Spotlight instance. For Exhibits, add Stanford’s alt text instructions: https://uit.stanford.edu/accessibility/concepts/images

**Comment by marlo-longley** [comment]
Blocked by https://github.com/sul-dlss/exhibits/issues/2582 -- the feature first needs to be first in Spotlight, then overridden in Exhibits here.

**Comment by hudajkhan** [comment]
I have set up this PR: https://github.com/projectblacklight/spotlight/pull/3188 in Spotlight to address #2582. 
If the current method is approved, overriding the link would look like the following in sir_trevor_block_overrides:
SirTrevor.Locales.en.blocks.alt_text_guidelines = $.extend(SirTrevor.Locales.en.blocks.alt_text_guidelines, {
  link_url: 'http://www.google.com'
});
