### ISSUE TITLE
Unable to change Browse category label in Rare Music exhibit

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2584]
This problem described below is somehow ringing a long-ago bell. I think there is a technical reason why this is happening, but I can't recall the specifics.

The exhibit curator made a labeling error when they created the Browse category called "Image" for https://exhibits.stanford.edu/rare-music. They meant to label the Browse category as "Images." However, when they try to edit the Browse category label from Image to Images the following error is thrown:

![Screen Shot 2024-09-27 at 10 29 57 AM](https://github.com/user-attachments/assets/763ea529-2093-423f-8f14-19c8a71c7b40)

Is it possible to change this Browse category label, and if so, can an exhibit curator do so?

**Comment by caaster** [comment]
Yes, that message reads as nonsensical to me. So it would be quite helpful to display something more clear. Let me know if we should loop Alan in here?

**Comment by corylown** [comment]
@caaster how about something like:

`The title "images" is reserved and cannot be used. Please choose a different title.`
<img width="613" alt="Screenshot 2024-09-27 at 4 36 03 PM" src="https://github.com/user-attachments/assets/5057b8d1-3124-489d-b7ca-b9e176f4e817">

**Comment by caaster** [comment]
@corylown perfect. Thank you.
