### ISSUE TITLE
Analytics data appearing for one exhibit that is for a different exhibit

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2592]
Amy Hodge reports:

The second most popular page is not in my exhibit (https://exhibits.stanford.edu/data), which seems odd. It's the one for Data Visualization and the Modern Imagination - Spotlight at Stanford at https://exhibits.stanford.edu/dataviz. Thanks.

![Screen Shot 2024-10-01 at 2 04 25 PM](https://github.com/user-attachments/assets/73ea57de-99a3-415b-b837-a47dc23ea3a4)

**Comment by dnoneill** [comment]
@caaster dataviz looks to be a separate exhibit which has it's own analytics dashboard: https://exhibits.stanford.edu/dataviz/dashboard/analytics
