### ISSUE TITLE
Breadcrumbs missing from bulk update page

### ISSUE THREAD

**Issue by corylown** [sul-dlss/exhibits#2595]
All the other admin pages show breadcrumbs except for `https://exhibits.stanford.edu/EXHIBIT_SLUG/bulk_updates/edit`
Bulk update page:
<img width="515" alt="Screenshot 2024-10-04 at 3 37 34 PM" src="https://github.com/user-attachments/assets/62129681-b959-47e0-8335-303e888997d4">

Feature page:
<img width="525" alt="Screenshot 2024-10-04 at 3 37 44 PM" src="https://github.com/user-attachments/assets/ea532390-753b-4d15-8ab9-52fd5bffbf49">

**Comment by dnoneill** [comment]
This is actually a spotlight bug.
