### ISSUE TITLE
Investigation: is there a way to streamline or more clearly display the metadata configuration

### ISSUE THREAD

**Issue by corylown** [sul-dlss/exhibits#2602]
This issue is in reference to this page: `https://exhibits.stanford.edu/{EXHIBIT_SLUG}/metadata_configuration/edit`
<img width="862" alt="Screenshot 2024-10-09 at 4 27 33 PM" src="https://github.com/user-attachments/assets/247435ef-0c6e-4a34-96ee-27637d8cc293">

From https://github.com/sul-dlss/exhibits/issues/2356
> The page is not currently user-friendly for exhibit creators. Is it true or not true that some metadata fields are custom & available only to selected exhibits, while others are universally available?

- Get a better understanding of when/why fields appear in this list?
- Is there a better way to organize the list?
- Are there fields displayed here that we could not display for some exhibits? How would we know not to display them?

**Comment by hudajkhan** [comment]
Happy to start on this, and happy to collaborate as well so please feel free to add yourself as an assignee

**Comment by hudajkhan** [comment]
Inspecting the HTML elements on the exhibits page appear to have the actual Solr field related to a fieldname within hidden inputs or in the id of the input. Based on what I can see in Solr and what is in the html, here is the mapping between the input field names and the Solr fields they represent. (List in progress)

- Inline Map: geographic_srpt
- Title: title_full_display
- Alternate title: title_variant_display
- Author: author_person_full_display
- Author (no Collectors): author_no_collector_ssim
- Editor: editor_ssim
- Collector: collector_ssim
- Corporate author: author_corp_display
- Meeting author: author_meeting_display
- Publisher: publisher_ssim
- Description: summary_display
- Topic: topic_display
- Subject: subject_other_display
- Language: language
- Physical description: physical
- Publication info:pub_display
- Date: date_ssim
- Place created: place_created_ssim
- Imprint: imprint_display
- Genre: genre_ssim
- Series: series_ssi
- Box: box_ssi
- Folder: folder_ssi
- Folder name:
- Identifier:
- Location:
- Repository:
- Donor tags:
- Document subtype:
- Volume:
- Pages:
- DOI:
- Issue:
- Edition:
- University:
- Degree Type:
- Book Title:
- Reference type:
- Notes:
- Collection:
- Dimensions:
- Provenance:
- Incipit:
- Table of contents: 
- Manuscript number:
- Section:
- Manuscript:
- Sample matches in document text: 
- Description:
- Attribution:
- Date: spotlight_upload_date_tesim
- Exhibit tags:
- Creators/Contributors:

**Comment by hudajkhan** [comment]
I am in the process of seeing how to query the Solr index for the indexed fields.  Of the fields above, 35 are indexed while the rest are not.  The rest are stored which means we will be able to see their values but we cannot query for examples where they exist.

Taking a quick look at the code (specifically app/views/spotlight/metadata_configurations), it appears the fields we see on the metadata configuration field are added to/present in the blacklight configuration.  Although the form URL does seem to take into account the exhibit, the fields on the top of the page seem to be global (across all exhibits and attacked to blacklight_configuration) and the fields at the bottom of the page under "exhibit specific fields" do seem to take the actual exhibit into account (i.e. are attached to a specific exhibit).

**Comment by hudajkhan** [comment]
In querying Solr, I am looking specifically at which exhibits a particular field is associated with and how many documents in that exhibit are related.  In the process, I have found there are documents which refer to exhibits that no longer exist.  @caaster has given me a list of currently published exhibits, so I will be comparing results to that list.

**Comment by hudajkhan** [comment]
[fieldnames.xlsx](https://github.com/user-attachments/files/17496378/fieldnames.xlsx)

**Comment by hudajkhan** [comment]
Attached above are the results of running various queries in Solr in spreadsheet format.

Summary:
I took the metadata configuration page on a single exhibit page.  This list will include both global configuration as well as some exhibit specific fields.   I queried to see how many exhibits these fields were included, to determine if there are any that never show up or only show up for one exhibit.  There were no fields that never showed up, but there were a few that were only present in the Parker exhibit. 

The fields I queried for were:

<img width="408" alt="Screenshot 2024-10-23 at 12 07 12 PM" src="https://github.com/user-attachments/assets/7663a987-3977-4eaf-9784-a37cdb7bd25d">

**Comment by hudajkhan** [comment]
The fields that only showed up in the Parker exhibit were: book_title_ssim, editor_ssim, university_ssim, range_labels_ssim, and related_document_id_ssim.

**Comment by hudajkhan** [comment]
The attached spreadsheet also includes which fields are represented in which exhibits as well as the solr document count for each field in that exhibit.  The spreadsheet includes more information about what the different tabs mean.

**Comment by hudajkhan** [comment]
Looking at the code, if setting up a new spotlight app, and commenting out all the "add_index_field" and "add_show_field" lines in the catalog controller yields the following:

<img width="1045" alt="Screenshot 2024-10-23 at 3 18 05 PM" src="https://github.com/user-attachments/assets/cb2d07c5-766b-4f2c-9ed2-4c42450f7a7a">

Spotlight initializer sets up specific fields for spotlight uploads, which appear to be reflected above. Exhibit tags are neither picked up from blacklight configuration/Solr nor from Spotlight initializer, so appear for different reasons.

**Comment by hudajkhan** [comment]
Summary:
Reviewing the code and trying out Spotlight using different catalog controller configurations, we have confirmed the following:

- For the top part of the page, the code retrieves:
- - all the index (and show fields) configured in catalog controller for the application as a whole (e.g. see https://github.com/sul-dlss/exhibits/blob/main/app/controllers/catalog_controller.rb#L230)
- - any Upload Config fields that are configured in the Spotlight initializer (see https://github.com/sul-dlss/exhibits/blob/main/config/initializers/spotlight_initializer.rb#L14 ).  For reference, the Spotlight engine comes with its own out of the box set of upload config fields, and then the initializer can add to these fields  or override them (see https://github.com/projectblacklight/spotlight/blob/main/lib/spotlight/engine.rb#L145)
- -any custom fields that are added through the interface through the bottom part of the metadata configuration page.  

As an example, the Parker exhibit has both fields that have been configured through the app as well as custom fields.  

![Screenshot 2024-10-28 at 12 32 24 PM](https://github.com/user-attachments/assets/5cd254bc-3c92-467b-9ffb-a3aeb5e42c66)
In the top portion of the page (above), all the fields are displayed i.e. configured as well as custom.  This section of the page allows curators to specify the ordering (overall) of the fields and the display of the fields in any of the given views (e.g. item, slideshow).

In the bottom portion of the page, curators can add or edit custom fields. 
![Screenshot 2024-10-28 at 12 32 31 PM](https://github.com/user-attachments/assets/5098d168-1eb6-4eba-8832-87f8ddfaca74)
![Screenshot 2024-10-28 at 12 32 36 PM](https://github.com/user-attachments/assets/9abfd037-8f06-417b-b5f6-82951f1bc874)

As far as what can be captured for any of these fields, each field has its associated Solr field name and label saved.  In addition, custom fields can have a short description.  Also, the app tracks custom fields by exhibit, whereas the configured fields are available for configuration in all exhibits.
