### ISSUE TITLE
SDR content not displaying for: https://exhibits.stanford.edu/hydrosurvey

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2621]
Discovered this problem of SDR content not displaying in https://exhibits.stanford.edu/hydrosurvey during a pre-pub review yesterday with the exhibit creator. 

- I subsequently reindexed the exhibit which appears to have been successful, but the images are still not displaying. 
- I looked at a couple of the images in the SDR and I can't find a reason why the images are not displaying, but I haven't checked in with @andrewjbtw about this yet. 
- A possible clue that may or may not be relevant: this exhibit stub was created back in 2017, and SDR items were first added years ago (maybe 2022 or earlier?).

Exhibit creators would like to publish within the next couple of weeks.

**Comment by corylown** [comment]
Clearing the Stacks cookie resolved the problem: `chrome://settings/content/all?searchSubpage=stacks`
