### ISSUE TITLE
Don't display Parker specific fields on exhibits that are not Parker

### ISSUE THREAD

**Issue by corylown** [sul-dlss/exhibits#2622]

**Comment by hudajkhan** [comment]
Based on the investigation issue, here are the five fields that only show up in Parker exhibits in Solr:
https://github.com/sul-dlss/exhibits/issues/2602 
"The fields that only showed up in the Parker exhibit were: book_title_ssim, editor_ssim, university_ssim, range_labels_ssim, and related_document_id_ssim."

**Comment by corylown** [comment]
Closed by #2643
