### ISSUE TITLE
In the metadata configuration table label upload fields and exhibit-specific fields

### ISSUE THREAD

**Issue by corylown** [sul-dlss/exhibits#2623]
This will help distinguish these fields from fields for metadata from SDR. Do not label fields for SDR metadata.

**Comment by alundgard** [comment]
<img width="835" alt="Metadata table mockup - Type column" src="https://github.com/user-attachments/assets/5b9e4ed9-0829-4b7a-aa38-aeadee3620b3">

**Comment by corylown** [comment]
I don't think this is something that makes sense to include in spotlight, but we probably want to make adjustments in spotlight to make it easier for us to add this feature without overriding the whole metadata editing template.

**Comment by taylor-steve** [comment]
Cory says this might need to be components

**Comment by dnoneill** [comment]
https://github.com/sul-dlss/exhibits/issues/2602#issuecomment-2442345767
