### ISSUE TITLE
In the metadata configuration table change the "Select all" button to a checkbox labeled "All"

### ISSUE THREAD

**Issue by corylown** [sul-dlss/exhibits#2624]
This will free up space to add labels to fields as described in #2623

**Comment by alundgard** [comment]
![Metadata table mockup - Check all](https://github.com/user-attachments/assets/d2116c8e-41ed-4eff-9cfd-0a4e7f71172f)

**Comment by corylown** [comment]
This should probably be changed in spotlight. Or we should make adjustments in spotlight to make it easier for us to make this customization in exhibits.
