### ISSUE TITLE
Add Accessibility Alternative text section to Curation Dashboard

### ISSUE THREAD

**Issue by alundgard** [sul-dlss/exhibits#2628]
- Add Accessibility (H2) Alternative text (H3) section to the Curation Dashboard.
- Add statistic reporting the total number of items displayed via exhibit widgets that have entered alt text or checked the decorative box — across the entire exhibit.
- Add table displaying the number of items displayed via exhibit widgets that have entered alt text or checked the decorative box —  for each page.
- If the number of pages in the exhibit exceeds five, display a `Show all` button that expands the table to show all pages in the exhibit.

![Image](https://github.com/user-attachments/assets/2a577fb7-69ef-4e4f-971f-169b16c89bee)

**Comment by corylown** [comment]
This should be implemented in Spotlight.

**Comment by taylor-steve** [comment]
@alundgard should this new section display both "feature pages" and "about pages" or only feature pages?

**Comment by alundgard** [comment]
I think any page where it is possible to embed an image using the exhibit widgets, so both. cc @caaster

**Comment by caaster** [comment]
Yes, what @alundgard says. The home page, feature pages, and about pages

**Comment by corylown** [comment]
Closed by #3264
