### ISSUE TITLE
Determine if exhibit slug "kircher" is still reserved

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2636]
Some years ago, an exhibit stub was created with the slug `kircher`. The exhibit was later deleted because it was thought that it was no longer needed.

Turns out we need to recreate the exhibit stub & support getting the exhibit published. The preference is to be able to use the slug `kircher` if at all possible.

Please note I just created a new exhibit stub for testing with the slug `kircher-test`

**Comment by corylown** [comment]
@caaster I did not find any trace of the previous 'kircher' exhibit in the production exhibits database, so I think this slug is safe to use for this new exhibit.

**Comment by caaster** [comment]
Thank you @corylown
