### ISSUE TITLE
Alt text should not be available for Browse category, Pages, and Saved search widgets

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2640]
Alt text should not be available for Browse category, Pages, and Saved search widgets. Alan agrees that the Browse and Feature page thumbnails are considered as decorative images, as we discussed in standup on 18 Nov 2024 (Browse category thumbnails are frequently, though not always used to display a Saved search.)

Please remove alt text verbiage from the above-mentioned widgets.

In addition, of these 3 widgets, the Pages widget is the only one that also includes the ability to actually add alt text to the widget. This ability should also be removed.

**Comment by dnoneill** [comment]
Part of this is fixed in https://github.com/projectblacklight/spotlight/pull/3264. The bug where the alt text instructions were showing up where they shouldn't be is fixed with https://github.com/projectblacklight/spotlight/pull/3264
