### ISSUE TITLE
Figure out what to do with sul-exhibits-template.js.erb

### ISSUE THREAD

**Issue by taylor-steve** [sul-dlss/exhibits#2646]
`sul-exhibits-template.js.erb` won't work when we move to propshaft. We need to determine if it's in use (10 years old and I didn't see any tests in the original commit). Remove it if we don't need it, otherwise we need to come up with a more modern alternative.

**Comment by corylown** [comment]
Looks like `sul-exhibits-template.js.erb` was added here: https://github.com/sul-dlss/exhibits/commit/7f6874c207dbb45e67d43ea386e496c5bc0d10ab

Then most of the related functionality was removed in a few later pull requests, including these:

- https://github.com/sul-dlss/exhibits/pull/17/files
- https://github.com/sul-dlss/exhibits/pull/90/files

I think this is cruft that can be safely removed.
