### ISSUE TITLE
User report: JSON API broken for Copyright Renewals

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2649]
User report:

From: "Kristina Hall" <keden@hathitrust.org>

It appears your JSON API is broken for the Copyright Renewal database. We use this in our production workflow for HathiTrust copyright review and the outage has been stalling our work. Can you take a look at it please?

**Comment by corylown** [comment]
Same issue as https://github.com/sul-dlss/exhibits/issues/2647

**Comment by corylown** [comment]
Fixed by re-saving the facet configuration for the copyright renewals exhibit.
