### ISSUE TITLE
Exhibits thumbnail redesign

### ISSUE THREAD

**Issue by alundgard** [sul-dlss/exhibits#2654]
Exhibits thumbnail
- Background color: **Fog Light** `#F4F4F4` Opacity: 90%

Exhibits category (All, Art & Humanities, Social Justice, etc.)
- Background color: **Fog Light** `#F4F4F4` Opacity: 100% 
- Font weight : `600` for active selection

https://www.figma.com/design/0LTbMiP5xdL6T94nmlKDci/Exhibits-Redesign-2024?node-id=465-10235&t=WZb88CX43UyeiIJp-4
![Image](https://github.com/user-attachments/assets/e98f2543-d8b4-4599-9c2f-5d8816649a39)

**Comment by corylown** [comment]
@alundgard is it a problem that the social justice pill always has font-weight: 700 whether it's selected or not:

<img width="334" alt="Screenshot 2024-11-26 at 4 09 47 PM" src="https://github.com/user-attachments/assets/b12bee85-7b08-4ad4-9be8-2c0903b3ab87">
