### ISSUE TITLE
Some partial exhibit titles are underlined on main exhibit tile & others are not

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2662]
Why are some partial exhibit titles are underlined on main exhibit tile & others are not? This looks strange. It also seems to only be happening in Chrome (Version 131.0.6778.86 (Official Build) (arm64)), and not in Safari or Firefox.
![Screen Shot 2024-12-02 at 8 09 33 AM](https://github.com/user-attachments/assets/2efc7f3d-00b9-4b25-8fc1-882016ff57e4)

**Comment by corylown** [comment]
Now that parker is using the standard footer, the parker specific stylesheet wasn't doing much for us. I've set Parker to use the default stylesheet for now. I expect this will address this problem. It's easy to switch back if we need to for some reason, but if we no longer need the parker stylesheet we should remove it to prevent future confusion.

**Comment by corylown** [comment]
This was fixed by removing the parker-specific stylesheet that was no longer doing much.
