### ISSUE TITLE
Exhibit tags have faded-out display -- illegible/barely legible

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2666]
Reported today:

From: "Natalie Marine-Street" <njmarine@stanford.edu>

Dear DLSS: I noticed the the exhibit tags for the items in the SHS collections exhibit are appearing in a very faded out manner. I don't remember it looking like this before. Do we have a setting problem that we need to fix in our exhibit, or is there something else going on? Thanks!

![Screen Shot 2024-12-03 at 2 30 14 PM](https://github.com/user-attachments/assets/721e33a3-43aa-4282-9821-08201570165a)

**Comment by taylor-steve** [comment]
Example Link: https://exhibits.stanford.edu/shs/catalog?f%5Bexhibit_tags%5D%5B%5D=Oral+Histories&q=&search_field=search
