### ISSUE TITLE
Item totals on a11y dashboard should not be dependent upon activation of the "show all" button

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2669]
Currently, the item totals displayed on the a11y dashboard (in the first sentence) are dependent upon the default display. Once the "show all" button is clicked on, then the totals change. This should not be the case -- the totals should always be dependent upon the full list. I checked in with Alan and he concurs.

**Comment by dnoneill** [comment]
Steps to fix:
1. Replace https://github.com/projectblacklight/spotlight/blob/d8c70482d8048499cc40219d19359032dcad9a0f/app/controllers/spotlight/accessibility_controller.rb#L13C1-L14 with
      pages = @exhibit.pages.order(Arel.sql('id = 1 DESC, created_at DESC')).select { |elem| elem.content.any?(&:alt_text?) }
2. Replace https://github.com/projectblacklight/spotlight/blob/d8c70482d8048499cc40219d19359032dcad9a0f/app/controllers/spotlight/accessibility_controller.rb#L11 with `@limit = params[:show_all] ? @pages.length : 5` it will also have to be moved down.
2. Replace https://github.com/projectblacklight/spotlight/blob/d8c70482d8048499cc40219d19359032dcad9a0f/app/views/spotlight/accessibility/alt_text.html.erb#L29 with ```@pages[0..@limit].each do | page_dict |```
