### ISSUE TITLE
Request to change one exhibit slug

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2674]
Here is the background re my request. I am building a Looker studio list that leverages GA4 -- to gather high-level stats for each published exhibit. I ran into problems adding some exhibits to the Looker template yesterday, as described below. Would it be possible (see Jacob's comments) to change the slug `blrcc` to `blrcc1`?

Hi Jacob, Something strange has happened with the [Looker template](https://lookerstudio.google.com/u/0/reporting/8b40d476-0e79-4fae-93fa-122b8e9b777b/page/p_ydvl4zabnd/edit). I have successfully added almost all exhibits, except the following 6 that I added are not appearing in the Looker spreadsheet. Can you please reality check me to see if I have done something wrong? I've tried to delete and re-add them to no avail. TIA.
https://exhibits.stanford.edu/blrcc
https://exhibits.stanford.edu/crrw
https://exhibits.stanford.edu/harrison
https://exhibits.stanford.edu/activism
https://exhibits.stanford.edu/publicsyncopations
https://exhibits.stanford.edu/mednarratives

Jacob Hill
  9:25 AM
Hi Cathy, I think the problem is there is some clashing between “group values”. For example the url pattern “rr” (The First Transcontinental Railroad) is contained in the url pattern crrw (Chinese Railroad Workers). Because of this, Looker was keeping “rr” and ditching “crrw”, probably because you entered the “rr” group value before the “crrw” group value. To fix the issue, a prepended the “exhibits.stanford.edu/” portion of the url to many of the group values. This seemed to solve the problem for the most part. I still see one issue with the “blrcc”, “blrcc2”, and “blrcc3" group values. Unfortunately, prepending “[exhibits.stanford.edu/](http://exhibits.stanford.edu/)” does not solve the issue because “exhibits.stanford.edu/blrcc” is still contained in “exhibits.stanford.edu/blrcc2” and “exhibits.stanford.edu/blrcc3”. What that means is “exhibits.stanford.edu/blrcc2” and “[exhibits.stanford.edu/](http://exhibits.stanford.edu/)blrcc3” are not showing up and the “[exhibits.stanford.edu/blrcc](http://exhibits.stanford.edu/blrcc)” group is tracking statistics for “exhibits.stanford.edu/blrcc”, “[exhibits.stanford.edu/blrcc2](http://exhibits.stanford.edu/blrcc2)” and “[exhibits.stanford.edu/blrcc3](http://exhibits.stanford.edu/blrcc3)” in a single row. I can’t think of a good solution for that issue. Ideally “[exhibits.stanford.edu/blrcc](http://exhibits.stanford.edu/blrcc)” would have been called “exhibits.stanford.edu/blrcc1” to avoid clashing. You could ask the devs to change the url but you might lose historical data (I don’t know what GA will do in that case).
9:26
You may also want to prepend “exhibits.stanford.edu/” to all of the other group values to avoid future clashing.

**Comment by caaster** [comment]
P.S. If the change is possible I'll work with Jacob to snapshot GA4 for blrcc so we don't loose all that data.

**Comment by corylown** [comment]
@caaster I know nothing about Looker Studio, but I wonder if it supports regular expressions as a filters, something like `^exhibits.stanford.edu/blrcc(/.*)?$`

**Comment by caaster** [comment]
Thanks @corylown I am asking Jacob

**Comment by caaster** [comment]
Yay! Regular expressions work! Thank you @corylown
