### ISSUE TITLE
The text widget call out enabling "H1" is in fact "H2"

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2677]
Can the label be changed for the text widget call out that is labeled `H1` to correctly reflect that it is in fact, `H2`?

I'm talking about this:
![Screen Shot 2024-12-06 at 8 52 04 AM](https://github.com/user-attachments/assets/65085765-13cc-49fd-92f1-6188601c4c15)

When I use the text widget + H1 button on [this page](https://exhibits.stanford.edu/cathy-test-exhibit/feature/heading-test) and I look at the source code, it is actually an H2 and not an H1:
![Screen Shot 2024-12-06 at 8 48 35 AM](https://github.com/user-attachments/assets/dc3d0c1d-d1b1-4cc6-88bd-c879f98e5e0e)

**Comment by taylor-steve** [comment]
@alundgard @caaster What do you think about https://github.com/projectblacklight/spotlight/pull/3352 as a simple first step?

**Comment by caaster** [comment]
@taylor-steve I can absolutely live with this!
