### ISSUE TITLE
Index MODS geographic records

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/exhibits#275]
For several of the records I looked at geospatial metadata was available as bounding boxes.

Examples:

 - https://purl.stanford.edu/rh234sw2751.mods checkout the geonames.org uri
```xml
<subject>
  <geographic valueURI="http://sws.geonames.org/5350937/"/>
</subject>
```

Then use the geonames.org API to grab the bounding box:
http://api.geonames.org/get?geonameId=5350937&username=demo
```xml
<bbox>
  <west>-119.9344</west>
  <north>36.91154</north>
  <east>-119.655</east>
  <south>36.66216</south>
</bbox>
```

**Comment by atz** [comment]
The code to accomplish this is in spotlight-dor-resources and the code is complete (but not yet part of a release).  The actual reindexing has not been accomplished and probably should be regarded as a separate operational task.
