### ISSUE TITLE
Sir Trevor widget UI does not match upstream spotlight

### ISSUE THREAD

**Issue by corylown** [sul-dlss/exhibits#2775]
Saved widgets are narrower and some controls appear outside the border of the widget. The expand + button is off center. This problem does not happen in Spotlight.

Currently in exhibits:
<img width="1351" alt="Screenshot 2024-12-19 at 5 41 08 PM" src="https://github.com/user-attachments/assets/f413f1e7-50e4-488c-920d-bcab5e1f1943" />

In Spotlight:
<img width="1138" alt="Screenshot 2024-12-19 at 5 49 59 PM" src="https://github.com/user-attachments/assets/ec26afee-a05d-4a7a-b466-fb910d165827" />

**Comment by dnoneill** [comment]
@corylown Are these screenshots from main or the release-4.x branch?

**Comment by corylown** [comment]
@dnoneill these are from exhibits -- which is running release-4.x. I don't see this in either version of spotlight though.

**Comment by dnoneill** [comment]
Yeah I am seeing the same thing now that I have release-4.x running. 🤞 there is something in the branch that will help me figure out what is going on because right now I am not seeing anything wrong, except visually.

**Comment by corylown** [comment]
Seems related to https://github.com/sul-dlss/exhibits/issues/2776

**Comment by dnoneill** [comment]
It is.
