### ISSUE TITLE
Restore port 80 firewall to dor-fetcher

### ISSUE THREAD

**Issue by atz** [sul-dlss/exhibits#283]
Both prod and stage are now configured to use HTTPS with dor-fetcher.  So the previous actions to remove the port 80 firewall can now be reverted.  

Spun off from: https://github.com/sul-dlss/exhibits/issues/253

**Comment by rsmith11** [comment]
Just so I'm clear, exhibits now only needs to talk on dorfetcher-prod on 443?

**Comment by atz** [comment]
That is the assertion.

**Comment by jkeck** [comment]
@rsmith11 can you validate if there is still work left to be done for this?  Thank you much!

**Comment by jkeck** [comment]
Closing this because we're not using dor-fetcher any longer.  I have raised this issue to Ops and will let them decide if they want to take any action.
