### ISSUE TITLE
Indexing message count error

### ISSUE THREAD

**Issue by atz** [sul-dlss/exhibits#297]
It's unclear whether this is a uniform problem or a special case, but when indexing a single item, I just got the output:

```
02 Aug 18:56 Began reindexing a total of 0 items.
02 Aug 18:56 Reindexed 1 of 0 items.
```

Something is off with the counting.

**Comment by atz** [comment]
Or off by *all* error, since the total is never correctly calculated (e.g. "5 of 0 items").

**Comment by caaster** [comment]
I am closing this ancient ticket. If the problem resurfaces we can open a new ticket.
