### ISSUE TITLE
Rename "Heatmaps" results view to "Map"

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#301]
The new blacklight_heatmaps result view is shown to the user as "Heatmaps" but this is not an intuitive label for end-users, who will have no idea the gem behind this is called "blacklight_heatmaps." We should just refer to it as "Map" in the UI.

I assume one change will fix it but note that the label displays both in the Results tab as shown below, and in the results page as a tooltip when you mouseover the  map icon.

![configuration_-_search___rare_music_materials_at_stanford__stage__-_online_exhibits__stage_](https://cloud.githubusercontent.com/assets/101482/17375650/be9e14e6-5966-11e6-8f95-ec562bd234d1.png)

**Comment by jcoyne** [comment]
@cbeer why was this reopened? Is it just because #302 failed to fix the issue?

**Comment by cbeer** [comment]
Exactly, although it was fixed (but not yet released) by https://github.com/projectblacklight/spotlight/commit/a7f14a13528afb84c570d57bd69fe3f099bacc83.
