### ISSUE TITLE
Index geo data for latlong types.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/exhibits#305]
- [x] find example metadata
- [x] index it into the SRPT field

**Comment by atz** [comment]
Looks like `subject.cartographics.coordinates` is already being indexed to SRPT:
https://github.com/sul-dlss/exhibits/issues/307

Examples cited there.   If there are **other** forms of lat long that are intended to be indexed, they should be ticketed as separate feature requests with example data (ideally, with actual druids).
