### ISSUE TITLE
embed services does not get along with almond.js

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/exhibits#311]
In the iiif branch

```
Error: See almond README: incorrect module build, no module name
define()
 application-14a5b828141c763f520065af1a33cb5446982011554b6429b2e6bc14c1461a31.js:28
<anonymous>
 image_x-418da0a23251a5219131cc00a9e3262a1fda50d0f082b487ec4ba9b5628c6185.js:17
<anonymous>
```

https://embed.stanford.edu/assets/image_x-418da0a23251a5219131cc00a9e3262a1fda50d0f082b487ec4ba9b5628c6185.js?_=1470343420771

**Comment by jcoyne** [comment]
This may be fixed when embed is sandboxed in an IFrame

**Comment by mejackreed** [comment]
Good to know for embed, since other sites maybe using almond.js?

**Comment by jcoyne** [comment]
@mejackreed Yes. I would think so. Almond.js is here: https://github.com/requirejs/almond

**Comment by jkeck** [comment]
FWIW, we have shipped the update to embed that returns an iframe as the HTML payload.

**Comment by jkeck** [comment]
I'm closing this as I believe that embed being in an iframe makes javascript clashes fundamentally impossible.
