### ISSUE TITLE
Images in the carousel are too big

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/exhibits#315]
Carousels are here:
https://exhibits.stanford.edu/mss
https://exhibits.stanford.edu/rare-music

They are using the stacks IIIF server, but they are requesting full size images:

https://stacks.stanford.edu/image/iiif/tj729jy7495%2Ftj729jy7495_00_0001/full/full/0/default.jpg

The page would load faster if we just grabbed an image of 400px high. e.g. https://stacks.stanford.edu/image/iiif/tj729jy7495%2Ftj729jy7495_00_0001/full/,400/0/default.jpg

**Comment by jcoyne** [comment]
Check to see if the thumbnail field (400px) is big enough, if so use that field.

Otherwise, pick a reasonable size, and index that field and use it in the carousel.

**Comment by ggeisler** [comment]
The Carousel widget enables the curator to select one of three sizes for the display of the carousel. If we want to be most efficient, we would use an image size appropriate for the display size selected in the widget, such as:

Small = 350px height (or could use the 400px thumbnail if that increases page load time despite the 50px extra in size)
Medium = 500px height
Large = 800px height

If it's tricky to be specific based on the curator's choice of display size option, we should go with 800px height. That would cover any display option chosen, while remaining a relatively small image size.

**Comment by cbeer** [comment]
We've updated the database to use smaller images in a variety of places. We should figure out how to do this better, though.
