### ISSUE TITLE
Index MODS cartographic point data (expressed as lat/long decimals)

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#316]
Here is the relevant MODS stanza as it will appear:
<img width="347" alt="screen shot 2016-08-05 at 10 44 37 am" src="https://cloud.githubusercontent.com/assets/3210225/17445472/fbcc67fc-5af9-11e6-8706-171297190370.png">

Content that uses this encoding schema is in the accessioning pipeline, and here is an example of a druid that will be published by 31 Aug 2016: druid:dq277kw6181

**Comment by atz** [comment]
This is already being done.

**Comment by cbeer** [comment]
For points? I thought we just did bboxes (mobile, not looking at the actual code)

**Comment by caaster** [comment]
This is point data (lat/long to be expressed as a point), as opposed to 2 sets of lat/longs, which is a bounding box. I won't have any fixture data until 30 Aug (content is in accessioning pipeline now & no way to hurry it up as we're working with a 3rd party partner). Fixture data aside, it would be helpful to know if this is anticipated to work or not. Thanks -- this is confusing to me...
