### ISSUE TITLE
druid:sb498hk6274 indexed as resource type = archive/manuscript, but should be resource type = image

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#317]
What MD field is Solr indexing for the resource type facet in exhibits? This item (druid:sb498hk6274) in both SW-prod & Argo, is correctly identified as content type = image. The contentMD datastream for the item lists content type as image. The curator expects this item to appear as resource type = image in his exhibit (https://exhibits.stanford.edu/rare-music). Does something need to change in the item level MD for this to be indexed as desired, or is there a different problem?

**Comment by cbeer** [comment]
The PURL page has: `<typeOfResource manuscript="yes">mixed material</typeOfResource>`, which we (and searchworks indexing before us..) translate as `Archive/Manuscript`.

**Comment by caaster** [comment]
Thank you for clarifying @cbeer. I will address this with the curator & MD staff so they can undertake the necessary remediations.

**Comment by blalbrit** [comment]
@caaster - not sure if you found the source of the problem. typeOfResource for this and similar objects is derived from the catalog MARC record through the MARC2MODS xslt. To correct this, the MARC record needs to be changed to the appropriate code, and then the DOR object's MD needs to be refreshed from source.

**Comment by caaster** [comment]
@blalbrit -- awesome, thank you -- I will remove this agenda item from our Wed 1:1 :)
