### ISSUE TITLE
Create measures to reduce spam received via Feedback

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#345]
Jessie shared the following measures that the SW team employed/currently have in place to reduce spam received via Searchworks feedback; we need to employ the same or similar methods:

We create a text-input in the page (that is visually hidden, but still exists in the DOM, i.e. is _not_ `display: none`).  We do everything we can to make this input look enticingly like an email address field (these spammers _love_ trying to use these fields to know if they have successfully triggered emails from a system).  We then capture for any data being entered into this field and block that traffic (fwiw, we also put some text above it, so just in case a user did come across it, they would know why it was there).

In addition to that, we also capture for certain text in the body of the message.  For instance, we do not allow people to send URLs to us via the SearchWorks feedback (we try to indicate to them that their current URL will be send to us so they should send the feedback from the results/record that they are reporting).  The majority of spam includes links, so blocking feedback that includes things like `http://` or `https://` as well as some simple wiki markup like `url:`, etc seems to help out a lot.

There are probably other solutions to consider as well. That is just what we did awhile back in SW, and haven't had much reason to change it.

**Comment by jkeck** [comment]
Question: Should we deal w/ this in Spotlight or using overrides in Exhibits?
