### ISSUE TITLE
Menuez collection erroneously indexed to Stanford Stories exhibit - needs to be removed

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#351]
Consulted with @ggeisler on this & we don't know how this occurred. The Menuez collection, which was added by the collection druid (vx796zh5418) to the Stanford Stories exhibit (currently unpublished), contains 8,344 images & needs to be removed.

**Comment by cbeer** [comment]
I talked about this with @ggeisler yesterday, and he also noted some Fitch objects in there too. Can you or the curator remove the offending druids, after that I can do something with Solr to clean them up.

**Comment by caaster** [comment]
@cbeer -- @ggeisler said that only an engineer can remove the druids -- or did I misunderstand?

**Comment by cbeer** [comment]
I would like someone to update the list of druids at https://exhibits.stanford.edu/stanford-stories/resources/new to include only the druids that should be part of the exhibit. This won't remove them from the exhibit, but ensure they aren't re-added later, and will help me do it without accidentally removing objects that should be part of the exhibit.

**Comment by caaster** [comment]
@cbeer -- for the Fitch items (there are over 300) -- sleuthing what collection they are from is a bit hair-raising, as there are 35 different Fitch collections. For the moment, Daniel & I are making sure all the Fitch items are marked private. Menuez is very easy -- one collection druid add was responsible for over 8K items

**Comment by caaster** [comment]
@cbeer -- Understood. I will work on this but won't have time until Friday:
 update the list of druids at https://exhibits.stanford.edu/stanford-stories/resources/new to include only the druids that should be part of the exhibit

**Comment by caaster** [comment]
I have the list of 24 druids (attached) that need to be removed from the druid list for the Stanford Stories exhibit. At present, there is an indexing job for Stanford Stories still running, according to the UI. I don't want to cause a hiccup in the current indexing job -- so I haven't removed the druids yet. I can either remove them now, if advised to do so -- or a developer can remove them later. Please let me know.

[Remove_druids_from_StanfordStories.txt](https://github.com/sul-dlss/exhibits/files/462752/Remove_druids_from_StanfordStories.txt)

**Comment by cbeer** [comment]
Go ahead and remove them now.

**Comment by caaster** [comment]
@cbeer Items are removed

**Comment by cbeer** [comment]
Removed from the index.
