### ISSUE TITLE
[exhibits/production] ActiveJob::DeserializationError: Error while trying to deserialize arguments: could not obtain a database connection within 5.000 seconds (waited 5.055 seconds)

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/exhibits#355]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49092/faults/31034050)

**Comment by jcoyne** [comment]
This is because the number of worker threads exceeds number of db connections.

See https://github.com/mperham/sidekiq/commit/52828e42123cc1c54b2a326bda5d00965ec05acb

**Comment by jcoyne** [comment]
This requires a change to puppet, so passing it on to @cbeer

**Comment by cbeer** [comment]
Fixed by https://github.com/sul-dlss/puppet/pull/943.
