### ISSUE TITLE
Images are not saving for exhibit mastheads & browse categories

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#375]
The problems with image process/save are not resolved.

I am not able to save an exhibit masthead. I have tried using an image (from the SDR) that is in my exhibit. As a workaround, I downloaded an image from the SDR, and cropped it in Photoshop to conform to masthead size. I saved the image as a PNG (2.3 MB) and as a JPG (610 KB), and I tried to save each one (separately, of course) as a masthead. None of the attempts described above were successful.

I am not able to reliably, consistently save an image for the “All Exhibit Items” browse category.

As of yesterday/this morning -- I am **also now unable to** reliably, consistently save images for other browse categories.

All of the above attempts result in server timeouts, unresponsiveness, and strangely cropped images (in one “save” instance).

I consider these issues to be blockers.

Three curators have reported this problem, although it should be noted it likely effects all exhibits:
1) Ben Stone for Fitch
2) Josh Schneider for SHPC
3) Jerry McBride for Paci

In addition, I have experienced the problem for both the Secret Service & Reid Dennis exhibits.

See attached server timeout message that I often see displayed after 10-20 minutes or more of the page spinning unsuccessfully. Note the screen shot is from Firefox but I have also experienced the same failures in Chrome.
![screen shot 2016-10-12 at 2 28 33 pm](https://cloud.githubusercontent.com/assets/3210225/19328404/55cf5cdc-9088-11e6-93cb-68d58c990db2.png)

**Comment by cbeer** [comment]
Can you share the images you're using?

**Comment by snydman** [comment]
i was able to save a masthead and browse thumb today at https://exhibits.stanford.edu/new-exhibit using the same 365K JPG image downloaded from fitch.  saving the masthead was quite fast.  saving the browse thumb was much slower.

**Comment by snydman** [comment]
Follow-up.  After my success earlier in the day, I tried to crop and add a masthead for the attached image to https://exhibits.stanford.edu/secret-service
![00005881_0001_small](https://cloud.githubusercontent.com/assets/3279382/19331429/af3e591a-9099-11e6-8c74-742580349071.jpg)

**Comment by caaster** [comment]
Here are the pre-cropped masthead images (from the above - druid:xd400vp5649) as PNG & JPG that I also tried to save with no success.
![masthead1](https://cloud.githubusercontent.com/assets/3210225/19356368/713fc390-9122-11e6-9965-bad430582b20.jpg)
![masthead](https://cloud.githubusercontent.com/assets/3210225/19356372/76b252d4-9122-11e6-9e68-23ab9a404713.png)

**Comment by caaster** [comment]
Another experience for a different exhibit. Using this image from the exhibit: dq860ms1450 -- I tried to save a cropped portion as a masthead. After spinning for 3-4 minutes, my screen went blank. See screenshot. The masthead image did not save.
![screen shot 2016-10-13 at 8 57 58 am](https://cloud.githubusercontent.com/assets/3210225/19356680/7a826736-9123-11e6-8f21-e92e38c82b74.png)

**Comment by caaster** [comment]
Also for Reid Dennis, I attempted to save an image for the "All Exhibit Items" browse category. Was not successful.

**Comment by caaster** [comment]
And for the Fitch exhibit, I've unsuccessfully tried to select, crop & save an image to use for the Bob Fitch on Camera Browse category. In fact, I can't even get this image from the exhibit to load (vs122jg1785). See screenshot. This has been hanging in this state for several minutes.
![screen shot 2016-10-13 at 11 36 59 am](https://cloud.githubusercontent.com/assets/3210225/19362011/bae0d2fc-9139-11e6-8811-4a66051cf4f2.png)

**Comment by caaster** [comment]
After an upgrade to passenger and fixing "some vmware system problem that rsmith can probably explain better,” plus various Spotlight code fixes that Chris and Jessie put in place, exhibits seems to be working as expected, both in terms of system stability and the ability to crop images for mastheads and browse categories
