### ISSUE TITLE
Ability to save thumbnail for browse tile is broken

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#378]
The ability to save a thumbnail for a browse tile is broken again - after selecting an existing image in an exhibit to crop for a browse thumbnail -- the server hangs - spins & spins with no result, and the image doesn't load for cropping. It is broken on prod, but it works on stage.

**Comment by ggeisler** [comment]
For what it's worth, I tried saving a browse category thumbnail in Fitch and the selected image loaded for me pretty quickly, but after I cropped it and clicked Save, the process eventually timed out.

So the delay seems to occur at either loading the selected image to crop _or_ saving an image cropped.

**Comment by caaster** [comment]
This is either already fixed or will be moot based upon IIIF work.
