### ISSUE TITLE
(377) Feature enhancement for metadata display: Index notes separately by display label

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#379]

**Comment by cbeer** [comment]
Is it possible to explicitly list the various display labels we want to extract?  At the very least, we'll need that information to make them appear within the Spotlight interface.

If it isn't, we'll need to spend some time determining a strategy for handling fully dynamic fields or improving the curator's ability to work with arbitrary Solr fields.

**Comment by caaster** [comment]
Please be sure and refer to Acceptance criteria matrix with more information about these issues. -- link is in https://github.com/sul-dlss/exhibits/issues/377

**Comment by caaster** [comment]
Closing, as this is now superceded by #543 and #544
