### ISSUE TITLE
(377) Feature enhancement for metadata display: Index names separately by role (as well as collectively)

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#380]

**Comment by arcadiafalcone** [comment]
List of commonly-used role terms in progress (waiting for input from out-of-town archivists).

**Comment by caaster** [comment]
Please be sure and refer to Acceptance criteria matrix with more information about these issues. -- link is in https://github.com/sul-dlss/exhibits/issues/377

**Comment by arcadiafalcone** [comment]
[spotlight relator roles.xlsx](https://github.com/sul-dlss/exhibits/files/736052/spotlight.relator.roles.xlsx)

Starting list of commonly-used relator roles.

**Comment by caaster** [comment]
Closing this ticket as better /more complete stories are now available in #545 #546 #547
