### ISSUE TITLE
(477) Feature enhancement for metadata display: Index end date of ranges

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#381]

**Comment by cbeer** [comment]
Can you provide more information? E.g. what ranges, what fields, some example records, etc?

**Comment by cbeer** [comment]
SHPC is one example.

**Comment by caaster** [comment]
Please be sure and refer to Acceptance criteria matrix with more information about these issues. -- link is in https://github.com/sul-dlss/exhibits/issues/377

**Comment by caaster** [comment]
Closing as stories in the following now better describe what is needed #548 #549
