### ISSUE TITLE
(377) Feature enhancement for metadata display: Don’t include <mods><genre> in topic index

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#382]

**Comment by cbeer** [comment]
What is a "topic index"?

And, I believe this will be a change from the default behavior provided by stanford-mods, implying a deviation from the behavior of the Searchworks indexer.

**Comment by cbeer** [comment]
Use `topic_facet` stanford-mods values?

**Comment by caaster** [comment]
Please be sure and refer to Acceptance criteria matrix with more information about these issues. -- link is in https://github.com/sul-dlss/exhibits/issues/377

**Comment by caaster** [comment]
Closing as #552 #553 and #554 more explicitly address this issue.
