### ISSUE TITLE
(377) Feature enhancement for metadata display: Index <relatedItem displayLabel=“Series”><title> as series

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#384]

**Comment by cbeer** [comment]
Is this a duplicate of #247?

**Comment by caaster** [comment]
Please be sure and refer to Acceptance criteria matrix with more information about these issues.
github_ticket_info_20170118.docx

**Comment by caaster** [comment]
Closing as #558 does a better job of spelling this out.
