### ISSUE TITLE
(377) Feature enhancement for metadata display: Support active URL links in metadata display

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#385]

**Comment by cbeer** [comment]
Related items with external links or DOIs should be clickable

**Comment by caaster** [comment]
Please be sure and refer to Acceptance criteria matrix with more information about these issues. -- link is in https://github.com/sul-dlss/exhibits/issues/377

**Comment by caaster** [comment]
Closing as #559 does a better job of articulating this.
