### ISSUE TITLE
Indexing and reindexing issues being reported for three collections

### ISSUE THREAD

**Issue by snydman** [sul-dlss/exhibits#386]
on 11/21/ Amy Hodge reported that her effort to reindex https://exhibits.stanford.edu/data us hung at 111% and is not finishing.

See is specifically looking for zq192cm6234, yj807zw8315, qy650sk8658

This is urgent.

---

Nicholas Taylor tried to index the 60,000 item collection using mq209xn7521 collection DRUID.  He reports "it hangs a bit, then takes me to https://exhibits.stanford.edu/gatt/dor_harvester with an empty page. Going back and revisiting https://exhibits.stanford.edu/gatt/catalog/admin suggests that the druid didn't take, but it could just be indexing and hasn't surfaced that information yet to the front-end. Will check again later and update if I see any changes." 

This is not urgent.

-----

After a quick look @jcoyne reports that "There’s an exception that indicates that fetching the collection membership from DOR is taking a long time"

**Comment by jcoyne** [comment]
Two of these are timeouts fetching collections from DOR: https://app.honeybadger.io/projects/49092/faults/31800847

**Comment by jcoyne** [comment]
I'm seeing SSL timeouts to dorfetcher (when called with curl) on the production servers, this is likely the cause of the timeouts.
