### ISSUE TITLE
Analysis needed: re Blacklight search gem

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#389]
As a product owner, I need to know if the Blacklight search gem will need to be updated in order for Advanced Search to be implemented in Spotlight. 

This analysis task must be completed before we can determine if/how to proceed with implementing Advanced Search.
It would be useful if the analysis was able to shed light on any dependencies and a work estimate for the tasks associated.

**Comment by cbeer** [comment]
I'm not sure I understand how this ticket is related to #390 or why we wouldn't plan on updating all of our dependencies. As long as we keep on top of dependencies, keeping them up to date is usually not a problem.

**Comment by caaster** [comment]
Closing. Will be addressed by #388.
