### ISSUE TITLE
Ability to add new items to an exhibit has stopped working

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#391]
Currently, as a curator, when I attempt to add a new druid or druids to the item list on the admin console of two different published exhibits (Hanna House & Stanford Oral History), the result I see is an
<img width="1172" alt="screen shot 2016-12-07 at 9 53 25 am" src="https://cloud.githubusercontent.com/assets/3210225/20981039/d51005f4-bc67-11e6-947b-b8a9ea00aaf4.png">
 error message (attached) "The exhibits.stanford.edu page isn't working. exhibits.stanford.edu is currently unable to handle this request" Subsequent to seeing this error message, I have searched for the items I attempted to add, in case the error message was incorrect -- and I have verified the items I attempted to add were not added, as they did not appear as a search result.

As a curator, I expect to be able to add new druids to a published or unpublished exhibit where I am an administrator. After I add a new druid or druids to the item list in the admin console, I expect to see confirmation when my items have been successfully added. I also expect to be able to search for the newly added items in my exhibit and have them appear as a search result.

**Comment by jkeck** [comment]
I believe this is being caused by a timeout in the DorHarvestor process (as indicated by HoneyBadger error reports).

FWIW, I only see 7 occurrences only affecting Hannah House and Oral History, so I do not believe this is a systemic problem affecting all exhibits/curators.
