### ISSUE TITLE
Update links provided on Exhibits landing page

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#405]
Reasons for update:

* We want to provide an easier way for the Stanford community to understand how to request an exhibit
* We want to provide visibility and access to the small set of documentation the Exhibits service team has recently produced

### Mockup

Suggested arrangement of the sidebar on exhibits.stanford.edu after making the updates explained below:

![exhibits-landing-page-links_360](https://cloud.githubusercontent.com/assets/101482/21235042/5ef047c0-c2b2-11e6-8f68-418592f17f56.png)

* New link "Exhibit documentation" goes to an index page in Consul, which links to the Thinking about an exhibit, Quick start guide, and Pre-Publication checklist documents. Show the Stanford "S" if this documentation requires WebAuth.

* New link "Request an exhibit" goes to a page in Consul that tells the user how to request an exhibit and mentions the caveats for requests (URL slug, are items in SDR, etc.). Show the Stanford "S" if this link requires WebAuth. (Longer term we might consider making this link go directly to a form--with the same info and caveats--so the user doesn't have to send an email to request an exhibit.)

* Remove the current button that superadmins see labeled "Request a new exhibit"

* Add a link under the Actions heading labeled "Create new exhibit." Only superadmins should see this. The link goes to the new exhibit form, previously linked to by the "Request a new exhibit" button mentioned above.

Note that the Consul pages are WIP by @caaster.

**Comment by caaster** [comment]
Please note, the landing pages in consul that Gary mentions above are
 behind webauth. The two links (Exhibits documentation & Request and exhibit) will be added to this ticket tomorrow.

**Comment by caaster** [comment]
"Request an exhibit" link in consul: https://consul.stanford.edu/x/g4A-CQ

"Exhibit documentation" link in consul: https://consul.stanford.edu/x/2ok1CQ

**Comment by jkeck** [comment]
Quick clarifying question: The current logic of who can see the `Create a new exhibit` isn't changing?  Just the placement and styling, correct?

**Comment by ggeisler** [comment]
I believe you are correct. The only users who can currently create a new exhibit are superadmins, correct?

I probably should have phrased it as "change the label and styling of the current button" ... rather than the replace and add steps.
