### ISSUE TITLE
Metadata display enhancement request

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#412]
User story from Amy Hodge:

I noticed an issue that effects custom metadata fields that I am reporting here. I have created a custom metadata field called "Data Story" for my exhibit. I am displaying this metadata field on the items (and this seems to be working fine). Today I started wondering if it would be possible to a create browse category by faceting on this custom metadata field. In order to do that, I would need to see the custom field displayed in the facets. I went into Configuration > Search > Facets to make sure the Data Story metadata field was turned on for the facets, but it turns out that this field does not show up in the list of options, so I am unable to turn it on. I would like to see custom metadata fields show up in the facet options, because I can envision people wanting to create browse categories based on custom metadata. This seems particularly important for hydrus objects, because there are very few metadata fields available to users for entering information. In addition, the metadata that I was adding in my example is really only relevant to the items within the context of the exhibit, so I wouldn't actually want it associated with the metadata in the SDR record. Please note that I am not actually wanting to use this feature for my exhibit at this time, but I can envision people wanting to do this, and the idea came to me within the context of a meeting with Karin Forrsell about and LDT exhibit.

**Comment by jkeck** [comment]
I _believe_ that the user will need to change the custom field from `Free text` type to `Controlled vocabulary`.

This configuration is available in Home > Configuration > Metadata, then at the bottom of the page there is an `Exhibit-Specific Fields` section.  Editing an exhibit specific field will present the following UI

<img width="705" alt="screen shot 2017-01-12 at 10 22 29 am" src="https://cloud.githubusercontent.com/assets/96776/21902532/1d1302a6-d8b1-11e6-93c9-c5024fc3c1c1.png">

We should validate that this will make the field available as a facet before we inform the user.

**Comment by caaster** [comment]
I'll work with Amy Hodge on this & report back here. Thanks, Jessie.

**Comment by caaster** [comment]
Yes, this issue/request is documented in the following ticket: https://github.com/projectblacklight/spotlight/issues/1660, so I am closing this one.
