### ISSUE TITLE
Create form for new exhibit requests

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#413]
As a curator, I like the new exhibits landing page sidebar link that provides information on how to request a new exhibit (https://consul.stanford.edu/display/SLREQ/Request+a+Spotlight+Exhibit). However, I want it to be easier and I'd like a form instead, so I don't have to draft an email, and I can submit my request easily.

As the Spotlight service manager, I'd like the following fields on a form to be mandatory:
1. Name
2. Job title
3. Department/unit
4. Title for your exhibit _(you can change this later, if needed)_
5. Preferred URL sub-path _(i.e., what comes after exhibits.stanford.edu/); preferably something short and pithy. Dashes are ok to include here, if desired.
NOTE: This can't be changed later, so please choose wisely._
6. Brief description of the content and purpose of the exhibit _(1-3 sentences)_

The following fields can be optional:
7. Whether or not the content is (or will be) in the Stanford Digital [Repository](https://sdr.stanford.edu/) _(if you know)_
8. Whether or not the content is (or will be) in [SearchWorks,](https://searchworks.stanford.edu/) the Stanford Libraries online catalog _(if you know)_

NOTE: I've placed explanatory text in italics, in the list above, and field labels in regular text.

Submission of the form should generate a ticket in the JIRA project; email sent to exhibits-feedback@lists.stanford.edu is already configured to do this (https://jirasul.stanford.edu/jira/projects/EXHBTF).

**Comment by cbeer** [comment]
Are we talking about building a stanford-only form and workflow, or is mediated exhibit creation a generally useful feature that might belong in Spotlight?

Or, if creating JIRA tickets is really preferable, I believe the JIRA workflow and available fields are highly customizable. Would it be appropriate to ask one of our JIRA admins to customize a form in JIRA itself?

**Comment by caaster** [comment]
I'd like to discuss these options face-to-face.

**Comment by cbeer** [comment]
We discussed this some during standup. It sounds like there's interest in adding mediated workflow for requesting new exhibits into spotlight. I'll transfer this ticket into spotlight with a design-needed tag.

**Comment by caaster** [comment]
Current system works fine. No longer needed at this time.
