### ISSUE TITLE
Add map to Show page when geospatial metadata is available

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#421]
Below are some very rough ideas for this feature. I think we'll need to iterate on this design a bit because I have a few questions and it'll be good to get input and ideas from others, especially @mejackreed and @drh-stanford on possibilities and practicalities for the map-specific aspects. 

If I understand correctly, there are two main types of geospatial metadata we can expect to find in item records: bounding box (metadata is either degrees and minutes or box coordinates) or point (metadata is either lat/long or a geo name). In either case, the mockups below assume that, given an item with geospatial metadata, we generate a map for the appropriate type of data and put it at the top of the right column (at desktop viewport size) on the item show page, above the item metadata.

Details about the map area:
* In the mockup I tried to balance having the map large enough to read, but not dominate the right column. This is trickier than I expected. It seems like making the map small enough to fit here can also result in text on the map being difficult to read. I used a 2:1 aspect ratio for the map size, to use most of all of the column width while minimizing height.

* It feels like we need some sort of caption below the map, otherwise users might not know what the map is doing there. I'm not sure that ```Location of item's geospatial metadata``` is the best wording, though?

* Because the map is fairly small, users might want to view it larger to really understand the context of the location. I added links for that purpose (I'm not sure we want to link the map itself, because that could make it too easy to inadvertently click it and be take away from the page). Does this make sense, and if so, what are the source(s) most reasonable to link to?

### Desktop layout

I think we can use the same styling for viewports 992px and up. The version shown below is 1200px but the map still fits fine from 992 to 1199px.

![layout-desktop](https://cloud.githubusercontent.com/assets/101482/22170106/4eb78138-df37-11e6-990e-d8974704c87c.png)

### Mobile layout

Below 992px, I just did some very minor CSS adjustments to have the map take the full width, to match what we're doing with the embed and metadata. The map is much bigger here, but I think that's okay? It fits with the existing content where each section takes full width of the viewport, and I'm not sure we gain anything by reducing its size (I don't see how we would use the extra horizontal space), other than making it feel less dominant.

![layout-mobile](https://cloud.githubusercontent.com/assets/101482/22170281/26eb09c0-df39-11e6-8490-8c50b7614629.png)

### Point version

The mockups above use the bounding box version of the map. Here's how a point version looks:

![point-version](https://cloud.githubusercontent.com/assets/101482/22170143/badd14e0-df37-11e6-9492-1213a826544a.png)

### Configuration

Do we assume that everyone who adds the blacklight-heatmaps gem to their Spotlight installation will want to show this map on their item show page? Or do we want to enable toggling the feature on/off in the Admin?

(Or does this feature really belong in the same gem as blacklight-heatmaps? I still kind of feel like they should be independent, but I might not fully understand the plan for blacklight-heatmaps.)

**Comment by jkeck** [comment]
@ggeisler wrt configuration, I think we can handle it completely independently.  Currently, the configuration is in the code  (e.g. in the BlacklightConfig) and would be site wide.

If we want to allow exhibits that have geo data to individually decide to not show a map, we would need some way of configuring that.

**Comment by jkeck** [comment]
Also, I'm not 100% sure we can simply open the same data in a larger interface (like OpenStreetMap).  Although perhaps @mejackreed knows more.  Looking briefly at EarthWorks, it doesn't appear that they attempt  to open in a larger map, but not sure if that was done intentionally.

**Comment by ggeisler** [comment]
@jkeck:

> If we want to allow exhibits that have geo data to individually decide to not show a map, we would need some way of configuring that.

Site-wide config is probably fine to start with. I'm not sure why a curator would not want to show the map if the exhibit items had the necessary metadata, so we could probably just wait and see if a need for an exhibit-specific toggle is expressed after the feature is available.

> Also, I'm not 100% sure we can simply open the same data in a larger interface (like OpenStreetMap). 

Yeah, I certainly don't think it's critical. I'm just worried about the map getting users interested in exploring the geospatial context more and not having a way to enable them to do that. But with a static map we're still providing more than just the text metadata, which is nice, so that could be sufficient.

**Comment by jkeck** [comment]
Great, thanks for the clarification!

**Comment by cbeer** [comment]
> I'm not sure why a curator would not want to show the map if the exhibit items had the necessary metadata, [...]

At least in some exhibits, the metadata we have borders on the point of uselessness ("Western hemisphere", "Africa"). I'm not sure how /harmful/ this is, but feels a little silly (although maybe we can use that as a way to encourage more precise metadata?).

E.g.:

<img width="1218" alt="screen shot 2017-02-02 at 8 29 57 am" src="https://cloud.githubusercontent.com/assets/111218/22558231/d00df98a-e921-11e6-9823-2904503e0277.png">

**Comment by cbeer** [comment]
Ok -- here's what may be a crazy idea... Can we just add the map as yet another field on that "Display and Order Metadata Fields" page, e.g.:

<img width="443" alt="screen shot 2017-02-02 at 8 49 06 am" src="https://cloud.githubusercontent.com/assets/111218/22558974/78fb0e14-e924-11e6-901e-28ddfc6f5524.png">

This should allow the curator to enable/disable it like any other field. We probably want to prevent it from appearing on search results pages (maybe?), but other than that, it seems like it might be an ok fit.

On the display side, we can add some CSS to simply hide the field label and make the map fill the full space just like the design.

**Comment by ggeisler** [comment]
I mostly like this idea. I do like having this be configurable within an exhibit.

My one hesitation is I think this would have the inline map, when enabled, showing up in the list of metadata fields on the show page at places other than the top. When doing my original mockup, I considered this but wasn't thrilled with the way the map looked when it was mixed in the flow of the other fields. I could take another look, though, and see if I was justified in not considering it.

I would definitely lean towards not including it on results pages. I worry that would make the results pages more cluttered and possibly confusing, since you'd have both an image thumbnail the map image for each item. I wonder if we could just disable the checkboxes for Inline Map in all but the Item Details column?
