### ISSUE TITLE
Additional design for Parker exhibit

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#443]
Discussions started with @ggeisler - this stub ticket represents work that might follow from Gary's design review.

**Comment by blalbrit** [comment]
Level 1 - no code change
* masthead images
* thumbnails
* widgets for page layouts

Level 2 - brand-bar updates (#446) + Level 1
* change background color for brand-bar to accommodate Corpus logo

Level 3 - code changes
* what kind of things can be done to Spotlight, specifically, to provide options for enhancing visual impact of exhibits.

**Comment by ggeisler** [comment]
To accomplish the goal of giving Parker a unique design within the context of Spotlight, I suggest we try a strategy of: 

1. Careful selection of masthead image, page creation and widget selection, browse categories (Level 1 items in @blalbrit's comment above)

2. Removing SU and SUL footer as documented in #527 

3. Adding a background pattern to the `body` element to provide a slightly different and customized page background. Generally, something like this (but with better page content):

![ricepaper](https://user-images.githubusercontent.com/101482/29341172-92c6427c-81d7-11e7-9f75-1a5b335ab276.png)

(I've about 10 example page backgrounds prepared to choose from.)

When we get those elements in place, we could evaluate whether that is sufficient to satisfy the goal of this ticket. So what I'm suggesting here is that I won't do any further work on this ticket until we start putting together the actual Parker exhibit site with real content, pages, etc.

If those elements are sufficient, the only technical updates we have to make are adding the background pattern image to `/assets` and updating the `parker.scss` (or equivalent) with a small number of CSS overrides.

**Comment by blalbrit** [comment]
👍

**Comment by ggeisler** [comment]
Based on @blalbrit's thumbs up, I'm going to remove the design needed label. There will be design-related work as part of the implementation of this ticket, but I think it is actionable now.

**Comment by blalbrit** [comment]
@ggeisler - from the Parker team:

"With regard to the Corpus Branding (which I'm not particularly fond of regardless of Circumstance), I think that could use a bit of work. At the moment it sort of looks like it's been pasted onto the page, and doesn't really integrate with the whole look and feel of the rest of the items.


[1:13] 
Perhaps put back in the big photograph of the Library again at the top? Or just make this bigger (but perhaps keep the logo the same size) so that it spans the width of the page?"

Any thoughts on these suggestions? And just to be clear, the first sentence refers to a general unhappiness with the college branding, not the work you've done with it.

**Comment by blalbrit** [comment]
All done - client has signed off on current design.
