### ISSUE TITLE
"Sort by author" has a bug -- sorts by title instead

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#445]
Isolated to one exhibit? -- Please note, this seems to be the only browse category in this exhibit with this sort bug.
<img width="1230" alt="screen shot 2017-02-22 at 9 10 01 am" src="https://cloud.githubusercontent.com/assets/3210225/23223377/c084b8aa-f8df-11e6-9e0b-768f9e8b2cdd.png">

**Comment by cbeer** [comment]
We sort first by author, then by title. We sort by author using logic from stanford-mods. gdor-indexer creates a field for author sort using the "main author", which is a name with the role "Creator" or "Author" (or, no role?). The couple records I looked at don't have data like that.

**Comment by caaster** [comment]
Amy Hodge will do more sleuthing on this issue in a few days & comment back on this ticket.

**Comment by caaster** [comment]
Comments & resolution on: https://jirasul.stanford.edu/jira/browse/EXHBTF-154 provide specific information about the nature of the problem reported here, and what was done to resolve it.
