### ISSUE TITLE
Enable some level of brand bar customization

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#446]
The Parker 2.0 exhibit needs to customize the brand bar to accommodate branding additional to the current "[rosette] Stanford University Libraries".

![online_exhibits](https://cloud.githubusercontent.com/assets/101482/23236507/c00bd2aa-f916-11e6-9a2a-0d0ce1a02109.png)

Ideally the solution would be flexible enough to enable future multi-institutional or multi-departmental exhibits to also easily customize the brand bar to reflect the primary organizations involved in the exhibit.

**Comment by blalbrit** [comment]
To support Corpus logo, need to be able to change color of brand bar as well.

**Comment by ggeisler** [comment]
This is a somewhat complicated requirement so below is just a general outline of an approach. I think we'll need some technical input on feasibility from one or more of, say @jkeck, @mejackreed  and @cbeer, and general thoughts from @blalbrit and @snydman.  I can refine after we agree on what is the most feasible approach.

### Assumptions
* This is an Exhibits ticket so we are not generalizing to Spotlight (a solution might be generalizable to Spotlight but would require more configuration to eliminate some default choices made based on the assumption that there is always a SUL logo).
* Although the immediate requirement (Parker) only requires one additional organization to display its logo in the brand bar, we’re likely to see future cases where more than two organizations are involved (e.g., the Lanciani/Rome project), so it probably makes sense for a solution to be more flexible than accommodating just two logos.
* We can’t assume that all organizations will have a logo that is visually compatible with the Cardinal Red background color our exhibits sites currently use (e.g., for Parker, the Corpus Christi logo includes a very similar red that would blend into a red background). The simplest approach is to simply offer the option of a white background. We could offer more choices, but limiting to either Cardinal red or white would likely cover the vast majority of cases and ensures the exhibit site visually matches existing SUL websites. (The white background will require some associated CSS overrides, for link colors.)


### Configuration
The mockups below are a first pass at how configuring additional institutions might work. 

We’d add a new tab to the Appearance configuration page, which enables the admin to change the top bar background color and to add institutions:

![configuration-appearance-main](https://cloud.githubusercontent.com/assets/101482/23916886/da4f64c6-08aa-11e7-9df8-73ac14d00449.png)

I think the approach we use for adding contacts in the About page section might work well as a model for adding institutions. This approach would enable the admin to easily reorder, edit, and delete institutions, which could be handy (especially editing, after they see how their uploaded logo looks).

So to add an institution, the admin selects the Add button and gets the Institution edit page to enter the appropriate information and upload the logo image. I don’t think we need cropping for this. But to keep file sizes down, we might want to proportionally scale the image down to 25px high, since that’s the size we use in the top bar.

![configuration-appearance-institution-edit](https://cloud.githubusercontent.com/assets/101482/23916914/f2c22d36-08aa-11e7-8104-c22befc2e361.png)

When a new institution is saved, it's shown on the main Institution logos page and added to the top bar.

![configuration-appearance-main-one-institution](https://cloud.githubusercontent.com/assets/101482/23916990/29dfcaee-08ab-11e7-94c5-e2377ef78bf6.png)

### Display
To display additional logos in the top bar, I believe we’ll have to adjust the way we currently display the SUL logo. We currently override the default Spotlight method (which shows the Blacklight logo based on a link/image in the HTML) by adding exhibits-specific CSS that shows the logo in a background image. However, I don’t think we can inject configuration-based data into the CSS, so I assume we’ll have to enhance the Spotlight approach and add a link/image for each institution defined by the exhibit. I can provide more details on that if and when we decide this is the approach we want to pursue.

The trickiest issue might be how to determine which SUL logo to display based on viewport width. Once there is more than just the SUL logo in the top bar we have to consider how much width is available in the top bar based on viewport width. For example, the values below are roughly the max widths the entire logo area can extend (at different viewport widths) until it reaches the left edge of fielded search select box:
        - at 1200px or greater: 800px
        - at 992px to 1199px: 600px
        - at 768px to 991px: 370px
        - at 767px or smaller: 250px

The SUL logo will always be present and takes up some of that width, the exact amount of which depends on which SUL logo variant is used:

Full logo (“Stanford University Libraries”): 320px

![sul-logo-h25](https://cloud.githubusercontent.com/assets/101482/23918642/0bba7130-08b1-11e7-968e-01b99aa40c2c.png)

Abbreviated logo (“SUL”): 100px

![sul-logo-small-h25](https://cloud.githubusercontent.com/assets/101482/23918655/129cf306-08b1-11e7-98f8-e426395861ff.png)

Stacked logo (“Stanford University Libraries” but on three lines): 90px

![sul-logo-stacked-h25](https://cloud.githubusercontent.com/assets/101482/23918663/1861cf1e-08b1-11e7-984b-0ce0db7bc4fd.png)


Two potential approaches I can think of:
1. Calculate the width of all additional institution logos and display the widest SUL logo that will fit given the viewport (using the max widths for logo area noted above). 
2. Simply assume that when there is more than one logo, we'll show the full SUL logo at, say 992px and above and one of the smaller SUL logos below 992px (relies on the admin uploading reasonably-sized logo images).

For illustration, below are some examples of the top bar with additional institution logos:

1200px viewport, two logos:

![sul-cc-white-background](https://cloud.githubusercontent.com/assets/101482/23918350/e24b568a-08af-11e7-856f-8954b170974c.png)

992px viewport, two logos:
![sul-cc-white-background-992ox](https://cloud.githubusercontent.com/assets/101482/23918386/fc4603c8-08af-11e7-9bb3-9e0f39e544bf.png)

800px viewport, two logos:

![sul-cc-white-background-800px](https://cloud.githubusercontent.com/assets/101482/23918391/00c6394a-08b0-11e7-8c3f-134ee5651a38.png)

1200px viewport, three (two minimal) logos:

![sul-biasa-inasa-white-background](https://cloud.githubusercontent.com/assets/101482/23918475/563f9f9c-08b0-11e7-939b-2c50b34f7787.png)

800px viewport, three logos:

![sul-biasa-inasa-white-background-800px](https://cloud.githubusercontent.com/assets/101482/23918494/6714e03e-08b0-11e7-8fa3-4febaa4be94c.png)

992px viewport, four logos:
![four-logos-992px](https://cloud.githubusercontent.com/assets/101482/23918502/78a52048-08b0-11e7-9380-85a740d27cd7.png)

**Comment by ggeisler** [comment]
I meant to point out that the approach above is obviously pretty complicated and given that the multiple institution scenario might not be all that common, maybe we shouldn't rule out a more custom, one-off approach where we (development, not the exhibit curators) create a custom HTML snippet for the top bar and conditionally load it (e.g., `if exhibit == "Parker" then ...`).

Not sure how easy or practical that would be, but it would eliminate a lot of configuration and would be easier to know the best SUL logo to use based on the other institution logos, etc.

**Comment by ggeisler** [comment]
Based on a recent conversation with @jkeck and @cbeer, we think an approach roughly like my previous comment above (as opposed to the longer comment before that with the configuration mockup, etc.) is likely a feasible and preferred approach. How it is actually implemented technically is TBD but I think conceptually all we need to do is 1) add the appropriate logo asset(s) to the application, and 2) conditionally activate a SCSS override to the `.navbar-brand` styling:

``` scss
#header-navbar {
  .navbar-brand {
    background-image: image-url("SUL-footer-stacked_whitetext.png"), image-url("cambridge.png");
    background-position: left, right;
    background-repeat: no-repeat, no-repeat;
    width: 250px;

    @media (min-width: $screen-md-min) {
      background-image: image-url("sul.png"), image-url("cambridge.png");
      width: 350px;
    }
  }
}
```

For example, locally I just put the SCSS snippet above into a new `.scss` file called `parker.scss` and loaded that file at the end of the SCSS load order. For any future exhibit with similar multi-institution needs, we could add the logo(s) and an equivalent SCSS override file with the snippet adjusted as necessary. This approach produces:

![parker-example-desktop-cambridge](https://user-images.githubusercontent.com/101482/28848159-ca12fd04-76c6-11e7-848c-410cf24fc164.png)


And at mobile:

![parker-example-mobile-cambridge](https://user-images.githubusercontent.com/101482/28848163-cd6d3226-76c6-11e7-84d8-60f6e276229a.png)


### Parker logo question
In the examples above I used the University of Cambridge logo, although the partnership is specifically with Corpus Christi College of Cambridge. @blalbrit do you know if we'd have to use the Corpus Christi logo versus the Cambridge logo? Corpus Christi seems to have updated their logo recently and the only version I've found seems to be intended for larger contexts. When used in our smaller brand bar context, it is difficult to read:

![parker-example-wide-corpus-christi](https://user-images.githubusercontent.com/101482/28848310-5122043e-76c7-11e7-935f-620159da9c63.png)

Changing the background color doesn't improve the readability:

![parker-example-wide-corpus-christi-dark-bg](https://user-images.githubusercontent.com/101482/28848338-655a9542-76c7-11e7-9735-bde415a89eb7.png)

The Cambridge logo works fine, so if we can use that, great. If not, we might need to find out if our partner contacts have a logo that is more legible at small sizes (~25px height).

**Comment by blalbrit** [comment]
Just to reiterate, as @ggeisler points out, this is not a Stanford/University of Cambridge collaboration. The participating entity will be Corpus Christi College, and I'm happy to see if we can find logos for them that might fit the current brand bar more legibly.

It's important to note, however, that we are looking for specific branding for Parker on the Web. See https://parker.stanford.edu for an example.

It is important to retain the Parker on the Web product branding, in addition to the institutional participant logos (which can actually be buried to a degree). If we go with something like the mocks above, then we'll need another way of actually branding the product below the current bar.

**Comment by ggeisler** [comment]
@blalbrit Okay, thanks. We'll see what you can find out regarding a Corpus Christi College logo that works better at a small size. 

The more general issue you mention about retaining the Parker on the Web branding is what ticket #443 is intended to deal with. After we update the masthead image, populate the exhibit with appropriate widgets, etc., and add the logo to the brand bar, we're into what you listed in that ticket as "Level 3" enhancements. That's the more challenging part, but I'll present any ideas for that in ticket #443.

**Comment by blalbrit** [comment]
@ggeisler - Corpus has sent along a folder of approved logos: https://stanford.box.com/s/io022wzqe61xsma2xs1xdmwoym7crfmt . Is any of this useful to you?

**Comment by ggeisler** [comment]
Yes, thanks @blalbrit, except these are only the logos, without the brand text. It's a lot easier to do what we want if we have an image that combines the logo and brand text. 

Good news, though, I used the Wayback Machine and found a previous version of their homepage before they switched to the pelican logo, and grabbed a combined logo/brand text image from there. I think that will work, and since it's the same logo image as one of the versions in the folder you shared, I assume they will be okay with it.

**Comment by ggeisler** [comment]
Below is a screenshot of the brand bar using the Corpus Christi logo. Because the only non-pelican version of their logo I could find uses a white background, I had to change the brand bar background to white as well. If we decide we don't like the white brand bar, we'd have to either get a CC logo that has a transparent background color, or skip putting their logo in the brand bar (relying on other places in the app to make CC's partnership clear).

![configuration_-_general___parker_library_-_stanford_university_libraries](https://user-images.githubusercontent.com/101482/29184025-abd9d3cc-7db9-11e7-9862-e367c957dcc8.png)

If do want to go with this, the SCSS is a bit more complicated than the snippet I posted in an earlier comment. I have a local branch with the necessary SCSS (still a single SCSS override file) and will just save that until we implement this ticket.

**Comment by blalbrit** [comment]
Thanks @ggeisler - you know, for Parker, if we foregrounded the Corpus Christi / Parker logos below the bar, and had a subtle Stanford brand in the bar, that might be okay. We should run a selection of design options by Corpus - we can't make this decision without consulting them.

**Comment by ggeisler** [comment]
It seems like we have a solution for Parker that does not require adding the Corpus Christi logo to the brand bar so I'm going to close this ticket. 

This could come up again with a future partnership exhibit, but we can reopen this ticket if and when that happens.
