### ISSUE TITLE
Negative number displays in previous/next browse

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#450]
https://exhibits.stanford.edu/shpc/catalog/qm871dx8736 This and many other items in the SHPC exhibit display a negative number in the previous-next browse above the embed viewer: this one has "-1 of 187". Also happens in Herbert Matter exhibit. Screen shots attached.
![screen shot 2017-03-13 at 3 43 53 pm](https://cloud.githubusercontent.com/assets/3210225/23878390/5a550ace-0804-11e7-853c-bc873c3dabfe.png)
![screen shot 2017-03-13 at 3 44 09 pm](https://cloud.githubusercontent.com/assets/3210225/23878392/5d2a9dc2-0804-11e7-9fde-ea05bb7263b5.png)
![screen shot 2017-03-13 at 3 45 36 pm](https://cloud.githubusercontent.com/assets/3210225/23878393/5eeb2bf4-0804-11e7-83cc-a7f8e80265af.png)

**Comment by mejackreed** [comment]
I wasn't able to recreate this issue unfortunately. Do we know any steps that can be done to reproduce this?

**Comment by jkeck** [comment]
Just was able to reproduce by opening up the first record in any browse category and then clicking the Previous link.  On the first record the Previous link should be disabled/unlinked (as is in a normal search result) but when getting to a record from a browse category Previous is linked and you can paginate into negative numbers indefinitely.
