### ISSUE TITLE
Custom metadata fields that are facetable should be searchable. 

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/exhibits#466]
Add *_ssim fields to the all_text (?) field so it is searchable.

**Comment by caaster** [comment]
Cathy note: Benefit would be exhibit specific MD fields added by a curator would be searchable. VT stakeholders might really like/be able to benefit from this.

**Comment by corylown** [comment]
- [ ] Developer investigation about what is required to make this work
- [ ] Review with Cathy which exhibits are impacted and whether a reindex would be required.

**Comment by dnoneill** [comment]
Assuming I have done this right, I believe we will need to do a full reindex.
