### ISSUE TITLE
Potential performance issues that could be guarded against for Bibliography Service

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#470]
Currently the bibliography service job kicked off for Parker can take 2-3 hours to complete. Usually ~1 hour for the sync job and then 1000's of reindexing jobs proceed to be kicked off. The first sync is guarded against resyncing, but subsequent ones have a "Synchronize button" available. A user may not be aware of the time delay and may submit several long running sync jobs.

cc @jkeck

**Comment by drh-stanford** [comment]
Note that the sidekiq configuration needs tuning for production. In stage, we're running 2 processes with 5 worker threads each. The database connection pool is set to 10 to match the number of workers. We were having problems with swapping on the stage box (16x16 box). Need to tune the production box too.

We have a single `default` queue right now.

**Comment by drh-stanford** [comment]
Also see https://github.com/sul-dlss/operations-tasks/issues/500
