### ISSUE TITLE
Permanently remove 491 Stanford Band exhibit items that now have access rights set to discoverable=dark

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#473]
List of druids to remove are attached.

This ticket describes the underlying problem that needs to be fixed:
https://github.com/sul-dlss/exhibits/issues/472

**Comment by blalbrit** [comment]
[PC0170 ser 1+2%2c discover%3dnone.txt](https://github.com/sul-dlss/exhibits/files/922916/PC0170.ser.1.2.2c.discover.3dnone.txt)

**Comment by jkeck** [comment]
@caaster I have deleted the items from the solr index as well as removed the references to the items in the Exhibit's database.

Please let me know if there appear to be any lingering issues, otherwise feel free to close this issue if you feel it has been resolved.
