### ISSUE TITLE
Blocker Bug when trying to edit home page of /atomic-energy exhibit

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#475]
This big appears to be isolated to the /atomic-energy exhibit. Neither Amy Hodge nor I have been able to reproduce the bug.

Curator James Jacobs states (at 12:12 pm on 25 April):
If I try to edit anything in my exhibit, I get an error (see screen shot). I was trying to add a widget without a title in order to make the thumbnail image I had uploaded show up my exhibit’s home page. btw, I was unable to send a feedback either, after this happened. Note: I can go to the dashboard and edit other pages in my exhibit
<img width="493" alt="screen shot 2017-04-26 at 1 31 04 pm" src="https://cloud.githubusercontent.com/assets/3210225/25455482/d531a62e-2a84-11e7-9b6e-8f2ffd2a59f0.png">
.

**Comment by jkeck** [comment]
I believe this is related to https://github.com/projectblacklight/spotlight/issues/1782

I updated the page content manually in the database to remove a browse block that had no browse categories.  I can now view the edit screen for this exhibit.
