### ISSUE TITLE
Allow facet sidebar in browse pages

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#482]
As a curator, I want to allow users of my exhibit to facet within browse categories. As an example, within a collection of papyri, I want users to be able to facet further on language.

I would want this to be an option that was off by default, but the sidebar/facets could be turned on for any browse page where appropriate or desirable.

**Comment by camillevilla** [comment]
@anarchivist @caaster I think this ticket was solved by the addition of Saved Search widgets:
- projectblacklight/spotlight#1862
- #900

**Comment by anarchivist** [comment]
Looks right to me. @blalbrit?

**Comment by blalbrit** [comment]
yep - exactly right @camillevilla - this was satisfied by the saved search widget. Will close.
