### ISSUE TITLE
Need service team notification when an exhibit is published

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#488]
As a Spotlight service team member, I need to be notified right away when an exhibit is published, so I can keep better track of new exhibits and provide quick exhibit review and support to curators. I also need notification when an exhibit is unpublished so I can reach out to the exhibit creator as necessary.

It would also be very helpful to be notified of **who** published or unpublished an exhibit.

The Spotlight at Stanford service team has a mailing list:
spotlight-service@lists.stanford.edu, although this creates a JIRA ticket, so if the slack suggestion below was do-able, it might be the preferred option

**Comment by caaster** [comment]
Not trying to suggest solutions, rather -- providing options. There is a channel for Spotlight at Stanford service managers. It is currently private. #spotlight-service-team -- and this could be another option for sending notifications

**Comment by caaster** [comment]
Here is what I would need a notification to state (whether notification it comes via email or slack)

for email subject line: Spotlight exhibit published: [list name of exhibit]

text for email or slack notification: 
Spotlight exhibit [list name of exhibit] published at [list date and time stamp, in local time if possible]

**Comment by jkeck** [comment]
@caaster should the notification be sent on publish state changes other than the initial un-published to published state?

Example:

1. `Exhibit A` is published for the first time (we'll send a notification)
1. `Exhibit A` is unpublished (any notification needed here?)
1. `Exhibit A` is re-published (any notification needed here?)

**Comment by caaster** [comment]
Yes @jkeck - good catch. Notification should be sent on all state changes you list above -- 1, 2 and 3.
