### ISSUE TITLE
Clean up delayed_jobs cruft?

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#497]
This seems leftover

**Comment by mejackreed** [comment]
`_scratches head_` thats all i see now too. Do we care about keeping those tables?

Or do we care enough to do anything about it? (I'm not sure we do)

**Comment by jkeck** [comment]
I don't think we do.  We could write a migrate to remove the tables, although I'm not sure if that'll ultimately put is in a better position. `/shrug`

**Comment by mejackreed** [comment]
Closing then.
