### ISSUE TITLE
Modify zotero_bibliography_* field to one that doesn't get clobbered in the solr analyzer

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#502]
We are having large stack trace errors for indexing of `zotero_bibliography_tsi` fields. They begin like this:
<details>
  <summary>See an example stack trace</summary>
I, [2017-07-12T06:21:14.907416 #127337]  INFO -- : [ActiveJob] [RecordIndexStatusJob] [b85462ec-7461-48ec-8e2d-fe2d8285f67d] Performing RecordIndexStatusJob from Sidekiq(default) with arguments: #<GlobalID:0x007f6684018820 @uri=#<URI::GID gid://exhibits/DorHarvester/6439>>, "fz541vq7367", {:ok=>false, :message=>"#<RSolr::Error::Http: RSolr::Error::Http - 400 Bad Request\nError: 'Exception writing document id xj416ct0118 to the index; possible analysis error: Document contains at least one immense term in field=\"zotero_bibliography_ssi\" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: \\'[60, 117, 108, 62, 60, 108, 105, 62, 60, 100, 105, 118, 32, 99, 108, 97, 115, 115, 61, 34, 99, 115, 108, 45, 98, 105, 98, 45, 98, 111]...\\', original message: bytes can be at most 32766 in length; got 38049. Perhaps the document has an indexed string field (solr.StrField) which is too large','code'=>400}}\n\nURI: https://solr_url/solr/exhibits_stage/update?wt=ruby&commitWithin=500\nRequest Headers: {\"Content-Type\"=>\"application/json\"}\nRequest Data: \"[{\\\"id\\\":\\\"xd669dx1412\\\",\\\"exhibit_parker_public_bsi\\\":true,\\\"spotlight_exhibit_slug_parker_bsi\\\":true,\\\"exhibit_parker-00357808-6987-4f9e-9678-fbaad451fb91_public_bsi\\\":true,\\\"zotero_bibliography_ssi\\\":\\\"\\\\u003cul\\\\u003e\\\\u003cli\\\\u003e\\\\u003cdiv class=\\\\\\\"csl-bib-body\\\\\\\" style=\\\\\\\"line-height: 1.35; padding-left: 2em; text-indent:-2em;\\\\\\\"\\\\u003e\\\\n  \\\\u003cdiv class=\\\\\\\"csl-entry\\\\\\\"\\\\u003eBevenot, M. \\\\u0026#x201C;The Oldest Surviving Manuscript of St. Cyprian Now in the British Library.\\\\u0026#x201D; \\\\u003ci\\\\u003eThe Journal of Theological Studies\\\\u003c/i\\\\u003e n.s., 31 (1980): 368\\\\u0026#x2013;77. doi:10.1093/jts/XXXI.2.368.\\\\u003c/div\\\\u003e\\\\n\\\\u003c/div\\\\u003e\\\\u003c/li\\\\u003e\\\\u003cli\\\\u003e\\\\u003cdiv class=\\\\\\\"csl-bib-body\\\\\\\" style=\\\\\\\"line-height: 1.35; padding-left: 2em; text-indent:-2em;\\\\\\\"\\\\u003e\\\\n  \\\\u003cdiv class=\\\\\\\"csl-entry\\\\\\\"\\\\u003eBloomfield, M. W., B.-G. Guyot, and et al. \\\\u003ci\\\\u003eIncipits of Latin Works on the Virtues and Vices, 1100-1500 A.D., Including a Section of Incipits of Works on the Pater Noster\\\\u003c/i\\\\u003e. Cambridge (Mass.), 1979.\\\\u003c/div\\\\u003e\\\\n\\\\u003c/div\\\\u003e\\\\u003c/li\\\\u003e\\\\u003cl

in 1 minute	5	default	RecordIndexStatusJob
--
  | {"_aj_globalid"=>"gid://exhibits/DorHarvester/6439"}, "fz541vq7367", {"ok"=>false, "message"=>"#<RSolr::Error::Http: RSolr::Error::Http - 400 Bad Request\nError: 'Exception writing document id xj416ct0118 to the index; possible analysis error: Document contains at least one immense term in field=\"zotero_bibliography_ssi\" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped. Please correct the analyzer to not produce such terms. The prefix of the first immense term is: \\'[60, 117, 108, 62, 60, 108, 105, 62, 60, 100, 105, 118, 32, 99, 108, 97, 115, 115, 61, 34, 99, 115, 108, 45, 98, 105, 98, 45, 98, 111]...\\', original message: bytes can be at most 32766 in length; got 38049. Perhaps the document has an indexed string field (solr.StrField) which is too large','code'=>400}}\n\nURI: https://solr.example.edu/solr/exhibits_stage/update?wt=ruby&commitWithin=500\nRequest Headers: {\"Content-Type\"=>\"application/json\"}\nRequest Data: \"[{\\\"id\\\":\\\"xd669dx1412\\\",\\\"exhibit_parker_public_bsi\\\":true,\\\"spotlight_exhibit_slug_parker_bsi\\\":true,\\\"exhibit_parker-00357808-6987-4f9e-9678-fbaad451fb91_public_bsi\\\":true,\\\"zotero_bibliography_ssi\\\":\\\"\\\\u003cul\\\\u003e\\\\u003cli\\\\u003e\\\\u003cdiv class=\\\\\\\"csl-bib-body\\\\\\\" style=\\\\\\\"line-height: 1.35; padding-left: 2em; text-indent:-2em;\\\\\\\"\\\\u003e\\\\n \\\\u003cdiv class=\\\\\\\"csl-entry\\\\\\\"\\\\u003eBevenot, M. \\\\u0026#x201C;The Oldest Surviving Manuscript of St. Cyprian Now in the British Library.\\\\u0026#x201D; \\\\u003ci\\\\u003eThe Journal of Theological Studies\\\\u003c/i\\\\u003e n.s., 31 (1980): 368\\\\u0026#x2013;77. doi:10.1093/jts/XXXI.2.368.\\\\u003c/div\\\\u003e\\\\n\\\\u003c/div\\\\u003e\\\\u003c/li\\\\u003e\\\\u003cli\\\\u003e\\\\u003cdiv class=\\\\\\\"csl-bib-body\\\\\\\" style=\\\\\\\"line-height: 1.35; padding-left: 2em; text-indent:-2em;\\\\\\\"\\\\u003e\\\\n \\\\u003cdiv class=\\\\\\\"csl-entry\\\\\\\"\\\\u003eBloomfield, M. W., B.-G. Guyot, and et al. \\\\u003ci\\\\u003eIncipits of L...
  | ActiveRecord::ValueTooLong: Mysql2::Error: Data too long for column 'index_status' at row 1: UPDATE `spotlight_solr_document_sidecars` SET `index_status` = x'2d2d2d0a3a6f6b3a2066616c73650a3a6d657373616...

</details>

**Comment by mejackreed** [comment]
@blalbrit are there query requirements for the Bibliography entries? If so what are they?

**Comment by mejackreed** [comment]
There is also indication that `_ssi` is being used too

**Comment by blalbrit** [comment]
@mejackreed the design and requirements ticket is here: https://github.com/sul-dlss/exhibits/issues/441 let me know if that's enough/too much/not enough detail for you.

**Comment by mejackreed** [comment]
Also looks like I already did this. But some of the existing data was holding onto the field in the `solr_sidecar_data`

**Comment by mejackreed** [comment]
Not relevant anymore as we are moving away from this approach.
