### ISSUE TITLE
Items with bounding box coordinates must display on show map

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#503]
I am confused about whether this is a bug or a feature enhancement. I thought that show map was supposed to be working for all flavors of the MODS geo extension: geonames, point coordinates, and bounding box coordinates. However, for this newly published exhibit (https://exhibits.stanford.edu/time-travel-japan) -- all items have bounding box coordinates, and they are not appearing on show map (item level view). Take this example: https://exhibits.stanford.edu/time-travel-japan/catalog/sg682vf1166. Attaching the mods-geo extension stanza for this item, as a reference point.
![japantravelthroughtime_sg682vf1166](https://user-images.githubusercontent.com/3210225/28134350-91994d2c-66f7-11e7-8686-4cd579011e2a.png)

**Comment by cbeer** [comment]
It doesn't look like the inline map was checked on the metadata configuration page?

**Comment by caaster** [comment]
@cbeer I missed this. Thank you for the reality check.
