### ISSUE TITLE
Data issue seems to be causing Spotlight bug in Copyright Renewals exhibit

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#508]
The year value (1990) is misaligned between the Author and Date fields. We have a number of other records that display in this way.
https://exhibits.stanford.edu/copyrightrenewals/catalog/RE495832UUID85c698b7-e86d-4f67-8c0b-dae8a50056aa

An example of data being displayed poorly is attached. 
NOTES from Chris Beer:
- the author field has no data and should not be displayed. i think that may be a bug in the spotlight code. 
- 
![screen shot 2017-07-13 at 9 16 00 am](https://user-images.githubusercontent.com/3210225/28176373-f47478b8-67ab-11e7-971a-ee66ab84cc23.png)
and isn’t really a metadata problem (not that Arcadia could do anything about it.. these records are only in some nasty row-based data format that we slurped in as exhibit custom fields)

**Comment by jkeck** [comment]
@caaster I believe this may actually be solved.  That same record has a new URL: https://exhibits.stanford.edu/copyrightrenewals/catalog/RE495832 and does't appear to exhibit this behavior any longer.

## Results
<img width="897" alt="result" src="https://user-images.githubusercontent.com/96776/39656111-85cbf07c-4fb2-11e8-9bfe-4858dc9d1701.png">

## Record
<img width="595" alt="record" src="https://user-images.githubusercontent.com/96776/39656110-85afc78a-4fb2-11e8-8056-d4e331822553.png">

**Comment by caaster** [comment]
Grooming tickets. Appears resolved per @mejackreed.
