### ISSUE TITLE
Thumbnail images don't always load

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#510]
User feedback via Feedback link:

> The Lanciani Digital archive is an amazing resource - thank you for making it available. However, I'm having a lot of problems with the interface. Many thumbnails and images don't load, or don't load completely; and when I go into full screen mode and enlarge the images, there is invariably one or more blocks of image that remain blurry and never resolve at the zoomed-in resolution. (I can send you screen grabs if you like.)

I think I've noticed the incomplete thumbnails loading myself recently, and confirmed with a couple of exhibits just now:

https://exhibits.stanford.edu/time-travel-japan/browse/changing-views-and-shifting-perspectives
produced 13 console errors of the type: `Failed to load resource: the server responded with a status of 500 (Internal Server Error) default.jpg`:

![changing_views_and_shifting_perspectives___travel_through_time__japan_-_online_exhibits](https://user-images.githubusercontent.com/101482/28434189-5379729a-6d43-11e7-9de1-2f43afb60eef.png)
----
A Lanciani feature page:

![snapshots_of_work_and_industry_in_rome___images_of_rome_-_online_exhibits](https://user-images.githubusercontent.com/101482/28434204-57b6777c-6d43-11e7-8ddf-707a44fc20c7.png)

**Comment by mejackreed** [comment]
I'm seeing thumbnails and images out in a lot of different places. I think this is related to the stacks LB problem.

**Comment by ggeisler** [comment]
Okay, thanks @mejackreed

**Comment by caaster** [comment]
@ggeisler @mejackreed I haven't heard of any recent complaints so I wasn't clear if the LB problems have been adequately resolved, and whether or not I should leave this ticket open?

**Comment by mejackreed** [comment]
Let's close it. Thanks @caaster
