### ISSUE TITLE
Bug: SDR item (druid) version 1 & version 2 of same druid both appear in exhibit, even after reindexing

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#514]
The Bookplate exhibit (https://exhibits.stanford.edu/digital-bookplates) is not yet published, but it will be ready for publication soon. Many bookplates, which have already been added to the exhibit, (individual druids) have poor quality images, and they are slowly being replaced in the SDR by versioning the item, uploading a new image, and unpublishing the old image from stacks. Here is an example:
https://argo.stanford.edu/view/druid:mj882wf6508

After reindexing the exhibit, and executing a search for the above bookplate using the keyword: Zenoff

.....here is the search result that displays:
![screen shot 2017-08-01 at 9 04 05 am](https://user-images.githubusercontent.com/3210225/28835249-992822d2-7699-11e7-91a4-e6c74107fd5e.png)

I expect, after reindexing, to see only the most current version of the item in the exhibit.

**Comment by mejackreed** [comment]
I'm seeing those as two separate druids. When an item is versioned does it get a new druid?

**Comment by caaster** [comment]
You are 100% correct, Jack. My mistake, There is a different issue going on here, and not a Spotlight problem.
