### ISSUE TITLE
Update exhibits.stanford.edu masthead

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#519]
Waiting for final approval from Stu.
<img width="703" alt="screen shot 2017-08-03 at 10 18 18 am" src="https://user-images.githubusercontent.com/3210225/28934282-2f69326c-7835-11e7-88a3-c3cbce5d8f3f.png">

**Comment by ggeisler** [comment]
Based on further discussion the update has been made, substituting "showcases" for "exhibits" in the tagline.

![spotlight_at_stanford](https://user-images.githubusercontent.com/101482/29587346-8cef0c38-8742-11e7-9ff4-d4201f699fb3.png)
