### ISSUE TITLE
Enable theming and omit SUL and SU footers from Parker exhibit site

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#527]
Based on discussion with @blalbrit, the  Parker use case requires not showing the SUL and SU footers for the Parker exhibit (because they overemphasize Stanford's role in the partnership).

Presumably this would involve a Parker CSS override to simply hide the footer elements from the exhibit when the exhibit is Parker.

If we do this, we will probably be able to not worry about #446.

**Comment by ggeisler** [comment]
If we can conditionally activate a `parker.scss` file when the users loads the Parker exhibit, omitting the SUL and SUL footers seems very easy:

1. Add `@import "modules/parker";` to the end of `assets/stylesheets/sul_theme.scss`
2. Add a new `parker.scss` file to `assets/stylesheets/modules`
3. Add SCSS to the `parker.scss` file:

```scss
.sul-footer,
#global-footer {
  display: none;
}
```
4. Ensure the Parker CSS is loaded when a user visits the Parker exhibit URL.

Along with some other CSS overrides this change could contribute to the "Additional visual design for Parker" goal in #443. As a simple example (actual homepage would be designed more interestingly), the site would look like this without the footers:

![exhibit-without-footers](https://user-images.githubusercontent.com/101482/29294518-9d26907e-8104-11e7-8112-3f2b4466242e.png)

**Comment by jkeck** [comment]
Spotlight does have a theme switching function that might be useful here.

**Comment by blalbrit** [comment]
See additional discussion in #446
