### ISSUE TITLE
Enable curators to remove items from exhibits

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#532]
If we're able to implement #485, we might consider also enabling curators to remove items from their own exhibits, since this has been requested in the past. If a curator can remove items from an exhibit, the "Public" field associated with items can be used just as originally intended (to temporarily hide an item from view) and the remove action can be used for cases where the curator accidentally added the wrong item, or it became clear later on that an item is not appropriate for the exhibit.

We could enable the curator to remove an item in two places: from the list of items on the Curation > Items page, or from the Item Detail page of a given item. (The mockups here don't propose adding a bulk remove option for the curator, although we could consider that later. For now, perhaps we should just rely on the superadmin's ability to do bulk removal, as proposed in #485.)

### Curation > Items page

This simply adds a "Remove" action to the existing View and Edit actions show below the title of each item:

![curation-items-add-remove-action](https://user-images.githubusercontent.com/101482/29481135-c896678a-8432-11e7-890d-ce7a0158b842.png)

As noted in the mockup, we should show a confirmation modal if the user chooses to remove an item, and a flash message indicating the outcome of the action.

### Item Detail page

Especially in exhibits with many items, it might be easier for the curator to remove an item by going to the detail page directly and editing the page. In the mockup below, I added the Remove button just above the Public checkbox control and floated the button right so it ends up positioned as shown:

![item-edit-remove-from-exhibit-button](https://user-images.githubusercontent.com/101482/29481200-4820b01e-8433-11e7-96a9-80e710c8e3b3.png)

When the user uses the Remove button from the Item Detail page, we should show the same confirmation modal and flash message as in the mockup in the section above.

### Question

Is it feasible to tell the user in the confirmation modal if the item to be removed is being used in one or more widgets? If so, the confirmation modal could read:

> Are you sure you want to remove this item from this exhibit? This item currently appears in one or more pages in the exhibit. If you remove it, you should review any pages in which it previously appeared to make any necessary updates.

(I'm not sure what actually happens if we delete an item that is used in a widget, so we can update that text as appropriate.)

**Comment by caaster** [comment]
Three comments:

1) Since the need to remove objects from exhibits, when it has surfaced, has involved many objects (not just onesies/twosies), it is desired to have a way to remove objects in bulk.
2) Since objects may need to be removed from an exhibit where the collection druid was added instead of individual object druids, this will provide an interesting implementation challenge, perhaps? 
3) I'd be super-thrilled, if a compromise is necessary, to provide this functionality to exhibit super-admins only (like me) -- instead of providing it to exhibit creators. Just wanted to toss this out there.

**Comment by jkeck** [comment]
Just as a general comment, this is something that we'll want to do upstream in Spotlight itself.

**Comment by jkeck** [comment]
Closing this for now as it's not likely that we'll do anything in exhibits for this. The design artifacts here are good and will be helpful for anybody trying to create this feature upstream, so we may want to add these to an issue somewhere in Spotlight itself.

For now, if we do go w/ a local solution, we're looking at something like #485
