### ISSUE TITLE
Ability to select page to display for multi-page item in UV doesn't work (didn't work with sul-embed either)

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#536]
As an exhibit creator, I have created a feature page for an exhibit: https://exhibits.stanford.edu/paci/feature/reaching-out-to-chinese

On the feature page, I am using several widgets. I am using the item embed widget to display druid:kq228ws6597 -- which is a multi-page object. I want page 3 to display as the default, so I am using the "change" option afforded to select page 3. Although in the widget/edit mode, it appears that my selection of page 3 as the default has been chosen (even when I hit "save") -- unfortunately page 1 still displays.

**Comment by mejackreed** [comment]
I would maybe characterize this as a feature enhancement to embed and potential of a design change for Exhibits. 

Embed does not offer the ability to "start" on a specific canvas. Some historical context in embed here: https://github.com/sul-dlss/sul-embed/issues/313

I offer the "design" question here as we probably should not present to users that this is something possible.

**Comment by ggeisler** [comment]
This is not a bug, then, but a loss of functionality that resulted from the move to UV as the viewer. The Embed widget thus now presents a option in the UI that doesn't work. Unless we can expect https://github.com/sul-dlss/sul-embed/issues/313 to be worked on soon (that ticket is open and @snydman says he thinks it's important, but based on @mejackreed's comment above it doesn't sound like we should expect it to be resolved soon), I'd suggest we just remove the page change option from the Embed widget UI.

**Comment by caaster** [comment]
So, @ggeisler -- I should create a new ticket for that -- to change the UI for the Embed option?

**Comment by mejackreed** [comment]
I think its fine to stay here. Just update the acceptance criteria.

**Comment by caaster** [comment]
Already created a ticket #827 to change the UI. I'll let this ticket stand because we'd love to have the functionality back in the future if possible.
