### ISSUE TITLE
Exhibit analytics are intermittently unavailable

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#537]
Clicking on analytics in the dashboard often returns a page that says, "Something went wrong". I can often "trigger" this behavior by clicking on analytics in a particular exhibit -- where I often get a positive result (ie, the analytics do display) -- and then a few minutes later, returning to the same exhibit and clicking on analytics again, where I will see the "Something went wrong" message.

**Comment by mejackreed** [comment]
I'm not able to recreate this. Is this still an issue?

**Comment by caaster** [comment]
Closing as I have not seen this issue happening anymore.
