### ISSUE TITLE
Newrelic not loading.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/exhibits#538]
On this page: https://exhibits.stanford.edu/1947-partition/browse/interviews
In Firefox
I'm seeing this in the javascript console: 
```
Loading failed for the <script> with source “https://js-agent.newrelic.com/nr-1044.min.js
```

**Comment by jkeck** [comment]
I'm not able to reproduce this in either Chrome or Firefox (and we appear to be receiving New Relic data).  Feel free to re-open if I've missed something.
