### ISSUE TITLE
For a bibliography item enable link to Zotero bibliographic item

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#539]
As a user of Parker on the Web,
I want to be able to click on a bibliographic item and be linked to the full bibliographic item in Zotero online,
In order to be able to see additional notes and commentary provided by the library (which includes manuscript-specific notes).

Ok, it sounds like the work here is:

- [ ] Modify the bibliography show page to include the "View on Zotero site" button -- see PR #670.
- [x] Modify the bibliography on the manuscript show page to have a link to View in Zotero. This is done in #660.

**Comment by mejackreed** [comment]
We plan on indexing the notes field and displaying them on a "Reference" show page. Is this issue still valid then?

**Comment by blalbrit** [comment]
Yes, please keep link back to Zotero item as a requirement.

**Comment by ggeisler** [comment]
I've updated the mockup in #605 to include a button that links to the bibliographic item's Zotero page. 

@mejackreed I assume this is feasible? 

@blalbrit assuming this is feasible, let us know if this doesn't satisfy the requirement in this ticket.

**Comment by blalbrit** [comment]
@ggeisler - this looks quite nice. One question, can a user navigate from a manuscript show page instance of the citation back up to the bibliographic item show page? I may just be missing that in the design docs, so if it's already there just let me know where.

**Comment by blalbrit** [comment]
If the user can navigate from a manuscript show page citation back to the main bibliographic record show page, and from there navigate out to Zotero, that satisfies the requirement.

Can I ask you both (@mejackreed & @ggeisler ) - would it be worth a quick review, for the three of us, just to make sure we're all on the same page? I find it hard to aggregate the wealth of ideas that crop up in tickets and wouldn't mind a quick discussion about current Parker 1.x functionality and the possibilities that are emerging in the design docs.

**Comment by ggeisler** [comment]
@blalbrit I believe the answer to your question above is Yes. Happy to discuss more via Zoom or whatever but I'll also document the relevant user paths here:

* Manuscript show page - this is the standard document show page already in the exhibit. We're enhancing it with a list of the bibliographic references associated with that manuscript (similar but improved from what we did earlier in the year). If a user is viewing the manuscript show page and clicks on a given reference, they will go to the reference show page as mocked up in #605.

* Reference show page - this is the new page shown in #605. The user can get there from the manuscript show page as described in the previous bullet, _or via a search result page_. Reference items will be shown in search results, similar to standard (manuscript) documents, so the difference is just that for a reference search result item, the user ends up at a slightly different-looking show page, the one in #605. From that page the user can also go to the reference on the Zotero site.

**Comment by blalbrit** [comment]
Thanks @ggeisler - this answers my question, and I think this satisfies requirements.

**Comment by drh-stanford** [comment]
Related to #585

**Comment by drh-stanford** [comment]
Ok, it sounds like the work here is:

- [ ] Modify the bibliography show page to include the "View on Zotero site" button
- [ ] Modify the bibliography on the manuscript show page to have a link to View in Zotero. This is done in #660.
