### ISSUE TITLE
Embed + Text widget display needs updating

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#542]
(I'm not sure off-hand if this is a Spotlight problem or specific to Exhibits; I'll move to the Spotlight repo if I figure out later it's applicable there.)

When using the "text align: right" option for the Embed + Text widget, the text can overlap the embed if the embed width exceeds the width allocated for the six columns assigned to it (bottom example below):

![kogu_me_lugu__digital_video_interviews___the_baltic_video_archive_-_spotlight_at_stanford](https://user-images.githubusercontent.com/101482/30232817-d656b09e-94a6-11e7-8278-c233bca1d803.png)

We might need to look at another way of presenting the embed and text side-by-side that doesn't use the 6 | 6 columns (or we might need to use a maxwidth on the embed column, but we'd then also need to respect the aspect ratio of the width and height given in the embed code).

When fixed, update EXHBTF-307 in JIRA so the reporter is notified.

**Comment by ggeisler** [comment]
@caaster I submitted a [PR](https://github.com/projectblacklight/spotlight/pull/1907) to Spotlight to fix this. If and when it is merged and a release with the fix is included in Exhibits, we can notify the feedback reporter via EXHBTF-307.

**Comment by caaster** [comment]
@ggeisler This issue was just reported again, so I am adding this for the record. Also wondering about the status of the merge etc.

**Comment by jkeck** [comment]
This was resolved in projectblacklight/spotlight#1907

That will come out in the next release of Spotlight (which should be at the beginning of this week).

**Comment by ggeisler** [comment]
@caaster I've verified the issue reported in EXHBTF-307 in JIRA is fixed in the latest release to -prod and am closing this ticket.

Note that it looks like the reporters of this issue have changed the page so that the text is always on the same side of the embed, which makes it harder to tell that the problem is fixed on their page, but I temporarily reversed the side with the text just to show that the issue is fixed. Compare the screenshot in the original ticket description to this:

<img width="478" alt="kogu_me_lugu__digital_video_interviews___the_baltic_video_archive_-_spotlight_at_stanford" src="https://user-images.githubusercontent.com/101482/37176677-45832b5c-22da-11e8-9799-22adc550c279.png">
