### ISSUE TITLE
Support date ranges in display and facets

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#548]
Story:
Metadata for special collections materials often provides date values as approximate ranges. Exhibit curators would like to provide an accurate representation of this information for users, with functionality on par with SearchWorks.

Acceptance criteria:
- [x]  The date display field should represent the values of /mods/originInfo/date*[@point=”start”] and /mods/originInfo/date*[@point=”end”] (where date* is dateCreated, dateIssued, or dateCaptured) as a range, and include the value of the qualifier attribute when present. 
 - [ ] A date slider facet (#994, #971) that works for date ranges in metadata should be available.

**Comment by blalbrit** [comment]
For Parker, see: https://purl.stanford.edu/cf386wt1778 for instance.

**Comment by caaster** [comment]
A researcher using the Herbert Matter exhibit has reported their confusion that many of the image descriptions are annotated: "[1937]" -- which is actually incorrect for many images. For accuracy/better research it would be helpful for both the approximate start and end dates to be displayed. Here is an example from the exhibit: https://exhibits.stanford.edu/herbert-matter/catalog/rx795tx1655

**Comment by arcadiafalcone** [comment]
To expand on this --
What displays in Spotlight:
1937
What should display (by mods_display rules):
[ca. 1937-1984]

Often with archives if an individual object is undated, the date span of the collection as a whole will be applied to the object to give at least a rough idea of the time period. Omitting the date range and qualifier (#551) creates a significant difference between the information in the metadata and what is displayed to the user.

**Comment by mejackreed** [comment]
Thanks for the help @arcadiafalcone and @caaster ! We have implemented the display in #906, looking into the date range facet slider seems to bring up more questions for me.

It seems like in SearchWorks (for SDR content) we index a single year. See: https://github.com/sul-dlss/sw-indexer/blob/master/lib/sw_mapper.rb#L102

We can do this same behavior in Exhibits, but it doesn't solve the range issue. Should we move ahead without the range information (and just use StanfordMods `pub_year_int` logic) ? If not I think we need more information about how StanfordMods should parse and understand an indexed date range.

**Comment by arcadiafalcone** [comment]
I hadn't realized the date slider facet in SearchWorks doesn't handle MODS date ranges. I would rather update the slider to have range functionality before implementing it in Spotlight. Having the slider reference only a single date causes relevant objects to disappear from facet results, and does so in a way that is completely invisible to the user, unless they already know the content well enough to realize that something is missing.
