### ISSUE TITLE
Support date qualifiers in display

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#551]
Story:
Dates are sometimes given as approximations using the “qualifier” attribute. Exhibit curators would like to provide an accurate representation of date uncertainty for users.

Acceptance criteria:
- Single date display should include qualifier information. (This reproduces current SearchWorks behavior.)
- Date range display should include qualifier information. (This reproduces current SearchWorks behavior.)

**Comment by mejackreed** [comment]
Our current mods_display has this working already in some capacity:
https://exhibits-stage.stanford.edu/mss/catalog/tw368kj5707
<img width="587" alt="screen shot 2017-11-16 at 11 02 00 am" src="https://user-images.githubusercontent.com/1656824/32910264-9eee49da-cabd-11e7-9bab-dc6e9fee5fc2.png">

SearchWorks displays this a bit differently:

<img width="375" alt="screen shot 2017-11-16 at 11 02 56 am" src="https://user-images.githubusercontent.com/1656824/32910298-b9bd800a-cabd-11e7-9813-44aabf6aee04.png">
https://searchworks.stanford.edu/view/9272935

Does the current implementation meet the Parker / Exhibits needs? How should it display?

cc @blalbrit @jvine

**Comment by arcadiafalcone** [comment]
The SearchWorks example above is pulling from the MARC record (and also, the MODS was converted from the MARC so the "circa 1400" is a literal and not encoded as a qualified date in MODS). For MODS the date displays the same as in the exhibits modal.

The MODS display varies depending on the qualifier used.
approximate: [ca. 1900]
questionable: [1900?]
inferred: [1900]

**Comment by arcadiafalcone** [comment]
To clarify (thanks, @jvine), this ticket is about the display of dates in the curator metadata, not as driven by the mods_display gem in the modal. The curator metadata dates should display according to the same rules as what is currently used in the modal.
