### ISSUE TITLE
Add values of /mods/subject/genre to “Genre” field

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#554]
Story:
Genre terms may also appear as part of a subject. Exhibit curators would like all genre information to be available for users, regardless of where it appears in the record.

Acceptance criteria:
- The genre display field should include the values of /mods/genre and /mods/subject/genre, deduplicated.
- The genre facet field should include the values of /mods/genre and /mods/subject genre. (This enhancement could also apply to SearchWorks.)

Fixture objects are in #889, and 1-3 apply

**Comment by cbeer** [comment]
Fixed by #917.
