### ISSUE TITLE
Create a field for place of origin

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#564]
Story:
In MODS, the place of origin for an object is often entered as a term from a controlled vocabulary such as the Library of Congress name authority file or the MARC List for Countries. Exhibit creators would like to leverage this data in faceting and display so that users may better explore and understand the different geographic contexts for objects in an exhibit.

Acceptance criteria:
1. A facet field should be available that contains only the values of /mods/originInfo/place/placeTerm[@type=”text”].
2. A display field should be available that contains only the values of /mods/originInfo/place/placeTerm[@type=”text”].

Fixture objects are in #889, and 1-5 apply

**Comment by mejackreed** [comment]
What should the label be for the field?

Should this be consolidated with our geographic_facet "Region" that we already have or would we then have two facets that represented place?

Should this be enabled by default on all exhibits (or opted in to)

**Comment by arcadiafalcone** [comment]
This should be a separate field from Region. Region is about the content of the resource, while place of origin is about its provenance.

For labels, "Place of origin" or "Place created" (to parallel "Date created") make sense to me. Enabling by default would be preferable.

See also #565. The reason for handling these two separately is that they are at different levels of granularity - the field in this ticket is usually at the city level, whereas the one in 565 is only at country or state level.

**Comment by mejackreed** [comment]
@blalbrit are there parker objects that have this? Can you link them?

**Comment by blalbrit** [comment]
@mejackreed - see for instance: https://purl.stanford.edu/wp146tq7625.mods

I'll try to find others that have secure originInfo.
