### ISSUE TITLE
Make all descriptive metadata for an object available for display

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#566]
Story:
Exhibit creators would like their exhibits to benefit from the significant labor involved in creating quality descriptive metadata by being able to provide any or all of that data to users.

See attachment.

**Comment by caaster** [comment]
[#566 notes.docx](https://github.com/sul-dlss/exhibits/files/1364036/566.notes.docx)

**Comment by blalbrit** [comment]
See #816 for design and implementation

**Comment by caaster** [comment]
Closing this because we now have the "More details" button on the item view, which displays all MD on the PURL page for the item.
