### ISSUE TITLE
Create a facet for repository name

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#570]
Story:
Several current Spotlight exhibits showcase materials not held by Stanford, and more are in process. Exhibit creators would like to provide a facet enabling users to limit their results to objects held by a particular institution.

Acceptance criteria:
- A facet field should be available that contains the value of /mods/location/physicalLocation[@type=”repository”].

**Comment by mejackreed** [comment]
Could you please provide an object that has this data?
