### ISSUE TITLE
Design for manuscript show page including bibliographic items

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#576]
I believe @ggeisler has already done these. Link to those here?

**Comment by blalbrit** [comment]
See #441

**Comment by ggeisler** [comment]
The mockup below updates slightly the previous design to reflect recent comments in Slack from @blalbrit, specifically:
 
- The bibliography list entries are now formatted with a hanging indent
- The title of each bib entry is linked to a show page for that entry, as proposed in #605.

(Note that the data shown in the mockup is not accurate in terms of the real bibliography data for the document shown.)

![show-page-with-bib-items](https://user-images.githubusercontent.com/101482/30941775-055ca3b8-a39c-11e7-89a2-b740728871ab.png)

**Comment by drh-stanford** [comment]
One concern I have is that these hyperlinks use the title as the anchor. It'll be some extra work to get that to render correctly I think. We may need to modify the CSL or somehow do a search and replace on the title. If there's another way to do the linking that makes sense, I'd be interested to hear.

**Comment by ggeisler** [comment]
@drh-stanford Yeah, I wanted to present that as the preferred approach, but I realize that it might not be feasible to wrap the link around just the title portion of the reference.

If it isn't feasible, we can just add a distinct "View full reference" link after each bib item instead. It'll just make the list a bit more busy.

I can update the mockup to provide a more exact recommendation.

**Comment by mejackreed** [comment]
We could also link them to a bibliography show page. And within a bib show page link all of the cited articles

**Comment by ggeisler** [comment]
@mejackreed That's what they are linking to in the mockup, unless I'm misunderstanding your meaning. They link to the page mocked up here: https://github.com/sul-dlss/exhibits/issues/605

**Comment by mejackreed** [comment]
Perfect @ggeisler sorry I misunderstood.

**Comment by ggeisler** [comment]
@drh-stanford Here's an updated version of the mockup, with the links distinct from the reference itself. If the CSS needed to match the mockup gets tricky, I can work on that after the basic implementation is done.

![show-page-with-bib-items-v2](https://user-images.githubusercontent.com/101482/30984159-6ad137c2-a441-11e7-8c27-da5b7fd18f77.png)
