### ISSUE TITLE
Analysis: citeproc / view approaches

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#578]
Placeholder: @mejackreed can you expand?

Requirements:
- [x] Generate a bibliographic reference in a single style
- [x] Sort the references (by author-date? or what?)
- [x] Show notes (not required)

**Comment by mejackreed** [comment]
This is likely dependent on #588 and #587 /

**Comment by mejackreed** [comment]
Also we should look at performance of CiteProc (potential concerns for CiteProc in Ruby)

**Comment by drh-stanford** [comment]
I got a reply from Zotero technical support on the feasibility of exporting formatted references along with the records (TL;DR "not really")

> Hi,

> I have a large Zotero library (6,000+ records) and I want to export them into the BibTeX format to use in my custom application. I need, however, the formatted bibliography for each record stored within the BibTeX -- that is, for each item key I need the styled reference for it.

> I verified that the Zotero API will allow me to retrieve a formatted bibliography for a given style for a given item (e.g., format=bib&style=apa), but I'm concerned that I need to make 6,000+ API requests to get these formatted bibliographies for each item in my library anytime I want to export it.

> I can use the Create bibliography... feature in the desktop Zotero application, but I haven't found a way to relate those formatted bibliographies back to the BibTeX records.

> Any advice?

> Thanks,
> -Darren

> adamsmith  7 minutes ago
> There's no reasonably easy way to do this: The citations and the bibtex are generated by different code that can't call each other. 
> The two things I can think of are 
> a) to include some code to generate basic citations into the bibtex translator. The degree to which this will work depends on the nature of your data and how good the citations need to be. 
> b) to generate the bibliography with some sort of unique marker included (e.g. in the extra field) and use that to match to bibtex in a post-processing script.

**Comment by drh-stanford** [comment]
Re: notes. @blalbrit suggests that we "don’t bring in the notes and always link out to the Zotero item" -- we can use the URL to show the full Zotero record (with notes and attachements), like so:

  https://zotero.org/groups/1051392/items/ZDIFTVQJ

Since the Parker library is public, anyone can view these links.

**Comment by mejackreed** [comment]
We have the notes by default at the moment. .we can just choose not to meet them.

**Comment by drh-stanford** [comment]
I've done measurements on how long it takes to generate citations in `citeproc` and it's fairly fast -- 6k+ items in 40 seconds:

```
$ time bundle exec ruby test.rb  > out.html

real	0m39.164s
user	0m35.244s
sys	0m1.961s
```

using this code in `test.rb`:

```ruby
require_relative 'config/environment'

# .convert :latex is needed to remove LaTeX markup inside BibTeX fields
bibliography = BibTeX.open('ParkerProductionBibliography.bib').convert :latex
cp = CiteProc::Processor.new style: 'chicago-author-date', format: 'html'
cp.import bibliography.to_citeproc

puts '<dl>'
bibliography.map(&:id).each do |id|
  formatted = cp.render :bibliography, id: id
  puts '<dd>' + formatted.first.to_s + '</dd>'
end
puts '</dl>'
```

**Comment by mejackreed** [comment]
That's great! Definitely will work nicely in indexing, and perhaps on the fly search results?
