### ISSUE TITLE
Sidekiq memory holding on in Production

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#580]
We have an issue in production where memory for our worker machine will start expanding and then start alerting. It is a very slow leak. Relevant sidekiq docs: https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting

In the past we removed `sidekiq-statistic` in the hopes that was an easy fix, but alas no. 

Likely this issues comes from a job that we run that uses ActiveRecord. This comes from a conversation with Sidekiq maintainer about pros v cons of SidekiqPro:

> Excessive memory consumption within your Sidekiq processes is due to application code, usually ActiveRecord usage.

We need to solve this in some way. Probably the best way would be to figure out which Job is holding onto the memory and then fix that application code.

**Comment by jkeck** [comment]
We've purchased a SidekiqPro subscription (that as best we can tell we will be able to use w/ various other apps that use Sidekiq under the same license).

We'll take a wait and see approach to see if this mitigates the problem itself.  If the issue arrises again, we may be able to use something like [Worker Metrics](https://github.com/mperham/sidekiq/wiki/Pro-Metrics) to help us suss out what's going on.

**Comment by jkeck** [comment]
Another thought I had when writing this up is if this comes up again, we should immediately (w/i 24 hours) see if we can gain any insight by looking at our [NewRelic Transaction data](https://rpm.newrelic.com/accounts/907124/applications/28077669/transactions?type=ActiveJob::Sidekiq&show_browser=false)

**Comment by mejackreed** [comment]
Potentially useful here and perhaps some easy wins: https://www.mikeperham.com/2018/04/25/taming-rails-memory-bloat/

**Comment by mejackreed** [comment]
And even more info: https://www.speedshop.co/2017/12/04/malloc-doubles-ruby-memory.html

cc @eefahy
