### ISSUE TITLE
Update UI for uploading bibliography file in Admin

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#586]
Related to #574

**Comment by ggeisler** [comment]
Requirements:

- Method of initiating a bibliographic data upload
- progress indicator (nice to have)

**Comment by mejackreed** [comment]
@ggeisler we added this (can be enhanced though) See:

![bibupload](https://user-images.githubusercontent.com/1656824/31081663-940f3e38-a75a-11e7-828b-e733660f0862.gif)

**Comment by camillevilla** [comment]
Per discussion 10/2, @ggeisler would like to redesign our current tab set up

**Comment by ggeisler** [comment]
Some background for why I'm making this more complicated than just adding the BibTex button as in the gif above: my concern is that there's no clear reason (at least from a non-technical user point of view) why the BibTex button is under "External resources" tab but to add resources via JSON file or IIIF URL you don't look under that tab but instead use dedicated tabs for those methods. We could make them more equivalent by adding an additional dedicated tab for BibTex, but I think we already are at the reasonable limit for top-level tabs on the page.

The mockup below will take a little more work to implement because of the rearrangement of existing tabs, but I think the new arrangement is a more logical and will be easier to extend if we want to include even more ways to add items in the future. This is the proposed page if the BibTex secondary tab is selected:

<img width="1214" alt="bibtex-panel" src="https://user-images.githubusercontent.com/101482/31202282-cc80afb4-a916-11e7-8339-2267517d63c5.png">

For context, here's what things look like if SDR is the selected secondary tab:

<img width="898" alt="sdr-panel" src="https://user-images.githubusercontent.com/101482/31202411-5cbb9224-a917-11e7-88fd-8b88a0f23957.png">

The JSON, IIIF, and CSV tab panels have the same content they currently do, they are just moved from primary tabs to secondary tabs of the "External resources" primary tab. For example:

<img width="876" alt="iiif-panel" src="https://user-images.githubusercontent.com/101482/31202448-8516c130-a917-11e7-80c5-3e4ff3776980.png">

The "Upload single item" tab remains unchanged, since it is distinctly different from adding items via the other methods.

**Comment by camillevilla** [comment]
Per story time discussion 10/5: the team noted this will require upstream changes in Spotlight and/or updating our Spotlight version.

**Comment by ggeisler** [comment]
If we decide to go with something simpler (hopefully just for the short-term) to avoid breaking Spotlight, I suggest some minor updates to the existing implementation:

- [ ] Change the label of the bib button to "BibTex"

- [ ] Use horizontal alignment of the label and input (for consistency with the presentation with the other resource options)

- [ ] Add the following hint text below the file picker input (assuming this wording makes sense to others):
> Each BibTex file entry will be added as an exhibit item with a “Reference” resource type.

**Comment by camillevilla** [comment]
@ggeisler those sound doable to me. I'll split off an implementation ticket for the short-term changes and leave this ticket open for now.
