### ISSUE TITLE
How large is the complete bibliography file?

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#587]
- [x] What format is it?
 - [x] What formats can we get?
 - [x] How do format types affect overall size?

Should we use bibtek over html for example

**Comment by drh-stanford** [comment]
See #573 for examples. The export of 6k+ records was 2+MB in BibTeX format. 

The Zotero desktop application provides a dozen or so export formats:

![Screen Shot 2017-09-25 at 4.06.55 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56424074872c261800e4abc9/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772a6456f66b7191a37cf1122d4f5a5a5ecc3c4a4356bcbbd671f3e57862804e0eead6685622923511afbc821db600b3208b498ce4b5db4cd2f42f67b6d5db1063474f4dcbed5727a19e41c95df64de24555ac11306be2742431.png)

**Comment by camillevilla** [comment]
Including @drh-stanford's comment from #593 about Zotero export for later reference:

> BTW, none of the export formats that I could access from the Zotero web UI had the ability to export the Notes information. The desktop Zotero UI does allow exporting of notes. So, it's important to do exporting ONLY via the desktop Zotero application.

**Comment by drh-stanford** [comment]
From standup today, @caaster will verify with @blalbrit that 6k records is the correct count for the complete Parker bibliography.

**Comment by blalbrit** [comment]
For the current bibliography there are 6165 objects @drh-stanford

**Comment by blalbrit** [comment]
@camillevilla and @drh-stanford : I have looked into exporting notes and have had no luck in any format with the desktop client. Have either of you succeeded in doing so?

**Comment by camillevilla** [comment]
@blalbrit I'm able to get notes in BibTeX and MODS, but not CSL JSON. 

![export_with_notes](https://user-images.githubusercontent.com/5402927/30881021-3bf7ba5e-a2b9-11e7-8a6f-ee00e259dfb6.png)

It looks like they did a bunch of Zotero development work this summer. Have you updated your desktop client recently? I have 5.0.21 .

**Comment by blalbrit** [comment]
@camillevilla - awesome, thanks for the pointer! Looks like I'm several point versions behind, will update.

**Comment by drh-stanford** [comment]
The customized CSL JSON is available in our box folder under `Zotero Exports > Zotero > translators`. You need to drop it in your `~/Zotero/translators` folder and restart the Zotero desktop application then do an Export...

**Comment by drh-stanford** [comment]
I think we have the answers we need in this ticket, so I'm closing it.
