### ISSUE TITLE
Research Zotero id, and potential implications on CRUD 

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#588]
We have an add/update/delete problem. How do we track citations and when they are updated? (Does zotero provide a unique id?)

**Comment by drh-stanford** [comment]
The Zotero IDs are available in some export formats natively (like TEI), and we've been successful in exporting them in BibTeX and CSL JSON using customize translators. An identifier looks like this:

```
http://zotero.org/groups/1051392/items/E3MS2TQK
```

The first id is the group identifer and the second is the specific record identifier. For our purposes the group identifier will not change, but it is a private group.

So, we can track citations based on these unique identifiers. Adding and updating should be straight-forward, but deleting may not be. When we do a synchronization, we need to have a complete list of identifiers that are in the library, and then delete any bib resources that are omitted. It's not clear whether deletes will be happening in the Parker bibliography though.

The Zotero library is internally a SQLite database and its `items` table looks like this:

```sql
CREATE TABLE items (
    itemID INTEGER PRIMARY KEY,
    itemTypeID INT NOT NULL,
    dateAdded TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dateModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    clientDateModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    libraryID INT NOT NULL,
    key TEXT NOT NULL,
    version INT NOT NULL DEFAULT 0,
    synced INT NOT NULL DEFAULT 0,
    UNIQUE (libraryID, key),
    FOREIGN KEY (libraryID) REFERENCES libraries(libraryID) ON DELETE CASCADE
);
```

The `key` is the item's identifier that's in the URI identifier, and it doesn't appear to change once the item is created.

**Comment by drh-stanford** [comment]
Confirmed with @blalbrit that deletes from the Parker bibliography are very rare (if ever). We can assume that additions and updates are the requirements. And this should be possible via the unique `key` field
