### ISSUE TITLE
Relate indexed bibliography object to indexed druid parent

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#589]

**Comment by camillevilla** [comment]
Here's where to find druids in our 3 fixture formats:

### MODS: 
```xml
<subject>
  <topic>mk707wk3350</topic>
</subject>
```

### BiBTeX:
`keywords = {mk707wk3350, qw038wz9710, zg752jp4185}`

### CSL JSON:
```
"keyword": [
  "mk707wk3350",
  "qw038wz9710",
  "zg752jp4185"
]
```

**Comment by drh-stanford** [comment]
I have a PR in the works #626. There's some details in how we validate that there's a resource (manuscript) associated with a bibliography that still needs to be worked through.
