### ISSUE TITLE
Update mirador_rails gem to most recent Mirador release for better side panel styling.

### ISSUE THREAD

**Issue by aeschylus** [sul-dlss/exhibits#599]

**Comment by aeschylus** [comment]
http://projectmirador.org/demo/advanced_features.html

![screen shot 2017-09-27 at 14 16 06](https://user-images.githubusercontent.com/145874/31028368-76d26c82-a502-11e7-8928-d872e638eb3c.png)

**Comment by mejackreed** [comment]
In progress pending merge of: https://github.com/sul-dlss/mirador_rails/pull/8
