### ISSUE TITLE
Design for Show page for Bibliography Item

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#605]
I think we decided to make bib items first-class objects, and we do have a ticket for including bib items in search results (#575), but unless I've missed it I don't think we have a ticket for a bib item show page.

Below is a first-pass at a design. This is the show page the user would arrive at when clicking on a bib item in the search results, or from the Bibliography list on the show page for a document (manuscript).

(Note that the data shown in the mockup is not accurate in terms of the real documents associated with the bib entry shown.)

![spotlight_graffle__parker__public___bib_item_show_page](https://user-images.githubusercontent.com/101482/30941698-9c63fbcc-a39b-11e7-9105-c25d19436dd7.png)

**Comment by mejackreed** [comment]
We may also have the ability to provide a download of the raw `BibTeX` data for users

**Comment by ggeisler** [comment]
Below is an update, putting the notes into the metadata list. I also added the download button as @mejackreed suggested (I started mocking up a copy to clipboard option, which seems potentially useful, but much more involved to implement, so decided to leave it off, given we haven't heard a real requirement for it).

![bib-show-page-v2](https://user-images.githubusercontent.com/101482/30987009-58491de6-a44a-11e7-96b8-962c8e1971f5.png)

**Comment by ggeisler** [comment]
Minor update, just adds the "View on Zotero site" button, which would link to the reference item's page on the Zotero site.

![bib-show-page-v3](https://user-images.githubusercontent.com/101482/31025861-16088ade-a4f9-11e7-8d72-5ae57d2a6c07.png)

**Comment by aeschylus** [comment]
This depends on having a meeting to refine the bibTex fields.

See:

**Comment by drh-stanford** [comment]
See #589 for how to get the related documents to the given reference

**Comment by camillevilla** [comment]
Per dicussion with @blalbrit on 10/3, `Item Type` should be renamed `Reference Type` (e.g. Book, Journal Article). `Resource` type will be  `Reference`.

**Comment by camillevilla** [comment]
This design ticket will be closed. Implementation tickets will refer back to this.

**Comment by drh-stanford** [comment]
@ggeisler here's what the View on Zotero site button looks like when the Edit button is enabled:

![screen shot 2017-10-05 at 12 11 34 pm](https://user-images.githubusercontent.com/1861171/31247790-8748638c-a9c6-11e7-9044-8dad51cc0465.png)

@blalbrit do we want the "Download as BibTeX" button on the show page? The BibTeX is available to export, along with multiple formats, on the Zotero page. I haven't implemented that in #539 as yet.

![screen shot 2017-10-05 at 12 16 24 pm](https://user-images.githubusercontent.com/1861171/31247957-0b4be8c0-a9c7-11e7-8c78-b69042a5104d.png)

**Comment by mejackreed** [comment]
One question I have here. Since our approach allows a user to upload a generic BibTeX file (one not necessarily generated using our Zotero exporter) is there a way we can confirm that this is always going to be a URL?

Are there design implications of this?

**Comment by drh-stanford** [comment]
Good question. I don't think so. We could enable the View in Zotero only if the key was a link to the Zotero website in #670
