### ISSUE TITLE
For BibliographyResource, index "exhibit specific metadata"

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#607]
Spotlight does some magic to provide automatic indexed fields for us. Currently our indexing isn't getting this for some reason. The magic is happening here: https://github.com/projectblacklight/spotlight/blob/master/app/services/spotlight/solr_document_builder.rb#L13-L23

Split out of work on #601 

 - [x] get the `exhibit_test_public_bsi` and `spotlight_exhibit_slug_test_bsi` fields (#608 does this)
 - [x] get the `spotlight_resource_id_ssim` and `spotlight_resource_type_ssim` fields

**Comment by mejackreed** [comment]
This seems to stem from us (Traject) returning a Ruby hash with string keys and not the expected `unique_id = :id` Symbol key

**Comment by drh-stanford** [comment]
Also see #605 for design of bibliography show page.
