### ISSUE TITLE
When trying to edit an exhibit home page, "page does not exist" or "something went wrong" message is displayed

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#609]
This has been reported for 2 exhibits:
https://exhibits.stanford.edu/oral-history - published exhibit - "page does not exist"
https://exhibits.stanford.edu/baltic-video - unpublished exhibit - "something went wrong"

I have validated/been able to repeat the above behavior.

I have tried to edit the home pages of other published and unpublished exhibits, and haven't encountered a problem.

**Comment by caaster** [comment]
This ticket explains the root cause of the problem:
https://github.com/projectblacklight/spotlight/issues/1782

**Comment by camillevilla** [comment]
This will hopefully be resolved by projectblacklight/spotlight#1850
Similar issue from the Alcoa exhibit #788
