### ISSUE TITLE
Index the complete Parker bibliography

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/exhibits#616]
There's 6k+ bibliography items in the Parker production library in Zotero. Right now only 3.5k are indexing correctly. We need to ensure that we can index them all. I put the BibTeX export in our shared folder here:

https://drive.google.com/open?id=0B5fLh2mc4FCbSTF3LWZRd3dpR0E

See #608 for background.

Handle cases:
 - [x] no title (skip)
 - [x] missing optional fields (empty)
 - [x] `Bibliography.new().to_html` raises error

**Comment by mejackreed** [comment]
I'm getting an error which is failing the process:

```
2017-09-29T11:08:32.925Z 19910 TID-oxhjnwqho WARN: ArgumentError: wrong number of arguments (given 1, expected 0)
2017-09-29T11:08:32.926Z 19910 TID-oxhjnwqho WARN: lib/traject/bibtex_config.rb:15:in `to_s'
```

**Comment by mejackreed** [comment]
Apparently 2 records do not have titles: http://zotero.org/groups/1051392/items/NNHKWP6C and http://zotero.org/groups/1051392/items/6Q6TF4HD 

This seems like bad data. @blalbrit ?

**Comment by blalbrit** [comment]
@mejackreed not necessarily bad data, just currently incomplete. As they maintain the main bibliography, Parker staff occasionally come across partial references to publications which they then will track down later, verify, and fill out further.

**Comment by blalbrit** [comment]
^^ two out of ~6K doesn't seem too bad. If they wind up being unverifiable, then these could be removed from the solr index (and Zotero) by me, correct? (that was the impression I got from discussion with @drh-stanford about the need for administrative intervention in very rare instances).

**Comment by drh-stanford** [comment]
@blalbrit can we enforce that a bibliography needs to have a title to be indexed?

**Comment by blalbrit** [comment]
I would be happy with that - even if the title is a placeholder, I can train the stakeholders on that @drh-stanford

**Comment by drh-stanford** [comment]
An implementation note: You can use `context.skip!` in Traject to reject processing a given record. This may be better than validating all of the BibTeX records in the reader.

**Comment by mejackreed** [comment]
@drh-stanford #637 handles some of this. Still getting an error on 

```
@article{http://zotero.org/groups/1051392/items/MT4A9V2I,
	title = {"{A} wese{\textbackslash}n/dan nacodnisse and þa ecan þistru": {Language} and {Mortality} in the {Homily} for {Doomsday} in {Cambridge}, {Corpus} {Christi} {College} {MS} 41},
	volume = {84},
	issn = {0013-838X (Print) 1744-4217 (Online)},
	shorttitle = {Rowley 2003},
	doi = {10.1076/enst.84.6.493.28779},
	journal = {English Studies},
	author = {Rowley, S.},
	year = {2003},
	keywords = {qd527zm3425},
	pages = {493--510},
	annote = { ELB},
	annote = {The following values have no corresponding Zotero field:custom1: 58}
}
```

See: 
```
W, [2017-09-29 17:11:28#27629]  WARN -- : Lexer: unbalanced braces at 210; brace level 0; mode :literal.
2017-09-29T17:11:28-05:00 ERROR Unexpected error on record id `MT4A9V2I` at file position
    while executing (to_field formatted_bibliography_ts at lib/traject/bibtex_config.rb:47)
    Exception: NoMethodError: undefined method `title' for #<BibTeX::Error:0x007fe2f83abca8>
    /Users/pjreed/dev/exhibits/app/models/bibliography.rb:43:in `block in remove_latex_markup!'
```

Do you see a nice way to handle that in your remove markup method?

**Comment by drh-stanford** [comment]
We can add the `\textbackslash` to https://github.com/sul-dlss/exhibits/blob/master/app/models/bibliography.rb#L53 but we're not using the `Bibliography` model during indexing. The indexer uses raw BibTeX code right now

**Comment by mejackreed** [comment]
We use `Bibliography` right here I think: https://github.com/sul-dlss/exhibits/blob/master/lib/traject/bibtex_config.rb#L49

And its getting caught up on some of that as it is trying to create the HTML citation for indexing.

**Comment by drh-stanford** [comment]
Duh. Sorry. Yes, that's recent. It looks like we need more smarts about handling BibTeX::Error issues. I'll try to reproduce this on my local instance...

Note that we can generate that formatted reference at show-time when we're displaying the bibliography resource rather than at index-time. I thought it would make the show view more simple to configure.

**Comment by drh-stanford** [comment]
The problem is that `BibTeX.parse` is failing to parse this record (a bug imho -- `{\textbackslash}` is legal TeX). I think we need to add `record.present?` to the indexer.

```
2.4.1 :020 > bibtex = BibTeX.parse(input_stream.read, filter: :latex) # as-is
 => #<BibTeX::Bibliography data=[0]> 
2.4.1 :018 > bibtex = BibTeX.parse(input_stream.read, filter: :latex) # without {\textbackslash}
 => #<BibTeX::Bibliography data=[1]> 
```

**Comment by mejackreed** [comment]
With #646 I think we can close this ticket.

Locally I'm able to index the entire Parker Library `.bib` file.  5,654 indexed successfully in 554.282 sec.
