### ISSUE TITLE
Replace Stanford theme PNG logos with SVG 

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/exhibits#625]
Replace the navbar and footer SUL logos with the shiny new SVGs logos ([files in Consul](https://consul.stanford.edu/display/Logos/Home))

## Current logos
<img width="193" alt="screen shot 2017-09-28 at 3 14 31 pm" src="https://user-images.githubusercontent.com/5402927/30992715-1ca21322-a460-11e7-8a1b-c7ba6bd7acb5.png">
<img width="209" alt="screen shot 2017-09-28 at 3 14 24 pm" src="https://user-images.githubusercontent.com/5402927/30992716-1ca4b762-a460-11e7-986f-d9b447aca249.png">

**Comment by aeschylus** [comment]
For Footer wordmark: https://identity.stanford.edu/name-emblems.html#stanford-signature

**Comment by ggeisler** [comment]
I'm not sure that wordmark is relevant to us. The SUL logos are in Consul, the entire Stanford footer is provided by the universal Stanford footer, described about halfway down this page: https://identity.stanford.edu/web-mobile.html
