### ISSUE TITLE
Load the sorted bibliography asynchonously on manuscript show page

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/exhibits#632]
This PR is split out from #589 and #585. Depends on #626 

- [x] Implement a way to use `CiteProc` to render a sorted bibliography (`formatted_bibliography_ts`)
- [x] Implement a query API to retrieve all bibliography references for a given manuscript
- [ ] Render sorted bibliography asynchronously on the manuscript show page PR #660

A suggested implementation is to use JavaScript and the JSON API to get the list of formatted references (which will apply the exhibit gated query) for that manuscript, and apply an author-date-title sort based on Solr fields.

Here's the JSON API query needed to retrieve all of the references for a given resource (druid):

```
f[related_document_id_ssim][]=gs233db8425&
f[format_main_ssim][]=Reference&
sort=author_sort asc, pub_year_isi asc, title_sort asc&
rows=999&
format=json
```

The other advantage is that the injection of the links to Zotero is straight-forward -- see #539.

**Comment by drh-stanford** [comment]
Blocked by design discussion needed for #635.

**Comment by drh-stanford** [comment]
@ggeisler how does this look for the bibliography (ignore the bad sorting), based on the design in #576?

![screen shot 2017-10-03 at 12 44 08 pm](https://user-images.githubusercontent.com/1861171/31145493-b7952f96-a838-11e7-8256-2a042fc5d527.png)

**Comment by drh-stanford** [comment]
I got the sorting to work and here's what the full manuscript show page looks like:

![screen shot 2017-10-03 at 2 27 19 pm](https://user-images.githubusercontent.com/1861171/31150046-14469636-a847-11e7-9b2e-12a7084c28df.png)

**Comment by ggeisler** [comment]
This is pretty minor, but the `div` with the Bibliography section looks like it has some default left margin (~20px) that is preventing it from being left-aligned with the sections above it (e.g. the left-edge of the view and item title). 

Maybe try to target the whole bibliography section and add a `margin-left: 0;` to it? (Or don't worry about it and I'll deal with it later on.)

**Comment by ggeisler** [comment]
Perfect @drh-stanford!
