### ISSUE TITLE
Do we need to do data validation on bibliography to manuscript mappings at index-time?

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/exhibits#634]
That is, should we add validation that related druids must exist in the exhibit at index-time? Or is at user-display time ok?

**Comment by mejackreed** [comment]
My feeling on this is no. It would force an exhibit curator to know how to properly order their indexing of the exhibit.

**Comment by mejackreed** [comment]
Consensus on closing this during backlog grooming.
