### ISSUE TITLE
Design for "Beta feature" label

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#647]
Before I can start design on this, I think we need to articulate exactly what the goals of having some sort of "beta feature" label are. Depending on how we implement this, it could impose a non-trivial amount of development and maintenance effort. Being more clear about what the goals of this idea are will help guide the most efficient way to accomplish those goals.

Some questions to prompt input:

- Is this intended only for exhibit curators, or potentially both curators and exhibit visitors?
- Is it sufficient to let them know about the feature once, and then remove the label (whatever form that takes)? Or should it be persistent until the feature is no longer "beta" (possibly because of the next bullet?)?
- Are we informing them of a "beta feature" because we want to cover ourselves if it doesn't work as expected? 
- Or, are we informing them of a new feature just so they know it has been added to the exhibit?

One of the things I'm trying to determine is whether marking individual features as "beta" is worth the extra overhead versus an alternative approach that describes all beta features in a single notification, such as a dismissible modal when the user visits the exhibit the first time after the notification has been added.

**Comment by mejackreed** [comment]
Discussed in story time 10/12/2017 as not needed.
