### ISSUE TITLE
Implement bibliographic items in search results

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#651]
Described and designed in #512 & #575

From the design document:
 - [x] 1: Confirm / test reference facetability
 - [x] 2: Add resource type thumb image/placeholder

![designdoc](https://user-images.githubusercontent.com/101482/31030936-f0a759ba-a50b-11e7-8599-0e1f45642968.png)

**Comment by camillevilla** [comment]
Will depend on analysis in #649

**Comment by drh-stanford** [comment]
For the sorting algorithm in #632, we'd like to add Author-Date-Title, so we need to index the year into the `pub_year_isi` field, and in CatalogController add:

```
config.add_sort_field 'author_sort asc, pub_year_isi asc, title_sort asc', label: 'author-date'
```

**Comment by jkeck** [comment]
WRT faceting, we do get the appropriate resource type for the Bibliography references themselves, however; ensuring that the other parker objects get a Resource Type of "Manuscript" may be the tricker part.  Digging into that now.

**Comment by jkeck** [comment]
@blalbrit it appears that the Resource Type value that we'll want to be present in the facet is `Archive/Manuscript`.  You can see all the Resource Types available to us in the [screenshot below](#sw-screenshot).

The indexing code in [stanford-mods](https://github.com/sul-dlss/stanford-mods/blob/ccde41b874dfcea4bda627df883adcbb4c95da96/lib/stanford-mods/searchworks.rb#L313-L314) indicates that the `typeOfResource` needs to be `mixed material` (e.g. `<typeOfResource manuscript="yes">mixed material</typeOfResource>`).  I'm not sure what the `manuscript="yes"` bit is about, but that's what I see in the wild for documents that have this Resource Type.

<img name="sw-screenshot" width="389" alt="sw-resource-tpes" src="https://user-images.githubusercontent.com/96776/31291350-7189fd9e-aa84-11e7-8a71-00105ce71abe.png">

**Comment by blalbrit** [comment]
Cool @jkeck - so just to confirm, typeOfResource should look like this example: https://purl.stanford.edu/cf386wt1778.mods  ?

**Comment by jkeck** [comment]
Exactly @blalbrit.

**Comment by jkeck** [comment]
#698 has been submitted as a potential solution to `Add resource type thumb image/placeholder`.  If that is acceptable and we now know the data requirements for `Confirm / test reference facetability`, would this ticket be closable?

**Comment by mejackreed** [comment]
Closing this with #698 being 🚢
