### ISSUE TITLE
Should we add changelog changes for each pull request?

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#662]
Should a PR also update the CHANGELOG.md ?

cc @drh-stanford @camillevilla @jkeck @aeschylus

**Comment by drh-stanford** [comment]
I'd vote no. I think it's more reliable to do that at the time of release. I'm not sure what others do to manage it -- it can be lengthy.

**Comment by jkeck** [comment]
I'm a bit indifferent.  Thinking forward to a continuous release cycle, it seems like we would almost have to make this part of our development process.  We're not there now, so `shrug.jpg`.

I do agree w/ Darren that (particularly at this juncture) something done at the time of release is likely to be more accurate.

**Comment by mejackreed** [comment]
A few observations about starting this process:
 - It is a bit of work (incumbent on the person creating the release) to keep this up to date, could this be shared?
 - The person creating the PR may have a better suggestion for the release note
 - The product owner might be able to use an up to date "Unreleased" section to plan for communication

**Comment by mejackreed** [comment]
Great discussion.. we aren't doing it this way.
