### ISSUE TITLE
Add the ability to feature flag based on an exhibit

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#667]
Our current feature flag ability is at the global exhibits level, if we can add exhibit level flags too, this could help us release functionality to specific exhibits sooner.

**Comment by ggeisler** [comment]
This might not be relevant for an initial implementation, but it seems like creating a UI at the super-admin level for turning on/off features at the exhibit-level would be handy. That way a member of the service team could easily adjust available features for new or existing exhibits, without involving developers.
