### ISSUE TITLE
Optimize (Re)use of Traject+ Work within Parker, Exhibits

### ISSUE THREAD

**Issue by cmharlow** [sul-dlss/exhibits#669]
- [x] Use of macros?
- [x] reuse of previous + future traject+ work?
- [x] Review + give any recs bibtex mapping w/tech team
- [ ] bibtex hash validation post-transform + data shape exception handling?
- [ ] multi-thread transform issues?
- [ ] Other Parker mapping options?

**Comment by cmh2166** [comment]
See: #685 (multiple, discrete fields accumulators errors) & #686 (open PR to move some of the BibTex Config to macros method def.)

Working on new branch to answer above, focused first on:

- [ ] ability to run Traject+ locally within exhibits with -w DebugWriter for dev testing
- [ ] add `README.md`to the `lib/traject/` directory to capture notes, best practices, etc. on these + the above points
- [ ] separate out macros into macros folder for cleaner macros + configs, leading to easier reuse of this Traject+ code later?
- [ ] fix multi-field accumulators
