### ISSUE TITLE
Refactor indexing pipeline to use Bibliography model for information extraction

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/exhibits#671]
The `Bibliography` model has some logic that cleans up data and renders HTML references, etc. We need a way to use the `Bibliography.new(record.to_s)` pattern to load the data into the model during the indexing. Otherwise, we won't get the logic in the model.

See https://github.com/sul-dlss/exhibits/blob/master/lib/traject/bibtex_config.rb#L114-L121 for an example of how we use the Bibliography model in the pipeline.

**Comment by cmh2166** [comment]
Perhaps this is an ideal pairing or tech team discussion opportunity? 

A proposal: 
1. we can first go through some options in traject+ (traject plus our additions from exhibits or DLME) in refactoring the `Bibliographic` model, like the use of macros; 
2. get work started on refactoring as decided for that model in exhibits; 
3. then maybe at least mention or foreshadow other exhibits models, representations, and data sources we currently have or will have that could leverage this work (if not already done somewhere).

I'd prefer if possible this happen when @cbeer could join as well, perhaps early next Monday if he's not available before.

**Comment by drh-stanford** [comment]
@cmh2166 has a feature branch that has several ideas for refactoring here -- https://github.com/sul-dlss/exhibits/blob/671-refactor-traject-cmh2166. Reopening this issue
