### ISSUE TITLE
Enable site-wide multi-up for show page Mirador viewer

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#677]
Acceptance criteria:
 - [ ] Update site wide config for mirador viewer to enable new slot (discussion about config below)

**Comment by aeschylus** [comment]
Assuming this involves configuring the viewer: Mirador was designed with this  usecase in mind by providing the ability to save state.

So one way to accomplish this is to allow the user to view whatever objects they want in an "editable" viewer session, which they can use arbitrarily (open and close windows, change layout, etc. through the Mirador interface), and then save this configuration when they're done.

A complicating factor is what controls the curator wants to put on the eventual user of this mirador instance. Should the curator have fine-grained control over what the end user can do in this Mirador instance? For example, should the curator be able to create a 3-pane view, but turn off the buttons that allow the user to close any of these windows? Or should this be the default?

In Mirador's settings, these controls are provided in two layers. One of them is the "windowSettings", which controls the available features of any window which may be opened, and then the settings given to each window in "windowObjects", which defined which features a specific window exhibits when Mirador automatically opens it on initialisation.

**Comment by aeschylus** [comment]
I'm not sure how this interacts with #678

**Comment by mejackreed** [comment]
Ah thanks for your comments @aeschylus and I realize I should have put a better description on the ticket since you weren't maybe there for the first part. I think we just want the ability for on a show page, allow a end user to drag in (or add manually) a comparison view. No need to persist the state here for the end user. Does this simplify things?

**Comment by aeschylus** [comment]
Yeah, certainly, depending on how much control is required. This just requires changing the configuration to allow the "add slot" buttons (but maybe not the "Replace Object" button). In more recent Mirador versions there is the option to inject an alternate localisation file which could change that text if we wanted, although it's something of a Beta feature.

The iFrame will complicate any more complex interaction, such as trying to override the default drag-n-drop behaviour to make a parallel slot open up to receive the new dropped object. The current default is to replace the existing object with the dragged object.
