### ISSUE TITLE
Make multi-up (or other Mirador options) configurable per exhibit

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#678]

**Comment by aeschylus** [comment]
Also relevant for this configuration: https://github.com/sul-dlss/exhibits/issues/677#issuecomment-334554162

**Comment by ggeisler** [comment]
If I'm correct in my understanding that the only Mirador viewer configuration we currently have to add is for the feature for adding slots to the viewer, I propose we keep it very simple and just add a checkbox option as in the mockup below. If and when we have more Mirador viewer configurations we want to give the curator, we can reassess whether we need something more elaborate than this design.

<img width="1230" alt="mirador-slots-config-checkbox" src="https://user-images.githubusercontent.com/101482/31302133-287f5dc6-aab4-11e7-9a6c-7e74ba12c230.png">

If the Mirador viewer option is not currently selected, we should disable the slot checkbox (whether it is checked or not), like this:

<img width="564" alt="mirador-slots-config-checkbox-disabled" src="https://user-images.githubusercontent.com/101482/31302154-4b9a0dd8-aab4-11e7-8c46-4aa7cecf79a1.png">

(Those of you more familiar with Mirador, feel free to suggest a better label for the checkbox if "Allow users to add slots to display additional images in viewer" doesn't sound right to you.)

I'd suggest the checkbox be selected by default.

In fact, I wonder (similar to something else I questioned in this week's storytime, or maybe it was this I was questioning when we cut off the discussion) whether we actually need this configuration at all. Is there really a good use case for giving an exhibit admin the power to prevent users from adding slots to a Mirador viewer? I guess I'm not clear why we aren't just enabling the add slots feature for all exhibits that use the Mirador viewer and leaving it at that?

**Comment by mejackreed** [comment]
I think the simplicity of this is great @ggeisler

**Comment by mejackreed** [comment]
Per team discussion, we are not going to make it configurable but globally available.
