### ISSUE TITLE
Add IIIF badge to show page for objects w/ a manifest

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#680]
Some information about IIIF drag and drop here:

http://zimeon.github.io/iiif-dragndrop/

Design in #679

**Comment by drh-stanford** [comment]
blocked on design approval

**Comment by aeschylus** [comment]
A walkthrough with a gist example, supposedly about email, but generally applicable.

https://medium.com/@aeschylus/create-and-share-iiif-items-quickly-and-easily-with-drag-and-drop-over-email-879f13c9caba

Gist with comments: https://gist.github.com/aeschylus/03880d1b7a1b6ac19e2f2a6201952791

**Comment by ggeisler** [comment]
See https://drive.google.com/file/d/0B-V5LU8rnUvqdF9saDd2MXYxVGs/view?usp=sharing for the IIIF drag 'n drop icon. Let me know if you have any problems with it (I'm not really an icon designer...).

For the show page I'd guess that 24px wide, keeping height proportional, might be a good size, but we can adjust based on how it looks.
