### ISSUE TITLE
Add IIIF badge to results page for objects w/ a manifest

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#681]
Some information about IIIF drag and drop here:

http://zimeon.github.io/iiif-dragndrop/

**Comment by drh-stanford** [comment]
blocked on design approval

**Comment by aeschylus** [comment]
Doubling up on resources in related ticket: 

A walkthrough with a gist example, supposedly about email, but generally applicable.

https://medium.com/@aeschylus/create-and-share-iiif-items-quickly-and-easily-with-drag-and-drop-over-email-879f13c9caba

Gist with comments: https://gist.github.com/aeschylus/03880d1b7a1b6ac19e2f2a6201952791

**Comment by ggeisler** [comment]
See https://drive.google.com/file/d/0B-V5LU8rnUvqdF9saDd2MXYxVGs/view?usp=sharing for the IIIF drag 'n drop icon. Let me know if you have any problems with it (I'm not really an icon designer...).

For the results page I'd guess that something a bit smaller than the show page, like 20px wide, keeping height proportional, might be a good size, but we can adjust based on how it looks.

**Comment by jkeck** [comment]
After talking this over with  a few people on the team I have come up with two possible approaches.  Happy to consider additional.

## Approach 1: Add partial to index partials array
We need to float the IIIF icon
<img width="879" alt="floats" src="https://user-images.githubusercontent.com/96776/31480075-84f80b5a-aed0-11e7-827b-cfb2ed173026.png">

This seems to have the potential for overlap issues with long titles on certain screen resolutions.

<img width="748" alt="floats-problem" src="https://user-images.githubusercontent.com/96776/31480092-9cdcccec-aed0-11e7-8c95-11efd63ad73f.png">


## Approach 2: Provide custom header partial to render bootstrap columns

This will change the current alignment between the thumbnail and title.

<img width="923" alt="1-10-1-column" src="https://user-images.githubusercontent.com/96776/31480123-c83cd4ae-aed0-11e7-8f52-adcb68b4bd0e.png">

**Comment by ggeisler** [comment]
Just speaking from a visual design point of view: it looks like the title element in Approach 2 is not as far left-aligned as the `dl` (e.g., Corporate Author seems to extend farther left than the title). I know it's very subtle, but if there is some margin or padding that is causing that difference and it could be removed, that slight shift to the left would make the title indention more tolerable, in my opinion.
