### ISSUE TITLE
Analysis: Support multiple annotations per bibliography resource

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/exhibits#685]
Our BibTeX reader only captures a single annotation! e.g. [book.bib](https://github.com/sul-dlss/exhibits/blob/676-bib-show-page-annotations/spec/fixtures/bibliography/book.bib) has 3 `annote` values. When I checked our our BibTeX `record`, we only get the last annotation.

## Design
![show page](https://user-images.githubusercontent.com/5402927/31249857-c8bf8082-a9cd-11e7-8c8c-be902ea225af.png)

![design notes](https://user-images.githubusercontent.com/5402927/31249856-c8bb631c-a9cd-11e7-86e1-d3d11d5e42f3.png)

#### BibTeX:
```
@book{http://zotero.org/groups/1051392/items/TXXUJDG2,
	address = {Coimbra},
	title = {A {Carta} ou {Memória} do {Cruzado} {Inglês} {R}. para {Osberto} de {Bawdsey} sobre a conquista de {Lisboa} em 1147},
        …
	annote = { KAW},
	annote = {CCC MS 470 [p. 9, and referred to (without MS number) throughout]reproductions from CCC MS 470, ff. 125-146, in the appendix},
	annote = {The following values have no corresponding Zotero field:custom1: 23}
}
```
#### BibTeX::Entry
```
#<BibTeX::Entry 
  address = Coimbra, 
  title = A Carta ou Memória do Cruzado Inglês R. para Osberto de Bawdsey sobre a conquista de Lisboa em 1147, 
  …
  annote = The following values have no corresponding Zotero field:custom1: 23
>
```

### Possible routes forward (please feel free to edit and add notes below)

1. mess with our BibTex translator so that we get something more like:
`annote = {KAW, The following values have no corresponding Zotero field:custom1: 23}}` and possibly make a PR to [zotero/translators](https://github.com/zotero/translators)) (@camillevilla)
2. adjust our Traject settings to deal with multiple `annote` values (in consultation with @cmh2166) 
3. issue a PR to bibtex-ruby to handle concatenation of multiple values with the same key (suggested by @drh-stanford)
4. [zotero-better-bibtex](https://github.com/retorquere/zotero-better-bibtex) (@mejackreed)

**Comment by cmh2166** [comment]
This is something relatively easy to fix in the Traject+ accumulator use (right now, it's just overwriting that field when multiple exist). Will try to get an example of repaired Traject+ code up this AM to show what it would look like. If it works for the case, then I'd think that's better than changing the munging of data sources or trying other data retrieval libraries.

**Comment by drh-stanford** [comment]
I _think_ we're using the accumulator correctly -- see https://github.com/sul-dlss/exhibits/blob/master/lib/traject/bibtex_config.rb#L119-L121. I'd like to see more examples of its use though. We basically have that one pattern throughout our Traject code. Also, see #686 as a possible improvement through the use of macros.

As for the BibTeX, I think we'll need to do (1) above so that we can avoid doing any pre-processing of the BibTeX data in the BibReader to collapse the annote fields before we call `BibTeX.parse`. The translator is JavaScript that we need to fix here:

  https://github.com/zotero/translators/blob/master/BibTeX.js#L1378-L1383

Note that we don't have our custom translator in git -- it's on the shared folder right now. It's called `BibTeX Item Uri.js` -- see https://drive.google.com/open?id=0B5fLh2mc4FCbY2NJMHdhYjFhdm8 -- its only change is to replace the normal key with the URL to the Zotero record.

**Comment by cmh2166** [comment]
Thanks for this. Yes, I think the accumulator is correct too, but I see the data passed to the lambda for each record discards repeated fields before getting there, so I'm deep diving in the BibTex reader at this moment.

If (1) above is easy for yall to do, sounds good. At this point, I'd like to be able to put a finger on why the multiple, repeated but discrete fields are dropping out of the BibTex Reader output, if only to better understand reworking of Traject. 

I'm working on a branch off yours ( yours: #686  mine branch rn: https://github.com/sul-dlss/exhibits/tree/671-refactor-traject-cmh2166 ) to at least capture some notes, examples, etc.

**Comment by camillevilla** [comment]
A status update on this:
- I'm working on edits to our `BibTeX Item Uri.js`. Currently have `mynote = {, ELB, Folio Box 11.3, The following values have no corresponding Zotero field:volume: Diplomarbeit}`. So close! 

@drh-stanford did a great job of starting a discussion in zotero/translators #1433

**Comment by camillevilla** [comment]
More updates: 
- annotations are currently a string of comma separated values: `annote = { ELB, Folio Box 11.3, The following values have no corresponding Zotero field:volume: Diplomarbei}`
- working on separating notes with `|`, per Christina's suggestion
