### ISSUE TITLE
Travis is timing out on rspecs

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/exhibits#689]
It doesn't happen all the time, but frequent enough to waste time. The specific spec that times out differs, but here's an example:

```
Top 3 slowest examples (60.24 seconds, 58.9% of total time):
  an exhibit loads the home page
    60.11 seconds ./spec/features/exhibit_spec.rb:6
```

**Comment by mejackreed** [comment]
As a data point, still seeing this happen intermittently

**Comment by blalbrit** [comment]
@mejackreed @drh-stanford - is this still a viable ticket?

**Comment by mejackreed** [comment]
Yes.

**Comment by blalbrit** [comment]
Leaving open then, removing Parker label.
