### ISSUE TITLE
Need developer to scope effort for enabling search across exhibits

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#694]
We need better ways to discover exhibits and the content of exhibits at exhibits.stanford.edu. One approach is to connect exhibits.stanford.edu to the bento search and allow asynchronous lookup from SearchWorks of exhibits associated with a collection or an individual item. This would require exhibits.stanford.edu to be searchable across all exhibits. (As more exhibits are created, this may be a benefit within exhibits as well.) To validate whether or not this is a viable option, we need a developer to scope the level of effort this would entail.

**Comment by mejackreed** [comment]
Do we have designs for this? I think there will likely be UX considerations that will inform much of this.

**Comment by caaster** [comment]
@ggeisler @jvine can you comment here? See Jack's note above.

**Comment by jvine** [comment]
@mejackreed i have some rough designs around the bento that i can clean up and can quickly sketch the SW stuff. will add to this ticket in the next week or 2.

**Comment by jvine** [comment]
### 1. Bento with a block for exhibit results. Note that exhibits are returned, not individual items.
![exhibits-fullbento](https://user-images.githubusercontent.com/6945691/31640006-b3760fea-b290-11e7-8048-f4a971a5b006.png)

-----
### 2.  SW collection record with a block for related exhibits 
Related = 
- items in the collection are included in the exhibit
- the collection itself is included in the exhibit (not sure how this happens?)
<img width="1205" alt="collection-exhibit link" src="https://user-images.githubusercontent.com/6945691/31640045-ee5a7c36-b290-11e7-9a93-412abfa49441.png">

-----
### 3. SW item record with a block for exhibits in which the item is included.
<img width="1218" alt="item-exhibit link" src="https://user-images.githubusercontent.com/6945691/31640080-1c4c6fe6-b291-11e7-9162-0c79d5af72f3.png">

**Comment by mejackreed** [comment]
There are several ways to approach this, but I will just outline one that I would take.

Likely we will need some type of "Exhibits" API to handle these requests. It feels potentially problematic to add more burden to the DOR SearchWorks indexing time/pipeline.

I'm not really clear on 2.a and the implications yet.

### 1. Bento with a block for exhibit results.
Could be handled with a basic Rails exhibits search api. Perhaps may need to use Solr if we want to do more special search related things. Estimate 2 - 3 days
### 2. SW collection record with a block for related exhibits.
I think we would need to create a query to the Exhibits Solr instance here, i would once again handle through an Exhibits API.  This query could kind of be ridiculous with `n` number of items in a collection. 3 days
### 3. SW item record with a block for exhibits in which the item is included.
Straightforward from Exhibits API. 1 day
### 4. Add exhibit results to SW/catalog search results - similar to articles [no mockup]
Could use the API from `#1` would likely require a solr backed api 1 day

I would estimate 2 weeks of a team to complete this. Some complications may arise from scalability

**Comment by mejackreed** [comment]
A developer has scoped this and design has been generated in additional tickets.
