### ISSUE TITLE
Is the bibliography display on show page limited to a certain number of objects?

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#700]
Per conversation with @mejackreed below, it looks like we're capped at 100 bibliographic items on a show page. We'll need to increase this number to accommodate some of the more studied manuscripts. CCC 286 has ~223 citations, for instance. I'm not sure which object has the largest bibliography - but even the largest will grow over time, so we might want a good buffer.

Original question convo below:

Not quite sure how to phrase this - but when I look at some of the bibliography lists, they appear truncated.

For instance: https://exhibits.stanford.edu/parker-2/catalog/mk707wk3350

The bibliography list ends with M.R. James, in this example, when it should go all the way to Youngman (if we're looking at the Parker 1.x version - https://parker-stanford-edu.stanford.idm.oclc.org/parker/actions/bibliography_search_results.do?journal=&primarySourceRef=286&author=&title=&sort=&shortTitle=&comment=&date=&referenceTypes=)

 Acceptance criteria:
 - [ ] Full display of all bibliography items for a given manuscript (not capped)

**Comment by mejackreed** [comment]
Yes it looks like it is truncated to the first 100.

**Comment by blalbrit** [comment]
Ah cool - thanks @mejackreed . Does it make sense to just turn this into a task ticket to lift that limit?

**Comment by mejackreed** [comment]
yep

**Comment by drh-stanford** [comment]
It's supposed to be the first 1000 so something is broken -- https://github.com/sul-dlss/exhibits/blob/master/app/assets/javascripts/bibliography.js#L16

**Comment by mejackreed** [comment]
I think this is coming from the `Blacklight::Configuration`: https://github.com/projectblacklight/blacklight/blob/master/lib/blacklight/configuration.rb#L115

Maybe we need a custom `SearchBuilder` to bypass?

**Comment by mejackreed** [comment]
This is how we do it in ArcLight: https://github.com/sul-dlss/arclight/blob/2f5f2b843de552bab437abe4f682bd3d266ec0b6/app/models/concerns/arclight/search_behavior.rb#L19-L24

But since we are Blacklight 6.. use SearchBuilder instead of Behavior

**Comment by drh-stanford** [comment]
Can we just override the `max_per_page` in our CatalogController to 1,000? Or do we want to restrict that override to the JSON API only?

**Comment by mejackreed** [comment]
I think that might enable it for end users in the UI. If that is the case, I would vote note to and just do for the JSON API or with a special param
