### ISSUE TITLE
[exhibits/stage] ActiveRecord::StatementInvalid: Mysql2::Error: Got a packet bigger than 'max_allowed_packet'

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/exhibits#709]
## Backtrace

    line 6 of [PROJECT_ROOT]/app/jobs/record_index_status_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49092/faults/34896431)

[exhibits/stage] ActiveRecord::StatementInvalid: Mysql2::Error: Got a packet bigger than 'max_allowed_packet' bytes: UPDATE `spotlight_solr_document_sidecars` SET `index_status` = x'2d2d2d0a3a6f6b3a2066616c73650a3a6d6573736167653a207c2d0a2020233c52536f6c723a3a4572726f723a3a487474703a2052536f6c723a3a4572726f723a3a48747470202d203430302042616420526571756573740a20204572726f723a207b22726573706f6e7365486561646572223a7b22737461747573223a3430302c225154696d65223a313732347d2c226572726f72223a7b226d65746164617461223...

**Comment by drh-stanford** [comment]
We checked and the packet size is 16MB already. The index_status column is only supposed to hold 10MB (though technically it's a mediumblob which is 16MB). See https://github.com/sul-dlss/operations-tasks/issues/1422

**Comment by cbeer** [comment]
I think it is definitely an indexing problem; we probably have an unnecessarily verbose exception serialization (that's, say, dumping the whole nokogiri object tree), and we should find and address that.

**Comment by drh-stanford** [comment]
I found that we're inspect'ing the Exception here -- https://github.com/sul-dlss/exhibits/blob/master/app/models/dor_harvester.rb#L63
