### ISSUE TITLE
Poor performance for BibTeX indexing

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/exhibits#713]
We have 6k records in our Parker bibliography and it takes roughly an hour+ to reindex.

The Traject pipeline handles concurrency via threads (set to 15 threads) as does our reindexing job processor Sidekiq (set to 5 threads per process), but using them together doesn't seem to speed up indexing at all.

Need further investigation. The DLME project had similar issues but their problem was a lack of sufficient database connections once the pipeline concurrency hit a certain level.

Note that running Traject in isolation allows for concurrency and has a good speedup factor.

**Comment by mejackreed** [comment]
Right now per @blalbrit the current performance for BibTeX indexing is acceptable.
