### ISSUE TITLE
Annotation Story Ticket

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#714]
As a Parker exhibit viewer, I want to be able to search on existing annotation lists so that I can find more granular information about these resources.

As a Parker exhibit viewer, I want to be able get a list of search results that includes annotations about a manuscript.

As a Parker exhibit viewer, I want to search for "elephant" and get back search results that show me the manuscripts and the pages within a manuscript where "elephant" occurs.

As a Parker exhibit viewer, if I view an individual annotation show page, I would like to be able to see the folio or page of the manuscript in which that annotation appears in the Mirador viewer.

As a Parker exhibit viewer, I would like to be able to navigate to the main manuscript show page from any annotation view.

As a Parker admin, I want to index a IIIF collection that contains many manifests where the manifests are not indexed but its otherContent (ie. annotation lists) are.
Several implementation approaches, among which:
- include the external manifest in MODS and know to find otherContent there
- follow the Spotlight external manifest path and get otherContent
- index in the IIIF collection, but don't index manifests - just otherContent and somehow link those back to the SDR object
- ? others ?

**Comment by ggeisler** [comment]
A couple of preliminary mockups intended to facilitate discussion of this story and refine concrete requirements:

----
### Search results with annotations presented similarly to manuscripts and references

<img width="1067" alt="annotation-results" src="https://user-images.githubusercontent.com/101482/31507399-61159dc4-af2f-11e7-9776-78630821787e.png">

----
### Annotation show page

<img width="1045" alt="annotation-show-page" src="https://user-images.githubusercontent.com/101482/31507412-6dfc0794-af2f-11e7-9324-0134b8f973a2.png">

**Comment by mejackreed** [comment]
Questions:

 - [ ] What metadata fields do/will we have access to?
 - [ ] How do we tell an indexer to index this stuff?
 - [ ] What do we do on the manuscript show page? Do we show the annotations?
   - Could we have a linked search here? 
   - We can get the count and display here to user if there are annotations.
 - [x] Is there a use case we need to think about for someone deleting an annotation?
   - Per @blalbrit the ones concerned here.. no.
 - [ ] What about the admin interface?
   - Per @blalbrit no additional options presented to user (curator).

**Comment by blalbrit** [comment]
Page details all show nicely.
