### ISSUE TITLE
For Parker... we need to be able to search on

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#718]
Individual fields split out to separate actionable tickets
 - [x] Manuscript number #721
 - [x] Manuscript title #722
 - [x] text title -  within each manuscript there can be one or more works (see #558 maybe?) #723 
 - [x] incipit (may be dependent on annotations)
 - [x] Language #724

**Comment by mejackreed** [comment]
Potentially related to: https://github.com/sul-dlss/exhibits/issues/377

**Comment by blalbrit** [comment]
Also need to know where we expect this information in MODS so that I can make sure it's in the right place.

**Comment by blalbrit** [comment]
This object has rich descMD (we're iterating on it to get the right fit for Parker): https://purl.stanford.edu/cf386wt1778 - see https://purl.stanford.edu/cf386wt1778.mods
