### ISSUE TITLE
Index and make searchable manuscript number

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#721]
see `<shelfLocator>` in https://purl.stanford.edu/cf386wt1778.mods for where this is currently.

- [x] Index metadata
- [x] Design fielded search UI
- [x] Support fielded search
- [x] Support "exact match" searches for manuscript number #778

**Comment by blalbrit** [comment]
Currently:

<location>
<physicalLocation type="repository">
UK, Cambridge, Corpus Christi College, Parker Library
</physicalLocation>
<shelfLocator>MS 69</shelfLocator>
</location>

But we can also add in additional information to make this easier to grab.

**Comment by drh-stanford** [comment]
From a slack discussion, we'll be looking to make _additions_ for metadata extraction in the `stanford-mods` gem for cases that are generally useful, as documented in Cathy's [MODS metadata document](https://consul.stanford.edu/pages/viewpage.action?title=MODS+indexing+and+display+in+SearchWorks+and+Spotlight&spaceKey=DIGMETADATA).

The mapping from the extraction method to the Solr document would be done in `Spotlight::Dor::Indexer` as a local concern.

**Comment by arcadiafalcone** [comment]
Just to clarify, that MODS indexing documentation is intended to be a representation of things as they currently are, not an indication of what might be generally useful.

**Comment by drh-stanford** [comment]
@arcadiafalcone thanks for the clarification!

**Comment by drh-stanford** [comment]
@blalbrit @ggeisler can you clarify was "make searchable" means in this context? Is this in the pulldown for the fielded search? If so, is it restricted to just the parker exhibit? Does it have any implications in the admin UI?

**Comment by arcadiafalcone** [comment]
Note also #557 re: exact-match searching, which came out of a similar issue in the Lanciani exhibit - for creating their browse categories, they wanted to be able to search "XIX.12" and not get "XIX.123" in the results. I could see something similar here where searching "MS 10" also returns MS 100, 101, 102, etc.

**Comment by blalbrit** [comment]
The main need, from the user point of view, is to be able to restrict search to manuscript number.

In Parker 1 - this would be a search on the specific field that contains the manuscript number as:
![screenshot 2017-10-13 12 29 27](https://user-images.githubusercontent.com/796990/31562978-41981d1c-b012-11e7-8d04-af507a65b667.png)

which results in:

![screenshot 2017-10-13 12 29 37](https://user-images.githubusercontent.com/796990/31562987-499c2382-b012-11e7-84c8-cc49a505c4fd.png)

Since many users already know the manuscript number they're after, being able to get to that manuscript through fielded search, or browse, is the key functionality we need.

**Comment by blalbrit** [comment]
To @arcadiafalcone 's point, exact match is helpful on this field:

![screenshot 2017-10-13 12 32 09](https://user-images.githubusercontent.com/796990/31563105-a2271318-b012-11e7-89cd-8165d752be88.png)

results in:

![screenshot 2017-10-13 12 32 19](https://user-images.githubusercontent.com/796990/31563108-a850e142-b012-11e7-9c15-06f5a176ad48.png)

**Comment by drh-stanford** [comment]
Ok that makes sense from a requirements perspective. I guess we need some design here. I could see this fielded search implemented in a few ways -- on the home page, a handcrafted Parker page, in the existing fielded search pulldown, etc.

If we just add a new fielded search, it'll show up in all exhibits and the admin UI like here:

![screen shot 2017-10-13 at 12 34 07 pm](https://user-images.githubusercontent.com/1861171/31563226-055270cc-b013-11e7-9c41-feb076455867.png)

**Comment by blalbrit** [comment]
Would feedback from @ggeisler be helpful re: ^^ ?

**Comment by drh-stanford** [comment]
Yes, I created a design ticket for us (https://github.com/sul-dlss/exhibits/issues/743) as it spans the other fields like #725 .

**Comment by drh-stanford** [comment]
shipped in v1.5.0
