### ISSUE TITLE
Index and make searchable manuscript title(s)

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#722]
- [x] Verify that the multiple titles are searchable (if not already so)
- [x] Displayed using "Alternative Title" label, or displayLabel if possible
- [x] Open question about using the `displayLabel` metadata: we need to be able to distinguish between multiple alternative titles.
- [x] Index #785 
- [x] Display (each labeled on their own line)
- [x] Search

**Comment by blalbrit** [comment]
Can have multiple titles like:

`<titleInfo>
<title>Gregory the Great, Homiliae XL in euangelia</title>
</titleInfo>
<titleInfo displayLabel="M.R. James Title" type="alternative">
<title>Gregorii Homiliae</title>
</titleInfo>`

**Comment by drh-stanford** [comment]
@blalbrit should these alternative titles be displayed? if so, should they be tagged using the displayLabel metadata?

**Comment by ggeisler** [comment]
@blalbrit @drh-stanford I don't think there are any design considerations. If I understand correctly, we should see an entry for "Alternative Title" in the metadata fields list on the Configuration > Metadata page. The curator of a given exhibit could then choose to display or hide that field from the various page types, and optionally change the label (e.g., in the context of the Parker exhibit, the label could be changed to display "Title variant". Not necessarily a suggestion, just an example.).

Let me know if you had another other possible design implication in mind that isn't apparent to me.

**Comment by blalbrit** [comment]
The main consideration for me, @ggeisler, is just that the Alternate Titles we're loading for Parker already have a displayLabel in the metadata ("M.R. James" or something similar) that means something in the specific context of the Parker exhibit. Occasionally, there is an additional alt title brought in from an earlier catalogue ("T. James") that will also mean something to Parker users. So long as we can distinguish between the two alt titles, then I think we're covered.

**Comment by ggeisler** [comment]
@blalbrit I see. In that case, maybe this warrants further discussion. If I understand correctly, you're saying something like this is possible (I added a "T. James" element):

`<titleInfo>`
`<title>Gregory the Great, Homiliae XL in euangelia</title>`
`</titleInfo>`
`<titleInfo displayLabel="M.R. James Title" type="alternative">`
`<title>Gregorii Homiliae</title>`
`<titleInfo displayLabel="T. James" type="alternative">`
`<title>Some other title</title>`
`</titleInfo>`

If so, I'm not sure the proposal above will be sufficient for distinguishing those two title variants. They'd both be indexed as "Alternative Title" I think, unless we use the `displayLabel` value to further distinguish them?

And when displayed in metadata the result would be something like (assuming the curator hasn't customized the Alternative Title display label in the configuration):

> Title: **Gregory the Great, Homiliae XL in euangelia**
> Alternative Title: **Gregorii Homiliae**
> Alternative Title: **Some other title**

**Comment by drh-stanford** [comment]
@blalbrit what's your thoughts on having `Alternative Title` as the label for all alternative titles (easier to implement), rather than the metadata in displayLabel?

**Comment by blalbrit** [comment]
@drh-stanford - it's preferable to have the displayLabel, but I would be willing to default to `Alternative Title` . @arcadia do you have a strong preference in the non-Parker realm?

**Comment by blalbrit** [comment]
one question on ^^ - the separate `Alternate Title` won't all be munged into a single display field, will they? The key is to keep each title separate.

**Comment by drh-stanford** [comment]
yes but we will need to implement some custom display logic to keep them on their own labeled lines. I don't think that's the default Blacklight behavior.

**Comment by blalbrit** [comment]
Okay - barring larger metadata issues that @arcadiafalcone might have - I would be okay with that approach.

**Comment by arcadiafalcone** [comment]
Using the displayLabel for greater specificity would be preferable, but displaying as Alternative Title is acceptable for now.

**Comment by drh-stanford** [comment]
@blalbrit how many alternative titles might there be? just one, or many?

**Comment by blalbrit** [comment]
For Parker, we have 1 alternative title for *most* objects and for most "table of contents" items (where "alternative title" will also appear in the MODS). For *some* objects (and I can do some analysis to find out), we have 2 alternative titles. I don't believe we have an instance of 3 alternative titles.

**Comment by blalbrit** [comment]
@drh-stanford ^^

**Comment by blalbrit** [comment]
One problem we bump into is that there are multiple catalogs providing different titles for works or manuscripts in the Parker collection. For instance: https://parker-stanford-edu.stanford.idm.oclc.org/parker/actions/manuscript_description_long_display.do?ms_no=101 has alt titles from the Nasmith catalog at the "work" or "table of contents"/relatedItem level, while the manuscript itself (the object) has alt title from the MR James catalog.

The Parker 1.x site handles it this way:
* MR James is the "core" text and so his titles aren't tagged
* updated titles from the Parker team are tagged CCCC
* Nasmith catalog titles are tagged Nasmith

See:
<img width="788" alt="screenshot 2017-10-20 14 16 45" src="https://user-images.githubusercontent.com/796990/31842088-5e3c9738-b5a1-11e7-81e7-19f60b074357.png">


For Parker 2.0, we're flipping slightly to:
* Parker titles are untagged (main title)
* MR James is an alternate title
* Nasmith is an alternate title
(it would be nice to distinguish those by displayLabel - but we can alter the metadata to clarify between the two sources)

**Comment by drh-stanford** [comment]
PR #785 indexes the titles such that we retain the displayLabel but it requires them to be alternate titles (which doesn't sound like a problem). We will need to write custom view code to display them with the displayLabel.

**Comment by drh-stanford** [comment]
shipped in v1.5.0
