### ISSUE TITLE
Design for annotations search results

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#726]

**Comment by ggeisler** [comment]
<img width="1096" alt="results-annotations" src="https://user-images.githubusercontent.com/101482/31518415-08287a72-af54-11e7-8ea0-69ea832cfb88.png">

----
![default-square-thumbnail-annotation](https://user-images.githubusercontent.com/101482/31518449-25ab3da0-af54-11e7-82fe-a6017ff7b09f.png)

**Comment by drh-stanford** [comment]
I think the section/page metadata are the only issues with the design, so I'm going to close this design ticket and further work will continue in #728.

**Comment by drh-stanford** [comment]
Based on a 10/26 discussion, we're interested in making the AnnotationList (i.e., Canvas, manuscript page) the first-class object. So, the action item here is to revisit the design with that idea.

**Comment by ggeisler** [comment]
Several options to discuss:

### Option A

<img width="1127" alt="annotation-list-results-a" src="https://user-images.githubusercontent.com/101482/32464913-e446089a-c2fe-11e7-8a80-f8c8d104ac26.png">


### Option B

<img width="1132" alt="annotation-list-results-b" src="https://user-images.githubusercontent.com/101482/32464917-e6f92c7a-c2fe-11e7-9caa-8ae6ca3d7bef.png">

----
<img width="1126" alt="annotation-list-results-b2" src="https://user-images.githubusercontent.com/101482/32464925-eb1cce38-c2fe-11e7-9e57-815be7a83671.png">


### Option C
<img width="1113" alt="annotation-list-results-c" src="https://user-images.githubusercontent.com/101482/32464927-ed556e94-c2fe-11e7-8718-5a4a90c26298.png">

**Comment by aeschylus** [comment]
I have a small script that produces these diagrams from OA/webAnnotation json:

![Screen Shot 2017-11-02 at 13.53.20.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/550f549aae095012000d538d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226454f16b7191a379ec0c2e52415d4ebe5d4a1f06a3a3dc78e2a436628f5b0ce8d83b0b7cc63e15acba8b1eb601ba26821d8ce7bc9850d2aa6c7bb3d4d216744b470a83ed5c3daa984ec958f64be54a52a6123465f43b.png)

It can work for multiple hits as well. Maybe not reasonable for the time being, but something to think about design-wise, especially for "commenting" style annotations on non-manuscript content down the line.
