### ISSUE TITLE
Analysis / Discussion: Figure out MVP indexing strategy for annotations

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#728]
## Considerations

 - [x] We need to be able to relate to the parent manuscript/object (druid)
 - [x] We need to be able to relate to the canvas in parent object (for mirador display)
 - [x] We need to be careful about indexing performance and triggering 100's & 1000's of reindexing jobs #RememberBibliographyService
 - [x] Should we use traject as part of this strategy?
 - [x] How do we know when the crawler is complete? (dereferencing)
 - [x] Is it possible to re-use the current indexing process (e.g. tap into gdor mods indexing or something else?)
 - [x] Is it useful for an additional `seeAlso` || `relatedItem` to be added?
 - [x] Is IIIF the right place to get the data?
 - [x] How/can we get the Page Number and Section heading for each annotation? 
 - [x] How do we generate/reduce the URL-based annotation identifier to something that will work in the exhibits route?
 - [x] Do the annotations change? No - not for the MVP which is a curated collection of annotations.
 - [x] Do we need to enable facets for annotations? Language is the only one that might be needed.
 - [x] Do we need to feature flag the annotations for the Parker exhibit? Yes.
cc @cmh2166 

Fixture data:
https://dms-data.stanford.edu/data/manifests/Parker/fh878gz0315/manifest.json

See `otherContent`

Example: https://dms-data.stanford.edu/data/manifests/Parker/fh878gz0315/list/text-f253v.json

**Comment by blalbrit** [comment]
Additional fixture data:  https://exhibits.stanford.edu/parker-2/catalog/bg021sq9590 & http://dms-data.stanford.edu/data/manifests/Parker/bg021sq9590/list/

**Comment by blalbrit** [comment]
The Colligo indexing approaching is here: https://github.com/sul-dlss/colligo/blob/master/lib/data_indexer.rb (this does both MODS indexing & annotation indexing).

**Comment by camillevilla** [comment]
Design #731

**Comment by drh-stanford** [comment]
We had our discussion of the annotation indexing strategy and we captured the whiteboard diagrams (see work cycle document). We also reviewed the design (#726) and created implemetation tickets (#747, #749, #759, #758, #756, #755, #754).

The basic strategy is we have an `Annotation` class that holds the data we need about an annotation (#754). The traject indexer will get fed a single annotation and it will populate Solr with the fields required to instantiate the `Annotation` model class (#759).  The data pipeline is fired off by `ReindexJob` on a per druid basis (O(500) jobs). That ReindexJob will have both its normal indexing plus the new annotation indexing (#756). The main loop in that ReindexJob for annotations is to harvest all of the IIIF Annotation Lists from the manifest for that druid (#755), and then iterate over each annotationList to feed the Traject pipeline each annotation (#758).

The performace considerations are important -- the Traject pipeline should be fast and the concurrency is per druid, but they will likely be long-running jobs as a single manifest has O(100) pages with O(10) annotations per page. We may need to add another worker machine or two. Right now, the worker machine has 50 workers listening for jobs.

**Comment by drh-stanford** [comment]
On 10/26 we discussed making Annotation List a first class object rather than the Annotation itself. This would require some UX design, but the Annotation List (1-to-1 mapping to a manuscript page). This would alleviate some of the performance issues (especially database/indexing requirements).

**Comment by mejackreed** [comment]
Perhaps this is even a "canvas" and would include the "otherContent" annotationlist?

**Comment by drh-stanford** [comment]
Yeah my terminology may be off here. The first class object should be a manuscript page (Canvas) that has a set of annotations (as described by the AnnotationList).

**Comment by drh-stanford** [comment]
The action item here is to gain a better sense of the scale and indexing requirements for making an AnnotationList (canvas) the first-class object. Right now, our estimation is O(100) SDR objects each with O(100) AnnotationLists (canvases) each with O(100) individual annotations. That makes O(10,000) first-class objects for the Parker exhibit.

**Comment by mejackreed** [comment]
Gotcha. And by using a `Canvas` as the first class object, we are at 0(1,000) scale for indexing. That seems more reasonable.

**Comment by drh-stanford** [comment]
@blalbrit can you count/estimate more precisely the number of pages in all the 556 manuscripts? right now our estimate is O(10,000) pages and we'd like to validate that.

**Comment by blalbrit** [comment]
@drh-stanford  - yep, I can run a report to give us an exact count. will do today.

**Comment by blalbrit** [comment]
^^ 200,000 pages (rounded)

**Comment by mejackreed** [comment]
All questions asked and answered
