### ISSUE TITLE
Create fixture data for page level description / annotation

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#729]
cc @blalbrit

**Comment by blalbrit** [comment]
Initial fixtures:
http://dms-data.stanford.edu/data/manifests/Parker/fh878gz0315/list/
http://dms-data.stanford.edu/data/manifests/Parker/bg021sq9590/list/
http://dms-data.stanford.edu/data/manifests/Parker/ft757ht3699/list/

More to come.
