### ISSUE TITLE
Design for manuscript show page to surface associated annotations

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#731]
From #714:

- What do we do on the manuscript show page? Do we show the annotations?
- Could we have a linked search here?
- We can get the count and display here to user if there are annotations.

**Comment by ggeisler** [comment]
Based on current manuscript show page, adding a new section with the annotations count and link:

<img width="1268" alt="manuscript-show-page-with-anno-link" src="https://user-images.githubusercontent.com/101482/31518560-829aabf4-af54-11e7-952a-69071863a3a3.png">

**Comment by camillevilla** [comment]
👍 we can load the number of annotations asynchronously, sort of similar to the SearchWorks zero results page

**Comment by drh-stanford** [comment]
I'm going to close this ticket as we've reviewed the design. Please reopen as needed.
