### ISSUE TITLE
[exhibits/stage] RSolr::Error::Http: 400 Bad Request: ErrorMaxBytesLengthExceededException

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/exhibits#737]
## Backtrace

    line 20 of [PROJECT_ROOT]/app/services/dor_solr_document_builder.rb: yield
    line 20 of [PROJECT_ROOT]/app/services/dor_solr_document_builder.rb: block (3 levels) in to_solr
    line 34 of [PROJECT_ROOT]/app/services/dor_solr_document_builder.rb: block in process_resource_with_logging

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49092/faults/34889907)

**Comment by jkeck** [comment]
I'm closing this for now, we haven't seen this issue come up in months (or at least w/i whatever our HB retention policy is).  It may have come up with doing experiments w/ various parker content indexing strategies.
