### ISSUE TITLE
If Bibliographic items don't exist, don't display "Bibliography" on show page

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#738]
Here is an example of where the heading "Bibliography" exists on a show page for an exhibit that doesn't contain bibliographic items.
![screen shot 2017-10-13 at 8 18 21 am](https://user-images.githubusercontent.com/3210225/31553446-5f84b330-afef-11e7-9621-cc67f8333f56.png)

**Comment by drh-stanford** [comment]
I've verified that this is fixed in production with v1.4.0
