### ISSUE TITLE
The IIIF logo is appearing on objects that are not images

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#745]
Currently, the IIIF logo appears on all objects, regardless of content type.

The IIIF logo should only appear on the following content types:
- image
- book
- map

**Comment by camillevilla** [comment]
So this is looking more complicated than I thought. 

We provide a manifest link (`iiif_manifest_url_ssi`) for all SDR objects added to an exhibit. I've zeroed in on [this code](https://github.com/sul-dlss/exhibits/blob/0c11e632596cbd7add5911a9cb1bdc0e33f3ea45/app/models/spotlight/dor/indexer.rb#L38). I don't think we check anything else about the object before adding a manifest. This leads to objects having invalid `iiif_manifest_url_ssi` values. As long as *something* is present in `iiif_manifest_url_ssi` field, the IIIF logo is added.

## Example manifests
🚨 Invalid manifest link generated (data set, pdf)
https://purl.stanford.edu/py883nd2578/iiif/manifest
https://purl.stanford.edu/rj585xk6315/iiif/manifest

✅ Valid manifest link from a Parker manuscript
https://purl.stanford.edu/sg012cr8689/iiif/manifest

## Example druids (for development)
py883nd2578
rj585xk6315
sg012cr8689

## Possible fixes
1. Fix #752 and restrict IIIF logos by `Resource type` / `format_main_ssim` (short-term)
2. Add something to our `dor/indexer.rb` that checks whether to create a IIIF manifest (I'd need someone with more SDR / IIIF knowledge for this)

**Comment by drh-stanford** [comment]
Thanks for digging into this @camillevilla. I think (2) is workable. Perhaps we need to do both a `.blank?` check and an actual fetch to see whether the URL is a 404/valid in the indexing code. I _think_ we can assume that the druid is published to PURL at index-time and if so I think this'll be fine.

**Comment by drh-stanford** [comment]
Our fix in 766 is causing a slowdown in indexing as the PURL manifest generation is taking too long. We have an alternative strategy which is to use the contentMetadata `@type` attribute to check to see whether the object has a IIIF manifest.

The logic is `%i(image manuscript map book).includes?(type)`

**Comment by camillevilla** [comment]
I agree that the second strategy will be more performant. But is it possible that we'll exclude valid objects? For example, this resource from a David Rumsey exhibit has a `Resource type` of `Object`. 
https://exhibits.stanford.edu/david-rumsey-map-collection/catalog?f%5Bformat_main_ssim%5D%5B%5D=Object&q=+&search_field=search

But it does have a IIIF manifest:
https://purl.stanford.edu/dm066db9496/iiif/manifest

**Comment by camillevilla** [comment]
Oh! Sorry, I spoke too quickly. I see the `@type` attribute you're referring to in the manifest.

**Comment by drh-stanford** [comment]
Yes, I think we're ok. In that case the `content_metadata_type_ssm` is `image`, so it'll show a IIIF logo when it gets indexed to have the `iiif_manifest_url_ssi` field.  See https://exhibits.stanford.edu/david-rumsey-map-collection/catalog/tc186wy5027.json
