### ISSUE TITLE
Async loading of annotations link on manuscript show page

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/exhibits#747]
See #731 for design, see #728 for indexing strategy.

- [ ] Annotation section on manuscript show page
- [ ] View annotations link
- [ ] Count of annotations related to manuscript

Blocked on indexing of annotation content

**Comment by mejackreed** [comment]
@ggeisler do we need to still do this with the current design approach?

**Comment by ggeisler** [comment]
@mejackreed I don't think so. I don't think we still have a plan to show the annotation section on the show page, given the switch to annotation list/page details.
