### ISSUE TITLE
Fix manifest parsing edge-case for thumbnails and resource format in iiif-evented-canvas

### ISSUE THREAD

**Issue by aeschylus** [sul-dlss/exhibits#751]
These two errors keep cropping up:
![screen shot 2017-10-17 at 14 43 25](https://user-images.githubusercontent.com/145874/31691078-a155f3ca-b349-11e7-9a63-2a6eaedee77d.png)

![screen shot 2017-10-17 at 14 44 22](https://user-images.githubusercontent.com/145874/31691102-b3776ebc-b349-11e7-9d74-93e943419741.png)

They are a result of overly-strict manifest parsing by one of Mirador's components: iiif-evented-canvas, which implements an observable object representation of a IIIF canvas and its resources, including their loading states.

There are two issues in the repo already related to this, one of them closed and integrated, the other pending, that need to be released to npm. Then Mirador will need to be updated to use the latest evented-canvas version, and the mirador-rails gem will need to be updated to pull in the latest Mirador, at which point exhibits will need to be updated to pull in the latest mirador-rails gem.

- [x] Add fixtures to the fixtures collection in evented-canvas, and make sure the objects load properly in the demo there
- [ ] Publish a new release of iiif-evented-canvas to npm
- [ ] Update Mirador to pull in the latest version of evented-canvas
- [ ] Publish a release of Mirador that includes the latest updates
- [ ] Update the mirador-rails gem to include this latest version of Mirador
- [ ] Update exhibits with the latest mirador-rails gem

Fixtures: 
https://exhibits.stanford.edu/parker-2/catalog/fp910bz4637
https://iiif.bodleian.ox.ac.uk/iiif/manifest/af500ae6-61b8-4df9-b290-8aab0c2dd10f.json

**Comment by aeschylus** [comment]
Update: https://validate.musiclibs.net/?manifest=https%3A%2F%2Fdms-data.stanford.edu%2Fdata%2Fmanifests%2FParker%2Ffp910bz4637%2Fmanifest.json

The first error is caused by malformed canvases in many dms manifests.

@blalbrit Can we talk about how to bulk-validate and update these?

**Comment by blalbrit** [comment]
Thanks for the chat @aeschylus - sounds like a few tests and then we can close this ticket as a non-issue.

**Comment by aeschylus** [comment]
Yep. Seems to be a non-issue in both cases. Implementation errors in other services.
