### ISSUE TITLE
Resource type facet doesn't have correct count of manuscript docs

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#752]
Other facets, such as the Topic facet, do seem to include the manuscript documents, but the Resource type facet doesn't:

<img width="551" alt="-_parker_library_on_the_web_-_spotlight_at_stanford_search_results" src="https://user-images.githubusercontent.com/101482/31692434-85856eaa-b34e-11e7-9616-9444adfcc925.png">

I don't see Resource Type listed as a metadata field in Configuration > Metadata, either, although I thought we were previously showing that field in the search results and show page (though I might be confusing that with my mockups, which suggest we do want to show that field on those pages to help the user distinguish the type of resource).

**Comment by mejackreed** [comment]
I'm pretty sure that @jkeck looked into this. Wasn't there something that @blalbrit had to add to the metadata?

**Comment by drh-stanford** [comment]
Yes, my understanding is that @blalbrit was going to add/relocate the resource type metadata in the Parker manuscript objects. I'm going to assign this to Ben.

**Comment by blalbrit** [comment]
resource type metadata was updated, but that uncovered an indexing issue in Exhibits prod (#768). @drh-stanford has confirmed that the data is as expected, so closing.
