### ISSUE TITLE
Reindexing removes custom tagged items from browse categories

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#753]
This afternoon I reindexed the Travel Through Time exhibit: https://exhibits.stanford.edu/time-travel-japan. AFTER reindexing (and I didn't check before) -- I noticed that several browse categories were displaying with `0` items: https://exhibits.stanford.edu/time-travel-japan/browse. This exhibit used custom tags to help create several browse categories. Total items for each custom tag are still displaying on Dashboard > Curation > Tags : https://exhibits.stanford.edu/time-travel-japan/tags -- yet when I execute a search on, for example: `Temple Precincts` (a browse category, and a custom tag with 46 items), the search result comes up empty.

I was concerned that perhaps my reindexing of the exhibit had caused this to occur (it should not have, but I was worried about any recent work that could have caused this indexing issue to occur). So, I went to -stage (where unfortunately, we do not have an instance of the Travel Through Time exhibit) -- but I found an exhibit there that has lots of custom tags used to create many browse categories (https://exhibits-stage.stanford.edu/harrison). I took before screen shots of the browse categories (see attachments), which now display many `0`results after reindexing. I also took before-reindexing screen shots of all the custom tags. 

Expected behavior: Custom tags & their relationships should be retained when reindexing an exhibit.

![screen shot 2017-10-17 at 4 34 26 pm](https://user-images.githubusercontent.com/3210225/31695096-3a095810-b35d-11e7-8868-174d7d5c47ea.png)
![screen shot 2017-10-17 at 4 34 38 pm](https://user-images.githubusercontent.com/3210225/31695097-3bdd1f3c-b35d-11e7-88d4-855c15b2f2cd.png)
![screen shot 2017-10-17 at 4 33 17 pm](https://user-images.githubusercontent.com/3210225/31695089-2a0f257a-b35d-11e7-9a36-98e691728b42.png)
![screen shot 2017-10-17 at 4 33 05 pm](https://user-images.githubusercontent.com/3210225/31695091-2dad19ee-b35d-11e7-8eab-10b024bda9a2.png)
![screen shot 2017-10-17 at 4 33 25 pm](https://user-images.githubusercontent.com/3210225/31695093-2faf0914-b35d-11e7-9973-e9d467871f0e.png)

**Comment by jkeck** [comment]
I have been doing a little investigation into this and I believe we're missing another migration.  I'll push a PR to add the migration from Spotlight, but I think somebody else should deploy this to stage to see if it works as my attention is divided at the Blacklight summit.

**Comment by drh-stanford** [comment]
I've tested this fix in stage and it's working ok. I'm re-testing it now with the v1.4.0 release where the PR was merged.
