### ISSUE TITLE
Create Canvas data model

### ISSUE THREAD

**Issue by aeschylus** [sul-dlss/exhibits#754]
see whiteboard photo (click me to see me right-side up :):

![img_1308](https://user-images.githubusercontent.com/1861171/31737218-a49cc196-b3fb-11e7-833b-81200ce9dec5.jpg)

Acceptance criteria:

- [x] Investigate whether a SolrDocument is sufficient
- [x] Resource type of "Annotation"
- [x] Solr field names for all data elements

Story #714 
Analysis #728

### Examples
Here is an example manifest from dms-data: http://dms-data.stanford.edu/data/manifests/Stanford/ege1/manifest.json

Search for an otherContent key in this manifest. The value will be a link to another JSON-LD document such as: http://dms-data.stanford.edu/data/manifests/Stanford/kq131cs7229/list/text-f8r.json

There may be up to one annotationList for every canvas in the manifest. Visiting the list above, you will see annotations, such as the one at the  `AnnotationList.resources[0]` path. It looks like this:

``` json
{
@id: "_:N43deaea09a5345379218db8cb72600c3",
@type: "oa:Annotation",
motivation: "sc:painting",
resource: {
@id: "7377e5fe51c46454bb01b62a817a4d42",
@type: "cnt:ContentAsText",
format: "text/plain",
chars: "Erant aut[em] qui manducaverant",
language: "lat"
},
on: "http://dms-data.stanford.edu/data/manifests/Stanford/kq131cs7229/canvas/canvas-3#xywh=600,450,1017,166"
}
```

**Comment by drh-stanford** [comment]
We need to revise this data model to include an AnnotationList that is comprised by a set (list?) of annotations.

**Comment by drh-stanford** [comment]
From the IIIF spec:

![](http://iiif.io/api/presentation/2.1/img/objects-all.png)

**Comment by drh-stanford** [comment]
I have the beginnings of a Canvas-based data model where they are first-class resources (CanvasResource), and some traject code for indexing. See #800.
