### ISSUE TITLE
Implement a Traject IIIF CanvasReader

### ISSUE THREAD

**Issue by aeschylus** [sul-dlss/exhibits#758]
Depends on #755.

The traject pipeline needs to have an Annotation List (canvas) as a record, and it'll aggregate all of the specific annotations into a multivalued field (accumulator).

Acceptance criteria:

- [ ] Investigate from DLME approach
- [ ] Integrate with harvester of AnnotationLists
- [ ] Integrate with the data pipeline record model (see BibTeXReader for example)

cc: @cmh2166

Story #714 
Analysis #728 
Fixtures #729

**Comment by cmh2166** [comment]
Putting some of the DLME influenced / sourced work in a branch for easier review / comparison. No expectation of reuse, just in case it is helpful. Will add link and notes in a second.

(fwiw, removed my previous traject example branches to keep the working space clean)

**Comment by mejackreed** [comment]
https://docs.google.com/drawings/d/1ivEG4pCNyFwhnMutjG56G_OmvQvwscNu6qId-JcTlSc/edit

**Comment by mejackreed** [comment]
On analysis w/ team this seems to be done already.
