### ISSUE TITLE
Implement a Traject data pipeline for each Canvas

### ISSUE THREAD

**Issue by aeschylus** [sul-dlss/exhibits#759]
Record parsing and population of the Annotation data model. We're assuming the default Traject SolrWriter

Acceptance criteria:

- [x] Look at reuse from DLME
- [x] Need parsing code for IIIF annotation schema 
- [x] Need to map that schema into our data model schema (see CanvasConcern for SolrDocument)
- [ ] Need to ensure that we get good concurrency with ReindexJobs per druid (or per page?)

cc @cmh2166

might be a big ticket -- split off as needed

Story #714 
Analysis #728 
Fixtures #729

**Comment by blalbrit** [comment]
For an example of code that traverses a manifest and extracts annotations from otherContent (ie. annotation lists), see: https://github.com/sul-dlss/colligo/blob/master/lib/data_indexer.rb
