### ISSUE TITLE
Improve monitoring for failed Sidekiq jobs

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/exhibits#769]
We have been seeing many (4k+) failed jobs in Sidekiq, but are not AFAICT receiving any alerts about it (nor notifications in Honeybadger). This ticket is to track improving our monitoring of failed Sidekiq jobs through some mechanism (nagios with okcomputer?)

Here's a snapshot of what we're seeing in production: 4,055 failed, 66 retries, and 15 dead jobs.

![screen shot 2017-10-18 at 4 44 59 pm](https://user-images.githubusercontent.com/1861171/31747788-b5123cd6-b423-11e7-877c-a96fac299501.png)

**Comment by caaster** [comment]
Cathy: Would provide ability for alerting re indexing issues which doesn't currently exist.
Jessie: May need ops support if we need to them to poke access through so we can access our retry queue, if we can get access ourselves, then no ops support needed

**Comment by corylown** [comment]
@caaster I'd advocate that we close this issue that has been open for 7 years with no action other than the okcomputer check that has already been added. We could open a new issue if this becomes a problem for us again.

**Comment by caaster** [comment]
@corylown agreed.
