### ISSUE TITLE
Navigate by page or folio number

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#771]
In Parker 1.x, a user was able to navigate the manuscript by page or folio number:

<img width="762" alt="screenshot 2017-10-19 09 47 27" src="https://user-images.githubusercontent.com/796990/31783298-a2241aba-b4b2-11e7-87af-99923c4bd261.png">

We have been hearing from users that this is desirable functionality in Parker 2.0. Given that the list of page/folio labels can be provided in the IIIF manifest for each object, is there a way that we could satisfy this request?

e-codices handles this with a drop-down:
<img width="920" alt="screenshot 2017-10-19 09 50 41" src="https://user-images.githubusercontent.com/796990/31783460-2acd4d96-b4b3-11e7-828e-d0ac9654de14.png">

digital Bodleian does it with a slider:
<img width="1389" alt="screenshot 2017-10-19 09 51 36" src="https://user-images.githubusercontent.com/796990/31783470-3590258c-b4b3-11e7-8d81-64fe667ae1b3.png">

cc. @ggeisler

**Comment by mejackreed** [comment]
Since a manifest is the unit of discovery, could we use the internal Mirador range display (table of contents) to accomplish this?

**Comment by mejackreed** [comment]
Gotcha. My first thoughts on this feel like this work should be considered in Mirador. Navigation of IIIF ranges is non-trivial , and the more we can consolidate that in clients that already have understanding of that the better. Keeping it contained in IIIF clients seems like a good idea especially with the possible deprecation of ranges.

Is the idea here that users need to "type in" a folio number to go to it? Or selecting from a TOC or scroll view is not efficient?

![scroll](https://user-images.githubusercontent.com/1656824/31794768-60c09f06-b55e-11e7-92bc-42663fff6f3e.gif)

**Comment by blalbrit** [comment]
@mejackreed - the primary feedback is that they would like to choose/type-in a folio/page number and go straight to it, rather than navigating the thumbnails (either along the thumbnail strip or in the thumbnail view). Some of it might be down to efficiency of navigation.

My understanding of this user need is that many scholars will have specific folio references they are looking for and want to just be able to go directly to it without navigating the thumbs - whether this is because the thumbs are slightly cumbersome (for larger manuscripts, lots of scrolling + slow thumb load times have been reported as frustrating), or because it seems like an unnecessary step is less clear to me.

**Comment by mejackreed** [comment]
Awesome thanks thats great feedback!

**Comment by mejackreed** [comment]
Seems like the best approach is for this to happen inside of mirador or in a mirador plugin: https://github.com/ProjectMirador/mirador/issues/950
