### ISSUE TITLE
From a browse result view, is it possible to limit search to items within that result list?

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#774]
In current search results, additional searches are additive (as below: first "manuscripts" and then "manuscripts + Augustine":
<img width="1302" alt="screenshot 2017-10-19 10 08 15" src="https://user-images.githubusercontent.com/796990/31784153-92d5f170-b4b5-11e7-9561-0064bcc31040.png">
<img width="1222" alt="screenshot 2017-10-19 10 08 30" src="https://user-images.githubusercontent.com/796990/31784165-99bfb0b6-b4b5-11e7-8866-4c7365961c04.png">

Is it possible to get the same results from the Browse categories?
1) Click on "Browse All Manuscripts"
2) Search on Augustine and *not* get bibliographic items in the results?

**Comment by cbeer** [comment]
Anything is possible; I suspect this should get a design needed tag, though.

**Comment by blalbrit** [comment]
Good point - we had discussed with @ggeisler but will tag it so that it stays on the radar.

**Comment by blalbrit** [comment]
See #772

**Comment by camillevilla** [comment]
This question was addressed at story time (11/2):
- using the search bar ejects the user from the browse category they were in
- sidebar / facets are not available from browse categories (discussed in #772)
- #816 will add a new "saved search" widget
