### ISSUE TITLE
Investigate exhibit-based feature flag for fielded search dashboard

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/exhibits#777]
We'd like to only show the Parker-specific fielded search metadata in the dashboard. See #743.

**Comment by mejackreed** [comment]
In reviewing this ticket for implementation, "text title" AKA TOC is a field that is used in other exhibits. I would think that this field should be global and not limited to Parker.

**Comment by drh-stanford** [comment]
I think this is resolved now with the fielded search implementation in v1.5.0

**Comment by cbeer** [comment]
I thought this ticket was, essentially, "hide parker-specific field configurations from other exhibits", which is not yet done.
