### ISSUE TITLE
Implement Solr query language support for boolean and prefix matching

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/exhibits#779]
We have existing behavior that supports this but we may need to tweak the Solr configuration.

Based on Discussion Below
 - [x] test/implement boolean
 - [ ] test /implement wildcard

See #406 for context but there may be some issues with using the wildcard operator from BLAS. This could now use "and" as a boolean operator (where previously it wasn't)

**Comment by mejackreed** [comment]
Verify that it is implemented.

**Comment by blalbrit** [comment]
Add example searches here.

**Comment by camillevilla** [comment]
## Fixtures
- Manuscript: [cf386wt1778](purl.stanford.edu/cf386wt1778)
- [Collection of bibliography items](https://drive.google.com/file/d/0B30Uf0ba2atMVWZTek91SXRId2c/view?usp=sharing)

## Booleans

- **AND** (4 results): http://localhost:3000/test/catalog?utf8=%E2%9C%93&exhibit_id=test&search_field=search&q=Corpus+AND+Christi 
- **OR** (6 results): http://localhost:3000/test/catalog?utf8=%E2%9C%93&exhibit_id=test&search_field=search&q=Corpus+OR+Christi
- **NOT** (2 results): http://localhost:3000/test/catalog?utf8=%E2%9C%93&exhibit_id=test&search_field=search&q=Christi+NOT+Corpus

**Comment by drh-stanford** [comment]
Yes, they are wildcard searches, i.e., `eleph*` for elephant

**Comment by camillevilla** [comment]
It looks like prefix / wildcard searches are **not** working. 

Same fixtures as above:

- corpus (4 results): [http://localhost:3000/test/catalog?utf8=%E2%9C%93&exhibit_id=test&search_field=search&q=corpus](http://localhost:3000/test/catalog?utf8=%E2%9C%93&exhibit_id=test&search_field=search&q=corpus)
- corp* (0 results) :[http://localhost:3000/test/catalog?utf8=%E2%9C%93&exhibit_id=test&search_field=search&q=corp*]( http://localhost:3000/test/catalog?utf8=%E2%9C%93&exhibit_id=test&search_field=search&q=corp*)

**Comment by mejackreed** [comment]
I believe this PR may add support for wildcards, but I'm not sure we exactly want that behavior. See the referenced caveat. 

@blalbrit Can you comment on the Parker user story for wildcard search?

**Comment by blalbrit** [comment]
I'm not sure I fully understand what you're asking @mejackreed  - but I think a minimum desire would be something like: "neum*" (expect 18 results: https://parker-stanford-edu.stanford.idm.oclc.org/parker/actions/manuscript_description_search_results.do?keyword=neum*) - that is, wildcards to complete stems. August* to return Augustine, Augustinian, etc.

Is that what you're asking?

**Comment by mejackreed** [comment]
Yep exactly. Thanks @blalbrit

**Comment by camillevilla** [comment]
More comments from @jkeck forthcoming. Concerns about #407 include:
>treats "and" and "or" as "AND" and "OR" in Lucene syntax mode
[(source](https://lucene.apache.org/solr/guide/6_6/the-extended-dismax-query-parser.html))

This could possibly affect existing browse categories.

**Comment by jkeck** [comment]
We believe that one of the concerns is that existing browse categories that used (even lowercase) "and"/"or" and expected those to be treated as literals would now potentially be treated as boolean operators and could return a different result set than originally expected.

One thought that was brought up when discussing this was the possibility of making the query parser configurable in the admin UI.  This would allow current exhibits to maintain their existing (default) behavior but exhibit administrators would have the ability to turn on this behavior (and we can use that opportunity to educate them as to the consequences of that decision).  This would obviously require some design considerations but might not be too difficult to implement administration wise.

**Comment by mejackreed** [comment]
@jkeck I wonder if we could use the `lowercaseOperators=false` w/ edismax to accomplish our goal here?

**Comment by blalbrit** [comment]
I think we got to a point where we are done with this work (or chose other strategies). @mejackreed or @jkeck - can you confirm and we can close?

**Comment by jkeck** [comment]
I think the PR for wildcards is still open.  I'll close this but leave a comment on the PR to make sure the context here is noted in case we pick this back up in the future.
