### ISSUE TITLE
Implement dashboard UI for extra fielded search fields

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/exhibits#781]
In #743, we have an admin UI for selecting which fields to put in the dropdown list next to the search box. This is an existing UI and we need to extend it to include the Parker fields. See #777 for extra considerations on making the new fields viewable only on Parker exhibit. The admin UI should enable/disable the fields in the dropdown list next tot he search box. This ticket might need to be broken up.

**Comment by drh-stanford** [comment]
This should be a configuration change based on #792.

**Comment by drh-stanford** [comment]
Can we turn them off (i.e., not checked) by default in the configuration UI? We talked about that as an option in the discussions around #743.

**Comment by mejackreed** [comment]
I think that would be ideal. I don't see a way to do that at the moment in Spotlight without some enhancement.

**Comment by drh-stanford** [comment]
This is resolved as part of the fielded search implementation in v1.5.0
