### ISSUE TITLE
<typeOfResource collection="yes"/> gets wrong format

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/exhibits#786]
It's setting `format_main_ssim` to Archive/Manuscript when it should be a collection. Example object:

https://exhibits.stanford.edu/parker-2/catalog/dx969tv9730.json

Also see https://github.com/sul-dlss/stanford-mods/blob/master/lib/stanford-mods/searchworks.rb#L289

Question: do old Solr fields get purged on reindex? perhaps this is stale data?

**Comment by mejackreed** [comment]
Are there SearchWorks implications here?

**Comment by drh-stanford** [comment]
I don't think so. We don't need to modify the stanford-mods (or mods) gems. The problem seems to be related to indexing. I thin the problem is that `format_main_ssim` isn't changing for a collection because it should be absent/nil. I'm trying to verify this but the indexing throughput on stage is terrible...

**Comment by drh-stanford** [comment]
I was able to reproduce this on my development instance. The collection is handled a bit differently than a normal druid, so I need to follow another code path.

**Comment by drh-stanford** [comment]
@blalbrit well, this behavior is hard-coded into the `gdor-indexer` gem. See https://github.com/sul-dlss/gdor-indexer/blob/master/lib/gdor/indexer.rb#L170.  Note the comment has a JIRA issue reference (INDEX-12, add this to all collection records (does not add dups)).

Is this something we want to override for Parker only, or Exhibits only?

**Comment by blalbrit** [comment]
@drh-stanford - since gdor indexer only is used by Spotlight/Exhibits now (I think - please correct me if I'm wrong), it probably makes sense to do it Exhibits-wide. ping @caaster for confirmation. If it's easier to do this Parker only, we can consider that as well. Given that it only impacts one object in Parker, is there a work-around we can come up with, or is a code-change required?

**Comment by drh-stanford** [comment]
a code change is required but it's pretty trivial and easier to do it exhibits-wide.
