### ISSUE TITLE
Determine which sir trevor widgets should be enabled in Exhibits

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#790]

**Comment by camillevilla** [comment]
Upstream fixes in Spotlight will remove the following widgets:
- Image
- Twitter
- blank widget in "Exhibit item widgets"

These fixes will also give us the ability to further restrict which widgets are available in Exhibits (if desired).

## Before
<img width="942" alt="31913272-94c77078-b7fb-11e7-9455-5acf758e2823" src="https://user-images.githubusercontent.com/5402927/31966933-2562cdec-b8c1-11e7-9e24-55994b12a876.png">

## After
![screen shot 2017-10-23 at 5 40 08 pm](https://user-images.githubusercontent.com/5402927/31966956-35d37604-b8c1-11e7-9e99-5c42a1eb785b.png)

**Comment by mejackreed** [comment]
As @camillevilla pointed out, I think we can just go with the "after" ones as they were the previously enabled widgets. Closing this issue.
