### ISSUE TITLE
Implement more advanced manuscript title

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#791]
Spun off from #722 see that ticket for original discussion. I believe we need some design around how the title should be displayed.

![screen shot 2017-10-24 at 12 11 25 pm](https://user-images.githubusercontent.com/1656824/31956259-e247f184-b8b8-11e7-8c2c-7d5fd28ec10d.png)

**Comment by camillevilla** [comment]
On the implementation side: I'm trying to figure out how to use `displayLabel` as a field label for PR #795 / #544 as well.

**Comment by mejackreed** [comment]
@camillevilla are there designs yet for what that should look like?

**Comment by camillevilla** [comment]
@mejackreed #544 suggests that these should blend in with other metadata fields. So for the example above, it would read: 
**M.R. James Title:** Gregorii Homiliae

**Comment by camillevilla** [comment]
I'm working on another ticket now, but in case someone else picks this up:
See approach in [#795](https://github.com/sul-dlss/exhibits/pull/795/files)

**Comment by camillevilla** [comment]
Closed by #872 / #919.
