### ISSUE TITLE
Add blacklight range facet gem for the year facet

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/exhibits#80]

**Comment by peetucket** [comment]
quick test of trying to install blacklight-range-limit causes an explosion when starting the server

blacklight 5.16.3
blacklight-spotlight 0.6.0
blacklight-range-limit  5.2.0
ActiveSupport::Concern::MultipleIncludedBlocks: Cannot define multiple 'included' blocks for a Concern
/Users/petucket/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.2/lib/active_support/concern.rb:126:in `included'
/Users/petucket/.rvm/gems/ruby-2.2.2/gems/blacklight-5.16.3/app/controllers/concerns/blacklight/catalog.rb:9:in `<module:SearchContext>'
/Users/petucket/.rvm/gems/ruby-2.2.2/gems/blacklight-5.16.3/app/controllers/concerns/blacklight/catalog.rb:6:in `<module:Catalog>'
/Users/petucket/.rvm/gems/ruby-2.2.2/gems/blacklight-5.16.3/app/controllers/concerns/blacklight/catalog.rb:2:in `<top (required)>'
............
/Users/petucket/.rvm/gems/ruby-2.2.2/gems/blacklight_range_limit-5.2.0/lib/blacklight_range_limit.rb:27:in `inject!'
/Users/petucket/.rvm/gems/ruby-2.2.2/gems/blacklight_range_limit-5.2.0/lib/blacklight_range_limit/engine.rb:20:in `block in <class:Engine>'

**Comment by cbeer** [comment]
With Blacklight 5.16.4 we get a little further:

```
No route matches {:action=>"range_limit", :controller=>"spotlight/catalog", :exhibit_id=>"default-exhibit", :q=>"", :range_end=>"2013", :range_field=>"pub_date", :range_start=>"1582", :search_field=>"search", :utf8=>"✓"}
```

Now the problem is, spotlight is looking for routes defined in the spotlight engine, but we have no way to inject it from the application's routes.
