### ISSUE TITLE
Unable to add druids (MD fixtures) to exhibit

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#801]
I created & accessioned a number of metadata fixture objects into the SDR. 
rs380fd6758
xp206mp4567
qc252vx8479
vg932xk2289
jg467pm5531

Please note these druids have no content -- but they do have metadata. When I try and add them to this exhibit, nothing happens.

https://exhibits.stanford.edu/md

I am seeing a big error message on the dashboard under
Add items > Item status > Object druids
...that I could use some assistance in deciphering.

The fixture objects will be important to have in this exhibit for the upcoming round of metadata work, once the Parker MVP is delivered.

**Comment by cbeer** [comment]
It looks like these items are missing a `contentMetadata` element in their public XML. The indexing code we're using expects and requires this. It might be possible to fix this upstream (in gdor-indexer), but I'm sure that's a good use of time (assuming we still intend to move off this legacy indexing stack, now that we're the only consumer of it..)
