### ISSUE TITLE
Need: The ability to test anno indexing at scale for production

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#812]
Our current annotation implementation "works" but we haven't tested this at scale. The Parker data is not yet in a state where this is even possible. With current estimates, the entire Parker collection will have ~100,000 annotations. I see two approaches for how to do this:

  - Create fake data and publish (perhaps to gh-pages or equivalent) with manifests and annotation lists for all manuscripts to appropriately understand scaling

OR

 - Help with the process of converting the TEI into IIIF manifests/ annotation lists. Per @blalbrit:

 > The page refs need to be mapped to canvases is the only tricky bit I can see.

TEI data at : https://github.com/ParkerWeb/descMD/tree/master/split-xmls/description

**Comment by mejackreed** [comment]
I generated some fake data here: https://github.com/mejackreed/parker-scale-data

And this can be used with a custom manifest pattern like so:

`https://mejackreed.github.io/parker-scale-data/{id}/manifest.json`

**Comment by mejackreed** [comment]
This ticket may need to figure out how to turn the TEI data into IIIF annotations.

**Comment by blalbrit** [comment]
Think we can close this, eh @mejackreed ?
