### ISSUE TITLE
Update configuration to make "format_main_ssim" an index field

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#815]
We currently show Resource type as a facet 

```
 config.add_facet_field 'format_main_ssim', label: 'Resource type', limit: true
```

but it's not configured as an index field and doesn't show up in the list of potential metadata fields.

I think we do want to show the Resource Type field in search results (and possibly the show pages), because it could be important for the user to be able to distinguish between the type of documents available, and I don't think we want to rely entirely on the thumbnail variations for distinguishing document types.

**Comment by jkeck** [comment]
Did a quick test on this and it is possible to add to the configuration and it will apply to existing exhibits, however it will have the behavior that it will be turned on by default in all exhibits.  (unsure if projectblacklight/spotlight#1854 may help us out here or not)

**Comment by ggeisler** [comment]
Given how many published exhibits we currently have (and the likelihood that "Resource type" is a field that will have a value in many or most exhibits and thus be displayed?) we should probably wait on this until we know more about projectblacklight/spotlight#1854. If that enables us to set default values per field, we can make `format_main_ssim` false by default and things should be okay.
