### ISSUE TITLE
Design for new saved search widget

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#816]
@ggeisler Do we need mocks for this or can we riff off of what is already in place for the feature page stuff?

**Comment by ggeisler** [comment]
Here's a simple option for discussion: 

1. Create a new widget icon, called "Saved Searches"
2. Create a new widget panel, which is identical to the existing "Browse Categories" widget panel except for the intro text:

<img width="482" alt="saved-search-widget" src="https://user-images.githubusercontent.com/101482/32621952-b48bae2e-c53e-11e7-85ca-b46940a5a0c1.png">

One difference from the Browse Categories widget is that any existing browse category, including ones not checked as "published", should be available for use as a saved search.

3. In the rendered feature page, use the same layout of saved Saved Searches as for the Browse Categories.
4. When the user selects a Saved Search item from the feature page, they are taken to the search result page produced by the underlying saved search parameters.

One drawback of this approach is a slight awkwardness in terminology, in that the curator is selecting a saved search that is stored in the admin as a "browse category." But addressing the terminology issues would involve a bunch of updates on the admin side and I'm not sure we want, or really need, to go that far.

**Comment by cbeer** [comment]
In https://github.com/projectblacklight/spotlight/commit/07d7efe9f0658a6fa507cdd5df66f7bf2e5ea826, we restricted the autocomplete pull-downs to only include published resources. To implement this, I think this should be relaxed to show all saved searches. We currently have a design that applies a `private` label to the autocomplete values:

<img width="253" alt="screen shot 2017-11-09 at 13 33 28" src="https://user-images.githubusercontent.com/111218/32630724-974fb6b6-c552-11e7-999e-4a6cb874cb4f.png">

I assume we can just go with that here (and for the regular browse category widget, and the search results widget)? Do we care about the distinction between published and unpublished for this new widget (or, do we care enough to suppress the label)?

**Comment by ggeisler** [comment]
Your suggestion sounds fine to me. Perhaps we should edit the last sentence of the introduction text on the saved search widget panel to use the term "private" so it matches what the user will see if they try to use an unpublished browse category. Updated text would be:

> This widget highlights saved searches. Each highlighted saved search links to the search results page generated by the saved search parameters. Any saved search listed on the Curation > Browse Categories page, whether public or private, can be highlighted as a saved search.

We don't label the "published/unpublished" checkbox on the browse categories page with any term so I don't think this would add any confusion?
