### ISSUE TITLE
Investigate traject_plus refactor

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/exhibits#818]
We're interested in using macros from the `traject_plus` gem to help standardize our indexing workflow. 

- [ ] install [traject_plus gem](https://github.com/sul-dlss/traject_plus)
- [ ] investigate abstracting out IIIF resource class logic (see @cmh2166 comments in #806 and sul-dlss/traject_plus#2 ) in the annotation indexing pipeline. @mejackreed points out that this may affect how we queue and process jobs.

**Comment by mejackreed** [comment]
@cbeer does https://github.com/sul-dlss/traject_plus/pull/3 address all/some of this?

**Comment by cbeer** [comment]
Yes, it's closely related.

**Comment by corylown** [comment]
The feature set of traject core has expanded so we no longer need to use traject plus for handling non-marc metadata.
