### ISSUE TITLE
Is it possible to have a default sort order other than relevancy ranking?

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#825]
On the search configuration page of the dashboard (https://exhibits.stanford.edu/parker-2/search_configuration/edit), under the "results" tab, it appears as if it might be possible to choose a default sort order other than relevance. Specifically, the accompanying text says: "The field listed first is the default sort field."

However, "Relevance" seems to be locked as the first field, cannot be unchecked, and appears to take precedence over the other sort fields (see example below):
<img width="667" alt="screenshot 2017-11-04 22 09 02" src="https://user-images.githubusercontent.com/796990/32412205-81f9f478-c1ad-11e7-96eb-14693628ee4c.png">

So - the question is: Is it possible to have a default sort order other than relevancy ranking?

If so, how?

**Comment by mejackreed** [comment]
It might be possible. What kind of goal are we trying to achieve here?
