### ISSUE TITLE
Investigate / remove duplicate table of contents search fields

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#828]
Originally raised by @camillevilla via Slack. It seems that both "Table of contents" and "Text title" search fields may just be the same content.

See: https://github.com/sul-dlss/exhibits/blob/master/app/controllers/catalog_controller.rb#L268-L277 and https://github.com/sul-dlss/exhibits/blob/master/app/controllers/catalog_controller.rb#L290-L299

The one difference may be how the field is being searched.

The work here is:
 - [x] Investigate and verify these are duplicates
 - [x] Figure out which search field should be searched (and the best label for it)
 - [ ] Remove duplicate search field / test how this may affect existing exhibits who chose this

**Comment by mejackreed** [comment]
@blalbrit Is "text title" always really just the table of contents (are there differences)? What is the preferred distinction / label for this in the UI?

**Comment by blalbrit** [comment]
@mejackreed - can you tell me which MODS elements are being indexed into the "text title" and "Table of Contents" SOLR fields? If I know what is being mapped from MODS to SOLR I think I'll be able to answer your question.

**Comment by mejackreed** [comment]
They are coming from `<mods><tableOfContents>`. Does it make sense to call this table of contents then everywhere? I think "text title" is the legacy parker name no?

**Comment by blalbrit** [comment]
If they're both coming from Table of Contents, I think calling it table of contents makes sense. Maybe you can confirm this though - I think "text title" was first used in the context of a fielded search (and you're right, from legacy parker). See the fielded search in Parker 1.x here:
<img width="760" alt="screenshot 2017-11-13 09 35 28" src="https://user-images.githubusercontent.com/796990/32739928-2ddb554e-c856-11e7-8e06-cf2aea42449b.png">

If that's the case, is there any argument for keeping a "text title" field separate from Table of Contents? (that is, does fielded search require something special?) That label does mean something specific in the case of search, I guess (you're only searching the titles of texts within a manuscript).

If we can get both the display and fielded search functionality from a single field, and it makes the most sense (from a clarity point of view) to call that field Table of Contents to reflect the MODS element that is being indexed (esp. if this is used across exhibits), then I would be comfortable calling it "Table of Contents" across the board.

**Comment by mejackreed** [comment]
Yes we can get both from a single field. I think it makes sense to move everything to "Table of contents". It doesn't seem like we are doing anything special to call it a "Text title" just popping the values from `<tableOfContents>` into it.
