### ISSUE TITLE
Add download function to Mirador a la BSB

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#829]
The BSB has what looks like a download plugin added to Mirador (see https://app.digitale-sammlungen.de/bookshelf/view/e091438b-3f83-4cd2-917b-d33adb4d8aab?view=ImageView&manifest=https%3A%2F%2Fapi.digitale-sammlungen.de%2Fiiif%2Fpresentation%2Fv2%2Fbsb00059963%2Fmanifest&canvas=https%3A%2F%2Fapi.digitale-sammlungen.de%2Fiiif%2Fpresentation%2Fv2%2Fbsb00059963%2Fcanvas%2F1 ).

Is it possible to use this plugin or something similar to achieve download in Mirador?

Additional exhibits have requested this functionality as well, @snydman suggested adding this ticket.

**Comment by aeschylus** [comment]
I don't see why not.

**Comment by blalbrit** [comment]
We think this can be accommodated through link to PURL and/or PDF -download in metadata.

**Comment by blalbrit** [comment]
Closing as we have an alternate strategy for Parker, and download functionality in Mirador should be addressed in Mirador.
