### ISSUE TITLE
Investigate why anno's are not indexing in production

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#838]
Ideas?

 - [x] Have the production configs been updated and sidekiq workers restarted

**Comment by jkeck** [comment]
🤔 hmm, as I mentioned I had to manually update the configs and did assert that they were updated an all 3 production VMs.  I also manually kicked off a restart, but I bet that doesn't restart sidekiq workers.

I'm going to restart via capistrano and try re-indexing.

**Comment by jkeck** [comment]
Getting cert errors from dor-fetcher.  Operations is on it and our reindex is stuck in a retry loop until that cert error is resolved (at least I hope that's the issue).

**Comment by jkeck** [comment]
That seemed to do it!  Looks like we're getting Page objects indexed in the `parker-2` exhibit after that certificate error was resolved.

<img width="312" alt="parker-facet" src="https://user-images.githubusercontent.com/96776/32506120-9eee2544-c398-11e7-8526-b979443050e7.png">
