### ISSUE TITLE
Handle case where only 1 text title is available

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#869]
`bg021sq9590`

![texttitle](https://user-images.githubusercontent.com/1656824/32677354-519048d8-c61b-11e7-95f4-16ff60d83135.gif)

cc @ggeisler

**Comment by ggeisler** [comment]
@mejackreed Yes, good point. I think this is the same situation as #865 and if we can handle it as suggested there that would be ideal. If only one entry in the text title field, just show the value in the `dd` and don't use the expand/collapse structure.

I guess in this case it's more complex to determine if there is only one entry in the field, but if we can do it, let's.
