### ISSUE TITLE
"Page Details" not showing up for new annotations

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#935]
After producing page-level annotations for most of the manuscripts, and reindexing, I'm seeing some things that confuse me. Primarily, the annotation bodies (ie. "Page Details") are not appearing, even though the annotationLists seem to be correctly identified and indexed. As an example (though this is widespread):

Looking at: http://dms-data.stanford.edu/data/manifests/Parker/zv088kx4487/manifest.json

If I load this into Mirador, I see annotations on f. 1r as follows:
<img width="1616" alt="screenshot 2017-11-22 04 13 49" src="https://user-images.githubusercontent.com/796990/33127185-515bb698-cf3c-11e7-9a6e-6d1d2e76d88a.png">

However, if I look at the same folio in the "Page Details" results in exhibits/parker-2 (https://exhibits.stanford.edu/parker-2/catalog/canvas-79d1a441fb92262228f948815919d490), the annotation bodies themselves don't appear:

<img width="658" alt="screenshot 2017-11-22 04 15 16" src="https://user-images.githubusercontent.com/796990/33127285-b06ed9da-cf3c-11e7-8892-66cb5cdee1f5.png">

I wonder if someone could help me understand this discrepancy? Particularly, if we could isolate if it's a data problem or an indexing problem, that would be most helpful.

**Comment by blalbrit** [comment]
@mejackreed - would you have time to take a look at this today?

**Comment by mejackreed** [comment]
@blalbrit I think I found the issue. We make sure that the annotation resource is of type `oa:Annotation`. Looking at the annotationList here: https://dms-data.stanford.edu/data/manifests/Parker/zv088kx4487/list/100v.json

I'm seeing that `@type` as `oa:annotation`.  I think that our validation of `oa:Annotation` is probably correct, so it seems like its perhaps a data issue? But would love more feedback from others who have worked more on this.

**Comment by blalbrit** [comment]
@mejackreed - I have made the change from annotation/Annotation for all page details and have kicked off reindexing. Will report back when that is complete.
