### ISSUE TITLE
Add expand/collapse behavior for related items

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/exhibits#947]
Blocked by #905/#938
Related to #905 for related items with nested metadata:

When there is more than one related item with nested metadata, the main label for the group gets an "expand all" link. 
  - Clicking the link opens all the nested items in the group; 
  - link text changes to "collapse all"
  - all arrows rotate 90 degrees CW
  - Clicking "collapse all" closes all nested items; label changes back to "expand all"; all arrows revert to starting state.

<img width="700" alt="related item open" src="https://user-images.githubusercontent.com/6945691/32915311-4bc10fb2-cacd-11e7-8e68-518a19186c86.png">

**Comment by blalbrit** [comment]
@camillevilla @mejackreed - can you confirm that this work is not complete? And, if not complete, can you confirm whether or not it will be completed?

**Comment by camillevilla** [comment]
@blalbrit this is up for review now

**Comment by arcadiafalcone** [comment]
I'm seeing the expand/collapse error display even when there is no nested metadata (as in, all archival series). Should that be suppressed?

![image](https://user-images.githubusercontent.com/7491842/33401147-33632f32-d50d-11e7-93ce-0a5dc65cf824.png)

**Comment by mejackreed** [comment]
@arcadiafalcone can you provide a related druid to that example?

**Comment by arcadiafalcone** [comment]
mj755vg3684

**Comment by jkeck** [comment]
I bet `Blacklight.onLoad` isn't triggered when the modal is opened.  It works on the separate page but not when the modal is popped open.  I'll file a bug in exhibits.
