### ISSUE TITLE
Add a link to full Google Analytics page on the current Analytics page

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#948]
- Current brief analytics is okay for normal use but want easy way to get fuller analytics
- Vatican is fine with a simple link on the current analytics page that takes them to the GA page
- Might **not** be ideal to add this in Spotlight or Exhibits because most exhibit admins won't have permissions to access the linked GA page, but this might be less of an issue for the Vatican since they have a limited number of exhibits and curators and it might be reasonable for them to give all curators access to their GA page.

**Comment by ggeisler** [comment]
Closing in favor of https://github.com/sul-dlss/vatican_exhibits/issues/12
