### ISSUE TITLE
Explore support for hierarchical tags in facet

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#951]
Mirador tags (small percentage of, anyway) can be hierarchical
- Animals - Lions
- Animals - Tigers

They want to display the hierarchy with second-level indented (they don't like just showing the hierarchy flattened as in the Animals example above). There is never more than a second level of hierarchy.

Story here is to explore possibilities for expand/contract in a facet breaking on special character, or other implementation possibilities if they are feasible.

**Comment by blalbrit** [comment]
@aeschylus wrote:
"I look forward to talking through these more carefully this afternoon, but the one on this list that "keeps me up at night" is "Indexing and hierarchical facet display of tags created in Mirador as annotations".

There is currently no way to create hierarchical tags in Mirador, and a "hierarchical display" of flat tags (if that is what is meant) feels underspecified to me. I also don't see a way this feature could be made generic to other exhibits, short of inventing some kind of pattern for indexing custom data that would necessarily be a lot more involved than, for instance, our custom manifest URL control.

Indexing the content from a dynamic remote annotation source in general is not implemented in exhibits, and would be a manual process as annotation sets are updated. This could be mitigated by linking to a changing annotation list with a stable URL in the custom manifest, but that has its own problems."

To begin clarifying: this ticket in no way impacts Mirador at all, there is no requirement to create hierarchical tags in Mirador. The expectation is that flat annotations would be received and this ticket is for exploring if those annotations could be split and hierarchically displayed. There is at least one example of such behavior already in the DLSS universe, see https://argo.stanford.edu , open the "Tags" facet, and look at the "Projects" tag:

<img width="345" alt="screenshot 2017-11-29 06 48 25" src="https://user-images.githubusercontent.com/796990/33380976-980c9e82-d4d1-11e7-898c-283d8ea63af8.png">

This hierarchy is produced by input like: "Project : 1947 partition : born digital video" (see identityMetadata datastream from https://argo.stanford.edu/view/druid:bj312jq7198 for example).

**Comment by ggeisler** [comment]
@blalbrit Thanks for this example. I didn't know Argo did this, but that is exactly the potential option I had in mind to explore. A minor difference in the facet display is that where in Argo all facet values seem to be hierarchical (i.e., all parent values have children), in the Vatican exhibit we'd only have a subset of values with child facet values. So the facet display might look roughly like this (with the addition of the expand/collapse icon next to parent facet values that have children):

<img width="154" alt="-_parker_library_on_the_web_-_spotlight_at_stanford_search_results" src="https://user-images.githubusercontent.com/101482/33388303-d2a683ee-d4ec-11e7-95da-1a6d086282f2.png">

The aspect I'm unsure about is whether we'd need to worry about the child value delimiter character (e.g., ` -- `) being used in other future exhibits where the Mirador "tag" annotations are indexed and the delimiter in those cases is not intended to be a child value delimiter, or if we can just handle that in the indexing somehow by saying "for the Vatican, use ` -- ` as the child tag value delimiter". (Though it seems pretty unlikely that a future exhibit that needs Mirador tag annotations indexed would happen to use ` -- ` in their tags and not intend that to be a parent child delimiter.)

**Comment by ggeisler** [comment]
@blalbrit What do you think about "Manuscript Tags" (or even something like "Folio Tags"?) as the label for the annotation-based tags? That feels a bit more concrete and specific than "Curatorial Tags" to me but I think you'd know better what will sound right to the curators and exhibit visitors.

**Comment by blalbrit** [comment]
@ggeisler - I think "Manuscript Tags" would work, but I'll call this out for Paola specifically - they may have something more Vatican-specific in mind.

**Comment by ggeisler** [comment]
Closing in favor of https://github.com/sul-dlss/vatican_exhibits/issues/15
