### ISSUE TITLE
Explore way for curators to provide translations for a subset of annotation tags

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#952]
- Some tags won’t be translated (e.g., names, places) so need to use the provided one for both languages if no translation provided

- NB: This applies to tags produced in IIIF annotations, not exhibit tags.

**Comment by jkeck** [comment]
Just thinking this through, would it be possible to have the curators add tags with the values in the multiple languages?  Tags are effectively metadata as far as Spotlight is concerned (can be faceted on, can be displayed w/ the metadata etc) so it feels like this falls into the internationalizing metadata bucket and would have a lot of the same complications to implementation.

**Comment by blalbrit** [comment]
^^ thanks @jkeck - I have updated the ticket with more specific information, it's pretty clear the term "tag" is going to be problematic here.

**Comment by ggeisler** [comment]
I've further edited the original ticket comment to remove a couple of notes that incorrectly assumed we were talking about translating exhibit tags, not the IIIF annotation tags (@blalbrit's point about the term "tag" being confusing exemplified).

**Comment by mejackreed** [comment]
@anarchivist I see that the VT label is applied here. The IIIF annotation tags are considered metadata within the context of Exhibits, and my understanding was that metadata translations are out of scope for VT. Is this feature somehow desired?

**Comment by anarchivist** [comment]
@mejackreed I was thinking about this in terms of exhibit tags, not annos. I'll remove the VT tag and try to capture the requirement in a new ticket. Thanks!

**Comment by ggeisler** [comment]
Closing in favor of https://github.com/sul-dlss/vatican_exhibits/issues/14
