### ISSUE TITLE
Explore how to add short narrative to manuscript detail page

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#954]
- Add short narrative to each (or some) manuscript detail page; show manuscript narrative distinct from metadata in some way
- Manuscript feature page would have thumbnail for each manuscript (e.g., using search result widget), clicking on thumbnail links to item show page, which has the additional non-metadata manuscript narrative
- Additional narrative should allow hyperlinks so can link names, etc. to another detail page

Easiest solution would be for Vatican to simply use a custom field for this, but that doesn't satisfy the "make it distinct from other metadata fields" goal.

**Comment by ggeisler** [comment]
Closing in favor of https://github.com/sul-dlss/vatican_exhibits/issues/11
