### ISSUE TITLE
Export Data button results in 500 error

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#959]
1. From dashboard (testing in https://exhibits.stanford.edu/parker-2/edit)...
2. Go to Configuration > General > Export Data and click the `Export Data` button

Result: {"status":500,"error":"Internal Server Error"}

**Comment by caaster** [comment]
Hi @blalbrit I am looking for your help to validate whether or not this is still a problem. Thank you.

**Comment by blalbrit** [comment]
@caaster  - this is no longer an issue, likely an artifact of the Parker 2 development cycle.

**Comment by caaster** [comment]
Per @blalbrit this is no longer happening, probably fixed during the Parker2 development cycle and never closed.
