### ISSUE TITLE
Parker-specific fielded search categories have disappeared in latest release

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#961]
We seem to have lost the Parker-specific fielded search categories (https://exhibits.stanford.edu/parker-2/search_configuration/edit). Is this an easy fix, or shall I file a bug ticket for the work?

<img width="925" alt="screenshot 2017-11-29 12 48 33" src="https://user-images.githubusercontent.com/796990/33398968-a32130ba-d505-11e7-8f88-59b0d2fc8d32.png">

**Comment by mejackreed** [comment]
Resolved.
