### ISSUE TITLE
Explore changing the label on the "View all metadata" button

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#968]
Per Parker user feedback, the "View all metadata" is less meaningful to non-librarians than we would expect.

![screenshot 2017-11-30 15 55 27](https://user-images.githubusercontent.com/796990/33461387-091a7002-d5e7-11e7-9dd2-ab5d47c52628.png)

Would it be possible to change this label? Thoughts @jvine and @ggeisler ?

Suggestions from the users were:
- "View all details" or
- "More details"

**Comment by jvine** [comment]
Hah, I thought everyone knew what metadata is by now thanks to the NSA.

I also recall that Arcadia had an issue with the "all", and I forgot to record it (Spotlight-specific metadata is not included). So I'd be inclined toward the "More..." idea.

**Comment by blalbrit** [comment]
@mejackreed - based on the above discussion, would you be able to turn this into an implementation ticket?

**Comment by mejackreed** [comment]
Yes.. PR submitted #969

**Comment by blalbrit** [comment]
Many thanks @mejackreed
