### ISSUE TITLE
Date range facet - preliminary support

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/exhibits#971]
As an exhibit creator or exhibit user, I should be able to facet based upon a range of dates at the year level.

**Comment by cbeer** [comment]
Duplicate of #548?

**Comment by anarchivist** [comment]
I'll take a closer look but I'd guess so. Thanks!

**Comment by anarchivist** [comment]
I'm not sure this is a full duplicate - this doesn't presume that the dates are encoded as a range themselves. I'd be inclined to split that part of #548 out here.
