### ISSUE TITLE
"View all metadata" modal returns network error on some manuscripts in Parker exhibit

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#974]
- Go to https://exhibits.stanford.edu/parker-2/catalog/sg197kx6643
- click "View all metadata"
- result from off-campus (not on VPN) is:
<img width="1416" alt="screenshot 2017-12-03 13 36 30" src="https://user-images.githubusercontent.com/796990/33530102-2633ecf0-d82f-11e7-8cc9-09763b548433.png">

- Same results with other objects that have many relatedItems, like https://exhibits.stanford.edu/parker-2/catalog/kf459tj3176

Based on Honeybadger reporting, this appears to be a time-out error: https://app.honeybadger.io/projects/49092/faults/35691474

**Comment by jkeck** [comment]
FWIW, I'm trying to track down where the bottleneck is here.  It appears to be specifically due to the addition of the nested related items.

**Comment by camillevilla** [comment]
I took a look at this as well, with the NestedRelatedItems JS turned off. Things eventually load, but it's still super slow. Maybe we need to revisit the `mods_display` implementation?

**Comment by camillevilla** [comment]
Note: addressed by sul-dlss/mods_display#51
