### ISSUE TITLE
Enabling/configuring Solr hit highlighting in Spotlight

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/exhibits#978]
Begin analysis on the best way to expose Solr hit highlighting in the context of Spotlight.

**Comment by cbeer** [comment]
See also https://github.com/sul-dlss/exhibits/pull/99.

**Comment by anarchivist** [comment]
To make #99 actionable for VT:

* Confirm that the hit highlighting field is configurable (label and placement)
* Break up individual hits with more visual space

See also #1175 for designs from @ggeisler

**Comment by anarchivist** [comment]
Closing this in preference of #993
