### ISSUE TITLE
Support multilingual text in the same field

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/exhibits#979]
Virtual Tribunals has documents that may have running text in multiple languages (e.g. mostly Portuguese, with a few paragraphs of English interspersed). Investigate methods for enabling indexing and search for this kind of content

**Comment by anarchivist** [comment]
Possibly useful: http://www.basistech.com/whitepapers/Optimizing-Multilingual-Search-With-Solr.pdf

**Comment by cbeer** [comment]
FWIW, we did a lazy version of indeed-field-per-language for DLME and it worked fine.

**Comment by anarchivist** [comment]
Part of the context here is that some of the documents for VT phase 1 are multilingual (e.g., one document is mostly Portuguese a few interspersed paragraphs of English). The OCR text does not specify the language, but we know the languages in the document overall.

**Comment by cbeer** [comment]
That's fine -- the lazy version for DLME just duplicated the content into indexed fields for every language.

**Comment by anarchivist** [comment]
(for my own reference:) Per my hallway conversation with @jkeck, this will implement the same solution we've used for content_search. Any specific acceptance criteria should be broken out into a separate tickets, which can either be added as new features or identify bugs.
