### ISSUE TITLE
Evaluate third party libraries for internationalization

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/exhibits#980]
Need to determine potential libraries to add i18n support for translated user interface elements and feature page content. `globalize` was mentioned as a possibility.

**Comment by drh-stanford** [comment]
Can you be more specific about the requirements for i18n? We currently use externalized text for various UI elements using the built-in Rails i18n support. Do we need more functionality than that?

The `globalize` gem is primarily for user-generated content, and it requires building translation tables.

**Comment by anarchivist** [comment]
I'm working on capturing this in #444 and associating detail in linked tickets. Essentially we have multiple types/sources of text to translate, with the focus being on the following:

* Navigation elements (e.g. labels like "Home", "Next"/"Previous" for paginated results) - likely to be pulled from the locale file
* User interface elements (e.g. exhibit title; subtitle; labels for menu items, facets, metadata, browse categories, etc.): all configurable by an exhibit curator 
* Feature page text: content of the Sir Trevor widgets: again, all configurable by an exhibit curator

**Out of scope** items are translation of the admin UI and translation of metadata.

**Comment by drh-stanford** [comment]
For (b) User interface elements: Are we modifying the Admin UI to support multiple languages for each element like the exhibit title, menu item labels, etc.? Or are we writing a low-level tool (i.e., script) that allows them to insert translations into a database table? If the former, do we have designs for that new UI/UX?

**Comment by jkeck** [comment]
@mejackreed should we be able to close this out now?

**Comment by mejackreed** [comment]
Yeah closing.
