### ISSUE TITLE
Add toggle to switch between languages (language selector)

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/exhibits#984]
As a user: 

* I should be able to see a control that allows me to select the language in which I wish to view an exhibit.
* Selecting a language should show me as much page content as possible translated for that language.

_Note:_ Translations will almost definitely need to be pulled from multiple sources (locales and db-backed content). Design can probably proceed on this, but I'm not sure when we should schedule the implementation yet.

**Comment by anarchivist** [comment]
Let's work on surfacing the Blacklight control for locale selection, and then having something for @ggeisler to respond to.

**Comment by jkeck** [comment]
`locale` parameter in the url (as opposed to a `/en/`) is preferable.

**Comment by jkeck** [comment]
The main concern that we need to keep in mind when choosing between going w/ a query parameter (`?locale=en`) vs. a url path segment (`/en/`) is how Google handles [international targeting](https://support.google.com/webmasters/answer/6059209).  The relevant section of that page being **Page-level markup**.

> Use the <link rel="alternate" hreflang="x" href="alternateURL"> tag in the <head> section of your pages to list alternate language versions for each page.  Each page should provide an hreflang tag that links to all other language variants of itself, as well as a tag that refers back to itself.  For more granular targeting, you can use the hreflang attribute to indicate language and country combinations (e.g. en-ie, en-ca, en-us). Read more about the hreflang tag in our Content guidelines section.  

Once we have this, it will enable a section of the Google Webmaster International Targeting dashboard referenced at the bottom of that page.  However; if I'm reading things correctly, we may not care about the things that dashboard enables.

Looking at the [Multi-regional and multilingual sites](https://support.google.com/webmasters/answer/182192) documentation, it does indicate that using a query parameter in the url structure is "Not Recommended".  The cons that it describes are "URL-based segmentation difficult" (?), Users not recognizing the query param in the URL, and Geotargeting in the search console not being possible.

A note about **Geotargeting** from their documentation:
> You can use the Country targeting tool in Search Console to indicate to Google that your site is targeted at a specific country. Do this only if your site has a generic top-level domain name. However, don’t use this tool if your site targets more than a single country. For example, it would make sense to set a target of Canada for a site about restaurants in Montreal; but it would not make sense to set the same target for a site that targets French speakers in France, Canada, and Mali.

I don't believe that's something we want, so enabling Geotargeting may not be a pressing concern.

**Comment by anarchivist** [comment]
Proposal from 1/31 storytime is to use `/$LOCALE/$SLUG`.  @jkeck to specify more specific concerns, e.g.

* can we identify `en` as the default local?
* impact on redirects (e.g. for Parker)

**Comment by anarchivist** [comment]
See projectblacklight/spotlight#1920.
