### ISSUE TITLE
Curator-driven translations for exhibit-level user interface elements

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/exhibits#985]
As an exhibit curator/admin I want to be able to provide translations in one or more languages for the following items under an exhibit's general configuration:

* Exhibit title
* Exhibit subtitle
* Exhibit description

**Acceptance criteria**

As a curator or exhibit admin: 

* [ ] I should be able to add translations for the title, subtitle, or description for an exhibit in a specified locale
* [ ] I should be able to see the translations side by side or in close proximity to make it easier for me to translate directly from the default tile

As a user, when I select the a locale from the locale selector:

* [ ] If translations exist for the exhibit title, exhibit subtitle, or exhibit description in that locale, I should see them
* [ ] If translations do not exist for the exhibit title, exhibit subtitle, or exhibit description in that locale, I should see the default translations

**Comment by ggeisler** [comment]
Closing; replaced by https://github.com/projectblacklight/spotlight/issues/1914
