### ISSUE TITLE
Options for adding currently uninvited or unconfirmed exhibit admins/curators as exhibits users

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#992]
Options for adding currently uninvited or unconfirmed exhibit admins/curators as exhibits users, below. Option A is preferred, but Option B is totally ok.

Dependency:
After Cathy cleans up the list of 59 (unconfirmed users) from Jessie (meaning I will delete a few of the users that I know don't need to be there)....implement either A or B, below.

Option A:
Automatically add the unconfirmed/uninvited users to the exhibits user list.

Option B:
To uninvited users, send an invite, so each person can confirm. To unconfirmed users, send a new invite so each person can confirm. NOTE: if this option is preferred, please let Cathy know so she can notify these two groups of people ahead of time, so they understand what is happening.

**Comment by jkeck** [comment]
For A:

**Comment by jkeck** [comment]
**For A:** we would need to do some investigation, but I think we can just set the appropriate columns on the user in the database and they'll begin getting the correct behavior.  Which columns (most likely `invitation_sent_at` and `invitation_accepted_at`) and what values is what we'll need to investigate (as well as that the user will have the behavior that we expect, such as having the correct exhibits show up in their `Your exhibits` tab).

**For B:** we can simply get an array of emails and do something along the lines of:

```ruby
User.where(email: email_array).map(&:deliver_invitation)
```

**Comment by mejackreed** [comment]
I like the idea of B. Not from a technical standpoint but more from an application usability and security standpoint. Users should have understand and confirmed that they want to be part of the Exhibit, via the Exhibits workflow.

**Comment by caaster** [comment]
@mejackreed Although many of the people who would be sent an invite are already active exhibit builders who have received training, there are a few stragglers. So your vote for option B makes sense for them. Across the board for all people who are uninvited or unconfirmed, I can absolutely live with option B. Reminder: I will need to email this list of people ahead of time to tell them to keep an eye out of the invite email.

**Comment by caaster** [comment]
@jkeck @camillevilla  I am closing this issue because it is done afaik

**Comment by jkeck** [comment]
👍
