### ISSUE TITLE
Hit highlighting in search results

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/exhibits#993]
As a user keyword searching an exhibit (especially one with full text), I want to have a better understanding of which material might be relevant when I look at a set of search results.

**Questions**

* How would hit highlighting work with fielded metadata that displays on the index pages of search results?
* ~How/where should hit highlighting appear for full text?~

**Examples from comparable initiatives**

[Residual Special Court for Sierra Leone](http://www.scsldocs.org/)

![screen shot 2017-12-06 at 11 50 55 am](https://user-images.githubusercontent.com/73732/33682356-105ca562-da7c-11e7-8ea4-b5dfd6493cea.png)

**Comment by anarchivist** [comment]
See also #99

**Comment by anarchivist** [comment]
To make #99 actionable for VT:

* Confirm that the hit highlighting field is configurable (label and placement)
* Break up individual hits with more visual space

See also projectblacklight/spotlight#1175 for designs from @ggeisler

**Comment by jkeck** [comment]
A few questions/thoughts that have come up as I have been working on this:

1. Do we need to have full-text indexed under "All fields"?  I believe the current full-text indexing is only surfaced when choosing a "Full text" option from the search drop down.  Should that still be the case here? 
1. The way the current implementation of the highlights in the results themselves is styled, being ordered anywhere except the first or last item in the results display will look very odd.  Perhaps that's okay, but just wanted to call it out.
1. When adding this field to metadata configuration, should it be enabled by default?

**Comment by anarchivist** [comment]
> Do we need to have full-text indexed under "All fields"? I'm not 100% sure if the current full-text indexing is only surfaced when choosing a "Full text" option from the search drop down.

I'm a little confused here. Is "All fields" the same as "Everything"?  Is there an example I can test?

> The way the current implementation of the highlights in the results themselves is styled, being ordered anywhere except the first or last item in the results display will look very odd. Perhaps that's okay, but just wanted to call it out.

Can you provide a screenshot or something else to demonstrate this?

> When adding this field to metadata configuration, should it be enabled by default?

I'm not sure. @caaster?

**Comment by jkeck** [comment]
@anarchivist see my screenshot on #1030.

The `Preview matches found in document text` is configured to be at the bottom of metadata, but an exhibit administrator could configure it to be anywhere in the block of metadata above it.  We might just classify that under "If you do that, it will look bad, so don't do it" and not worry too much about it.  Just wanted to call it out.

This is what it'll look like if an admin configures the field to display in the middle.

<img width="714" alt="silly" src="https://user-images.githubusercontent.com/96776/34063935-4a5050ea-e1aa-11e7-8abf-d71cf850a154.png">

**Comment by jkeck** [comment]
@anarchivist yes, sorry, "All fields" and "Everything" are the same thing.

In the [exhibit that I'm using as an example](https://exhibits.stanford.edu/feigenbaum) I _think_ full text is in the "Everything" search, but could help use some validation.

**Comment by jkeck** [comment]
@anarchivist https://github.com/sul-dlss/sul-solr-configs/blob/14665661ce02ca4f3272bdb21d3bcfa8f719f37e/exhibits/schema.xml#L339-L343 gives me pause...

**Comment by anarchivist** [comment]
> In the [exhibit that I'm using as an example](https://exhibits.stanford.edu/feigenbaum) I think full text is in the "Everything" search, but could help use some validation.

I think I've been able to validate that. That sounds good to me. I'd wonder if we need a "metadata only" search, but we could break that into a new ticket if that sounds OK to you. 

> We might just classify that under "If you do that, it will look bad, so don't do it" and not worry too much about it. Just wanted to call it out.

I think that's fine by me.
